Repository openshift/ci-tools, pull requests merged in 2019-12, with the labels that each got.

#305 Don't call out to make jobs in repo-init
  cmd/repo-init/main.go
  test/repo-init-integration/expected/Makefile
  test/repo-init-integration/input/Makefile
  test/repo-init-integration/run.sh
Labels: approved, lgtm, size/S

#288 Expose shared directory for users in test continers
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm, size/M

#300 Add a group auto updater tool
  Makefile
  cmd/group-auto-updater/main.go
  images/group-auto-updater/Dockerfile
  pkg/steps/testing.go
  test/group-auto-updater-integration/data/expected.yaml
  test/group-auto-updater-integration/data/peribolos-config.yaml
  test/group-auto-updater-integration/run.sh
  vendor/github.com/openshift/api/user/v1/doc.go
  vendor/github.com/openshift/api/user/v1/generated.pb.go
  vendor/github.com/openshift/api/user/v1/generated.proto
  vendor/github.com/openshift/api/user/v1/legacy.go
  vendor/github.com/openshift/api/user/v1/register.go
  vendor/github.com/openshift/api/user/v1/types.go
  vendor/github.com/openshift/api/user/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/user/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/doc.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/group.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/identity.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/user.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/user_client.go
  vendor/github.com/openshift/client-go/user/clientset/versioned/typed/user/v1/useridentitymapping.go
  vendor/k8s.io/test-infra/prow/config/org/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/org/org.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#307 prowgen: add --lease-server to remaining tests
  cmd/ci-operator-prowgen/main.go
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#291 pj-rehearse: resolve multi-stage configurations
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/load/registryAgent.go
  pkg/registry/resolver.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm, size/L

#309 test/ci-operator-*: improve configresolver tests
  test/ci-operator-configresolver-integration/run.sh
  test/ci-operator-integration/multi-stage/run.sh
Labels: approved, lgtm, size/L

#308 pkg: make and use reloadWatcher designed for configmaps
  pkg/load/agent_utils.go
  pkg/load/configAgent.go
  pkg/load/registryAgent.go
  pkg/watcher/watcher.go
  test/ci-operator-configresolver-integration/ci-op-configmaps/master/..2019_11_15_19_57_20.547184898/openshift-installer-master.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/master/..data
  test/ci-operator-configresolver-integration/ci-op-configmaps/master/openshift-installer-master.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/release-4.2/..2019_11_15_19_57_20.547184898/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/release-4.2/..data
  test/ci-operator-configresolver-integration/ci-op-configmaps/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/run.sh
Labels: approved, lgtm, size/L

#306 Replace svc bokos with its route
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator/main.go
  go.mod
  go.sum
  pkg/lease/client.go
  vendor/k8s.io/test-infra/boskos/client/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/client/client.go
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/config/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/inrepoconfig.go
  vendor/k8s.io/test-infra/prow/git/git.go
  vendor/k8s.io/test-infra/prow/plugins/buildifier/buildifier.go
  vendor/k8s.io/test-infra/prow/plugins/golint/golint.go
  vendor/k8s.io/test-infra/prow/plugins/mergecommitblocker/mergecommitblocker.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/trigger/generic-comment.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/k8s.io/test-infra/prow/plugins/updateconfig/updateconfig.go
  vendor/k8s.io/test-infra/prow/plugins/verify-owners/verify-owners.go
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#312 Introduce a set of migrated repos
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/M

#313 Generate pull-secret arg for migrated jobs
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/S

#279 pkg/registry: add registry graph
  pkg/registry/graph.go
  pkg/registry/graph_test.go
Labels: approved, lgtm, size/L

#318 repo-init: correctly choose origin base, golang 1.13
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml
Labels: approved, lgtm, size/S

#316 pkg/lease: use AcquireWait instead of Acquire
  pkg/lease/client.go
  pkg/lease/client_test.go
  pkg/lease/fake.go
  pkg/steps/lease.go
Labels: approved, lgtm, size/S

#304 [ci-operator] Add OAuth token authentication support while cloning
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/git_source.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  test/ci-operator-integration/base/auth_files/id_rsa
  test/ci-operator-integration/base/auth_files/oauth-token
  test/ci-operator-integration/base/expected_files/expected_src_oauth.json
  test/ci-operator-integration/base/expected_files/expected_src_ssh.json
  test/ci-operator-integration/base/run.sh
Labels: approved, lgtm, size/XL

#320 ci-operator: use lease client in upgrade tests
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/template.go
  test/ci-operator-integration/base/run.sh
Labels: approved, lgtm, size/L

#321 pkg/defaults: defer lease client validation
  pkg/defaults/defaults.go
  pkg/steps/lease.go
Labels: approved, lgtm, size/S

#319 pj-rehearse: implement rehearsing of changed registry steps
  cmd/ci-operator-prowgen/main.go
  cmd/pj-rehearse/main.go
  pkg/config/load.go
  pkg/config/release.go
  pkg/jobconfig/files.go
  pkg/rehearse/jobs.go
  pkg/rehearse/metrics.go
  test/pj-rehearse-integration/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm, size/XXL

#310 SDCICD-99: Add multi-secret support in ci-operator
  CONFIGURATION.md
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
Labels: approved, lgtm, size/L

#323 lease: use acquire with priority
  pkg/lease/client.go
  pkg/lease/client_test.go
  pkg/lease/fake.go
  pkg/steps/lease_test.go
Labels: approved, lgtm, size/M

#326 registry: create graph in loadRegistry to detect cycles
  pkg/load/load.go
Labels: approved, lgtm, size/XS

#325 pkg/steps/lease: forward junit sub-tests
  pkg/steps/lease.go
  pkg/steps/lease_test.go
Labels: approved, lgtm, size/S

#327 Update Configuration.MD
  CONFIGURATION.md
Labels: approved, lgtm, size/XS

#303 [prowgen] Generate private jobs by using OAuth token instead of SSH
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#328 hack/jira.py: ignore sub-tasks
  hack/jira.py
Labels: approved, lgtm, size/XS

#329 pkg/steps/template: force a failure when cancelled
  pkg/steps/template.go
Labels: approved, lgtm, size/XS

#331 pkg/lease: retry updates
  cmd/ci-operator/main.go
  pkg/lease/client.go
  pkg/lease/client_test.go
  pkg/lease/fake.go
  pkg/steps/lease_test.go
Labels: approved, lgtm, size/L

#333 Wait cluster-version-operator to be imported
  pkg/steps/release/create_release.go
Labels: approved, lgtm, size/M

#334 ci-operator: postpone lease client creation
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
Labels: approved, lgtm, size/M

#332 Remove unnecessary parameter in integration tests
  test/ci-operator-integration/base/run.sh
Labels: approved, lgtm, size/M

#337 Workaround BZ1784163
  pkg/steps/source.go
  pkg/steps/source_test.go
  test/ci-operator-integration/base/expected_files/expected.json
  test/ci-operator-integration/base/expected_files/expected_src_oauth.json
  test/ci-operator-integration/base/expected_files/expected_src_ssh.json
  test/ci-operator-integration/base/expected_files/expected_with_template.json
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm, size/L

#322 Migrate openshift/origin to build01
  GENERATOR.md
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/config-migrater/README.md
  cmd/config-migrater/main.go
  pkg/jobconfig/files.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/L

#338 Revert "Migrate openshift/origin/master to build01"
  GENERATOR.md
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/config-migrater/README.md
  cmd/config-migrater/main.go
  pkg/jobconfig/files.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/L

#340 pkg/steps/clusterinstall/template: Sync with openshift/release
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/M
