Repository openshift/ci-tools, pull requests merged in 2019-07, with the labels that each got.

#12 prowgen: DRY out JobBase generation
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/jobconfig/files.go
Labels: approved, lgtm, size/L

#13 Prowgen: Rewrite pruning stale jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
Labels: approved, lgtm, size/L

#15 prowgen: Add integration tests for pruning and variants
  test/prowgen-integration/data/input/config/super/duper/super-duper-master-removed-promotion.yaml
  test/prowgen-integration/data/input/config/super/duper/super-duper-master__variant.yaml
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-removed-ciop-config-postsubmits.yaml
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-removed-promotion-postsubmits.yaml
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
Labels: approved, lgtm, size/L

#20 prowgen: DRY template test generation
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/L

#19 refactor job configuration
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#23 prowgen: use default GOPATH
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#16 prowgen: operate on sub-directories
  CI_OPERATOR_PROWGEN.md
  Makefile
  cmd/ci-operator-prowgen/main.go
  pkg/config/load.go
  pkg/jobconfig/files.go
  test/prowgen-integration/data/input/config/subdir/repo/subdir-repo-master.yaml
  test/prowgen-integration/data/input/jobs/super/remove/super-remove-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/run.sh
Labels: approved, lgtm, size/L

#22 pj-rehearse: Add periodic jobs to the rehearsals
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/metrics.go
  pkg/rehearse/metrics_test.go
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
Labels: approved, lgtm, size/XL

#24 introduce generic test image test type
  cmd/ci-operator-prowgen/main.go
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/M

#26 Build ipi_deprovision image
  .gitignore
  cmd/ipi-deprovision/ipi-deprovision.sh
  images/ipi-deprovision/Dockerfile
Labels: approved, lgtm, size/S

#27 ci-operator: fix missing dependencies messages
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#28 determine working directory for the source image.
  pkg/api/job_spec.go
  pkg/steps/source.go
Labels: approved, lgtm, size/S

#25 include extrarefs pulls to authors
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/S

#29 Install less in ipi-deprivision image
  cmd/ipi-deprovision/ipi-deprovision.sh
  images/ipi-deprovision/Dockerfile
Labels: approved, lgtm, size/S

#30 Check if AWS_SHARED_CREDENTIALS_FILE is set
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/M

#33 Add region into hive command
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#31 allow no extra_refs in periodics
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/XS

#34 remove git-ref/extra_refs workaround.
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/S

#35 Deprovision clusters with hiveutil
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#36 Add logs indicating the end of provision
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#40 Fix an example of destination_dir in ONBOARD.md
  ONBOARD.md
Labels: approved, lgtm, size/XS

#39 Collect metadata in ipi-deprovision
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/S

#42 Cp oc cli from cli image to ipi-deprovision
  images/ipi-deprovision/Dockerfile
Labels: approved, lgtm, size/XS

#43 Improve debugging logs of ipi-deprovision script
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#44 Use if-condition to check the namespace existence
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#45 Update prowgen to generate test secret mount if configured in tests.
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/L

#41 Remove git-ref arg, use extra_refs with workdir.
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/L

#47 Revert "Merge pull request #41 from droslean/git-ref-remove"
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/L
