Repository openshift/ci-tools, pull requests merged in 2019-08, with the labels that each got.

#48 ci-operator: inject path alias to refs
  pkg/steps/source.go
Labels: approved, lgtm, size/M

#49 Revert "Revert "Merge pull request #41 from droslean/git-ref-remove""
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/L

#52 Move `applyconfig` from release to ci-tools
  cmd/applyconfig/README.md
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
  images/applyconfig/Dockerfile
Labels: approved, lgtm, size/L

#53 add oc to applyconfig image
  images/applyconfig/Dockerfile
Labels: approved, lgtm, size/XS

#55 convert Periodics to Presubmits
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/L

#51 add rehearse label to generated presubmits
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/jobconfig/files.go
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/M

#56 Embed jobSpec from downwardapi
  cmd/ci-operator/main.go
  pkg/api/job_spec.go
  pkg/defaults/defaults_test.go
  pkg/steps/git_source.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
Labels: approved, lgtm, size/L

#59 Upgrade version of k8s.io/test-infra
  go.mod
  go.sum
  test/pj-rehearse-integration/expected.yaml
  vendor/k8s.io/test-infra/ghproxy/ghcache/ghcache.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/BUILD.bazel
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghmetrics.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghpath.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/BUILD.bazel
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/bugzilla/types.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/config/secret/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/secret/agent.go
  vendor/k8s.io/test-infra/prow/flagutil/github.go
  vendor/k8s.io/test-infra/prow/gcsupload/options.go
  vendor/k8s.io/test-infra/prow/gcsupload/run.go
  vendor/k8s.io/test-infra/prow/git/git.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/kube/BUILD.bazel
  vendor/k8s.io/test-infra/prow/kube/client.go
  vendor/k8s.io/test-infra/prow/kube/types.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/README.md
  vendor/k8s.io/test-infra/prow/plugins/cat/cat.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/dco/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/dco/dco.go
  vendor/k8s.io/test-infra/prow/plugins/dog/dog.go
  vendor/k8s.io/test-infra/prow/plugins/retitle/retitle.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/generic-comment.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/k8s.io/test-infra/prow/plugins/verify-owners/verify-owners.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#54 Populate env. var. in test pods
  pkg/api/job_spec.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
Labels: approved, lgtm, size/M

#63 Disallow redundant path aliases
  cmd/ci-operator-checkconfig/main.go
  cmd/ci-operator/main.go
  pkg/api/config.go
  pkg/api/types.go
  pkg/config/load.go
  pkg/defaults/defaults.go
  pkg/load/load_test.go
Labels: approved, lgtm, size/M

#65 Update test-infra vendor
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/plugins/heart/heart.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#64 Add unit tests for generating the job base
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/M

#66 Add a test for source build creation
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm, size/L

#67 Don't change refs at runtime unless running locally
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator/main.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  test/prowgen-integration/data/input/config/super/duper/super-duper-master__variant.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#69 Kill hiveutil after 10m
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#70 cmd/ipi-deprovision/ipi-deprovision.sh: Debug logs for aws-tag-deprovision
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#72 Add AWS quota leasing to internal template
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/M

#71 Fix timeout command in ipi-deprovision script
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#73 Don't serialize `upgrade: false`
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#68 determine ref with workdir when cloning source from git
  pkg/steps/git_source.go
  pkg/steps/git_source_test.go
Labels: approved, lgtm, size/L

#74 Remove unused function
  pkg/jobconfig/files.go
Labels: approved, lgtm, size/S

#58 make rehearse tool to check for requred label to rehearse a job
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#61 Add dependency-section into doc
  .gitignore
  CONTRIBUTORS.md
  Makefile
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#79 Commit the chagnes on go-mod files
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, size/XS

#77 add org/repo label in template pods
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#80 Update inline template to mirror those in openshift/release
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/XS

#81 add branch label in template pods
  pkg/steps/template.go
Labels: approved, lgtm, size/XS

#75 Small bug fixes
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/artifacts.go
  pkg/steps/pod.go
Labels: approved, lgtm, size/M

#86 Adding checks for additional possible infra failures
  pkg/steps/source.go
Labels: approved, lgtm, size/XS

#87 ci-operator: DRY pod generation, use bash
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm, size/L

#84 Inject resources in template pods, refactor label injection
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#88 fix unmarhal error log
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#90 Add a new tool: autobumper
  cmd/autobumper/main.go
  go.mod
  go.sum
  images/autobumper/Dockerfile
  vendor/k8s.io/test-infra/ghproxy/ghcache/ghcache.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghmetrics.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghpath.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/flagutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/kube/client.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
  vendor/k8s.io/test-infra/prow/plugins/retitle/retitle.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#93 Revert changes to set resources for template pods from config
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#95 ci-operator: add TestStep type
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
Labels: approved, lgtm, size/L

#97 rehearse jobs when optional and always_run changes.
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
Labels: approved, lgtm, size/M

#98 Implement multi-stage test registry interface
  pkg/api/config.go
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/types/types.go
Labels: approved, lgtm, size/L

#101 ci-operator multi-stage: use appropriate names
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/types/types.go
Labels: approved, lgtm, size/M

#92 Inject org/repo/branch labels to pods created by ci-operator
  pkg/steps/pod_test.go
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm, size/L

#100 ci-operator multi-stage: MultiStageTestStep
  pkg/api/config.go
  pkg/api/job_spec.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm, size/XL, ¯\_(ツ)_/¯

#102 pkg/registry: add support for test references
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm, size/L
