Repository openshift/ci-tools, pull requests merged in 2019-06, with the labels that each got.

#3 rehearse: detect cluster types
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/M

#4 Shard validator: shard job-config-master further (by job type)
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
Labels: approved, lgtm, size/S

#5 Update URL and build command
  CI_OPERATOR.md
  CONTRIBUTORS.md
Labels: approved, lgtm, size/S

#6 prowgen: add IaaS-agnostic installer test type
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/api/config.go
  pkg/api/types.go
  test/prowgen-integration/data/input/config/super/duper/super-duper-master.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#7 clusterinstall: sync the template with openshift/release@16eaebe45
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/L

#8 Fix ERROR prefixes to be hightlighted by Spyglass
  cmd/pj-rehearse/main.go
  test/pj-rehearse-integration/run.sh
  test/prowgen-integration/run.sh
  test/validate-prowgen-breaking-changes.sh
Labels: approved, lgtm, size/M

#9 ci-operator: check extra refs in gitSourceStep
  pkg/steps/git_source.go
Labels: approved, lgtm, size/S

#10 Wait longer for image import
  pkg/steps/release/create_release.go
Labels: approved, lgtm, size/XS

#11 prowgen: Remove some dead code
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/M

#1 rehearse: Get changed periodics
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
Labels: approved, lgtm, size/L
