Repository openshift/ci-tools, pull requests merged in 2019-10, with the labels that each got.

#188 ci-operator multi-stage: add cluster profile
  pkg/api/types.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm, size/L

#189 secret-wrapper: add test to `integration` target
  Makefile
  test/secret-wrapper-integration.sh
Labels: approved, lgtm, size/S

#190 ci-operator: check for permission to create events
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M, ¯\_(ツ)_/¯

#60 Allow users to generate periodic jobs
  cmd/ci-operator-prowgen/main.go
  pkg/api/types.go
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
  test/prowgen-integration/data/input/config/super/duper/super-duper-master.yaml
  test/prowgen-integration/data/input/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
Labels: approved, lgtm, size/L

#191 testgrid-config-generator: Support more informing jobs
  cmd/testgrid-config-generator/main.go
  pkg/jobconfig/files.go
  test/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-okd-release-4.2-informing.yaml
  test/testgrid-config-generator/run.sh
Labels: approved, lgtm, size/M

#192 Collapse job configuration configmaps for master branch
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
Labels: approved, lgtm, size/S

#194 Revert "Collapse job configuration configmaps for master branch"
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
Labels: approved, lgtm, size/S

#195 Make determinizer deterministic for periodics
  pkg/jobconfig/files.go
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
Labels: approved, lgtm, size/L

#196 Revert "Revert "Collapse job configuration configmaps for master branch""
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
Labels: approved, lgtm, size/S

#197 ci-operator multi-stage: create release image
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm, size/M

#193 testgrid-config-generator: Correct some faulty assumptions
  cmd/testgrid-config-generator/main.go
  test/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-okd-release-4.2-informing.yaml
  test/testgrid-config-generator/run.sh
Labels: approved, lgtm, size/L

#198 Ensure periodics still the correct workdir in rehearsal
  pkg/rehearse/jobs.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/XS

#187 ci-operator-configresolver: add metrics
  cmd/ci-operator-configresolver/main.go
  go.mod
  pkg/load/configAgent.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/push/deprecated.go
  vendor/github.com/prometheus/client_golang/prometheus/push/push.go
  vendor/k8s.io/test-infra/prow/metrics/BUILD.bazel
  vendor/k8s.io/test-infra/prow/metrics/README.md
  vendor/k8s.io/test-infra/prow/metrics/metrics.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#199 images: add ci-operator-configresolver image
  images/ci-operator-configresolver/Dockerfile
Labels: approved, lgtm, size/XS

#200 Fix failures when no update of image is made
  cmd/autobumper/main.go
Labels: approved, lgtm, size/XS

#201 ci-operator-configresolver: improve metrics buckets
  cmd/ci-operator-configresolver/main.go
  pkg/load/configAgent.go
Labels: approved, lgtm, size/S

#202 Trigger images jobs even when they're brand new
  cmd/config-change-trigger/main.go
Labels: approved, lgtm, size/XS

#203 pkg/load/configAgent.go: don't call fsnotify.Remove on REMOVE event
  pkg/load/configAgent.go
Labels: approved, lgtm, size/XS

#206 Correctly honor "extra" fields for refs in rehearsal
  pkg/rehearse/jobs.go
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
Labels: approved, lgtm, size/L

#207 ci-operator: implement retrieving config from configresolver
  cmd/ci-operator/main.go
  pkg/load/configAgent.go
  pkg/load/load.go
  pkg/load/load_test.go
  test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/ci-operator-integration/multi-stage/run.sh
Labels: approved, lgtm, size/L

#208 prowgen: add configresolver flags to ci-tools repo
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/S

#210 change ci-op and configresolver logging to improve debugging
  cmd/ci-operator-configresolver/main.go
  pkg/load/configAgent.go
  pkg/load/load.go
Labels: approved, lgtm, size/XS

#211 configresolver: improve metrics buckets and change logging
  cmd/ci-operator-configresolver/main.go
  pkg/load/configAgent.go
Labels: approved, lgtm, size/S

#212 testgrid-config-generator: Update naming and dashboard ordering
  cmd/testgrid-config-generator/main.go
  test/testgrid-config-generator/expected/groups.yaml
  test/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.1-blocking-ci.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.1-informing-ci.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.2-blocking-ci.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.2-blocking-ocp.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.2-informing-ci.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.2-informing-ocp.yaml
Labels: approved, lgtm, size/L

#213 pj-rehearse: remove configresolver flags from rehearsals
  pkg/load/load.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/M

#214 ci-operator-prowgen: enable configresolver for all jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/L

#215 testgrid-config-generator: Filter the monitor cluster test from testgrid
  cmd/testgrid-config-generator/main.go
  test/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.1-blocking-ci.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.1-informing-ci.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.2-blocking-ci.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.2-blocking-ocp.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.2-informing-ci.yaml
  test/testgrid-config-generator/expected/redhat-openshift-release-4.2-informing-ocp.yaml
Labels: approved, lgtm, size/S

#216 Add UPI-src template to prowgen.
  cmd/ci-operator-prowgen/main.go
  pkg/api/config.go
  pkg/api/types.go
  pkg/load/load_test.go
Labels: approved, lgtm, size/S

#218 Fix failures when no update of image is made (2)
  cmd/autobumper/main.go
Labels: approved, lgtm, size/S

#219 ci-operator: use configresolver config directly for ci-tools repo
  pkg/load/load.go
Labels: approved, lgtm, size/S

#220 Use HasChanges in autobumper from upstream
  cmd/autobumper/main.go
  go.mod
  go.sum
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/experiment/image-bumper/bumper/bumper.go
  vendor/k8s.io/test-infra/pkg/genyaml/BUILD.bazel
  vendor/k8s.io/test-infra/pkg/genyaml/genyaml.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/BUILD.bazel
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/register.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/metrics/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/hold/hold.go
  vendor/k8s.io/test-infra/prow/plugins/override/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#222 ci-operator: Update the upgrade template to match release
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/XL

#226 cmd/blocking-issue-creator: Use "Failed to ..." for all failing errors
  cmd/blocking-issue-creator/main.go
Labels: approved, lgtm, size/XS

#227 cmd/blocking-issue-creator: Log reason for skipping a config
  cmd/blocking-issue-creator/main.go
Labels: approved, lgtm, size/XS

#225 [prowgen] Introduce prowgen configuration files.
  cmd/ci-operator-prowgen/main.go
  pkg/config/load.go
  test/prowgen-integration/data/input/config/private/duper/.config.prowgen
  test/prowgen-integration/data/input/config/private/duper/private-duper-master.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#228 [prowgen] Manually inject private bucket on decoration config of private jobs
  cmd/ci-operator-prowgen/main.go
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
Labels: approved, lgtm, size/M

#231 cmd/ipi-deprovision: Shuffle cluster IDs
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#229 Specify context name of kubeconfig in applyConfig
  cmd/applyconfig/README.md
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
Labels: approved, lgtm, size/L

#233 pkg/api: use strongly-typed constants
  pkg/api/types.go
Labels: approved, lgtm, size/M

#238 Improve the format of error msg for applyConfig
  cmd/applyconfig/applyconfig.go
Labels: approved, lgtm, size/XS

#240 ci-operator: use configresolver for all repos
  pkg/load/load.go
  pkg/load/load_test.go
Labels: approved, lgtm, size/M

#241 Import initial release into test namespace correctly
  pkg/steps/release/create_release.go
Labels: approved, lgtm, size/XS

#243 remove decoration config injection to private jobs.
  cmd/ci-operator-prowgen/main.go
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
Labels: approved, lgtm, size/M

#239 Read and cache prowgen configs in prowgen
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/config/load.go
  pkg/config/load_test.go
  test/prowgen-integration/data/input/config/private-org/.config.prowgen
  test/prowgen-integration/data/input/config/private-org/duper/private-org-duper-master.yaml
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#246 pkg/load/configAgent: make some functions more generic
  pkg/load/agent_utils.go
  pkg/load/configAgent.go
Labels: approved, lgtm, size/L

#245 types: consolidate api.LiteralTestStep & steps/types.TestStep
  pkg/api/config.go
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/types/types.go
Labels: approved, lgtm, size/L
