Repository openshift/ci-tools, pull requests merged in 2019-09, with the labels that each got.

#96 Refactor artifacts container injection to a template pod
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#104 ci-operator multi-stage: dry-run mode
  pkg/steps/multi_stage.go
Labels: approved, lgtm, size/S

#107 Revert "Refactor artifacts container injection to a template pod"
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#108 Refactor artifacts container injection to a template pod
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#109 Introduce a dry run logger to ci-operator
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/testing.go
  pkg/steps/testing_test.go
Labels: approved, lgtm, size/L

#111 Revert "Refactor artifacts container injection to a template pod"
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#105 ci-operator multistage: implement chains
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
Labels: approved, lgtm, size/L

#106 ci-operator: add validation
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm, size/M

#116 clusterinstall: sync upstream template
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/L

#117 OWNERS: add AlexNPavel
  OWNERS
Labels: approved, lgtm, size/XS

#110 ci-operator multi-stage: gather artifacts
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm, size/L

#113 ci-operator: implement multi stage test workflows
  pkg/api/config.go
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
Labels: approved, lgtm, size/L

#121 pkg/api/config.go: use apimachinery's DNS 1123 subdomain check for Secret names
  pkg/api/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#91 Implement autobumper for release repo
  cmd/autobumper/main.go
  images/autobumper/Dockerfile
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/BUILD.bazel
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/experiment/image-bumper/bumper/BUILD.bazel
  vendor/k8s.io/test-infra/experiment/image-bumper/bumper/bumper.go
  vendor/k8s.io/test-infra/robots/pr-creator/updater/BUILD.bazel
  vendor/k8s.io/test-infra/robots/pr-creator/updater/updater.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#122 Use openshift-bot in autobumper
  cmd/autobumper/main.go
Labels: approved, lgtm, size/XS

#118 ci-operator multistage: add loading code for registry
  pkg/api/types.go
  pkg/load/load.go
  pkg/load/load_test.go
  test/multistage-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  test/multistage-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.yaml
  test/multistage-registry/ipi/deprovision/ipi-deprovision-chain.yaml
  test/multistage-registry/ipi/deprovision/must-gather/ipi-deprovision-must-gather-commands.sh
  test/multistage-registry/ipi/deprovision/must-gather/ipi-deprovision-must-gather-ref.yaml
  test/multistage-registry/ipi/install/install/ipi-install-install-commands.sh
  test/multistage-registry/ipi/install/install/ipi-install-install-ref.yaml
  test/multistage-registry/ipi/install/ipi-install-chain.yaml
  test/multistage-registry/ipi/install/rbac/ipi-install-rbac-commands.sh
  test/multistage-registry/ipi/install/rbac/ipi-install-rbac-ref.yaml
  test/multistage-registry/ipi/ipi-workflow.yaml
Labels: approved, lgtm, size/L

#125 Inject auth info into git-commit command
  cmd/autobumper/main.go
Labels: approved, lgtm, size/XS

#119 Upgrade k8s.io/test-infra
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/plugins/label/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/label/label.go
  vendor/k8s.io/test-infra/robots/pr-creator/updater/updater.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#126 Fix the https remote url
  cmd/autobumper/main.go
Labels: approved, lgtm, size/XS

#129 Upgrade k8s.io/test-infra
  cmd/autobumper/main.go
  go.mod
  go.sum
  vendor/github.com/prometheus/procfs/arp.go
  vendor/github.com/prometheus/procfs/crypto.go
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/internal/util/parse.go
  vendor/github.com/prometheus/procfs/internal/util/sysreadfile.go
  vendor/github.com/prometheus/procfs/internal/util/sysreadfile_compat.go
  vendor/github.com/prometheus/procfs/internal/util/valueparser.go
  vendor/github.com/prometheus/procfs/net_softnet.go
  vendor/github.com/prometheus/procfs/proc.go
  vendor/github.com/prometheus/procfs/proc_fdinfo.go
  vendor/github.com/prometheus/procfs/schedstat.go
  vendor/github.com/prometheus/procfs/vm.go
  vendor/github.com/prometheus/procfs/zoneinfo.go
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/BUILD.bazel
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghpath.go
  vendor/k8s.io/test-infra/prow/clonerefs/options.go
  vendor/k8s.io/test-infra/prow/clonerefs/run.go
  vendor/k8s.io/test-infra/prow/gcsupload/run.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#130 Add the `fail` field in clonerefs options.
  go.mod
  go.sum
  pkg/steps/source.go
  pkg/steps/source_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/M

#134 Remove flags of autoowners from dependencies
  cmd/autoowners/README.md
  cmd/autoowners/main.go
Labels: approved, lgtm, size/M

#135 Add ignore-repo flag in autoowners README.md
  cmd/autoowners/README.md
  cmd/autoowners/main.go
Labels: approved, lgtm, size/XS

#137 Fix the commit msg in autoowners
  cmd/autoowners/main.go
Labels: approved, lgtm, size/XS

#142 config-brancher: Only bump the fields actually present in the config
  cmd/config-brancher/main.go
Labels: approved, lgtm, size/XS

#140 Update Prow config paths
  cmd/autobumper/main.go
  pkg/config/release.go
  pkg/diffs/diffs.go
  test/pj-rehearse-integration/candidate/core-services/prow/02_config/_config.yaml
  test/pj-rehearse-integration/master/core-services/prow/02_config/_config.yaml
  test/pj-rehearse-integration/master/core-services/prow/02_config/_plugins.yaml
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm, size/S

#144 ci-operator: Update install template to have latest settings
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/S

#145 Handle errors from DeepCopy()
  pkg/diffs/diffs_test.go
Labels: approved, lgtm, size/L

#148 pkg/load_test.go: use reflect.DeepEqual
  pkg/load/load_test.go
Labels: approved, lgtm, size/M

#103 Add ci-operator integration tests
  Makefile
  cmd/ci-operator/main.go
  pkg/steps/input_image_tag.go
  pkg/steps/output_image_tag.go
  pkg/steps/source.go
  pkg/steps/testing.go
  test/ci-operator-integration/config/test-config.yaml
  test/ci-operator-integration/config/test-template.yaml
  test/ci-operator-integration/expected_files/expected.json
  test/ci-operator-integration/expected_files/expected_with_template.json
  test/ci-operator-integration/run.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#149 Upgrade k8s.io/test-infra
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/bugzilla/BUILD.bazel
  vendor/k8s.io/test-infra/prow/bugzilla/fake.go
  vendor/k8s.io/test-infra/prow/bugzilla/status.go
  vendor/k8s.io/test-infra/prow/bugzilla/types.go
  vendor/k8s.io/test-infra/prow/clonerefs/options.go
  vendor/k8s.io/test-infra/prow/interrupts/BUILD.bazel
  vendor/k8s.io/test-infra/prow/interrupts/interrupts.go
  vendor/k8s.io/test-infra/prow/kube/prowjob.go
  vendor/k8s.io/test-infra/prow/pjutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pjutil/health.go
  vendor/k8s.io/test-infra/prow/pjutil/pprof.go
  vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/k8s.io/test-infra/prow/repoowners/BUILD.bazel
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#146 Use a data structure with more metadata for storing config
  cmd/pj-rehearse/main.go
  pkg/config/load.go
  pkg/config/load_test.go
  pkg/config/release.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
Labels: approved, lgtm, size/L

#147 ci-operator: make the artifact worker testable
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/template.go
Labels: approved, lgtm, size/L

#143 Don't add extraRefs if the job belongs to the same org/repo with refs.
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/L

#150 Upgrade k8s.io/test-infra
  go.mod
  go.sum
  vendor/github.com/prometheus/procfs/buddyinfo.go
  vendor/github.com/prometheus/procfs/cpuinfo.go
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/proc_status.go
  vendor/github.com/prometheus/procfs/schedstat.go
  vendor/k8s.io/test-infra/prow/plugins/label/label.go
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#139 Ignore the repo with no OWNERS file in the upstream repo
  cmd/autoowners/README.md
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#152 Add debug logs into autoowners
  cmd/autoowners/main.go
Labels: approved, lgtm, size/XS

#151 Add testing section in autoowners README
  cmd/autoowners/README.md
Labels: approved, lgtm, size/S

#153 sort keys when comparing the files in ci-op integration tests
  test/ci-operator-integration/run.sh
Labels: approved, lgtm, size/XS

#154 fix jq 1.5 flag in integration tests script
  test/ci-operator-integration/run.sh
Labels: approved, do-not-merge/hold, lgtm, size/XS

#155 integration: Add sorting command and update expected files
  test/ci-operator-integration/expected_files/expected.json
  test/ci-operator-integration/expected_files/expected_with_template.json
  test/ci-operator-integration/run.sh
Labels: approved, lgtm, size/XXL

#156 Use HideSecretsWriter as stderr for git-status command
  cmd/autoowners/main.go
Labels: approved, lgtm, size/S

#157 Fix logs for changeDir
  cmd/autobumper/main.go
  cmd/autoowners/main.go
Labels: approved, lgtm, size/XS

#124 Refactor artifacts container injection to Template pods.
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  pkg/steps/testing.go
  test/ci-operator-integration/config/test-template.yaml
  test/ci-operator-integration/expected_files/expected_with_template.json
Labels: approved, lgtm, size/XL

#158 Refactor away more compound configuration usage
  cmd/pj-rehearse/main.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
Labels: approved, lgtm, size/S

#159 Remove unused loggers
  cmd/pj-rehearse/main.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
Labels: approved, lgtm, size/S

#160 Remove compound type entirely
  cmd/pj-rehearse/main.go
  pkg/config/load.go
  pkg/config/load_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/metrics.go
  pkg/rehearse/metrics_test.go
Labels: approved, lgtm, size/L

#162 Remove the commit releated header in OWNERS file
  cmd/autoowners/main.go
Labels: approved, lgtm, size/S

#164 Add Dockerfile for auto-config-brancher
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm, size/S

#165 ci-operator multi-stage: add integration test
  Makefile
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  test/ci-operator-integration/base/config/test-config.yaml
  test/ci-operator-integration/base/config/test-template.yaml
  test/ci-operator-integration/base/expected_files/expected.json
  test/ci-operator-integration/base/expected_files/expected_with_template.json
  test/ci-operator-integration/base/run.sh
  test/ci-operator-integration/multi-stage/config.yaml
  test/ci-operator-integration/multi-stage/expected.json
  test/ci-operator-integration/multi-stage/run.sh
Labels: approved, lgtm, size/XXL

#166 Refactor labels injection and add tests.
  pkg/steps/template.go
  pkg/steps/template_test.go
Labels: approved, lgtm, size/M

#161 Add a tool to trigger images postsubmits from changes
  cmd/ci-operator/main.go
  cmd/config-change-trigger/main.go
  cmd/config-change-trigger/main_test.go
  cmd/pj-rehearse/main.go
  go.mod
  images/config-change-trigger/Dockerfile
  pkg/config/release.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/util/client.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#94 Inject resources in template pod's container named "test"
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  test/ci-operator-integration/base/config/test-config.yaml
  test/ci-operator-integration/base/config/test-template.yaml
  test/ci-operator-integration/base/expected_files/expected_with_template.json
Labels: approved, lgtm, size/L

#167 Add tool auto-config-brancher
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm, size/L

#169 Ignore the changes on modules.txt
  Makefile
Labels: approved, lgtm, size/XS

#168 Build auto-config-brancher image with its binary
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm, size/XS

#163 Add ci-operator-configresolver
  Makefile
  cmd/ci-operator-configresolver/main.go
  test/ci-operator-configresolver-integration/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
  test/ci-operator-configresolver-integration/run.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#174 correction of misspelled words and yaml fields.
  cmd/ci-operator/main.go
  cmd/ipi-deprovision/ipi-deprovision.sh
  pkg/api/types.go
  test/artifact/test.yaml
Labels: approved, lgtm, size/S

#175 Staticcheck nits corrections
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator/main.go
  pkg/api/config.go
  pkg/api/graph.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/pod.go
  pkg/steps/source.go
Labels: approved, lgtm, size/M

#176 Fix getOwnersHTTP in autoowners
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm, size/L

#172 Add options of github endpoints to auto-tools
  cmd/autobumper/main.go
  cmd/autoconfigbrancher/main.go
  cmd/autoowners/README.md
  cmd/autoowners/main.go
Labels: approved, lgtm, size/L

#179 Add a Dockerfile to build blocking-issue-creator
  cmd/blocking-issue-creator/main.go
  images/blocking-issue-creator/Dockerfile
Labels: approved, lgtm, size/XS

#180 Install git for the postsubmit change trigger
  images/config-change-trigger/Dockerfile
  images/pj-rehearse/Dockerfile
Labels: approved, lgtm, size/XS

#181 Grab base config from one commit back
  cmd/config-change-trigger/main.go
Labels: approved, lgtm, size/XS

#185 Ask GitHub for the correct ref
  cmd/config-change-trigger/main.go
  cmd/config-change-trigger/main_test.go
Labels: approved, lgtm, size/S

#184 Ignore a job that is not sharded by version
  cmd/testgrid-config-generator/main.go
  test/testgrid-config-generator/config/release/ocp-4.2.json
  test/testgrid-config-generator/config/release/okd-4.1.json
  test/testgrid-config-generator/config/release/okd-4.2.json
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-okd-release-4.1-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-okd-release-4.2-informing.yaml
Labels: approved, lgtm, size/M

#173 ci-op-configresolver: add fsnotify and periodic reloaders
  Makefile
  cmd/ci-operator-configresolver/main.go
  go.mod
  pkg/coalescer/coalescer.go
  pkg/coalescer/coalescer_test.go
  pkg/load/configAgent.go
  test/ci-operator-configresolver-integration/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
  test/ci-operator-configresolver-integration/run.sh
Labels: approved, lgtm, size/L

#171 ci-operator multi-stage: create secret
  Makefile
  cmd/ci-operator/main.go
  cmd/secret-wrapper/main.go
  images/secret-wrapper/Dockerfile
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/util/secret.go
  test/ci-operator-integration/multi-stage/expected.json
  test/secret-wrapper-integration.sh
Labels: approved, lgtm, size/XL, ¯\_(ツ)_/¯

#177 Add script to generate Jira report
  hack/jira.py
Labels: approved, lgtm, size/M

#178 Allow ci-operator to build/clone from private repositories
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/git_source.go
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm, size/L
