Repository openshift/ci-tools, pull requests merged in 2019-11, with the labels that each got.

#204 Lease client
  cmd/ci-operator/main.go
  go.sum
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/lease/client.go
  pkg/lease/client_test.go
  pkg/lease/fake.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/go-multierror/.travis.yml
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/k8s.io/test-infra/boskos/client/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/client/README.md
  vendor/k8s.io/test-infra/boskos/client/client.go
  vendor/k8s.io/test-infra/boskos/common/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/common/common.go
  vendor/k8s.io/test-infra/boskos/common/config.go
  vendor/k8s.io/test-infra/boskos/common/mason_config.go
  vendor/k8s.io/test-infra/boskos/storage/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/storage/storage.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#250 pkg/load: propagate filepath.Walk errors
  pkg/load/load.go
Labels: approved, lgtm, size/XS

#251 pkg/load: add registryAgent
  pkg/load/registryAgent.go
Labels: approved, lgtm, size/L

#253 ci-operator: use lease step for templates
  pkg/api/types.go
  pkg/defaults/defaults.go
Labels: approved, lgtm, size/M

#255 pkg/api: fix Azure profile strings
  pkg/api/types.go
Labels: approved, lgtm, size/XS

#258 Add a tool to determinize prow configuration
  cmd/determinize-prow-config/main.go
  images/determinize-prow-config/Dockerfile
  pkg/config/release.go
Labels: approved, do-not-merge/hold, lgtm, size/M

#259 Ignore the cluster param in prowgen
  GENERATOR.md
  pkg/jobconfig/files.go
Labels: approved, lgtm, size/XS

#260 Fix import ordering
  cmd/determinize-prow-config/main.go
Labels: approved, lgtm, size/XS

#262 prowgen: Generate private jobs as `hidden: true`
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
Labels: approved, lgtm, size/M

#263 Use the exposed resolver address
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/M

#252 Added the ability to attach custom prow metadata to ci-operator jobs.
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
Labels: approved, lgtm, size/L

#264 Allow individual repos to enter branch cut early
  pkg/promotion/promotion.go
  pkg/promotion/promotion_test.go
Labels: approved, lgtm, size/S

#268 pkg/load: add validation during registry loading
  pkg/load/agent_utils.go
  pkg/load/load.go
  test/ci-operator-configresolver-integration/run.sh
Labels: approved, lgtm, size/M

#269 Add ovirt as a cluster profile
  CONFIGURATION.md
  cmd/ci-operator-prowgen/main.go
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#270 pkg/lease: increase mutual exclusion
  pkg/lease/client.go
Labels: approved, lgtm, size/XS

#266 pkg/api: validate configuration is fully-resolved
  cmd/ci-operator/main.go
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm, size/L

#271 Add kubeconfig arg to ci-operator
  CONFIGURATION.md
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/util/client.go
  pkg/util/client_test.go
Labels: approved, lgtm, size/L

#272 prowgen: Generate promoting postsubmit on only additional_images
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#273 Validate flags in the configresolver, add a validator mode
  cmd/ci-operator-configresolver/main.go
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#276 Allow README and OWNERS in registry directories
  pkg/load/load.go
  test/ci-operator-configresolver-integration/configs/README.md
  test/ci-operator-configresolver-integration/configs2/OWNERS
  test/multistage-registry/registry/README.md
  test/multistage-registry/registry2/OWNERS
Labels: approved, lgtm, size/XS

#278 configresolver: make registry work with configmap mounts
  cmd/ci-operator-configresolver/main.go
  pkg/load/configAgent.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/load/registryAgent.go
  test/multistage-registry/configmap/..2019_11_15_19_57_20.547184898/invalid-ref.yaml
  test/multistage-registry/configmap/..2019_11_15_19_57_20.547184898/ipi-install-install-commands.sh
  test/multistage-registry/configmap/..2019_11_15_19_57_20.547184898/ipi-install-install-ref.yaml
  test/multistage-registry/configmap/..data
  test/multistage-registry/configmap/ipi-install-install-commands.sh
  test/multistage-registry/configmap/ipi-install-install-ref.yaml
Labels: approved, lgtm, size/L

#274 Use kubuconfig arg with prowgen
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/M

#283 Add a nil check to the registry load code
  pkg/load/load.go
Labels: approved, lgtm, size/XS

#281 Remove warning on job name length
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/XS

#280 Update with custom metadata during CI job failure.
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#287 convert metadata revision to string and refactor the tests
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
Labels: approved, lgtm, size/L

#286 Default artifacts directory, set env
  pkg/api/config.go
  pkg/api/types.go
  pkg/steps/artifacts.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  test/ci-operator-integration/base/expected_files/expected.json
Labels: approved, lgtm, size/L

#292 Update ONBOARD.md
  ONBOARD.md
Labels: approved, lgtm, ok-to-test, size/XS

#289 prowgen: build all promoted images in `images` presubmits
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
Labels: approved, lgtm, size/L

#293 Revert "Default artifacts directory, set env"
  pkg/api/config.go
  pkg/api/types.go
  pkg/steps/artifacts.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  test/ci-operator-integration/base/expected_files/expected.json
Labels: approved, lgtm, size/L

#295 Re-revert defaulting PR
  pkg/api/config.go
  pkg/api/types.go
  pkg/steps/artifacts.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  test/ci-operator-integration/base/config/test-config.yaml
  test/ci-operator-integration/base/expected_files/expected.json
Labels: approved, lgtm, size/L

#296 cmd/autoowners/README: openshift/origin link and other cleanup
  cmd/autoowners/README.md
Labels: approved, lgtm, size/S

#290 Create pull secret for importing is from api.ci
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M

#297 ci-operator: Update the embedded template to the latest
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/L

#277 prowgen: add --lease-server to one test type
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/S

#265 Add an interactive tool to bootstrap a repo's config
  Makefile
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  images/repo-init/Dockerfile
  pkg/api/types.go
  pkg/config/load.go
  pkg/diffs/diffs.go
  test/repo-init-integration/expected/Makefile
  test/repo-init-integration/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/repo-init-integration/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
  test/repo-init-integration/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
  test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/repo-init-integration/expected/core-services/prow/02_config/_config.yaml
  test/repo-init-integration/expected/core-services/prow/02_config/_plugins.yaml
  test/repo-init-integration/input/Makefile
  test/repo-init-integration/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/repo-init-integration/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
  test/repo-init-integration/input/core-services/prow/02_config/_config.yaml
  test/repo-init-integration/input/core-services/prow/02_config/_plugins.yaml
  test/repo-init-integration/run.sh
Labels: approved, lgtm, size/XXL

#298 Replace SA builder with ci-operator
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  test/ci-operator-integration/base/expected_files/expected.json
  test/ci-operator-integration/base/expected_files/expected_with_template.json
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
Labels: approved, lgtm, size/L
