Repository openshift/ci-tools, pull requests merged in 2020-08, with the labels that each got.

#1059 Configresoler integration test: Check for exact number of rev changes
  hack/lib/integration.sh
  pkg/load/agents/configAgent.go
  pkg/load/agents/registryAgent.go
  pkg/load/agents/utils.go
  test/integration/ci-operator-configresolver.sh
Labels: approved, lgtm

#1063 [autopublicizeconfig] allow validation to change the options
  cmd/autopublicizeconfig/main.go
Labels: approved, lgtm

#1064 Order clones by Target Release
  pkg/backporter/backporter.go
Labels: approved, lgtm

#1065 Pkg/Steps: Use fixture-based tests
  pkg/steps/multi_stage_test.go
  pkg/steps/pod_test.go
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
  pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_no_secret_results_in_no_mounted_secrets.yaml
  pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_artifacts__secret_name_and_path_results_in_multiple_mounts.yaml
  pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_memory_backed_volume_gets_a_volume.yaml
  pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_secret_name_and_path_results_in_mounted_secret_with_custom_path.yaml
  pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_secret_name_results_in_secret_mounted_with_default_path.yaml
  pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_no_secret_results_in_no_mounted_secrets.yaml
  pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_artifacts__secret_name_and_path_results_in_multiple_mounts.yaml
  pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_memory_backed_volume_gets_a_volume.yaml
  pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_secret_name_and_path_results_in_mounted_secret_with_custom_path.yaml
  pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_secret_name_results_in_secret_mounted_with_default_path.yaml
Labels: approved, lgtm

#1066 Test images distributor: use 20 instead of 1 worker
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#1062 Simplify usage of registry and config agent
  cmd/ci-operator-configresolver/main.go
  cmd/dptp-controller-manager/main.go
  pkg/coalescer/coalescer.go
  pkg/coalescer/coalescer_test.go
  pkg/load/agents/configAgent.go
  pkg/load/agents/registryAgent.go
Labels: approved, lgtm

#1067 Test image distribution controller: Only allow certain registries
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1068 perform a merge when depth is shallow out and push was still failing
  cmd/private-org-sync/main.go
Labels: approved, lgtm

#1073 ci-operator: explicitly name ephemeral releases
  CONFIGURATION.md
  cmd/ci-operator-prowgen/main_test.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/release/create_release.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-release-3.11.yaml
Labels: approved, lgtm

#1075 Revert "ci-operator: explicitly name ephemeral releases"
  CONFIGURATION.md
  cmd/ci-operator-prowgen/main_test.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/release/create_release.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-release-3.11.yaml
Labels: approved

#1076 ci-operator: allow origin-v3.11 release version
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/release/create_release.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-release-3.11.yaml
Labels: approved, lgtm

#1072 pkg/load/agents: expand critical section
  pkg/load/agents/configAgent.go
  pkg/load/agents/configAgent_test.go
  pkg/load/agents/registryAgent.go
  test/integration/ci-operator-configresolver.sh
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-regChange.json
  test/integration/pj-rehearse/expected.yaml
  test/multistage-registry/registry2/ipi/install/empty-parameter/ipi-install-empty-parameter-chain.yaml
  test/multistage-registry/registry2/ipi/install/install/ipi-install-install-ref.yaml
  test/multistage-registry/registry2/ipi/install/with-parameter/ipi-install-with-parameter-chain.yaml
Labels: approved, lgtm

#1081 [publicize] exit with error if merge won't succeed
  cmd/publicize/server.go
Labels: approved, lgtm

#1070 Update controller-runtime and test-infra dependencies
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  vendor/k8s.io/test-infra/prow/entrypoint/run.go
  vendor/k8s.io/test-infra/prow/plugins/approve/approve.go
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/owners.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/downwardapi/jobspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/wrapper/options.go
  vendor/k8s.io/test-infra/prow/sidecar/run.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/VERSIONING.md
  vendor/sigs.k8s.io/controller-runtime/alias.go
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/leaderelection/leader_election.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/predicate/predicate.go
  vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/http.go
Labels: approved, lgtm

#1080 DPTP-CM: Fix typo, opeartor->operator
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#1083 Revert "ci-operator: allow origin-v3.11 release version"
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/release/create_release.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-release-3.11.yaml
Labels: approved

#1082 perform a merge --abort when merge is not possible
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#1079 Add info box to show missing clones
  pkg/backporter/backporter.go
  pkg/backporter/backporter_test.go
Labels: approved, lgtm

#1069 fix link in successful publicize message
  cmd/publicize/server.go
Labels: approved, lgtm

#1074 Keep ssh bastion jobs on api.ci
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/jobconfig/files.go
Labels: approved, lgtm

#1086 [publicize] extend unittest coverage to cover also the git operations
  cmd/publicize/server_test.go
Labels: approved, lgtm

#1087 pj-rehearse: don't remove unnecessary flags on accident
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm

#1077 Add secret syncer to dptp-controller-manager
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  cmd/dptp-controller-manager/main.go
  hack/run-dptp-controller-manager.sh
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/controller/secretsyncer/README.md
  pkg/controller/secretsyncer/config/agent.go
  pkg/controller/secretsyncer/config/agent_test.go
  pkg/controller/secretsyncer/config/config.go
  pkg/controller/secretsyncer/config/config_test.go
  pkg/controller/secretsyncer/secretsyncer.go
  pkg/controller/secretsyncer/secretsyncer_test.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/util/client.go
Labels: approved, lgtm

#1091 [private-org-sync] change git merge commit message
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#1090 improve publicize message responses and commits
  cmd/publicize/server.go
  cmd/publicize/server_test.go
Labels: approved, lgtm

#1017 Add ocp build data enforcer
  cmd/ocp-build-data-enforcer/README.md
  cmd/ocp-build-data-enforcer/main.go
  cmd/ocp-build-data-enforcer/main_test.go
  cmd/ocp-build-data-enforcer/types.go
  cmd/ocp-build-data-enforcer/types_test.go
Labels: approved, lgtm, tide/merge-method-squash

#1088 DPTP-CM: Use null logger to require less memory
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#1092 Secret syncer: Fix recreate functionality
  pkg/controller/secretsyncer/secretsyncer.go
Labels: approved, lgtm

#1089 Only enq changed imagestreamtags on imagestream update event
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/util/imagestreamtagmapper/imagestreamtagmapper.go
  pkg/util/imagestreamtagmapper/imagestreamtagmapper_test.go
Labels: approved, lgtm

#1094 Dptp-cm: Add flag for block profile sampling
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#1095 [publicize] include a link to the direct merge commit in the success message
  cmd/publicize/server.go
  cmd/publicize/server_test.go
Labels: approved, lgtm

#1096 Reduce test-images-distributor controller workers back to 1
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#1101 disable the failing custom-release e2e test
  test/e2e/simple.sh
Labels: approved, lgtm

#1098 ci-operator: expose ephemeral cluster versions based on parents
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
Labels: approved, lgtm

#1099 fix git-version-dependent tests in publicize tool
  cmd/publicize/server_test.go
Labels: approved, lgtm

#1097 [private-org-sync] don't fail on merge conflict errors, instead print a warning
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#1044 ci-operator: allow users to depend on images in steps
  cmd/cvp-trigger/main.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/release_images.go
  pkg/steps/utils/env.go
  pkg/steps/utils/env_test.go
  pkg/webreg/webreg.go
  test/e2e/multi-stage.sh
  test/e2e/multi-stage/dependencies.yaml
Labels: approved, lgtm

#1102 Specify registry-config for oc adm release command
  pkg/defaults/defaults.go
  pkg/steps/release/import_release.go
  test/e2e/simple.sh
Labels: approved, lgtm

#1105 blocking-issue-creator: block merges to current-release too
  cmd/blocking-issue-creator/main.go
Labels: approved, lgtm

#1023 pkg/load: partially validate registry contents
  cmd/ci-operator-configresolver/main.go
  pkg/load/load.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  test/integration/ci-operator-configresolver.sh
Labels: approved, lgtm

#1106 OCP build data enforcer: Add pr creation capabilities
  cmd/ocp-build-data-enforcer/main.go
  cmd/ocp-build-data-enforcer/main_test.go
  cmd/ocp-build-data-enforcer/types.go
  cmd/ocp-build-data-enforcer/types_test.go
  pkg/api/ocpbuilddata/types.go
  pkg/api/ocpbuilddata/types_test.go
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm

#1085 Auto detect source bug for create clones
  cmd/bugzilla-backporter/main.go
  pkg/backporter/backporter.go
  pkg/backporter/backporter_test.go
Labels: approved, lgtm

#1109 upgrade: annotate prowjob with version info
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#1100 Add dependence tree to backporter UI
  pkg/backporter/backporter.go
  pkg/backporter/backporter_test.go
Labels: approved, lgtm

#1110 ci-operator: steps: importing a release creates the stream
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#1112 upgrade tempalate: use $BRANCH since it's already set
  pkg/steps/clusterinstall/template.go
Labels: approved

#1115 clusterinstall: fix template
  pkg/steps/clusterinstall/template.go
Labels: approved

#1093 Registry replacer: Update dockerfiles from ocp-build-data
  cmd/registry-replacer/README.md
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Context_dir_gets_fixed_up.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Dockerfile_gets_fixed_up.yaml
  pkg/api/ocpbuilddata/types.go
Labels: approved, lgtm

#1114 Test image distributor: Better cover rehaersals when streams get updated
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1084 ci-operator: add support for building operator index images
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/bundle_source.go
  pkg/steps/bundle_source_test.go
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
  pkg/steps/project_image.go
  test/e2e/simple.sh
  test/e2e/simple/optional-operators.yaml
  test/manifests/4.6/hive.crd.yaml
  test/manifests/4.6/image-references
  test/manifests/4.6/meteringconfig.crd.yaml
  test/manifests/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  test/manifests/4.6/prestotable.crd.yaml
  test/manifests/4.6/report.crd.yaml
  test/manifests/4.6/reportdatasource.crd.yaml
  test/manifests/4.6/reportquery.crd.yaml
  test/manifests/4.6/storagelocation.crd.yaml
  test/manifests/bundle.Dockerfile
  test/manifests/metadata/annotations.yaml
Labels: approved, lgtm

#1117 Builds: Set OPENSHIFT_CI variable
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
Labels: approved, lgtm

#1108 Make pr deploy maketargets easier to use
  Makefile
Labels: approved, lgtm

#1119 Registry replacer: Explain promotion dockerfile fixup
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#1122 Add Dockerfile for ocp-build-data-enforcer
  images/ocp-build-data-enforcer/Dockerfile
Labels: approved, lgtm

#1123 Enable ineffassign and misspell linters
  .golangci.yml
  cmd/autoconfigbrancher/main.go
  cmd/autoowners/main.go
  cmd/ci-operator/main_test.go
  cmd/ocp-build-data-enforcer/main.go
  cmd/ocp-build-data-enforcer/main_test.go
  cmd/pj-rehearse/main.go
  cmd/private-org-sync/main.go
  cmd/prow-job-dispatcher/main.go
  cmd/registry-replacer/main.go
  cmd/testgrid-config-generator/main.go
  pkg/backporter/backporter.go
  pkg/config/jobs.go
  pkg/controller/util/request_coalescer.go
  pkg/dispatcher/prometheus.go
  pkg/release/candidate/client_test.go
  pkg/release/official/client_test.go
  pkg/release/prerelease/client_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1124 Fix ocp-build-data-enforcer Dockerfile
  images/ocp-build-data-enforcer/Dockerfile
Labels: approved, lgtm

#1060 Secret generator tool
  cmd/ci-secret-generator/README.md
  cmd/ci-secret-generator/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
  pkg/bitwarden/fake.go
Labels: approved, lgtm, tide/merge-method-squash

#1121 Fix ceiling setting of ocp-build-data-enforcer
  cmd/ocp-build-data-enforcer/main.go
Labels: approved, lgtm

#1127 PRCreation: Add missing self-approve flag
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm

#1131 WIP: add continous watcher to monitor the jobs
  pkg/steps/clusterinstall/template.go
Labels: do-not-merge/work-in-progress, lgtm

#1129 image distributor: use local image reference policy
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1135 Fix steps, this causes build failures
  pkg/steps/clusterinstall/template.go
Labels: approved

#1138 bitwarden: make the client more resilient
  pkg/bitwarden/cli.go
Labels: approved, lgtm

#1132 e2e: use import secrets always
  pkg/steps/template.go
  test/e2e/simple.sh
Labels: approved

#1133 Update test-infra to 859d15fc4364265500611c3c137d6dd610dafbcf
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/bugzilla/BUILD.bazel
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/bugzilla/fake.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/git/git.go
  vendor/k8s.io/test-infra/prow/hook/BUILD.bazel
  vendor/k8s.io/test-infra/prow/initupload/run.go
  vendor/k8s.io/test-infra/prow/logrusutil/logrusutil.go
  vendor/k8s.io/test-infra/prow/pjutil/filter.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
  vendor/modules.txt
Labels: approved, lgtm

#1139 pkg/steps/clusterinstall/template: Fix resourcewatch jsonpath quote
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#1147 resourcewatch: copy output into resourcewatch.log
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#1141 e2e: use import secrets always
  test/e2e/multi-stage.sh
  test/e2e/simple.sh
Labels: approved, lgtm

#1145 PRcreation: Also set commiter name
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm

#1149 Detect failed pods better
  pkg/steps/template.go
Labels: approved, lgtm

#1120 Add the job-release annotation
  pkg/jobconfig/files.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_specific_release.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_fourth.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-job-release.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-job-release-periodics.yaml
Labels: approved, lgtm

#1137 ci-secret-generator: quality-of-life fixes
  cmd/ci-secret-generator/main.go
Labels: approved, lgtm

#1150 Secret Bootstrap: Finish processing valid secrets before failing when encountering errors
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm

#1143 webreg: document configuration sharding
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1148 Secret syncer: Keep existing fields not in source secret
  pkg/controller/secretsyncer/secretsyncer.go
  pkg/controller/secretsyncer/secretsyncer_test.go
Labels: approved, lgtm

#1153 Update test-infra to 43b6c04
  cmd/autobumper/main.go
  go.mod
  go.sum
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/BUILD.bazel
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/experiment/image-bumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/bugzilla/types.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/kube/BUILD.bazel
  vendor/k8s.io/test-infra/prow/kube/config.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/slackevents/slackevents.go
  vendor/k8s.io/test-infra/prow/plugins/updateconfig/README.md
  vendor/k8s.io/test-infra/prow/pod-utils/clone/clone.go
  vendor/modules.txt
Labels: approved, lgtm

#1158 ci-operator: create Pods with resolved refs
  pkg/defaults/defaults.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
Labels: approved, lgtm

#1163 Revert "ci-operator: create Pods with resolved refs"
  pkg/defaults/defaults.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
Labels: approved

#1160 ocp-build-data-enforcer: cleaup input path
  cmd/ocp-build-data-enforcer/main.go
Labels: approved, lgtm

#1161 pj-rehearse: fix misleading copy-pasted error message
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#1164 ci-operator: create imagestreams with local reference policy
  pkg/steps/release/release_images.go
Labels: approved, lgtm

#1154 Remove stale todo from ocp-build-data enforcer readme
  cmd/ocp-build-data-enforcer/README.md
Labels: approved, lgtm

#1168 e2e: don't require vars from the owning job
  test/e2e/simple.sh
Labels: approved, lgtm

#1165 Revert "Test image distribution controller: Only allow certain regist…
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1162 CI operator: Tolerate IsAlreadyExists when creating PDBs
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1159 ci-operator: allow overriding dependency definitions
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1166 Clarify that alternates to ocp-build-data prs are allowed
  cmd/ocp-build-data-enforcer/main.go
Labels: approved, lgtm

#1167 Secretsyncer: Verify per-key if secret is mangaged by ci-secret-boostrap
  pkg/controller/secretsyncer/secretsyncer.go
  pkg/controller/secretsyncer/secretsyncer_test.go
Labels: approved, lgtm

#1151 Secret bootstrapper: Respect existing secrets
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#1169 Prompotionreconciler: Only start once
  pkg/controller/promotionreconciler/prowjobreconciler/prowjobreconciler.go
Labels: approved, lgtm

#1171 Secretsyncer: Allow configuring a cluster
  pkg/controller/secretsyncer/config/agent_test.go
  pkg/controller/secretsyncer/config/config.go
  pkg/controller/secretsyncer/config/config_test.go
  pkg/controller/secretsyncer/secretsyncer.go
  pkg/controller/secretsyncer/secretsyncer_test.go
Labels: approved, lgtm

#1136 pkg/steps: some cleanups for index+bundle image building
  pkg/api/config.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/defaults/defaults.go
  pkg/steps/bundle_source.go
  pkg/steps/bundle_source_test.go
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
  pkg/steps/project_image.go
  pkg/steps/testdata/4.6-expected/another-manifest.yml
  pkg/steps/testdata/4.6-expected/meteringoperator.v4.6.0.clusterserviceversion.yaml
  pkg/steps/testdata/4.6-expected/not-a-manifest.txt
  pkg/steps/testdata/4.6/another-manifest.yml
  pkg/steps/testdata/4.6/not-a-manifest.txt
  test/e2e/simple.sh
  test/e2e/simple/optional-operators.yaml
Labels: approved, lgtm

#1125 Allow user to specify promotion namespace when do fast-forward
  cmd/repo-brancher/main_test.go
  pkg/promotion/promotion.go
  pkg/promotion/promotion_test.go
Labels: approved, lgtm

#1170 TestImageDistributor: Add setting for forbidden registries
  cmd/dptp-controller-manager/main.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1176 registry docs: cleanups
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1177 ipi-deprovision: always try all clusters
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#1181 ci-operator: artifacts: don't delete pods, handle missing container
  pkg/steps/artifacts.go
Labels: approved, lgtm

#1180 ci-operator: immediately print when a Pod fails to start
  pkg/steps/template.go
Labels: approved, lgtm

#1182 ci-operator: show commands in release creation
  pkg/steps/release/create_release.go
Labels: approved, lgtm

#1178 api/config: add support for using ci-index as step dependency
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm

#1183 ci-operator: build oo indices with `--mode semver`
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
Labels: approved, lgtm

#1185 simplifypath: handle root elements
  cmd/bugzilla-backporter/main.go
  cmd/ci-operator-configresolver/main.go
Labels: approved, lgtm
