Repository openshift/ci-tools, pull requests merged in 2020-05, with the labels that each got.

#738 Deflake configresolver integration test
  test/ci-operator-configresolver-integration/run.sh
Labels: approved, lgtm

#735 ci-operator: Only log errors if they haven't been written
  cmd/ci-operator/main.go
Labels: approved, lgtm

#744 autoconfigbrancher: restructure commands
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#733 ci-operator: initialize a lease client only when appropriate
  cmd/ci-operator/main.go
  test/ci-operator-integration/base/run.sh
  test/ci-operator-integration/multi-stage/run.sh
Labels: approved, lgtm

#743 ci-operator: add finer-grained error identifiers
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/interrupt/interrupt.go
  pkg/load/load.go
  pkg/results/results.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/input_image_tag.go
  pkg/steps/lease.go
  pkg/steps/multi_stage.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/write_params.go
Labels: approved, lgtm

#746 ci-operator: correctly default error reaons
  cmd/ci-operator/main.go
Labels: approved, lgtm

#748 ci-operator: fix an off-by-one bug in error handling
  cmd/ci-operator/main.go
Labels: approved, do-not-merge/hold, lgtm

#750 Bump lint timeout to 10m
  hack/lint.sh
Labels: approved, lgtm

#752 webreg: document RBAC for `base_images`
  pkg/webreg/webreg.go
Labels: approved, lgtm

#754 ci-operator multi-stage: omit empty ClusterProfile
  pkg/api/types.go
Labels: approved, lgtm

#747 Get rid of glog dependency
  cmd/ci-operator/main.go
  go.mod
  pkg/results/report.go
  pkg/steps/artifacts.go
  vendor/github.com/golang/glog/LICENSE
  vendor/github.com/golang/glog/README
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/modules.txt
Labels: approved, lgtm

#755 Move ci-op recursive config loading from pkg/load/agents to pkg/load
  pkg/load/agents/configAgent.go
  pkg/load/agents/configAgent_test.go
  pkg/load/load.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#756 hack: inject ldflags only on official builds
  hack/install.sh
Labels: approved, lgtm

#702 ImageStreamReconciler: Initial working implementation
  cmd/dptp-controller-manager/README.md
  cmd/dptp-controller-manager/main.go
  hack/run-dptp-controller-manager.sh
  pkg/api/types.go
  pkg/controller/image-stream-tag-reconciler/README.md
  pkg/controller/image-stream-tag-reconciler/prowjobreconciler/prowjobreconciler.go
  pkg/controller/image-stream-tag-reconciler/reconciler.go
  pkg/controller/image-stream-tag-reconciler/reconciler_test.go
  pkg/controller/image-stream-tag-reconciler/testdata/imagestreamtag.yaml
  pkg/controller/image-stream-tag-reconciler/testdata/ist_with_git_suffix.yaml
  pkg/load/agents/configAgent.go
  pkg/load/agents/configAgent_test.go
Labels: approved, lgtm

#757 Revert "add a list of conditions when operating in ci-operator configs"
  pkg/config/load.go
Labels: approved, lgtm

#758 Remove config-migrator
  cmd/config-migrator/README.md
  cmd/config-migrator/main.go
Labels: approved, lgtm

#760 ci-operator: return better errors on lease failures
  pkg/steps/lease.go
Labels: approved, lgtm

#762 lease: fix a typo in a failure reason
  pkg/steps/lease.go
Labels: approved, lgtm

#761 api: declare our directory structure and naming an api, use it
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-prowgen/main.go
  cmd/config-brancher/main_test.go
  cmd/config-change-trigger/main.go
  cmd/config-change-trigger/main_test.go
  cmd/determinize-ci-operator/main.go
  cmd/pj-rehearse/main.go
  cmd/private-org-sync/main_test.go
  cmd/private-prow-configs-mirror/main.go
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  pkg/api/metadata.go
  pkg/api/metadata_test.go
  pkg/config/load.go
  pkg/config/load_test.go
  pkg/config/options.go
  pkg/config/options_test.go
  pkg/config/release.go
  pkg/config/whitelist_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/jobconfig/files.go
  pkg/load/agents/configAgent.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm

#766 Build static binaries
  hack/install.sh
Labels: approved, lgtm

#765 Dptp controller manager: Allow using a dedicated prowjob cluster
  cmd/dptp-controller-manager/main.go
  images/dptp-controller-manager/Dockerfile
  pkg/config/release_test.go
  pkg/controller/image-stream-tag-reconciler/prowjobreconciler/prowjobreconciler.go
  pkg/controller/image-stream-tag-reconciler/reconciler.go
Labels: approved, lgtm

#763 [private-prow-configs-mirror] include whitelisted repos in private prow configs mirror
  cmd/private-prow-configs-mirror/main.go
Labels: approved, lgtm

#769 config-brancher: set branch correctly in metadata
  cmd/config-brancher/main.go
Labels: approved, lgtm

#770 prowgen: don't add flags with default values
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm

#771 ci-operator-configresolver: serve matching configurations
  cmd/ci-operator-configresolver/main.go
  pkg/api/metadata.go
  pkg/load/agents/configAgent.go
  pkg/load/agents/configAgent_test.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/webreg/webreg.go
  test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
Labels: approved, lgtm

#776 Fix flaky TestLoad complex input
  Makefile
  cmd/cvp-trigger/main_test.go
  pkg/load/load_test.go
Labels: approved, lgtm

#777 Rename ImageStreamTagReconciler to PromotionReconciler
  cmd/dptp-controller-manager/main.go
  hack/run-dptp-controller-manager.sh
  pkg/controller/promotionreconciler/README.md
  pkg/controller/promotionreconciler/prowjobreconciler/prowjobreconciler.go
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
  pkg/controller/promotionreconciler/testdata/imagestreamtag.yaml
  pkg/controller/promotionreconciler/testdata/ist_with_git_suffix.yaml
Labels: approved, lgtm

#772 add remote libvirt profile for ppc64le
  pkg/api/config.go
  pkg/api/types.go
  pkg/prowgen/prowgen.go
Labels: approved, lgtm

#764 [private-org-peribolos-sync] include whitelisted repos in peribolos sync
  cmd/private-org-peribolos-sync/main.go
Labels: approved, lgtm

#773 webreg: fix job page
  pkg/webreg/webreg.go
Labels: approved, lgtm

#774 webreg: improve graphs
  pkg/webreg/graphviz.go
  pkg/webreg/graphviz_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#775 Add helper to extract all ImageStreamTags for a test config
  go.mod
  pkg/api/helper/imageextraction.go
  pkg/api/helper/imageextraction_test.go
  pkg/api/types.go
Labels: approved, lgtm

#778 prowgen: separate multi-stage generation
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
Labels: approved, lgtm

#741 hack: add a script to grab a kubeconfig from a running cluster
  hack/extract-kubeconfig.sh
Labels: approved, lgtm

#780 extract-kubeconfig: update to use oc extract
  hack/extract-kubeconfig.sh
Labels: approved, lgtm

#779 ci-operator: support basic auth for result aggregator
  pkg/results/report.go
  pkg/results/report_test.go
Labels: approved, lgtm

#782 ci-operator: only load password when set
  pkg/results/report.go
Labels: approved, lgtm

#784 hack: expose production-install target
  Makefile
  hack/install.sh
Labels: approved, lgtm

#781 result-aggregator: handle basic auth in server
  cmd/result-aggregator/main.go
  pkg/results/report.go
Labels: approved, lgtm

#788 PJ rehearse: Allow using dedicated kubeconfig for prowjobs
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#785 ci-operator-prowgen: add report username and password
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm

#789 Fix result-aggregator flags
  cmd/result-aggregator/main.go
Labels: approved

#783 ci-operator: require basic auth for result aggregator
  cmd/result-aggregator/main.go
  pkg/results/report.go
Labels: approved, lgtm

#753 [private-org-sync] Include whitelisted org/repo/branches in synching
  cmd/private-org-sync/main.go
Labels: approved, lgtm

#790 Use app.ci configresolver
  cmd/ci-operator/main.go
Labels: approved, lgtm

#792 pass a whitelist file in the autoperibolos sync tool
  cmd/autoperibolossync/main.go
Labels: approved, lgtm

#793 pass whitelist file to the private sync tools in autoconfigbrancher
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#796 c-o-config-mirror: dont disable promotion for official image repos on whitelist
  cmd/ci-operator-config-mirror/main.go
  test/ci-operator-config-mirror-integration/data/input/foo/barry-white/foo-barry-white-official.yaml
  test/ci-operator-config-mirror-integration/data/output/foo/barry-white/foo-barry-white-official.yaml
  test/ci-operator-config-mirror-integration/data/output/super-priv/barry-white/super-priv-barry-white-official.yaml
Labels: approved, lgtm

#797 Controller manager: Use json log
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#799 Autobumper: Stop running make update-app-ci as its gone
  cmd/autobumper/main.go
Labels: approved, lgtm

#798 ci-operator multi-stage: make profile need release
  pkg/api/parameters.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm

#800 Use app.ci result aggregator
  pkg/results/report.go
Labels: approved, lgtm

#801 Promotionreconciler: Avoid logging things we cant fix on error level
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
Labels: approved, lgtm

#628 hack: import hack/lib, restructure integration tests
  Makefile
  hack/build-go.sh
  hack/install.sh
  hack/lib/cleanup.sh
  hack/lib/cmd.sh
  hack/lib/compress.awk
  hack/lib/constants.sh
  hack/lib/init.sh
  hack/lib/integration.sh
  hack/lib/log/output.sh
  hack/lib/log/stacktrace.sh
  hack/lib/test/junit.sh
  hack/lib/util/build.sh
  hack/lib/util/ensure.sh
  hack/lib/util/environment.sh
  hack/lib/util/find.sh
  hack/lib/util/misc.sh
  hack/lib/util/text.sh
  hack/lib/util/trap.sh
  hack/test-go.sh
  hack/test-integration.sh
  hack/verify-gofmt.sh
  hack/verify-govet.sh
  test/integration/ci-operator-config-mirror.sh
  test/integration/ci-operator-configresolver.sh
Labels: approved, lgtm

#803 make: add a stub for the e2e target
  Makefile
Labels: approved, lgtm

#804 ci-operator: default --artifact-dir to $ARTIFACTS
  cmd/ci-operator/main.go
Labels: approved, lgtm

#672 Autoconfigbrancher: use exposed bumper library's function, and refactor
  cmd/autoconfigbrancher/main.go
  go.mod
  go.sum
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/BUILD.bazel
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/bugzilla/BUILD.bazel
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/bugzilla/fake.go
  vendor/k8s.io/test-infra/prow/bugzilla/types.go
  vendor/k8s.io/test-infra/prow/config/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/config/secret/agent.go
  vendor/k8s.io/test-infra/prow/git/v2/client_factory.go
  vendor/k8s.io/test-infra/prow/github/BUILD.bazel
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/pjutil/filter.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/skip/skip.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/generic-comment.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/modules.txt
Labels: approved, lgtm

#805 cleanup: stop setting default values
  Makefile
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
  hack/lib/integration.sh
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  test/integration/ci-operator-prowgen.sh
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm

#807 ci-operator: annotate namespace as active while acquiring lease
  pkg/defaults/defaults.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
Labels: approved, lgtm

#808 ci-operator: monitor the namespace we run in
  cmd/ci-operator/main.go
Labels: approved, lgtm

#811 [autoperibolossync]] add a self-approve option
  cmd/autoperibolossync/main.go
Labels: approved, lgtm

#812 ipi-deprovision: actually skip 3.11 clusters on GCP
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#810 rehearse: only include targeted test in CONFIG_SPEC
  pkg/api/metadata.go
  pkg/api/metadata_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm

#809 Limit concurrency on ci-secret-bootstrap
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  go.mod
Labels: approved, lgtm

#815 Log o.maxConcurrency in ci-secret-bootstrap
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm

#817 rehearsal: fail when not able to inline configuration
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm

#819 webreg: fix syntax error in templates
  pkg/webreg/webreg.go
Labels: approved, lgtm

#820 Enable `make pr-deploy` on app.ci
  Makefile
  hack/pr-deploy.yaml
Labels: approved, lgtm

#813 ci-operator: allow custom credentials in steps
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/webreg/webreg.go
  test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
Labels: approved, lgtm

#822 tests: migrate ci-operator-config-mirror suite
  Makefile
  test/ci-operator-config-mirror-integration/run.sh
  test/integration/ci-operator-config-mirror.sh
  test/integration/ci-operator-config-mirror/input/foo/bar/foo-bar-master.yaml
  test/integration/ci-operator-config-mirror/input/foo/barry-white/foo-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/input/foo/barry-white/foo-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/input/super/duper/super-duper-master.yaml
  test/integration/ci-operator-config-mirror/input/super/trooper/super-trooper-master.yaml
  test/integration/ci-operator-config-mirror/output/foo/bar/foo-bar-master.yaml
  test/integration/ci-operator-config-mirror/output/foo/barry-white/foo-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output/foo/barry-white/foo-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/duper/super-priv-duper-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/trooper/super-priv-trooper-master.yaml
  test/integration/ci-operator-config-mirror/output/super/duper/super-duper-master.yaml
  test/integration/ci-operator-config-mirror/output/super/trooper/super-trooper-master.yaml
  test/integration/ci-operator-config-mirror/whitelist.yaml
Labels: approved, lgtm

#818 rehearse,registry: make explicit maps for type in NodeByName
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/registry/graph.go
  pkg/registry/graph_test.go
  pkg/rehearse/jobs.go
Labels: approved, lgtm

#823 test: migrate ci-operator-configresolver suite
  Makefile
  test/ci-operator-configresolver-integration/run.sh
  test/ci-operator-integration/multi-stage/run.sh
  test/integration/ci-operator-configresolver.sh
  test/integration/ci-operator-configresolver/ci-op-configmaps/master/..2019_11_15_19_57_20.547184898/openshift-installer-master.yaml
  test/integration/ci-operator-configresolver/ci-op-configmaps/master/..data
  test/integration/ci-operator-configresolver/ci-op-configmaps/master/openshift-installer-master.yaml
  test/integration/ci-operator-configresolver/ci-op-configmaps/release-4.2/..2019_11_15_19_57_20.547184898/openshift-installer-release-4.2.yaml
  test/integration/ci-operator-configresolver/ci-op-configmaps/release-4.2/..data
  test/integration/ci-operator-configresolver/ci-op-configmaps/release-4.2/openshift-installer-release-4.2.yaml
  test/integration/ci-operator-configresolver/config.yaml
  test/integration/ci-operator-configresolver/configs/README.md
  test/integration/ci-operator-configresolver/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/integration/ci-operator-configresolver/configs2/OWNERS
  test/integration/ci-operator-configresolver/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-golang111.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-regChange.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2.json
  test/integration/ci-operator-prowgen.sh
  test/integration/ci-operator-prowgen/input/config/private-org/.config.prowgen
  test/integration/ci-operator-prowgen/input/config/private-org/duper/private-org-duper-master.yaml
  test/integration/ci-operator-prowgen/input/config/private/duper/.config.prowgen
  test/integration/ci-operator-prowgen/input/config/private/duper/private-duper-master.yaml
  test/integration/ci-operator-prowgen/input/config/subdir/repo/subdir-repo-master.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master-removed-promotion.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master__variant.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-release-3.11.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-removed-ciop-config-postsubmits.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-removed-promotion-postsubmits.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/remove/super-remove-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/prowgen-integration/run.sh
Labels: approved, lgtm

#826 ci-operator: create a new secret instead of copying
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#816 webreg: doc API for $KUBECONFIG
  pkg/webreg/webreg.go
Labels: approved, lgtm

#828 ci-operator: load KUEBCONFIG if set, then use in-cluster
  pkg/util/client.go
Labels: approved, lgtm

#832 secret-wrapper: use in-cluster config
  cmd/secret-wrapper/main.go
Labels: approved, lgtm

#829 load: use new test-infra watchers for agents
  go.mod
  go.sum
  pkg/load/agents/utils.go
  pkg/watcher/watcher.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/config/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/agent.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/hook/events.go
  vendor/k8s.io/test-infra/prow/io/BUILD.bazel
  vendor/k8s.io/test-infra/prow/io/iterator.go
  vendor/k8s.io/test-infra/prow/io/opener.go
  vendor/k8s.io/test-infra/prow/io/option.go
  vendor/k8s.io/test-infra/prow/io/providers/providers.go
  vendor/k8s.io/test-infra/prow/pjutil/filter.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/modules.txt
Labels: approved, lgtm

#836 integration: don't depend on $GOPATH
  hack/lib/util/find.sh
Labels: approved, lgtm

#837 fix missing json tags
  pkg/api/types.go
  test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
Labels: approved, lgtm

#830 Add re-usable terminal errors
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
  pkg/controller/util/error.go
  pkg/controller/util/error_test.go
Labels: approved, lgtm

#835 ci-operator: allow requesting resolution of raw config
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator/main.go
  hack/test-e2e.sh
  pkg/load/load.go
  pkg/load/load_test.go
  test/e2e/multi-stage.sh
  test/e2e/multi-stage/config.yaml
  test/e2e/multi-stage/configs/master/..2019_11_15_19_57_20.547184898/test-test-master.yaml
  test/e2e/multi-stage/configs/master/..data
  test/e2e/multi-stage/configs/master/test-test-master.yaml
  test/e2e/multi-stage/registry/step/step-commands.sh
  test/e2e/multi-stage/registry/step/step-ref.yaml
  test/integration/ci-operator-configresolver.sh
  test/integration/ci-operator-configresolver/expected/resolved-config.json
  test/integration/ci-operator-configresolver/unresolved-config.json
Labels: approved, lgtm

#840 make: deploy test servers to app.ci
  Makefile
Labels: approved, lgtm

#841 Promotionreconciler: Clarify getRef error message
  pkg/controller/promotionreconciler/reconciler.go
Labels: approved, lgtm

#825 [private-org-sync] Add a source/destination merge logic after it fails to push the last retry.
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#842 Promotionreconciler: Stop retrying on requests that get a 404 from GH
  cmd/dptp-controller-manager/main.go
  hack/run-dptp-controller-manager.sh
  pkg/controller/promotionreconciler/reconciler.go
Labels: approved, lgtm

#821 ci-operator: allow steps to reference external images
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/helper/imageextraction.go
  pkg/api/helper/imageextraction_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/webreg/webreg.go
  test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
Labels: approved, lgtm

#843 api: make architecture omitempty as it should be
  pkg/api/types.go
Labels: approved, lgtm

#631 Simplify 2 commands in integration tests
  test/repo-init-integration/run.sh
  test/secret-wrapper-integration.sh
Labels: approved, lgtm

#844 util: DRY out the service host for our main cluster
  cmd/ci-operator/main.go
  cmd/testgrid-config-generator/main.go
  pkg/prowgen/prowgen.go
  pkg/release/candidate/client.go
  pkg/steps/input_image_tag.go
  pkg/util/domain.go
Labels: approved, lgtm

#824 Add a testimages distributing controller
  cmd/ci-operator/main.go
  cmd/dptp-controller-manager/main.go
  cmd/testgrid-config-generator/main.go
  go.mod
  go.sum
  hack/run-dptp-controller-manager.sh
  pkg/api/domain.go
  pkg/api/helper/imageextraction.go
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/prowgen/prowgen.go
  pkg/release/candidate/client.go
  pkg/steps/input_image_tag.go
  pkg/util/domain.go
  pkg/util/imagestreamtagwrapper/imagestreamtagwrapper.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/OWNERS_ALIASES
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/dynamicrestmapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/config/config.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/options.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
Labels: approved, lgtm, tide/merge-method-squash

#846 Dptp-controller-manager: Fix kubeconfig arg
  cmd/dptp-controller-manager/main.go
  hack/run-dptp-controller-manager.sh
Labels: approved, lgtm

#848 ci-operator: multi-stage: expose $IMAGE_FORMAT with profiles
  pkg/steps/multi_stage.go
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm

#849 ipi-deprovision: skip 3.11 clusters on GCP based on network's autoCreateSubnetwork
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#851 Ipi-deprovision: Re-Add lost infraID
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#847 ci-operator: propagate release input steps for releases
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  test/ci-operator-integration/base/expected_files/expected_with_template.json
  test/e2e/simple.sh
Labels: approved, lgtm

#852 ci-operator: expose leased resource env
  pkg/defaults/defaults.go
Labels: approved, lgtm

#845 Add openshift-tests run-resourcewatch to ugprades
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#853 [private-org-sync] Add `--debug` flag
  cmd/private-org-sync/main.go
Labels: approved, lgtm

#856 ci-operator: don't wait for release images in templates
  pkg/steps/template.go
Labels: approved, lgtm

#861 Improve promotionreconcilers logging
  pkg/controller/promotionreconciler/prowjobreconciler/prowjobreconciler.go
  pkg/controller/promotionreconciler/reconciler.go
Labels: approved, lgtm

#858 ci-operator: multi-stage: require release images only without payload
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm

#862 ci-operator: expose more lease step params
  pkg/defaults/defaults.go
Labels: approved, lgtm

#855 Make `Architecture` field omitempty in all Release structs
  pkg/api/types.go
Labels: approved, lgtm

#850 webreg: allow chains with the same name as a reference be displayed
  pkg/webreg/graphviz.go
  pkg/webreg/graphviz_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#864 ci-operator-prowgen: create a pull secret when resolving releases
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
Labels: approved, lgtm

#859 Dptp-controller-manager: Degrade "no promotionconfig found" to trace
  pkg/controller/promotionreconciler/reconciler.go
Labels: approved, lgtm

#857 respect exit codes in git command errors
  cmd/private-org-sync/main.go
Labels: approved, lgtm

#860 Revert "Add openshift-tests run-resourcewatch to ugprades"
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#866 add git name,email flags to be used in merge commands
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#868 ci-operator: depend on images when we underride a release
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
Labels: approved, lgtm

#867 webreg: add example of overriding workflow with literal steps
  pkg/webreg/webreg.go
Labels: approved, lgtm

#865 webreg: support variant jobs in the job list and search
  pkg/webreg/webreg.go
Labels: approved, lgtm

#870 Promotionreconciler: Infer org/repo/branch from config and not imagestreamtag
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
Labels: approved, lgtm
