Repository openshift/ci-tools, pull requests merged in 2020-01, with the labels that each got.

#344 Define const CanBeRehearsedLabel in one place
  pkg/rehearse/jobs.go
Labels: approved, lgtm, size/XS

#345 Set LC_ALL in artifacts so that aws cli would convert unicode correctly
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/XS

#348 Detect breaking changes caused by test-infra updates
  test/validate-prowgen-breaking-changes.sh
Labels: approved, lgtm, size/S

#346 Make rehearsals of hidden jobs have `skip_report: true`
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#351 rehearse: fix detection of jobs affected by ciop config changes
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
Labels: approved, lgtm, size/M

#349 Add a new tool: ci-secret-mirroring
  cmd/ci-secret-bootstrap/README.md
Labels: approved, lgtm, size/M

#352 steps/artifacts: fix artifact size suffix
  pkg/steps/artifacts.go
Labels: approved, lgtm, size/XS

#354 pkg/registry: add types for maps of registry components
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/registry/graph.go
  pkg/registry/graph_test.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
Labels: approved, lgtm, size/M

#359 fix retry around template instance ready check (in case it is called …
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#358 pkg/api: default artifact_dir in multi-stage tests
  pkg/api/config.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm, size/XL

#361 Remove --allow-volumes flag from the pj-rehearse tool
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm, size/M

#362 Revert "Merge pull request #359 from gabemontero/fix-wait-for-templat…
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#363 fix retry around template instance ready check (in case it is called …
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#364 steps: Update cluster upgrade template to latest
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/S

#366 Fix a typo in ci-op config reference
  CONFIGURATION.md
Labels: approved, lgtm, size/XS

#356 Prevent rehearsing hidden jobs
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/M

#357 Add a tool for syncing git content between mirrors
  cmd/private-org-sync/README.md
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
  pkg/promotion/promotion.go
Labels: approved, lgtm, size/XXL

#360 Add a Dockerfile for private-org-sync
  images/private-org-sync/Dockerfile
Labels: approved, lgtm, size/XS

#368 Install git for private-org-sync and base it on centos:8
  images/private-org-sync/Dockerfile
Labels: approved, lgtm, size/XS

#367 private-org-sync: add another retried error pattern
  cmd/private-org-sync/main.go
Labels: approved, lgtm, size/XS

#370 pkg/load: improve error msg when configresolver returns non-200 status
  pkg/load/load.go
Labels: approved, lgtm, size/XS

#365 testgrid: Gather more testgrid results for jobs that run less frequently
  cmd/testgrid-config-generator/main.go
  test/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
Labels: approved, lgtm, size/M

#371 applyconfig: use --validate
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
Labels: approved, lgtm, size/M

#372 Revert "applyconfig: use --validate"
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
Labels: approved, lgtm, size/M

#369 private-org-sync: fail-fast when destination does not exist
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm, size/M

#374 ci-operator: Update template from latest
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/XS

#353 Implement ci-secret-bootstrap
  cmd/ci-secret-bootstrap/README.md
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
  pkg/bitwarden/fake.go
Labels: approved, lgtm, size/XXL

#376 pkg/registry/graph: fix panics for invalid regsitry components
  pkg/registry/graph.go
Labels: approved, lgtm, size/S

#377 ci-secret-bootstrap: simplify censoring formatter setup
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm, size/M

#375 fix wait for template instance failing on get with empty key
  pkg/steps/template.go
Labels: approved, lgtm, size/XS

#378 Improve the secret-bootstrap tool
  cmd/ci-secret-bootstrap/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
  pkg/bitwarden/fake.go
  pkg/util/client.go
  pkg/util/client_test.go
Labels: approved, lgtm, size/M

#380 ipi-deprovision: refactor to add gcp
  cmd/ipi-deprovision/ipi-deprovision.sh
  images/ipi-deprovision/Dockerfile
  images/ipi-deprovision/google-cloud-sdk.repo
Labels: approved, lgtm, size/L

#383 ipi-deprovision: install latest awscli
  images/ipi-deprovision/Dockerfile
Labels: approved, lgtm, size/XS

#384 ipi-deprovision: script fixes
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/S

#379 Build image for ci-secret-bootstrap
  images/ci-secret-bootstrap/Dockerfile
Labels: approved, lgtm, size/XS

#387 ipi-deprovision: shuffle all possible clusters to reap
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#388 registry: refactor naming for component maps
  pkg/load/configAgent.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/load/registryAgent.go
  pkg/registry/graph.go
  pkg/registry/graph_test.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/L

#385 ipi-deprovision: turn deprovisioning on
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#389 ipi-deprovisioner: do not prematurely exit on no-matching grep
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#382 Detect diff. between BW items and secrets
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm, size/L

#391 Timeout after 30m of destroying a cluster
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#392 Revertd92df0facdccf541f126d679750e214bd33c7c9d
  pkg/steps/template.go
Labels: approved, lgtm, size/M

#393 ci-operator: fixes in template-handling logic
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#381 pkg/registry: add unit tests for NewGraph
  pkg/registry/graph_test.go
Labels: approved, lgtm, size/M

#390 prowgen: generate multi-stage test jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/M

#395 ipi-deprovision: calculate GCE TTL from creation time
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/S

#397 ipi-deprovision: fix GCE timing
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#399 ipi-deprovision: use US pacific time zone
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm, size/XS

#401 pkg/steps/clusterinstall/template: Sync with openshift/release
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/L

#394 Support .login.password for ci-secret-bootstrap
  cmd/ci-secret-bootstrap/README.md
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
  pkg/bitwarden/fake.go
Labels: approved, lgtm, size/L

#404 Fix the bugs of ci-secret-bootstrap found in test
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
Labels: approved, lgtm, size/M

#396 pkg/webreg: add graphs
  images/ci-operator-configresolver/Dockerfile
  pkg/webreg/graphviz.go
  pkg/webreg/graphviz_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/L

#405 webreg: various small style improvements
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/M

#403 ci-operator multi-stage: create service account
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm, size/L

#398 secret-wrapper: don't try to create the secret
  cmd/secret-wrapper/main.go
Labels: approved, lgtm, size/XS

#407 lease: log when acquiring, lower timeout
  pkg/lease/client.go
  pkg/steps/lease.go
Labels: approved, lgtm, size/XS

#408 Fix a flaky test TestConstructSecrets
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm, size/XS

#409 Improve doc for ci-secret-bootstrap
  cmd/ci-secret-bootstrap/README.md
Labels: approved, lgtm, size/XS

#410 ci-operator multi-stage: save container logs
  pkg/steps/artifacts.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm, size/M

#411 private-org-sync: allow failing on missing destinations
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm, size/M
