Repository openshift/ci-tools, pull requests merged in 2020-03, with the labels that each got.

#502 Autoowners: Ignore casing when checking if owners are org members
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm, size/M

#503 Add cluster for base_rpm_images
  cmd/config-migrator/main.go
Labels: approved, lgtm, size/S

#505 Migrate presubmits of installer repo
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/XS

#496 help: document a step's execution environment
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/M

#504 ci-operator: Do not overwrite TTL annotations unless explicit
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M

#513 webreg: change "reference" to "step"
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/M

#507 Migrate presubmits of origin repo
  pkg/migrate/migrate.go
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/XS

#509 ci-operator: make build functions interruptible
  pkg/steps/git_source.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
Labels: approved, lgtm, size/L

#514 Migrate all presubmits to build01
  pkg/migrate/migrate.go
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm, size/L

#519 Revert "Migrate all presubmits to build01"
  pkg/migrate/migrate.go
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm, size/L

#515 add secret keys for git source strategy builds
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/XS

#521 Back to default
  pkg/migrate/migrate.go
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
Labels: approved, lgtm, size/L

#510 ci-operator: make pod functions interruptible
  pkg/steps/multi_stage.go
  pkg/steps/pod.go
  pkg/steps/release/create_release.go
  pkg/steps/template.go
Labels: approved, lgtm, size/M

#522 [private-org-sync] Include tags while fetching
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm, size/S

#524 [private-org-sync] Include tags while pushing
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm, size/S

#523 secret-wrapper: update secret unconditionally
  cmd/secret-wrapper/main.go
  test/secret-wrapper-integration.sh
Labels: approved, lgtm, size/M

#511 ci-operator: make other functions interruptible
  pkg/steps/input_image_tag.go
  pkg/steps/release/create_release.go
  pkg/steps/rpm_server.go
Labels: approved, lgtm, size/M

#508 ci-operator multi-stage: delete pods only once
  pkg/steps/multi_stage.go
Labels: approved, lgtm, size/S

#525 prowgen: duplicate tests on build01 that don't use quota
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm, size/XXL

#527 Revert "prowgen: duplicate tests on build01 that don't use quota"
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm, size/XXL

#530 Revert "Revert "prowgen: duplicate tests on build01 that don't use quota""
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm, size/XXL

#490 [ci-op-configs-mirror] Enable promotion
  cmd/ci-op-configs-mirror/main.go
  cmd/ci-op-configs-mirror/main_test.go
  test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/output/super-priv/trooper/super-priv-trooper-master.yaml
Labels: approved, lgtm, size/XS

#528 Autoowners: Allow to optionally self-approve
  cmd/autoowners/main.go
Labels: approved, lgtm, size/S

#532 upgrade: tar must-gather output
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#533 test/pj-rehearse: fix an incorrect job
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/ci-operator/config/super/duper/super-duper-cluster-profile.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
Labels: approved, lgtm, size/M

#535 Revert "prowgen: temporarily rename private postsubmits"
  cmd/ci-operator-prowgen/main.go
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
Labels: approved, lgtm, size/S

#520 Reintegrate nested virt enablement into custom-test-image template
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/XL

#531 Ignore the cluster param in prowgen
  GENERATOR.md
  cmd/ci-operator-prowgen/main.go
  pkg/jobconfig/files.go
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/M

#512 ci-operator: don't exit when steps are interrupted
  cmd/ci-operator/main.go
  pkg/steps/multi_stage.go
  pkg/steps/run.go
Labels: approved, lgtm, size/L

#534 prowgen,pj-rehearse: do not add CONFIG_SPEC to generated jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/jobconfig/files.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm, size/XL

#539 Revert "prowgen,pj-rehearse: do not add CONFIG_SPEC to generated jobs"
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/jobconfig/files.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm, size/XL

#540 autobumper: update clusters/
  cmd/autobumper/main.go
Labels: approved, lgtm, size/XS

#541 prowgen,pj-rehearse: do not add CONFIG_SPEC to generated jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/jobconfig/files.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/pj-rehearse-integration/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm, size/XXL

#542 Applyconfig: Allow to disable --as when applying admin config
  cmd/applyconfig/applyconfig.go
Labels: approved, lgtm, size/S

#538 Add the CVP trigger tool skeleton
  Makefile
  cmd/cvp-trigger/README.md
  cmd/cvp-trigger/main.go
  cmd/cvp-trigger/main_test.go
  test/cvp-trigger-integration/config.yaml
  test/cvp-trigger-integration/jobs.yaml
  test/cvp-trigger-integration/periodic-ipi-deprovision.expected
  test/cvp-trigger-integration/run.sh
Labels: approved, lgtm, size/L

#544 secret-wrapper: unify input and output directories
  cmd/secret-wrapper/main.go
  pkg/steps/multi_stage.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/secret-wrapper-integration.sh
Labels: approved, lgtm, size/L

#547 secret-wrapper: update documentation
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/S

#546 Secret bootstrap: Allow provisioning only one cluster
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm, size/L

#545 ci-operator,prowgen: don't set redundant ci-operator flags
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  go.mod
  pkg/load/load.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/ci-operator-integration/multi-stage/run.sh
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  vendor/k8s.io/utils/diff/diff.go
  vendor/k8s.io/utils/field/path.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#551 Revert "ci-operator,prowgen: don't set redundant ci-operator flags"
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  go.mod
  pkg/load/load.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/ci-operator-integration/multi-stage/run.sh
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  vendor/k8s.io/utils/diff/diff.go
  vendor/k8s.io/utils/field/path.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#550 Autobumper: Run make update-app-ci
  cmd/autobumper/main.go
Labels: approved, lgtm, size/XS

#552 Autobumper: Install make
  images/autobumper/Dockerfile
Labels: approved, lgtm, size/XS

#554 ci-operator: log the configresolver fetch if we do it
  pkg/load/load.go
Labels: approved, lgtm, size/XS

#553 Secret bootstrapper: fix --cluster flag
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm, size/M

#556 inject version and name when building
  Makefile
  cmd/ci-operator/main.go
  go.mod
  go.sum
  hack/install.sh
  vendor/github.com/fsnotify/fsnotify/.editorconfig
  vendor/github.com/fsnotify/fsnotify/.gitattributes
  vendor/github.com/fsnotify/fsnotify/.travis.yml
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/README.md
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/go.mod
  vendor/github.com/fsnotify/fsnotify/go.sum
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/k8s.io/test-infra/prow/config/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/github/BUILD.bazel
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/hook/events.go
  vendor/k8s.io/test-infra/prow/logrusutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/logrusutil/logrusutil.go
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
  vendor/k8s.io/test-infra/prow/version/BUILD.bazel
  vendor/k8s.io/test-infra/prow/version/doc.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/codec.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/typed_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/unstructured_client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/client_go_adapter.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/listener.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/workqueue.go
Labels: approved, lgtm

#557 update bug template generation logic to use bz
  cmd/testgrid-config-generator/main.go
  test/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
Labels: approved, lgtm

#555 webreg: document different types of jobs and how to configure them
  pkg/webreg/webreg.go
Labels: approved, lgtm

#537 Private prow configs mirroring tool
  cmd/private-prow-configs-mirror/README.md
  cmd/private-prow-configs-mirror/main.go
  cmd/private-prow-configs-mirror/main_test.go
  images/private-prow-config-mirror/Dockerfile
Labels: approved, lgtm, size/XXL

#506 Added a libvirt profile for remote s390x testing.
  cmd/ci-operator-prowgen/main.go
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#561 ci-operator multi-stage: default images to `stable`
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm

#564 fix private-prow-configs mirror image name
  images/private-prow-config-mirror/Dockerfile
  images/private-prow-configs-mirror/Dockerfile
Labels: approved, lgtm

#558 Add private-prow-configs-mirror tool in autoconfigbrancher pipeline
  cmd/autoconfigbrancher/main.go
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm

#566 Revert "Add private-prow-configs-mirror tool in autoconfigbrancher pipeline"
  cmd/autoconfigbrancher/main.go
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm

#563 fix generator for testgrid file bug template
  cmd/testgrid-config-generator/main.go
  test/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
  test/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
Labels: approved, lgtm

#560 ci-operator,prowgen: don't set redundant ci-operator flags
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  go.mod
  pkg/load/load.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/ci-operator-integration/multi-stage/run.sh
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  vendor/k8s.io/utils/diff/diff.go
  vendor/k8s.io/utils/field/path.go
  vendor/modules.txt
Labels: approved, lgtm

#569 [private-prow-configs-mirror] Fix the private plugins generation
  cmd/private-prow-configs-mirror/main.go
  cmd/private-prow-configs-mirror/main_test.go
Labels: approved, lgtm

#570 Applyconfig: Allow passing multiple config dirs
  cmd/applyconfig/applyconfig.go
Labels: approved, lgtm

#572 Add prow-configs-mirror tool in autoconfigbrancher pipeline
  cmd/autoconfigbrancher/main.go
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm

#559 Populate testgrid dashboardtab description from k8s.io/description annotation on prowjob
  cmd/testgrid-config-generator/main.go
Labels: approved, lgtm

#573 pkg/webreg: Drop colons from headers
  pkg/webreg/webreg.go
Labels: approved, lgtm

#574 webreg: replace `centos:7` with `base`
  pkg/webreg/webreg.go
Labels: approved, lgtm

#571 Autoowners: Default Reviewers to Approvers
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm

#575 Ci operator prowgen: Test via fixtures
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
Labels: approved, lgtm

#576 cmd/testgrid-config-generator: Add a README
  cmd/testgrid-config-generator/README.md
Labels: approved, lgtm

#578 cvp-trigger: describe interface to common CVP jobs
  cmd/cvp-trigger/README.md
Labels: approved, lgtm

#579 ci-operator: omit `commands` in tests if empty
  pkg/api/types.go
  pkg/rehearse/jobs_test.go
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-regChange.json
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm

#577 Determinize job config: Set api.ci cluster if cluster is unset
  Makefile
  cmd/determinize-prow-jobs/main.go
  cmd/determinize-prow-jobs/main_test.go
  pkg/jobconfig/files.go
  test/prowgen-integration/run.sh
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm

#581 vendor: bump prow
  go.mod
  go.sum
  test/cvp-trigger-integration/periodic-ipi-deprovision.expected
  test/pj-rehearse-integration/expected.yaml
  test/repo-init-integration/expected/core-services/prow/02_config/_config.yaml
  vendor/k8s.io/test-infra/ghproxy/ghcache/README.md
  vendor/k8s.io/test-infra/ghproxy/ghcache/coalesce.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghmetrics.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/flagutil/github.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/OWNERS
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/modules.txt
Labels: approved, lgtm

#583 webreg: remove old CSS for a sidenav that was never implemented
  pkg/webreg/webreg.go
Labels: approved, lgtm

#584 hack/pr-deploy: build images faster
  hack/pr-deploy.yaml
Labels: approved, lgtm

#586 Determinize job config: Run over all jobs
  cmd/determinize-prow-jobs/main.go
Labels: approved, lgtm

#582 webreg: change layout of workflow table to better fit step names
  pkg/webreg/webreg.go
Labels: approved, lgtm

#585 ci-operator: validate multi-stage test images
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#580 ci-operator: identify ci-operator specific workloads
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  test/ci-operator-integration/base/expected_files/expected.json
  test/ci-operator-integration/base/expected_files/expected_pull_secret.json
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm

#568 prowgen: add expose option to prowgen config (DPTP-972)
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/config/load.go
Labels: approved, lgtm

#588 Autoconfigbrancher: Run determinize-prow-jobs
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#589 Rehearsals: Don't force reporting
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm

#590 Autoconfigbrancher image: Add determinize prow jobs
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm

#591 Autoconfigbrancher: Fix determinize-prow-job call arguments
  cmd/autoconfigbrancher/main.go
  cmd/determinize-prow-jobs/main.go
Labels: approved, lgtm

#592 Revert "prowgen: duplicate tests on build01 that don't use quota"
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/presubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm

#595 ci-operator: fix promotion validation
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm

#593 ci-operator-checkconfig: disallow duplicate promotions
  cmd/ci-operator-checkconfig/main.go
  cmd/ci-operator-checkconfig/main_test.go
  pkg/defaults/defaults.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm

#596 Rename sanitize-prow-jobs to determinize-prow-jobs
  cmd/autoconfigbrancher/main.go
  cmd/sanitize-prow-jobs/README.md
  cmd/sanitize-prow-jobs/main.go
  cmd/sanitize-prow-jobs/main_test.go
  images/autoconfigbrancher/Dockerfile
  images/determinize-prow-jobs/Dockerfile
  images/sanitize-prow-jobs/Dockerfile
  test/repo-init-integration/run.sh
Labels: approved, lgtm

#597 ci-operator: make promotion validation more strict
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm

#599 pr-deploy: use correct cm and use create not apply
  Makefile
  hack/pr-deploy.yaml
Labels: approved, lgtm

#598 webreg: number lines and make them linkable
  pkg/webreg/webreg.go
Labels: approved, lgtm

#601 ipi-deprovision: install the azure cli
  images/ipi-deprovision/Dockerfile
  images/ipi-deprovision/azure-cli.repo
Labels: approved, lgtm

#603 pkg/load: validate full filename for registry components
  pkg/load/load.go
  pkg/load/load_test.go
  test/multistage-registry/invalid-filename/ipi/install/ipi-install-commands.sh
  test/multistage-registry/invalid-filename/ipi/install/ipi-install-install-ref.yaml
Labels: approved, lgtm

#602 ipi-deprovision: prune azure clusters, too
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#605 cvp-trigger: describe parameters specifying optional operator under test
  cmd/cvp-trigger/README.md
Labels: approved, lgtm

#600 Pass optional operator installation parameters to steps
  pkg/steps/multi_stage.go
  pkg/steps/optional_operators.go
  pkg/steps/optional_operators_test.go
Labels: approved, lgtm

#610 Applyconfig: Log command
  cmd/applyconfig/applyconfig.go
Labels: approved, lgtm

#613 Revert "Merge pull request #602 from stevekuznetsov/skuznets/ipi-depr…
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#609 webreg: document leases and quota
  Makefile
  pkg/webreg/webreg.go
Labels: approved, lgtm

#612 ci-operator-prowgen: set max concurrency on publication jobs
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_Using_a_variant_config,_one_test_and_images,_one_existing_job._Expect_one_presubmit,_pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/postsubmit-TestFromCIOperatorConfigToProwYaml_one_test_and_images,_no_previous_jobs._Expect_test_presubmit_+_pre_post_submit_images_jobs.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
Labels: approved, lgtm

#608 ci-operator: expose which resource was leased to steps
  pkg/steps/lease.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/ci-operator-integration/multi-stage/run.sh
Labels: approved, lgtm

#614 fix job name safe env var for the variant jobs
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm

#615 webreg: document $OPENSHIFT_CI
  pkg/webreg/webreg.go
Labels: approved, lgtm

#616 webreg: cross-reference lease doc in env doc
  pkg/webreg/webreg.go
Labels: approved, lgtm

#617 webreg: reformat identifiers
  pkg/webreg/webreg.go
Labels: approved, lgtm

#604 Check empty cluster in ci-op's config
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/multi_stage.go
  test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
  test/ci-op-configs-mirror-integration/data/output/foo/bar/foo-bar-master.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/master/..2019_11_15_19_57_20.547184898/openshift-installer-master.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/release-4.2/..2019_11_15_19_57_20.547184898/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-regChange.json
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
  test/ci-operator-integration/base/config/test-config.yaml
  test/ci-operator-integration/base/expected_files/expected.json
  test/ci-operator-integration/base/expected_files/expected_pull_secret.json
  test/ci-operator-integration/base/expected_files/expected_with_template.json
  test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/prowgen-integration/data/input/config/private-org/duper/private-org-duper-master.yaml
  test/repo-init-integration/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/repo-init-integration/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
  test/repo-init-integration/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
  test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/repo-init-integration/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/repo-init-integration/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#620 Revert "Merge pull request #604 from hongkailiu/cluster_stanza"
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/multi_stage.go
  test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
  test/ci-op-configs-mirror-integration/data/output/foo/bar/foo-bar-master.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/master/..2019_11_15_19_57_20.547184898/openshift-installer-master.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/release-4.2/..2019_11_15_19_57_20.547184898/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-regChange.json
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
  test/ci-operator-integration/base/config/test-config.yaml
  test/ci-operator-integration/base/expected_files/expected.json
  test/ci-operator-integration/base/expected_files/expected_pull_secret.json
  test/ci-operator-integration/base/expected_files/expected_with_template.json
  test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/prowgen-integration/data/input/config/private-org/duper/private-org-duper-master.yaml
  test/repo-init-integration/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/repo-init-integration/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
  test/repo-init-integration/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
  test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/repo-init-integration/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/repo-init-integration/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved

#618 integration: don't acquire multiple leases in one run
  test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm

#621 test: remove unused files
  test/config.json
  test/config.yaml
Labels: approved, lgtm

#623 add variant prefix in secret names
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm

#626 add a tool to determinize the peribolos config
  cmd/determinize-peribolos/main.go
  images/determinize-peribolos/Dockerfile
Labels: approved, lgtm

#622 Revert "Revert "Merge pull request #604 from hongkailiu/cluster_stanza""
  cmd/ci-operator/main.go
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/multi_stage.go
  test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
  test/ci-op-configs-mirror-integration/data/output/foo/bar/foo-bar-master.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/master/..2019_11_15_19_57_20.547184898/openshift-installer-master.yaml
  test/ci-operator-configresolver-integration/ci-op-configmaps/release-4.2/..2019_11_15_19_57_20.547184898/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-configresolver-integration/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-golang111.json
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2-regChange.json
  test/ci-operator-configresolver-integration/expected/openshift-installer-release-4.2.json
  test/ci-operator-integration/base/config/test-config.yaml
  test/ci-operator-integration/base/expected_files/expected.json
  test/ci-operator-integration/base/expected_files/expected_pull_secret.json
  test/ci-operator-integration/base/expected_files/expected_with_template.json
  test/ci-operator-integration/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/prowgen-integration/data/input/config/private-org/duper/private-org-duper-master.yaml
  test/repo-init-integration/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/repo-init-integration/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
  test/repo-init-integration/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
  test/repo-init-integration/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/repo-init-integration/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/repo-init-integration/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#625 rename ci-op-configs-mirror to ci-operator-config-mirror
  Makefile
  cmd/autoconfigbrancher/main.go
  cmd/ci-operator-config-mirror/main.go
  cmd/ci-operator-config-mirror/main_test.go
  images/autoconfigbrancher/Dockerfile
  images/ci-op-configs-mirror/Dockerfile
  images/ci-operator-config-mirror/Dockerfile
  test/ci-operator-config-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
  test/ci-operator-config-mirror-integration/data/input/super/duper/super-duper-master.yaml
  test/ci-operator-config-mirror-integration/data/input/super/trooper/super-trooper-master.yaml
  test/ci-operator-config-mirror-integration/data/output/foo/bar/foo-bar-master.yaml
  test/ci-operator-config-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
  test/ci-operator-config-mirror-integration/data/output/super-priv/trooper/super-priv-trooper-master.yaml
  test/ci-operator-config-mirror-integration/data/output/super/duper/super-duper-master.yaml
  test/ci-operator-config-mirror-integration/data/output/super/trooper/super-trooper-master.yaml
  test/ci-operator-config-mirror-integration/run.sh
Labels: approved, lgtm
