Repository openshift/ci-tools, pull requests merged in 2020-09, with the labels that each got.

#1189 update test-infra vendors
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghpath.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/crier/reporters/github/BUILD.bazel
  vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
  vendor/modules.txt
Labels: approved, lgtm

#1172 Secret Generator: Accept piped commands as input
  cmd/ci-secret-generator/main.go
Labels: approved, lgtm

#1184 OCP Build Data: Don't replace with entrys in stream.yaml that have mirror: false
  pkg/api/ocpbuilddata/types.go
  pkg/api/ocpbuilddata/types_test.go
Labels: approved, lgtm

#1174 CI secret boostrap: Allow targeting a named group of clusters
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/api/secretbootstrap/secretboostrap_test.go
  pkg/controller/secretsyncer/secretsyncer.go
  pkg/controller/secretsyncer/secretsyncer_test.go
Labels: approved, lgtm

#1194 Build data enforcer: Recommend aos-art channel
  cmd/ocp-build-data-enforcer/main.go
Labels: approved, lgtm

#1186 Imagebuild: connection reset by peer is a transient failure
  pkg/steps/source.go
Labels: approved, lgtm

#1191 Add allow-list as input to testgrid
  cmd/testgrid-config-generator/README.md
  cmd/testgrid-config-generator/main.go
  cmd/testgrid-config-generator/main_test.go
  test/integration/testgrid-config-generator.sh
  test/integration/testgrid-config-generator/config/_allow-list.yaml
  test/integration/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
Labels: approved, lgtm

#1192 ci-operator: check if init containers are running
  pkg/steps/template.go
  pkg/steps/template_test.go
Labels: approved, lgtm

#1196 Promotionreconciler: log istcommit
  pkg/controller/promotionreconciler/reconciler.go
Labels: approved, lgtm

#1197 Bump test-infra to a33a9aaf77f7
  go.mod
  go.sum
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/io/iterator.go
  vendor/k8s.io/test-infra/prow/io/opener.go
  vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/modules.txt
Labels: approved, lgtm

#1193 prowgen: add support for generating ci-index presubmit
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_operator_section_creates_ci_index_presubmit_job.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
Labels: approved, lgtm

#1198 Make sure build labels are always set correctly
  pkg/steps/project_image.go
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
Labels: approved, lgtm

#1195 prowgen: add support for generating postsubmits
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_two_tests_and_empty_Images_with_one_test_configured_as_a_postsubmit.yaml
  pkg/webreg/webreg.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml
Labels: approved, lgtm

#1201 images: install diffutils on centos8
  images/ci-operator-prowgen/Dockerfile
  images/determinize-ci-operator/Dockerfile
  images/determinize-prow-config/Dockerfile
  images/sanitize-prow-jobs/Dockerfile
Labels: approved, lgtm

#1199 Promotionreconciler: Filter out ISTs to which we don't promote
  hack/run-dptp-controller-manager.sh
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
  pkg/promotion/promotion.go
  pkg/promotion/promotion_test.go
Labels: approved, lgtm

#1200 Bump all Dockerfiles to centos:8
  images/autobumper/Dockerfile
  images/autoowners/Dockerfile
  images/blocking-issue-creator/Dockerfile
  images/ci-operator-checkconfig/Dockerfile
  images/ci-operator-configresolver/Dockerfile
  images/ci-operator-prowgen/Dockerfile
  images/ci-operator/Dockerfile
  images/config-brancher/Dockerfile
  images/config-change-trigger/Dockerfile
  images/config-shard-validator/Dockerfile
  images/determinize-ci-operator/Dockerfile
  images/determinize-peribolos/Dockerfile
  images/determinize-prow-config/Dockerfile
  images/group-auto-updater/Dockerfile
  images/pj-rehearse/Dockerfile
  images/repo-brancher/Dockerfile
  images/repo-init/Dockerfile
  images/result-aggregator/Dockerfile
  images/sanitize-prow-jobs/Dockerfile
  images/secret-wrapper/Dockerfile
  images/testgrid-config-generator/Dockerfile
Labels: approved, lgtm

#1205 Fix mountPath vs mount_path in README
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1202 webreg: fix `dependencies` documentation
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1206 pkg/webreg: add a page with useful links
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1203 pkg/steps/lease: print resource metrics on failure
  pkg/lease/client.go
  pkg/lease/fake.go
  pkg/steps/lease.go
Labels: approved, lgtm

#1207 ci-operator image: install python2
  images/ci-operator/Dockerfile
Labels: approved, lgtm

#1179 webreg: document build_root images
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1175 Secret Generator: Improve input mechanism
  cmd/ci-secret-generator/README.md
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
  pkg/bitwarden/fake.go
Labels: approved, lgtm

#1208 update links
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1209 pj-rehearse: stop assuming to run on api.ci
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#1190 ci-operator: document operator-sdk testing
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1214 ci-config-generator: add Dockerfile
  images/ci-secret-generator/Dockerfile
Labels: approved, lgtm

#1215 Updates to ci-secret-generator
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
Labels: approved, lgtm

#1217 slack-bot: seed binary, image
  cmd/slack-bot/main.go
  images/slack-bot/Dockerfile
Labels: approved, lgtm

#1216 Delete attachment from local bw mirror after running bw cmd
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
Labels: approved, lgtm

#1219 Update test-infra to 6e1d254
  cmd/autoconfigbrancher/main.go
  go.mod
  go.sum
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/modules.txt
Labels: approved, lgtm

#1211 Tool to periodically generate testgrids in test-infra
  cmd/autotestgridgenerator/main.go
Labels: approved, lgtm, tide/merge-method-squash

#1221 Testgrid: Remove support for release-type annotation
  cmd/testgrid-config-generator/main.go
  test/integration/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
Labels: approved, lgtm

#1223 Migrate rpm server to python3
  pkg/steps/rpm_server.go
Labels: approved, lgtm, priority/critical-urgent

#1226 Allow rpm server to run in python2 or 3
  pkg/steps/rpm_server.go
Labels: approved, lgtm

#1218 Fix links to ocp-build-data to use existing branch
  cmd/ocp-build-data-enforcer/README.md
  cmd/ocp-build-data-enforcer/main.go
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#1220 Build data enforcer: Handle openshift-x.Y. brancing scheme
  cmd/ocp-build-data-enforcer/main.go
Labels: approved, lgtm

#1222 generate-registry-metadata: generate metadata individually for steps
  Makefile
  cmd/generate-registry-metadata/main.go
  cmd/generate-registry-metadata/main_test.go
  pkg/api/types.go
  pkg/load/agents/registryAgent.go
  pkg/load/load.go
  pkg/webreg/webreg.go
  test/multistage-registry/registry-metadata/README.md
  test/multistage-registry/registry-metadata/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  test/multistage-registry/registry-metadata/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.yaml
  test/multistage-registry/registry-metadata/ipi/deprovision/ipi-deprovision-chain.yaml
  test/multistage-registry/registry-metadata/ipi/deprovision/must-gather/ipi-deprovision-must-gather-commands.sh
  test/multistage-registry/registry-metadata/ipi/deprovision/must-gather/ipi-deprovision-must-gather-ref.yaml
  test/multistage-registry/registry-metadata/ipi/install/install/ipi-install-install-commands.sh
  test/multistage-registry/registry-metadata/ipi/install/install/ipi-install-install-ref.yaml
  test/multistage-registry/registry-metadata/ipi/install/ipi-install-chain.yaml
  test/multistage-registry/registry-metadata/ipi/install/rbac/ipi-install-rbac-commands.sh
  test/multistage-registry/registry-metadata/ipi/install/rbac/ipi-install-rbac-ref.yaml
  test/multistage-registry/registry-metadata/ipi/ipi-workflow.yaml
  test/multistage-registry/registry-metadata/metadata.json
  test/multistage-registry/registry/ipi/OWNERS
  test/multistage-registry/registry/ipi/deprovision/OWNERS
  test/multistage-registry/registry/ipi/deprovision/deprovision/OWNERS
  test/multistage-registry/registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.metadata.json
  test/multistage-registry/registry/ipi/deprovision/ipi-deprovision-chain.metadata.json
  test/multistage-registry/registry/ipi/deprovision/must-gather/OWNERS
  test/multistage-registry/registry/ipi/deprovision/must-gather/ipi-deprovision-must-gather-ref.metadata.json
  test/multistage-registry/registry/ipi/install/OWNERS
  test/multistage-registry/registry/ipi/install/empty-parameter/OWNERS
  test/multistage-registry/registry/ipi/install/empty-parameter/ipi-install-empty-parameter-chain.metadata.json
  test/multistage-registry/registry/ipi/install/install/OWNERS
  test/multistage-registry/registry/ipi/install/install/ipi-install-install-ref.metadata.json
  test/multistage-registry/registry/ipi/install/ipi-install-chain.metadata.json
  test/multistage-registry/registry/ipi/install/rbac/OWNERS
  test/multistage-registry/registry/ipi/install/rbac/ipi-install-rbac-ref.metadata.json
  test/multistage-registry/registry/ipi/install/with-parameter/OWNERS
  test/multistage-registry/registry/ipi/install/with-parameter/ipi-install-with-parameter-chain.metadata.json
  test/multistage-registry/registry/ipi/ipi-workflow.metadata.json
Labels: approved, lgtm

#1227 Add Dockerfile for autotestgridgenerator
  images/autotestgridgenerator/Dockerfile
Labels: approved, lgtm

#1204 pkg/steps/lease: fail faster if client not present
  cmd/ci-operator/main.go
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/steps/bundle_source.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/index_generator.go
  pkg/steps/input_env.go
  pkg/steps/input_image_tag.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/write_params.go
Labels: approved, lgtm

#1212 ci-operator: validate operator.substitute.with better
  cmd/ci-operator/main.go
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/steps/bundle_source.go
  pkg/steps/source.go
Labels: approved, lgtm

#1230 validateLiteralTestStepCommon: allow using imagestreamtag references
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm

#1229 Add a test image with boskos
  test/images/e2e-bin/Dockerfile
Labels: approved, lgtm

#1231 ci-operator: wait 15m for pending pods
  pkg/steps/template.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#1236 Registry replacer: Add support to replace copy --from
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_Copy_from.yaml
Labels: approved, lgtm

#1238 Revert "validateLiteralTestStepCommon: allow using imagestreamtag references"
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm

#1235 Registry-Replacer: Add support for private repositories
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  pkg/github/github.go
Labels: approved, lgtm

#1234 test-images-distributor: copy annotations for ImageStreams
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1240 configresolver: fix nil pointer access
  cmd/ci-operator-configresolver/main.go
Labels: approved, lgtm

#1210 Improve failed pod output
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/source.go
  pkg/steps/template.go
Labels: approved, lgtm

#1225 webreg: openshift/release contribution guidelines
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1241 ci-operator: improve namespace auth wait
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1239 prow-job-dispatcher: Add flag -prometheus-days-before
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  pkg/dispatcher/prometheus.go
  pkg/dispatcher/prometheus_test.go
Labels: approved, lgtm

#1173 Config sanitizer: Force vsphere jobs onto the vsphere cluster
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm

#1244 Disable forcing applyconfig jobs on vphere
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm

#1243 Testgrid: Updated docs for allow-list
  cmd/testgrid-config-generator/README.md
Labels: approved, lgtm

#1242 rename regcred secret to registry-pull-credentials
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/ci-tools-presubmits.yaml
  cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/cluster-api-provider-gcp-presubmits.yaml
  cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/cluster-etcd-operator-master-presubmits.yaml
  cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/wildfly-operator-presubmits.yaml
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_0.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_1.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_2.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_3.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_4.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_5.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_additional_args_and_secret_are_included_in_podspec.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_additional_args_are_included_in_podspec.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_multiple_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_private_job.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_standard_use_case.yaml
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  test/e2e/simple.sh
  test/integration/ci-operator-prowgen/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-job-release-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm

#1245 TestgrigGen: Add option to validate the allow-list
  cmd/testgrid-config-generator/main.go
  cmd/testgrid-config-generator/main_test.go
Labels: approved, lgtm

#1248 private-org-peribolos-sync: force generated repos to private
  cmd/private-org-peribolos-sync/main.go
  cmd/private-org-peribolos-sync/main_test.go
Labels: approved, lgtm

#1250 empty agent jobs are running on k8s
  cmd/prow-job-dispatcher/main_test.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/dispatcher/testdata/TestLoadConfig/good_config.yaml
  pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm.yaml
  pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml
  pkg/dispatcher/testdata/TestLoadConfig/invalid_regex.yaml
Labels: approved, lgtm

#1249 docs: document openshift-priv and private repositories
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1232 e2e: add an initial version of lease tests
  cmd/ci-operator/main.go
  hack/lib/integration.sh
  pkg/lease/client.go
  pkg/lease/fake.go
  test/e2e/lease.sh
  test/e2e/lease/boskos.yaml
  test/e2e/lease/config.yaml
Labels: approved, lgtm

#1252 vendor: update test-infra
  go.mod
  go.sum
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/clonerefs/run.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/github/BUILD.bazel
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/io/providers/BUILD.bazel
  vendor/k8s.io/test-infra/prow/io/providers/providers.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/pod-utils/clone/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pod-utils/clone/clone.go
  vendor/k8s.io/test-infra/prow/pod-utils/clone/format.go
  vendor/k8s.io/test-infra/prow/pod-utils/clone/types.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/modules.txt
Labels: approved, lgtm

#1246 multistage: handle imagestream references in From
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
  test/e2e/multi-stage/config.yaml
Labels: approved, lgtm

#1126 pkg/steps/lease: add support for multiple leases
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/lease/client_test.go
  pkg/lease/fake.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1254 not include the namespace while detecting an applyconfig job
  pkg/dispatcher/config.go
Labels: approved, lgtm

#1253 Make prBody and MatchTitle optional parameters
  cmd/ocp-build-data-enforcer/main.go
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm

#1134 e2e: various minor fixes
  test/e2e/multi-stage.sh
  test/e2e/multi-stage/dependencies.yaml
  test/e2e/simple.sh
Labels: approved, lgtm

#1237 Autotestgridgen: Create fork if not present
  cmd/autotestgridgenerator/main.go
Labels: approved, lgtm

#1256 Revert "Merge pull request #1126 from bbguimaraes/lease_conf"
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/lease/client_test.go
  pkg/lease/fake.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1255 Verify duplications in the keys from secret-bootstrap's config
  cmd/ci-secret-bootstrap/main.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/api/secretbootstrap/secretboostrap_test.go
  pkg/api/secretbootstrap/testdata/TestLoadConfigFromFile/basic_base.yaml
  pkg/api/secretbootstrap/testdata/TestLoadConfigFromFile/dup_key.yaml
Labels: approved, lgtm

#1247 docs: more details about built oo indices
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1260 Reporter: Add error message for missing report-password file
  pkg/results/report.go
Labels: approved, lgtm

#1261 Use kubeconfig to promote images
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
Labels: approved, lgtm

#1251 Allow specifying build_root_image in the repository
  Makefile
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_expose_option_set_but_not_private_with_clone__true.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_specific_release_and_clone__true.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Lowercase_org_repo_and_branch.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Lowercase_org_repo_and_branch_with_release.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Uppercase_org__repo_and_branch.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_Uppercase_org__repo_and_branch_with_clone__true.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified_and_clone.yaml
  pkg/webreg/webreg.go
Labels: approved, lgtm, tide/merge-method-squash

#1263 Revert "Use kubeconfig to promote images"
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
Labels: approved, lgtm
