Repository openshift/ci-tools, pull requests merged in 2020-02, with the labels that each got.

#402 Add a pre-upgrade save for iptables and must-gather
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/S

#412 Move prowgen config to config package
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  pkg/config/load.go
Labels: approved, lgtm, size/S

#415 Revert "Add a pre-upgrade save for iptables and must-gather"
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/S

#416 Add tool to mirror ci-operator configs to a single private repo
  Makefile
  cmd/ci-op-configs-mirror/main.go
  test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
  test/ci-op-configs-mirror-integration/data/input/super/duper/super-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/input/super/trooper/super-trooper-master.yaml
  test/ci-op-configs-mirror-integration/expected_files/expected.yaml
  test/ci-op-configs-mirror-integration/expected_files/expected_skipped.yaml
  test/ci-op-configs-mirror-integration/run.sh
Labels: approved, do-not-merge/hold, lgtm, size/L

#417 Revert "Add tool to mirror ci-operator configs to a single private repo"
  Makefile
  cmd/ci-op-configs-mirror/main.go
  test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
  test/ci-op-configs-mirror-integration/data/input/super/duper/super-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/input/super/trooper/super-trooper-master.yaml
  test/ci-op-configs-mirror-integration/expected_files/expected.yaml
  test/ci-op-configs-mirror-integration/expected_files/expected_skipped.yaml
  test/ci-op-configs-mirror-integration/run.sh
Labels: approved, lgtm, size/L

#420 Clean up build01 setup on ci-secret-mirroring repo
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
Labels: approved, lgtm, size/M

#419 globalize prowgen's configuration name
  cmd/ci-operator-prowgen/main.go
  pkg/config/load.go
Labels: approved, lgtm, size/XS

#406 webreg: add job search page
  cmd/ci-operator-configresolver/main.go
  pkg/webreg/webreg.go
  test/ci-operator-configresolver-integration/config.yaml
  test/ci-operator-configresolver-integration/run.sh
  test/ci-operator-integration/multi-stage/run.sh
Labels: approved, lgtm, size/L

#421 configresolver: make prow-config flag required
  cmd/ci-operator-configresolver/main.go
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/M

#422 pkg/load: check error from filepath.Walk in Registry
  pkg/load/load.go
  pkg/load/load_test.go
Labels: approved, lgtm, size/M

#418 Add tool to mirror ci-operator configs to a single repo
  Makefile
  cmd/ci-op-configs-mirror/main.go
  images/ci-op-configs-mirror/Dockerfile
  test/ci-op-configs-mirror-integration/data/input/foo/bar/foo-bar-master.yaml
  test/ci-op-configs-mirror-integration/data/input/super/duper/super-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/input/super/trooper/super-trooper-master.yaml
  test/ci-op-configs-mirror-integration/data/output/foo/bar/foo-bar-master.yaml
  test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/output/super-priv/trooper/super-priv-trooper-master.yaml
  test/ci-op-configs-mirror-integration/data/output/super/duper/super-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/output/super/trooper/super-trooper-master.yaml
  test/ci-op-configs-mirror-integration/run.sh
Labels: approved, lgtm, size/L

#424 add ci-op-configs-mirror step in autoconfigbrancher tool
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm, size/S

#426 add ci-op-configs-mirror to autoconfigbrancher image
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm, size/XS

#336 Specify pull secret in build steps
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/git_source.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  test/ci-operator-integration/base/expected_files/expected_pull_secret.json
  test/ci-operator-integration/base/run.sh
Labels: approved, lgtm, size/XXL

#428 configresolver: add jobs arg for configresolver's jobAgent
  cmd/ci-operator-configresolver/main.go
Labels: approved, lgtm, size/XS

#430 Migrate openshift/jenkins-openshift-login-plugin/master to build01
  GENERATOR.md
  cmd/ci-operator-prowgen/main.go
  cmd/config-migrator/README.md
  cmd/config-migrator/main.go
  pkg/jobconfig/files.go
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/L

#431 Migrate openshift/jenkins-openshift-login-plugin to build01
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/S

#425 Add support for a separate OpenStack cloud for the ppc64le architecture
  cmd/ci-operator-prowgen/main.go
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#435 Migrate presubmits of jenkins-openshift-login-plugin to build01
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm, size/S

#437 Migrate presubmits of 30 repos
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/M

#436 rehearse: add options to ignore templates, profiles and registry
  cmd/pj-rehearse/main.go
Labels: approved, lgtm, size/M

#432 Complete args for all jobs
  \
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/config-migrator/main.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm, size/XXL

#440 Fix silent breakage of breaking-change check
  test/validate-prowgen-breaking-changes.sh
Labels: approved, lgtm, size/S

#439 config-change-trigger: limit maximum number of triggerd jobs
  cmd/config-change-trigger/main.go
Labels: approved, lgtm, size/XS

#441 breaking-changes check: revert `git -C` to pushd/popd
  test/validate-prowgen-breaking-changes.sh
Labels: approved, lgtm, size/S

#444 Revert "Merge pull request #432 from hongkailiu/aaaALL"
  \
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/config-migrator/main.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: size/XXL

#445 Revert "Merge pull request #444 from hongkailiu/rev"
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/config-migrator/main.go
  test/prowgen-integration/data/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/repo-init-integration/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, do-not-merge/hold, size/XXL

#446 config agent: ignore missing files
  pkg/load/configAgent.go
Labels: approved, lgtm, size/XS

#447 Add packet cluster profile
  CONFIGURATION.md
  cmd/ci-operator-prowgen/main.go
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/S

#450 Make alvaroaleman owner
  OWNERS
Labels: approved, lgtm, size/XS

#443 ci-operator: add flag to resolve steps
  cmd/ci-operator/main.go
  pkg/load/configAgent.go
  pkg/load/load.go
  pkg/load/load_test.go
  test/ci-operator-integration/multi-stage/run.sh
Labels: approved, lgtm, size/M

#451 ci-op-configs-mirror: change promotion config naming configuration
  cmd/ci-op-configs-mirror/main.go
  test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/output/super-priv/trooper/super-priv-trooper-master.yaml
Labels: approved, lgtm, size/S, ¯\_(ツ)_/¯

#449 Autoconfigbrancher: Add option to self-approve
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm, size/M

#452 breaking-changes check: check breaking r-o-e/release
  test/validate-prowgen-breaking-changes.sh
Labels: approved, lgtm, size/M

#453 ci-operator: remove random job
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  test/prowgen-integration/data/input/config/super/duper/super-duper-master.yaml
  test/prowgen-integration/data/output/jobs/super/duper/super-duper-master-presubmits.yaml
Labels: approved, lgtm, size/L

#455 pj-rehearse: choose periodics and presubmits with changed clusters
  cmd/pj-rehearse/main.go
  pkg/config/jobs.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/metrics.go
  test/pj-rehearse-integration/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm, size/L

#438 Migrate presubmits: repo: 31 - 200
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/L

#433 webreg: add help page
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/XL

#456 Censor seesion in the log of ci-secret-bootstrap
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
Labels: approved, lgtm, size/M

#458 Revert "Merge pull request #438 from hongkailiu/mig30"
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/L

#429 testgrid: Add upgrade jobs to generic informing automatically
  cmd/testgrid-config-generator/main.go
Labels: approved, lgtm, size/XS

#461 steps: Update cluster upgrade template
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm, size/M

#462 ci-operator: wait for build deletion properly
  pkg/steps/source.go
Labels: approved, lgtm, size/XS

#459 Change all imagestream tag references in the generated ci-op configuration files.
  cmd/ci-op-configs-mirror/main.go
  cmd/ci-op-configs-mirror/main_test.go
  test/ci-op-configs-mirror-integration/data/input/super/duper/super-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
  test/ci-op-configs-mirror-integration/data/output/super/duper/super-duper-master.yaml
Labels: approved, lgtm, size/L

#464 prowgen: temporarily rename private postsubmits
  cmd/ci-operator-prowgen/main.go
  test/prowgen-integration/data/output/jobs/private/duper/private-duper-master-postsubmits.yaml
Labels: approved, lgtm, size/S

#463 pkg/load: make agents a sub-package
  cmd/ci-operator-configresolver/main.go
  pkg/load/agents/configAgent.go
  pkg/load/agents/registryAgent.go
  pkg/load/agents/utils.go
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/M

#457 webreg: help: expand the section on using tests from another repo
  Makefile
  hack/pr-deploy.yaml
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/L

#465 help: don't use 'config' slang
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/M

#466 help: style ci-operator consistently
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/S

#467 ci-operator multi-stage: use more precise link
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm, size/S

#468 ci-operator multi-stage: fix pipeline image tag
  pkg/steps/multi_stage.go
  test/ci-operator-integration/multi-stage/expected/hyperkube.json
Labels: approved, lgtm, size/XS

#469 help: give all headers identifiers and self-links
  hack/pr-deploy.yaml
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/M

#471 help: use long-form works for numbers
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/XS

#472 help: be more explicit about which end-to-end tests are run
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/XS

#470 Wait pipeline image ready before build src
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
  pkg/util/imagestream.go
Labels: approved, lgtm, size/L

#473 help: add a page explaining ci-operator and its config
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/L

#477 pkg/webreg: change a tab to spaces to keep formatting consistent
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/S

#478 webreg: fix broken link
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/XS

#476 Add code for configuring new template "gcp nested virt custom test image"
  cmd/ci-operator-prowgen/main.go
  pkg/api/config.go
  pkg/api/types.go
Labels: approved, lgtm, size/M

#474 Autoconfigbrancher: Use UpdatePullRequestWithLabel
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm, size/M

#481 Rehersals: Always report
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm, size/S

#480 ci-operator: check err when waiting for Pods to finish
  pkg/steps/template.go
Labels: approved, lgtm, needs-rebase, size/XS, ¯\_(ツ)_/¯

#479 Use upstream boskos client retrying
  Makefile
  go.mod
  go.sum
  vendor/k8s.io/test-infra/boskos/client/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/client/client.go
  vendor/k8s.io/test-infra/prow/crier/reporters/github/BUILD.bazel
  vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#482 Revert "ci-operator: check err when waiting for Pods to finish"
  pkg/steps/template.go
Labels: approved, lgtm, size/XS

#483 ci-operator: remove dead code
  cmd/ci-operator/main.go
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/input_env.go
  pkg/steps/input_image_tag.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/testing.go
  pkg/steps/write_params.go
Labels: approved, lgtm, size/L

#486 ci-operator: restrict interrupt handling area
  cmd/ci-operator/main.go
Labels: approved, lgtm, size/M

#487 Migrate presubmits: repo 31 - 200
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/L

#488 Keep integr8ly-ansible-tower-configuration on default
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/XS

#485 Make TestMakeRehearsalPresubmit fixture-based to easen maintainability
  go.mod
  pkg/rehearse/jobs_test.go
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_doesn't_report_reports_on_rehearsal.yaml
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#489 ci-operator: properly handle deleted pods
  pkg/steps/template.go
Labels: approved, lgtm, size/S

#484 Rehearsals: validate job config
  cmd/pj-rehearse/main.go
  go.mod
  go.sum
  pkg/rehearse/jobs.go
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/rehearse/testdata/TestMakeRehearsalPresubmit_job_that_doesn't_report_reports_on_rehearsal.yaml
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#491 Migrate presubmits: repo 201 - 230
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/M

#492 Migrate presubmits: repo 231 - 300
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/M

#494 multi-stage: expose cluster profile location via env
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm, size/XS

#498 Keep presubmits openshift/release on default
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/XS

#495 [ci-op-configs-mirror] Update only integration imagestreams to private ones
  cmd/ci-op-configs-mirror/main.go
  cmd/ci-op-configs-mirror/main_test.go
  test/ci-op-configs-mirror-integration/data/output/super-priv/duper/super-priv-duper-master.yaml
Labels: approved, lgtm, size/M

#497 ci-operator multi-stage: add tests with profiles
  pkg/steps/multi_stage.go
  test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-integration/multi-stage/expected/installer.json
Labels: approved, lgtm, size/L

#493 Autoowners: Remove non-org members
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm, size/M

#500 Revert "Keep presubmits openshift/release on default"
  pkg/migrate/migrate.go
Labels: approved, lgtm, size/XS

#501 help: use spaces, not tabs, for consistent indents
  pkg/webreg/webreg.go
Labels: approved, lgtm, size/XS
