Repository openshift/ci-tools, pull requests merged in 2020-06, with the labels that each got.

#873 Dptp-controller-manager: Log in-cluster config loading
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#869 ci-operator: split the import and creation of releases
  cmd/ci-operator/main.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#874 Revert "Merge pull request #869 from stevekuznetsov/skuznets/import-r…
  cmd/ci-operator/main.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
Labels: approved

#876 Test images distributor: Resolve multi-stage steps
  cmd/dptp-controller-manager/main.go
  hack/run-dptp-controller-manager.sh
  pkg/api/helper/imageextraction.go
  pkg/api/helper/imageextraction_test.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/load/agents/registryAgent.go
Labels: approved, lgtm

#875 Add script to revert ci-operator version
  hack/revert-ci-operator.sh
Labels: approved, lgtm

#794 [ci-operator-config-mirror] allow the tool to delete the existing but deprecated configs
  cmd/ci-operator-config-mirror/main.go
  test/integration/ci-operator-config-mirror.sh
  test/integration/ci-operator-config-mirror/input-to-clean/foo/bar/foo-bar-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/barry-white/super-priv-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/barry-white/super-priv-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/deprecated-repo/super-priv-deprecated-repo-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/duper/super-priv-duper-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/trooper/super-priv-trooper-deprecated.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/trooper/super-priv-trooper-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super/duper/super-duper-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super/trooper/super-trooper-master.yaml
Labels: approved, lgtm

#878 Promotionreconciler: Enable github IsNotFound based test
  go.mod
  go.sum
  pkg/controller/promotionreconciler/reconciler_test.go
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/bugzilla/fake.go
  vendor/k8s.io/test-infra/prow/bugzilla/types.go
  vendor/k8s.io/test-infra/prow/flagutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/flagutil/github.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/flagutil/storage.go
  vendor/k8s.io/test-infra/prow/gcsupload/BUILD.bazel
  vendor/k8s.io/test-infra/prow/gcsupload/options.go
  vendor/k8s.io/test-infra/prow/gcsupload/run.go
  vendor/k8s.io/test-infra/prow/git/git.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/hmac.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/initupload/BUILD.bazel
  vendor/k8s.io/test-infra/prow/io/BUILD.bazel
  vendor/k8s.io/test-infra/prow/io/opener.go
  vendor/k8s.io/test-infra/prow/io/option.go
  vendor/k8s.io/test-infra/prow/io/providers/BUILD.bazel
  vendor/k8s.io/test-infra/prow/io/providers/providers.go
  vendor/k8s.io/test-infra/prow/metrics/metrics.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/dco/dco.go
  vendor/k8s.io/test-infra/prow/plugins/retitle/retitle.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/generic-comment.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/k8s.io/test-infra/prow/plugins/verify-owners/verify-owners.go
  vendor/k8s.io/test-infra/prow/plugins/welcome/welcome.go
  vendor/k8s.io/test-infra/prow/plugins/wip/wip-label.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/k8s.io/test-infra/prow/sidecar/BUILD.bazel
  vendor/modules.txt
Labels: approved, lgtm

#879 registry: keep track of chain stack when resolving
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/load/agents/registryAgent.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/registry/graph.go
  pkg/registry/graph_test.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/webreg/graphviz.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#883 ci-operator: emit better errors when failing to resolve
  pkg/release/candidate/client.go
  pkg/release/official/client.go
  pkg/release/prerelease/client.go
Labels: approved, lgtm

#880 ci-operator: evaluate namespace at runtime
  cmd/ci-operator/main.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#885 Update boskos dependency to sigs.k8s.io/boskos
  go.mod
  go.sum
  pkg/lease/client.go
  pkg/lease/fake.go
  vendor/k8s.io/test-infra/boskos/client/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/common/BUILD.bazel
  vendor/k8s.io/test-infra/boskos/storage/BUILD.bazel
  vendor/modules.txt
  vendor/sigs.k8s.io/boskos/LICENSE
  vendor/sigs.k8s.io/boskos/client/README.md
  vendor/sigs.k8s.io/boskos/client/client.go
  vendor/sigs.k8s.io/boskos/common/common.go
  vendor/sigs.k8s.io/boskos/common/config.go
  vendor/sigs.k8s.io/boskos/common/mason_config.go
  vendor/sigs.k8s.io/boskos/storage/storage.go
Labels: approved, lgtm, ok-to-test

#882 Test images distributor: Create rbac for ci-operator
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#887 Limit dptp-controller-manager to 300 gh tokens/hour
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#871 Implement Prow Jobs dispatcher
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  go.mod
  pkg/dispatcher/prometheus.go
  pkg/dispatcher/prometheus_test.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/modules.txt
Labels: approved, lgtm

#854 ci-operator multi-stage: add step parameters
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#889 Use methods for getting/setting the namespace on jobConfig
  cmd/ci-operator/main.go
  pkg/api/job_spec.go
  pkg/defaults/defaults.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/template.go
Labels: approved, lgtm

#891 ci-operator: allow waiting before importing a release
  pkg/defaults/defaults.go
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#894 Test images distributor: use imagestream.status to find all tags
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#895 ci-operator: remove step link equality
  pkg/api/graph.go
Labels: approved, lgtm

#896 ci-operator: refactor step links to be generic on is or istag
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/release_images.go
  pkg/steps/template.go
Labels: approved, lgtm

#897 Remove validation for cluster field set in imagestreamtags
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm

#898 [ci-operator-config-mirror] Add the ability to mirror the configs from a specific organization
  cmd/autoconfigbrancher/main.go
  cmd/ci-operator-config-mirror/main.go
  test/integration/ci-operator-config-mirror.sh
  test/integration/ci-operator-config-mirror/output-only-super/foo/bar/foo-bar-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/duper/super-priv-duper-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/trooper/super-priv-trooper-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super/duper/super-duper-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super/trooper/super-trooper-master.yaml
Labels: approved, lgtm

#899 Remove remaining imagestreamtag cluster check
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm

#901 registry: copy step environment when resolving
  hack/lib/integration.sh
  pkg/load/load_test.go
  pkg/registry/resolver.go
  test/ci-operator-integration/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/ci-operator-integration/multi-stage/expected/installer.json
  test/ci-operator-integration/multi-stage/run.sh
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-golang111.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2.json
  test/multistage-registry/configmap/..2019_11_15_19_57_20.547184898/ipi-install-install-ref.yaml
  test/multistage-registry/registry/ipi/install/install/ipi-install-install-ref.yaml
  test/multistage-registry/registry/ipi/install/with-parameter/ipi-install-with-parameter-chain.yaml
Labels: approved, lgtm

#900 Rehearsals: Use ctlrruntimeclient for prowjobs
  cmd/config-change-trigger/main.go
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/pj-rehearse-integration/expected.yaml
  test/pj-rehearse-integration/run.sh
  vendor/k8s.io/test-infra/prow/client/clientset/versioned/fake/BUILD.bazel
  vendor/k8s.io/test-infra/prow/client/clientset/versioned/fake/clientset_generated.go
  vendor/k8s.io/test-infra/prow/client/clientset/versioned/fake/doc.go
  vendor/k8s.io/test-infra/prow/client/clientset/versioned/fake/register.go
  vendor/k8s.io/test-infra/prow/client/clientset/versioned/typed/prowjobs/v1/fake/BUILD.bazel
  vendor/k8s.io/test-infra/prow/client/clientset/versioned/typed/prowjobs/v1/fake/doc.go
  vendor/k8s.io/test-infra/prow/client/clientset/versioned/typed/prowjobs/v1/fake/fake_prowjob.go
  vendor/k8s.io/test-infra/prow/client/clientset/versioned/typed/prowjobs/v1/fake/fake_prowjobs_client.go
  vendor/modules.txt
Labels: approved, lgtm

#902 ci-operator: parameterize names of release steps
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#903 Rehearse: Set passed namespace
  hack/revert-ci-operator.sh
  pkg/rehearse/jobs.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved

#905 ci-operator: fix configuration access order
  cmd/ci-operator/main.go
Labels: approved, lgtm

#911 ci-operator: require stable image stream before creating tags
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
Labels: approved, lgtm

#912 ci-operator: set PathAlias iff --git-ref is set
  cmd/ci-operator/main.go
Labels: approved, lgtm

#910 Step tests: Use fixtures to make changes easier
  pkg/steps/source_test.go
  pkg/steps/testdata/TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/TestCreateBuild_with_ssh_key.yaml
Labels: approved, lgtm

#888 Implement prow-job-dispatcher
  cmd/prow-job-dispatcher/README.md
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/ci-tools-presubmits.yaml
  cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/cluster-api-provider-gcp-presubmits.yaml
  cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/cluster-etcd-operator-master-presubmits.yaml
  cmd/prow-job-dispatcher/testdata/TestDispatchJobs/basic_case/wildfly-operator-presubmits.yaml
  cmd/sanitize-prow-jobs/main.go
  cmd/sanitize-prow-jobs/main_test.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/dispatcher/testdata/TestLoadConfig/good_config.yaml
  pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm.yaml
  pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml
  pkg/dispatcher/testdata/TestLoadConfig/invalid_regex.yaml
  pkg/dispatcher/testdata/TestLoadConfig/invalid_yaml.yaml
Labels: approved, lgtm

#914 config-brancher: always update all affected versions
  cmd/config-brancher/main.go
  pkg/promotion/promotion_test.go
  test/integration/ci-operator-config-mirror.sh
  test/integration/config-brancher.sh
  test/integration/config-brancher/expected/org/bump/org-bump-master.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-release-4.5.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-release-4.6.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-master.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-release-4.5.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-release-4.6.yaml
  test/integration/config-brancher/expected/org/new/org-new-master.yaml
  test/integration/config-brancher/expected/org/new/org-new-release-4.5.yaml
  test/integration/config-brancher/expected/org/new/org-new-release-4.6.yaml
  test/integration/config-brancher/input/org/bump/org-bump-master.yaml
  test/integration/config-brancher/input/org/existing/org-existing-master.yaml
  test/integration/config-brancher/input/org/existing/org-existing-release-4.5.yaml
  test/integration/config-brancher/input/org/existing/org-existing-release-4.6.yaml
  test/integration/config-brancher/input/org/new/org-new-master.yaml
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm

#904 Support multiple build clusters in pj-rehearse
  cmd/pj-rehearse/main.go
  pkg/results/report.go
  test/pj-rehearse-integration/expected.yaml
Labels: approved, lgtm

#893 Remove dockercfg option from ci-operator
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/git_source.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  test/ci-operator-integration/base/expected_files/expected_pull_secret.json
  test/ci-operator-integration/base/run.sh
Labels: approved, lgtm

#916 Revert "Merge pull request #893 from alvaroaleman/remove-dockercfg-ma…
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/git_source.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  test/ci-operator-integration/base/expected_files/expected_pull_secret.json
  test/ci-operator-integration/base/run.sh
Labels: approved, lgtm

#917 Fix api.ci config loading
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#918 private-org-sync: use authentication for sources
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#919 autoowners: allow ignoring full orgs
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm

#920 Remove deprecated handling of nil registry from controller-manager
  cmd/dptp-controller-manager/main.go
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#923 Remove unused TagOverrides field from ReleaseTagConfiguration
  pkg/api/types.go
Labels: approved, lgtm

#924 webreg: fix broken chain table on homepage
  pkg/webreg/webreg.go
Labels: approved, lgtm

#922 TestImagesDistributor: Honor tag_specification
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/load/agents/configAgent.go
  pkg/load/agents/configAgent_test.go
Labels: approved, lgtm

#926 Promotionreconciler: Don't retry on multiple results
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
Labels: approved, lgtm

#927 ci-operator: unconditionally expose paramters from steps
  pkg/defaults/defaults.go
Labels: approved, lgtm

#928 Add unparam linter to prevent unused function arguments and returns
  .golangci.yml
  cmd/ci-operator/main.go
  cmd/private-prow-configs-mirror/main.go
  hack/lint.sh
  pkg/defaults/defaults.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/steps/artifacts.go
  pkg/steps/output_image_tag.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/write_params.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#929 Bump test-infra
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/modules.txt
Labels: approved, lgtm

#909 Rehearsals: Propagate back Imagestreamtags
  cmd/pj-rehearse/main.go
  pkg/api/helper/imageextraction.go
  pkg/api/metadata.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm

#930 Fix escaping of fixture names
  cmd/ci-operator-prowgen/testdata/postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit_testfromcioperatorconfigtoprowyaml_input_is_yaml_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit_testfromcioperatorconfigtoprowyaml_one_test_and_images__no_previous_jobs._expect_test_presubmit___pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit_testfromcioperatorconfigtoprowyaml_using_a_variant_config__one_test_and_images__one_existing_job._expect_one_presubmit__pre_post_submit_images_jobs._existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/presubmit_testfromcioperatorconfigtoprowyaml_input_is_yaml_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/presubmit_testfromcioperatorconfigtoprowyaml_one_test_and_images__no_previous_jobs._expect_test_presubmit___pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/presubmit_testfromcioperatorconfigtoprowyaml_using_a_variant_config__one_test_and_images__one_existing_job._expect_one_presubmit__pre_post_submit_images_jobs._existing_job_should_not_be_changed..yaml
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/TestGenerateJobs_Promotion_configuration_causes_promote_job.yaml
  pkg/prowgen/testdata/TestGenerateJobs_template_test_which_doesn_t_require_tag_specification_.yaml
  pkg/prowgen/testdata/TestGeneratePodSpecTemplate.yaml
  pkg/prowgen/testdata/TestGeneratePodSpecTemplate_testcase_0.yaml
  pkg/prowgen/testdata/TestGeneratePodSpecTemplate_testcase_1.yaml
  pkg/prowgen/testdata/TestGeneratePodSpecTemplate_testcase_2.yaml
  pkg/prowgen/testdata/TestGeneratePodSpecTemplate_testcase_3.yaml
  pkg/prowgen/testdata/TestGeneratePodSpecTemplate_testcase_4.yaml
  pkg/prowgen/testdata/TestGeneratePodSpecTemplate_testcase_5.yaml
  pkg/prowgen/testdata/TestGeneratePostSubmitForTest_first.yaml
  pkg/prowgen/testdata/TestGeneratePostSubmitForTest_second.yaml
  pkg/prowgen/testdata/TestGeneratePostSubmitForTest_third.yaml
  pkg/testhelper/testhelper.go
  pkg/testhelper/testhelper_test.go
Labels: approved, lgtm

#932 pkg/webreg: Normalize "release :" YAML
  pkg/webreg/webreg.go
Labels: approved, lgtm

#931 Configresolver test: Prevent flakes by making registry change atomic
  test/integration/ci-operator-configresolver.sh
Labels: approved, lgtm

#933 Remove stale fixtures and add prefix to identify fixtures
  cmd/ci-operator-prowgen/testdata/postsubmit_testfromcioperatorconfigtoprowyaml_input_is_yaml_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit_testfromcioperatorconfigtoprowyaml_one_test_and_images__no_previous_jobs._expect_test_presubmit___pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/postsubmit_testfromcioperatorconfigtoprowyaml_using_a_variant_config__one_test_and_images__one_existing_job._expect_one_presubmit__pre_post_submit_images_jobs._existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/presubmit_testfromcioperatorconfigtoprowyaml_input_is_yaml_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/presubmit_testfromcioperatorconfigtoprowyaml_one_test_and_images__no_previous_jobs._expect_test_presubmit___pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/presubmit_testfromcioperatorconfigtoprowyaml_using_a_variant_config__one_test_and_images__one_existing_job._expect_one_presubmit__pre_post_submit_images_jobs._existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_config_variant.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_expose_job_for_private_repos_with_public_results.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_expose_option_set_but_not_private.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_hidden_job_for_private_repos.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_no_special_options.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_path_alias.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_rehearsable.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_no_Promotion_configuration_has_no_branch_job.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_template_test.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_template_test_which_doesn_t_require_tag_specification_.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_two_tests_and_empty_Images_so_only_two_test_presubmits_are_generated.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_two_tests_and_nonempty_Images_so_two_test_presubmits_and_images_pre_postsubmits_are_generated_.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_a_test_in_a_variant_config.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_standard_test.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_0.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_1.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_2.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_3.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_4.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_5.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_additional_args_and_secret_are_included_in_podspec.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_additional_args_are_included_in_podspec.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_multiple_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_private_job.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_standard_use_case.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_first.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_second.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_third.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_a_test_in_a_variant_config.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_standard_test.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
  pkg/testhelper/testhelper.go
  pkg/testhelper/testhelper_test.go
Labels: approved, lgtm

#934 peribolos sync: add --only-org
  cmd/autoperibolossync/main.go
  cmd/private-org-peribolos-sync/main.go
Labels: approved, lgtm

#937 Enable unconvert and errcheck linter
  .golangci.yml
  cmd/ci-operator-config-mirror/main.go
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  cmd/config-brancher/main_test.go
  cmd/config-change-trigger/main.go
  cmd/determinize-ci-operator/main.go
  cmd/group-auto-updater/main.go
  cmd/pj-rehearse/main.go
  cmd/private-org-peribolos-sync/main.go
  cmd/private-prow-configs-mirror/main.go
  cmd/repo-brancher/main_test.go
  cmd/result-aggregator/main.go
  cmd/sanitize-prow-jobs/main.go
  cmd/secret-wrapper/main.go
  pkg/bitwarden/cli_test.go
  pkg/coalescer/coalescer_test.go
  pkg/controller/util/request_coalescer.go
  pkg/controller/util/request_coalescer_test.go
  pkg/load/agents/configAgent.go
  pkg/load/agents/registryAgent.go
  pkg/load/load_test.go
  pkg/promotion/promotion_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/release/candidate/client_test.go
  pkg/release/official/client_test.go
  pkg/release/prerelease/client_test.go
  pkg/steps/artifacts.go
  pkg/steps/template_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#935 PJ rehearse: Create imagestreamtag imports
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  test/pj-rehearse-integration/expected.yaml
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: approved, lgtm

#886 Bugzilla backporter tool
  cmd/bugzilla-backporter/main.go
  go.sum
  pkg/backporter/backporter.go
  pkg/backporter/backporter_test.go
  vendor/k8s.io/test-infra/pkg/flagutil/BUILD.bazel
  vendor/k8s.io/test-infra/pkg/flagutil/flagutil.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash

#938 ci-operator: allow explicit env overrides for releases
  pkg/defaults/defaults.go
  test/e2e/simple.sh
Labels: approved, lgtm

#939 TestImageDestributor: Add option to allowlist imagestreams
  cmd/dptp-controller-manager/main.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#941 ci-operator configs: omitempty images.from
  pkg/api/types.go
Labels: approved, lgtm

#940 Bugzilla: Add dockerfile for backporter deployment
  images/bugzilla-backporter/Dockerfile
Labels: approved, lgtm, tide/merge-method-squash

#943 Code cleanups in ci-op config Load()
  pkg/load/load.go
Labels: approved, lgtm

#945 test: migrate repo-init integration
  Makefile
  test/integration/repo-init.sh
  test/integration/repo-init/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/integration/repo-init/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
  test/integration/repo-init/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
  test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  test/integration/repo-init/expected/core-services/sanitize-prow-jobs/_config.yaml
  test/integration/repo-init/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/integration/repo-init/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
  test/integration/repo-init/input/core-services/prow/02_config/_config.yaml
  test/integration/repo-init/input/core-services/prow/02_config/_plugins.yaml
  test/integration/repo-init/input/core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, lgtm

#946 test: migrate testgrid-config-generator integration
  Makefile
  test/integration/testgrid-config-generator.sh
  test/integration/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
  test/integration/testgrid-config-generator/config/release/ocp-4.2.json
  test/integration/testgrid-config-generator/config/release/ocp-latest.json
  test/integration/testgrid-config-generator/config/release/okd-4.1.json
  test/integration/testgrid-config-generator/config/release/okd-4.2.json
  test/integration/testgrid-config-generator/config/testgrid/groups.yaml
  test/integration/testgrid-config-generator/config/testgrid/other.yaml
  test/integration/testgrid-config-generator/expected/groups.yaml
  test/integration/testgrid-config-generator/expected/other.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.3-broken.yaml
  test/testgrid-config-generator/run.sh
Labels: approved, lgtm

#948 test: migrate cvp-trigger integration
  Makefile
  test/cvp-trigger-integration/run.sh
  test/integration/cvp-trigger.sh
  test/integration/cvp-trigger/config.yaml
  test/integration/cvp-trigger/jobs.yaml
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#947 test: migrate group-auto-updater integration
  Makefile
  test/integration/group-auto-updater.sh
  test/integration/group-auto-updater/expected.yaml
  test/integration/group-auto-updater/peribolos-config.yaml
Labels: approved

#951 test: remove random unused files
  test/artifact/test.yaml
  test/env
  test/group-auto-updater-integration/run.sh
  test/template.yaml
  test/testdata/copy_input_tag_to_output.yaml
Labels: approved, lgtm

#949 test: update a test suite name
  test/integration/repo-init.sh
Labels: approved, lgtm

#950 test: migrate pj-rehearse integration
  Makefile
  hack/test-integration.sh
  pkg/config/template_test.go
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/candidate/ci-operator/config/super/duper/super-duper-ciop-cfg-change.yaml
  test/integration/pj-rehearse/candidate/ci-operator/config/super/duper/super-duper-master.yaml
  test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/templates/subdir/test-template.yaml
  test/integration/pj-rehearse/candidate/cluster/test-deploy/test-profile/vars.yaml
  test/integration/pj-rehearse/candidate/core-services/prow/02_config/_config.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/duper/super-duper-ciop-cfg-change.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/duper/super-duper-cluster-profile.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/duper/super-duper-master.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/templates/subdir/test-template.yaml
  test/integration/pj-rehearse/master/cluster/test-deploy/test-profile/vars-origin.yaml
  test/integration/pj-rehearse/master/cluster/test-deploy/test-profile/vars.yaml
  test/integration/pj-rehearse/master/core-services/prow/02_config/_config.yaml
  test/integration/pj-rehearse/master/core-services/prow/02_config/_plugins.yaml
  test/integration/testgrid-config-generator.sh
  test/pj-rehearse-integration/run.sh
Labels: approved, lgtm

#954 Boskos: Directly use app.ci rather than going via api.ci tunnel
  pkg/api/domain.go
  pkg/api/domain_test.go
Labels: approved, lgtm

#942 Add registry-replacer
  cmd/registry-replacer/README.md
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_ContextDir_is_respected.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Default_to_dockerfile.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Existing_base_image_is_not_overwritten.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_with_tag.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_without_tag.yaml
Labels: approved, lgtm, tide/merge-method-squash

#960 TestImageStreamImports: Use name that passes DNS-1123 validation
  cmd/pj-rehearse/main_test.go
  pkg/api/testimagestreamtagimport/v1/types.go
  pkg/api/testimagestreamtagimport/v1/types_test.go
Labels: approved, lgtm

#961 Update test-infra to 605ceec5b025
  go.mod
  go.sum
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
  test/integration/pj-rehearse/expected.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/git/git.go
  vendor/k8s.io/test-infra/prow/git/v2/client_factory.go
  vendor/k8s.io/test-infra/prow/git/v2/interactor.go
  vendor/k8s.io/test-infra/prow/logrusutil/logrusutil.go
  vendor/k8s.io/test-infra/prow/plugins/approve/approve.go
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/README.md
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/owners.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
  vendor/k8s.io/test-infra/prow/plugins/updateconfig/updateconfig.go
  vendor/k8s.io/test-infra/prow/pod-utils/clone/clone.go
  vendor/modules.txt
Labels: approved, lgtm

#955 Omitempty paths attribute
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_ContextDir_is_respected.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Default_to_dockerfile.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Existing_base_image_is_not_overwritten.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_with_tag.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Replaces_without_tag.yaml
  pkg/api/types.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
  test/integration/pj-rehearse/expected.yaml
  test/integration/repo-init/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#959 test: migrate ci-operator integration tests
  Makefile
  hack/lib/integration.sh
  hack/test-e2e.sh
  hack/test-integration.sh
  test/ci-operator-integration/base/expected_files/expected_src_oauth.json
  test/ci-operator-integration/base/expected_files/expected_src_ssh.json
  test/ci-operator-integration/base/run.sh
  test/ci-operator-integration/multi-stage/run.sh
  test/integration/ci-operator-configresolver/ci-op-configmaps/master/..2019_11_15_19_57_20.547184898/openshift-installer-master.yaml
  test/integration/ci-operator-configresolver/ci-op-configmaps/release-4.2/..2019_11_15_19_57_20.547184898/openshift-installer-release-4.2.yaml
  test/integration/ci-operator-configresolver/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/integration/ci-operator-configresolver/configs2/release-4.2/openshift-installer-release-4.2-golang111.yaml
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-golang111.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-regChange.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2.json
  test/integration/ci-operator.sh
  test/integration/ci-operator/base/auth_files/id_rsa
  test/integration/ci-operator/base/auth_files/oauth-token
  test/integration/ci-operator/base/config/test-config.yaml
  test/integration/ci-operator/base/config/test-template.yaml
  test/integration/ci-operator/base/expected_files/expected.json
  test/integration/ci-operator/base/expected_files/expected_pull_secret.json
  test/integration/ci-operator/base/expected_files/expected_src_oauth.json
  test/integration/ci-operator/base/expected_files/expected_src_ssh.json
  test/integration/ci-operator/base/expected_files/expected_with_template.json
  test/integration/ci-operator/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/integration/ci-operator/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/integration/ci-operator/multi-stage/expected/hyperkube.json
  test/integration/ci-operator/multi-stage/expected/installer.json
  test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/trooper/super-trooper-master.yaml
Labels: approved, lgtm

#956 Avoid no-op changes in integration test fixtures
  hack/lib/integration.sh
  test/integration/cvp-trigger.sh
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#957 Prowgen should handle duplicate targets
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
Labels: approved, lgtm

#962 Bump go-zglob to 0.0.2 to get brace expansion
  go.mod
  go.sum
  vendor/github.com/mattn/go-zglob/.travis.yml
  vendor/github.com/mattn/go-zglob/fastwalk/fastwalk_portable.go
  vendor/github.com/mattn/go-zglob/zglob.go
  vendor/modules.txt
Labels: approved, lgtm

#963 Builds: Consider DNS errors to be transient
  pkg/steps/source.go
Labels: approved, lgtm

#944 Fix pj-reherase integration flakes
  cmd/pj-rehearse/main.go
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#964 ci-operator multi-stage: allow empty env default
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/load/load_test.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm

#968 Add main branch support.
  pkg/api/metadata.go
  pkg/api/metadata_test.go
Labels: approved, lgtm
