Repository openshift/ci-tools, pull requests merged in 2020-07, with the labels that each got.

#967 ci-operator multi-stage: add E2E test
  pkg/load/load_test.go
  test/integration/ci-operator/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/integration/ci-operator/multi-stage/expected/installer.json
  test/multistage-registry/registry/ipi/install/empty-parameter/ipi-install-empty-parameter-chain.yaml
Labels: approved, lgtm

#970 pj-rehearse: Avoid reusing loop iterators in closures
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
Labels: approved, lgtm

#971 Consider a pullspec an input for ImportReleaseStep
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#965 Add run-resourcewatch (back) to upgrade tests
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#973 Conditionally run the resourcewatch during the upgrade tests
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#974 create namespace for leader election to succeed for resource watcher in upgrade
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#976 remove all changes for resourcewatch
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#983 Configresolver integration tests: Avoid flakyness by making atomic changes
  test/integration/ci-operator-configresolver.sh
Labels: approved, lgtm

#977 Ci-operator: Log more information when failing to import images
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#979 CI-Operator: Report lease type when acquiring fails
  pkg/steps/lease.go
Labels: approved, lgtm

#981 CI-Operator: Report successes
  cmd/ci-operator/main.go
  pkg/results/report.go
Labels: approved, lgtm

#984 PJ-Reharse: Do not create imports on api.ci
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
Labels: approved, lgtm

#966 Registry replacer: add pr creation functionality
  cmd/registry-replacer/main.go
  images/applyconfig/Dockerfile
  images/registry-replacer/Dockerfile
Labels: approved, lgtm

#985 Imagestreamtagwrapper: Significantly reduce allocations
  pkg/util/imagestreamtagwrapper/imagestreamtagwrapper.go
Labels: approved, lgtm

#936 Bugzilla: Create clones functionality for backporter
  cmd/bugzilla-backporter/main.go
  pkg/backporter/backporter.go
  pkg/backporter/backporter_test.go
Labels: approved, lgtm, tide/merge-method-squash

#953 pkg/steps: add new bundle source step
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/bundle_source.go
  pkg/steps/bundle_source_test.go
  pkg/steps/project_image.go
  pkg/steps/testdata/4.6-expected/meteringoperator.v4.6.0.clusterserviceversion.yaml
  pkg/steps/testdata/4.6/meteringoperator.v4.6.0.clusterserviceversion.yaml
  test/integration/ci-operator/base/config/test-config.yaml
  test/integration/ci-operator/base/expected_files/expected.json
  test/integration/ci-operator/base/expected_files/expected_pull_secret.json
  test/integration/ci-operator/base/expected_files/expected_with_template.json
Labels: approved, lgtm

#986 PJ-Reharse: Deduplicate extraRefs/Refs
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#987 Registry Replacer: Add github flags
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#988 Registry replacer: Add git to the docker image
  images/autoconfigbrancher/Dockerfile
  images/registry-replacer/Dockerfile
Labels: approved, lgtm

#989 Registry replacer: Fix github client init
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#991 Registry cleaner: Prune replacements
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
Labels: approved, lgtm

#993 pj-rehearse code cleanups
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/config/release_test.go
  pkg/config/template.go
  pkg/config/template_test.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm

#995 Registry replacer: Add explanation in PR body
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#978 Pod step: Fail if pod doesn't start running within 30 minutes
  pkg/steps/source.go
  pkg/steps/template.go
Labels: approved, lgtm

#994 rehearse: extract CMManager to rehearse package
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/rehearse/configmaps.go
  pkg/rehearse/configmaps_test.go
Labels: approved, lgtm

#998 Imagebuild: All mirrors tried means its non-terminal
  pkg/steps/source.go
Labels: approved, lgtm

#997 Registry replacer pruning: Consider copy --from and allow alias replacement
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/replacement.go
Labels: approved, lgtm

#1001 Registry replacer: Fix self-approve option
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#1003 add more logging to the group-auto-updater tool
  cmd/group-auto-updater/main.go
Labels: approved, lgtm

#1005 [DPTP-1119] Allow ReporterConfig for Slack notifications to be added …
  pkg/jobconfig/files.go
Labels: approved, lgtm

#1002 CI-Operator: Dump step graph to artifacts
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1008 Bump test-infra to 2d13d8065278
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/metrics/BUILD.bazel
  vendor/k8s.io/test-infra/prow/metrics/http.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/lgtm/lgtm.go
  vendor/modules.txt
Labels: approved, lgtm

#1009 Factor githubFileGetter out of registry-replacer
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  pkg/github/github.go
Labels: approved, lgtm

#1010 Bump test-infra to 96f632166e02 to get some omitempties
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/modules.txt
Labels: approved, lgtm

#1011 multi_stage: add link to registry info page for failed steps
  pkg/steps/multi_stage.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1014 Kubeconfig loading: Error if env var has not found kubeconfig
  pkg/util/client.go
  pkg/util/client_test.go
Labels: approved, lgtm

#1007 e2e: add a test that runs a template
  cmd/ci-operator/main.go
  test/e2e/simple.sh
  test/e2e/simple/artifacts/junit_operator.xml
  test/e2e/simple/artifacts/template/container-logs/cli.log.gz
  test/e2e/simple/artifacts/template/container-logs/setup.log.gz
  test/e2e/simple/artifacts/template/container-logs/teardown.log.gz
  test/e2e/simple/artifacts/template/container-logs/test.log.gz
  test/e2e/simple/artifacts/template/setup
  test/e2e/simple/artifacts/template/teardown
  test/e2e/simple/artifacts/template/test
  test/e2e/simple/template-config.yaml
  test/e2e/simple/template.yaml
  test/integration/ci-operator/base/config/test-template.yaml
  test/integration/ci-operator/base/expected_files/expected_with_template.json
Labels: approved, lgtm

#1016 provide an explicit sample invocation for testgrid-config-generator
  cmd/testgrid-config-generator/README.md
Labels: approved, lgtm

#1018 ci-operator: expose rpm repo env var for periodics
  pkg/steps/rpm_server.go
Labels: approved, lgtm

#1012 vendor: update test-infra dependency
  Makefile
  go.mod
  go.sum
  pkg/backporter/backporter_test.go
  vendor/k8s.io/test-infra/prow/bugzilla/BUILD.bazel
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/bugzilla/fake.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/modules.txt
Labels: approved, lgtm

#1021 pkg/registry: simplify tests
  pkg/registry/resolver_test.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#1020 Registry replacer: Prune ocp/builder replacements
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_OCP_builder_pruning_happens.yaml
Labels: approved, lgtm

#996 rehearse: rework the handling of temporary CMs
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/config/release_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/configmaps.go
  pkg/rehearse/configmaps_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#969 Use upstream prow package for http metrics
  cmd/bugzilla-backporter/main.go
  cmd/ci-operator-configresolver/main.go
  pkg/backporter/backporter.go
  pkg/backporter/backporter_test.go
Labels: approved, lgtm, tide/merge-method-squash

#906 Define AllowSkipOnSuccess and OptionalOnSuccess flags
  pkg/api/config.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/webreg/webreg.go
  test/e2e/multi-stage.sh
  test/e2e/multi-stage/config.yaml
Labels: approved, lgtm

#1006 Add maketarget for deploying the bugzilla backporter from a PR
  Makefile
  hack/pr-deploy-backporter.yaml
Labels: approved, lgtm, tide/merge-method-squash

#1022 Update test-infra to 4e866c6
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/bugzilla/fake.go
  vendor/k8s.io/test-infra/prow/githubeventserver/githubeventserver.go
  vendor/k8s.io/test-infra/prow/githubeventserver/options.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/modules.txt
Labels: approved, lgtm

#1024 ci-operator: remove dry-run functionality
  cmd/ci-operator/main.go
  cmd/group-auto-updater/main.go
  cmd/secret-wrapper/main.go
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/defaults/defaults.go
  pkg/steps/bundle_source.go
  pkg/steps/bundle_source_test.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/input_env.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  pkg/steps/testing.go
  pkg/steps/testing_test.go
  pkg/steps/write_params.go
  test/e2e/simple/template.yaml
  test/integration/ci-operator.sh
  test/integration/ci-operator/base/auth_files/id_rsa
  test/integration/ci-operator/base/auth_files/oauth-token
  test/integration/ci-operator/base/config/test-config.yaml
  test/integration/ci-operator/base/config/test-template.yaml
  test/integration/ci-operator/base/expected_files/expected.json
  test/integration/ci-operator/base/expected_files/expected_pull_secret.json
  test/integration/ci-operator/base/expected_files/expected_src_oauth.json
  test/integration/ci-operator/base/expected_files/expected_src_ssh.json
  test/integration/ci-operator/base/expected_files/expected_with_template.json
  test/integration/ci-operator/multi-stage/configs/master/openshift-hyperkube-master.yaml
  test/integration/ci-operator/multi-stage/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/integration/ci-operator/multi-stage/expected/hyperkube.json
  test/integration/ci-operator/multi-stage/expected/installer.json
  test/integration/group-auto-updater/expected.yaml
  test/secret-wrapper-integration.sh
Labels: approved, lgtm

#1027 update test-infra vendors
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/githubeventserver/BUILD.bazel
  vendor/k8s.io/test-infra/prow/githubeventserver/githubeventserver.go
  vendor/k8s.io/test-infra/prow/hook/plugin-imports/BUILD.bazel
  vendor/k8s.io/test-infra/prow/hook/plugin-imports/plugin-imports.go
  vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/merge-method-comment/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/merge-method-comment/merge-method-comment.go
  vendor/modules.txt
Labels: approved, lgtm

#990 Parallelize externalBugPR calls and add help option
  cmd/bugzilla-backporter/main.go
  pkg/backporter/backporter.go
Labels: approved, lgtm

#952 ci-operator: DRY out the relationships between step links and env
  cmd/cvp-trigger/main.go
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/api/parameters.go
  pkg/api/parameters_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/bundle_source.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/images_ready_test.go
  pkg/steps/input_env.go
  pkg/steps/input_env_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/testing.go
  pkg/steps/utils/env.go
  pkg/steps/utils/env_test.go
  pkg/steps/utils/image.go
  pkg/steps/write_params.go
  pkg/steps/write_params_test.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#1031 dptp-controller-manager: a new flag additional-image-stream-namespaces
  cmd/dptp-controller-manager/main.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1028 cmd/ipi-deprovision: Fall back to assuming us-east1 for GCP
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#1032 pkg/webreg: Document openshift-priv management via private-prow-configs-mirror
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1025 Ci-Operator: Create PDBs to prevent evictions of test workloads
  cmd/ci-operator/main.go
  pkg/util/namespacewrapper/namespacewrapper.go
  pkg/util/secret.go
Labels: approved, lgtm

#1033 rehearse: fix `wait.Poll` return value
  pkg/rehearse/jobs.go
Labels: approved, lgtm

#1026 Use gotestsum to produce junit in tests
  Makefile
  hack/test-go.sh
Labels: approved, lgtm

#1030 pkg/steps/artifacts: Wait for running artifacts container
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm

#1035 CI operator: Don't panic when reporting fails
  pkg/results/report.go
Labels: approved, lgtm

#1015 Add a caching transport for the Bugzilla client
  cmd/bugzilla-backporter/main.go
  pkg/backporter/httpcache.go
  pkg/backporter/httpcache_test.go
Labels: approved, lgtm, tide/merge-method-squash

#1038 initial commit for auto publicize config tool
  cmd/autopublicizeconfig/README.md
  cmd/autopublicizeconfig/main.go
  images/autopublicizeconfig/Dockerfile
Labels: approved, lgtm

#1040 Bugzilla backporter TestRoundTrip: Deflake
  pkg/backporter/httpcache.go
  pkg/backporter/httpcache_test.go
Labels: approved, lgtm

#1029 generate-registry-metadata: create new tool
  cmd/generate-registry-metadata/main.go
  cmd/generate-registry-metadata/main_test.go
  pkg/api/types.go
  pkg/load/load.go
  test/multistage-registry/registry-metadata/README.md
  test/multistage-registry/registry-metadata/ipi/OWNERS
  test/multistage-registry/registry-metadata/ipi/deprovision/OWNERS
  test/multistage-registry/registry-metadata/ipi/deprovision/deprovision/OWNERS
  test/multistage-registry/registry-metadata/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  test/multistage-registry/registry-metadata/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.yaml
  test/multistage-registry/registry-metadata/ipi/deprovision/ipi-deprovision-chain.yaml
  test/multistage-registry/registry-metadata/ipi/deprovision/must-gather/OWNERS
  test/multistage-registry/registry-metadata/ipi/deprovision/must-gather/ipi-deprovision-must-gather-commands.sh
  test/multistage-registry/registry-metadata/ipi/deprovision/must-gather/ipi-deprovision-must-gather-ref.yaml
  test/multistage-registry/registry-metadata/ipi/install/OWNERS
  test/multistage-registry/registry-metadata/ipi/install/install/OWNERS
  test/multistage-registry/registry-metadata/ipi/install/install/ipi-install-install-commands.sh
  test/multistage-registry/registry-metadata/ipi/install/install/ipi-install-install-ref.yaml
  test/multistage-registry/registry-metadata/ipi/install/ipi-install-chain.yaml
  test/multistage-registry/registry-metadata/ipi/install/rbac/OWNERS
  test/multistage-registry/registry-metadata/ipi/install/rbac/ipi-install-rbac-commands.sh
  test/multistage-registry/registry-metadata/ipi/install/rbac/ipi-install-rbac-ref.yaml
  test/multistage-registry/registry-metadata/ipi/ipi-workflow.yaml
  test/multistage-registry/registry-metadata/metadata.json
Labels: approved, lgtm

#1037 Enable allow_skip_on_success also for non-literal MultiStageTestConfi…
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  test/e2e/multi-stage/config.yaml
Labels: approved, lgtm

#1036 Add ocp-build-data enforcer
  cmd/ocp-build-data-enforcer/README.md
  cmd/ocp-build-data-enforcer/main.go
  cmd/ocp-build-data-enforcer/main_test.go
  cmd/ocp-build-data-enforcer/types.go
  cmd/ocp-build-data-enforcer/types_test.go
Labels: approved, lgtm, tide/merge-method-squash

#1041 images: add generate-registry-metadata image
  images/generate-registry-metadata/Dockerfile
Labels: approved, lgtm

#1039 Replace landing page with the help page
  pkg/backporter/backporter.go
  pkg/backporter/backporter_test.go
Labels: approved, lgtm

#1045 images/generate-registry-metadata: install diffutils
  images/generate-registry-metadata/Dockerfile
Labels: approved, lgtm

#1046 Revert "ci-operator: DRY out the relationships between step links and env"
  cmd/cvp-trigger/main.go
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/api/parameters.go
  pkg/api/parameters_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/bundle_source.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/images_ready_test.go
  pkg/steps/input_env.go
  pkg/steps/input_env_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/testing.go
  pkg/steps/utils/env.go
  pkg/steps/utils/env_test.go
  pkg/steps/utils/image.go
  pkg/steps/write_params.go
  pkg/steps/write_params_test.go
Labels: approved, lgtm

#1042 appyconfig: support symlinks
  cmd/applyconfig/applyconfig.go
Labels: approved, lgtm

#1047 applyconfig: handle properly the relative path of a symlink
  cmd/applyconfig/applyconfig.go
Labels: approved, lgtm

#1051 Config Agent: Fix data race
  pkg/load/agents/configAgent.go
Labels: approved, lgtm

#1043 webreg: add metadata based info to web UI
  cmd/pj-rehearse/main.go
  pkg/config/release.go
  pkg/load/agents/registryAgent.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/rehearse/jobs_test.go
  pkg/webreg/graphviz_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1050 Revert "Revert "ci-operator: DRY out the relationships between step links and env""
  cmd/cvp-trigger/main.go
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/api/parameters.go
  pkg/api/parameters_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/bundle_source.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/images_ready_test.go
  pkg/steps/input_env.go
  pkg/steps/input_env_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/testing.go
  pkg/steps/utils/env.go
  pkg/steps/utils/env_test.go
  pkg/steps/utils/image.go
  pkg/steps/write_params.go
  pkg/steps/write_params_test.go
Labels: approved, lgtm

#1048 ci-operator: use the vanity URL for our config API
  cmd/ci-operator/main.go
  pkg/api/domain.go
  pkg/api/domain_test.go
  test/integration/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.3-broken.yaml
Labels: approved, lgtm

#1052 Parallelize config loading
  pkg/load/load.go
Labels: approved, lgtm

#1054 Test image distributor: Make sure imagestreams have local: true
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#872 init implementation of the publicize plugin
  cmd/publicize/README.md
  cmd/publicize/main.go
  cmd/publicize/server.go
  cmd/publicize/server_test.go
  go.mod
  go.sum
  images/publicize/Dockerfile
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/git/localgit/BUILD.bazel
  vendor/k8s.io/test-infra/prow/git/localgit/localgit.go
  vendor/k8s.io/test-infra/prow/git/v2/remote.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/modules.txt
Labels: approved, lgtm

#1055 ipi-deprovision: send SIGQUIT to installer on timeout
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#1056 Fix pod timeout check
  pkg/steps/template.go
Labels: approved, lgtm

#1057 [pkg/report] fix result's report message
  pkg/results/report.go
Labels: approved, lgtm

#1053 FIx some linting issues found by newer versions of golangci-lint
  cmd/ci-secret-bootstrap/main.go
  pkg/steps/input_env.go
Labels: approved, lgtm
