Repository openshift/ci-tools, pull requests merged in 2020-12, with the labels that each got.

#1456 pkg/defaults: add step leases to tests
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  test/e2e/lease.sh
  test/e2e/lease/boskos.yaml
  test/e2e/lease/config.yaml
  test/e2e/lease/step-registry/declare-and-check-leases/declare-and-check-leases-commands.sh
  test/e2e/lease/step-registry/declare-and-check-leases/declare-and-check-leases-ref.yaml
Labels: approved, lgtm

#1472 isTag handler: reconcile when DeletionTimestamp is defined
  pkg/util/imagestreamtagmapper/imagestreamtagmapper.go
  pkg/util/imagestreamtagmapper/imagestreamtagmapper_test.go
Labels: approved, lgtm

#1471 Add maketarget to install binaries in race mode
  Makefile
  hack/install.sh
Labels: approved, lgtm

#1469 DPTP-CM: Use protobuf where possible
  cmd/dptp-controller-manager/main.go
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/deleg_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client_cache.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/split.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/metrics/metrics.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/client_builder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/manager.go
Labels: approved, lgtm

#1467 ci-operator multi-stage: add a count to leases
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/lease/client.go
  pkg/lease/client_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  test/e2e/lease.sh
  test/e2e/lease/boskos.yaml
  test/e2e/lease/config.yaml
  test/e2e/lease/step-registry/declare-and-check-leases-with-count/declare-and-check-leases-with-count-commands.sh
  test/e2e/lease/step-registry/declare-and-check-leases-with-count/declare-and-check-leases-with-count-ref.yaml
Labels: approved, lgtm

#1430 pj-rehearse: support handcrafted jobs with UNRESOLVED_CONFIG
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#1474 Revert "ipi-deprovisioner: tighen timeout to 10m per cluster"
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#1445 secretsyncer: Watch for config changes
  cmd/dptp-controller-manager/main.go
  pkg/controller/secretsyncer/config/agent.go
  pkg/controller/secretsyncer/config/agent_test.go
  pkg/controller/secretsyncer/secretsyncer.go
Labels: approved, lgtm

#1464 Allow unmarshaling ci-operator step graph
  cmd/ci-operator/main.go
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/loggingclient/loggingclient.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/run.go
Labels: approved, lgtm

#1475 registrySyncer: remove locks on imagestream at reconcile
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
Labels: approved, lgtm

#1476 registrySyncer: delete IS when it is deleted on any cluster
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
Labels: approved, lgtm

#1479 ci-operator: clean up scheme init
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1481 registrySyncer: ingore logging of IsAlreadyExists errors
  pkg/controller/registrysyncer/registrysyncer.go
Labels: approved, lgtm

#1477 [DPTP-1731] add the ability to create rbacs and wait until the image pull secret has been created
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/util/rbacs.go
  pkg/util/rbacs_test.go
Labels: approved, lgtm

#1478 template-deprecator: add enforcing checks
  cmd/template-deprecator/main.go
  pkg/deprecatetemplates/allowlist.go
  pkg/deprecatetemplates/allowlist_test.go
  pkg/deprecatetemplates/enforcer.go
  pkg/deprecatetemplates/enforcer_test.go
Labels: approved, lgtm

#1480 ci-operator: allow passing a GCS upload secret
  cmd/ci-operator/main.go
  pkg/api/constant.go
Labels: approved, lgtm

#1482 slack-bot: fix rehearsal PR link
  pkg/slack/events/joblink/link.go
Labels: approved, lgtm

#1437 registrysyncer: use isTag instead of isImport
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
Labels: approved, lgtm

#1485 ci-operator: stop explicitly updating submodules
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
Labels: approved, lgtm

#1486 ci-operator: throughput limit xargs on clone
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
Labels: approved, lgtm

#1483 registrySyncer: delete isTags when they are soft-deleted
  pkg/api/constant.go
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
  pkg/util/imagestreamtagmapper/imagestreamtagmapper.go
  pkg/util/imagestreamtagmapper/imagestreamtagmapper_test.go
Labels: approved, lgtm

#1492 Bump test-infra
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/git/git.go
  vendor/k8s.io/test-infra/prow/git/v2/adapter.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/hook/plugin-imports/BUILD.bazel
  vendor/k8s.io/test-infra/prow/hook/plugin-imports/plugin-imports.go
  vendor/k8s.io/test-infra/prow/kube/BUILD.bazel
  vendor/k8s.io/test-infra/prow/kube/metrics.go
  vendor/k8s.io/test-infra/prow/labels/labels.go
  vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/lgtm/lgtm.go
  vendor/k8s.io/test-infra/prow/plugins/milestone/milestone.go
  vendor/k8s.io/test-infra/prow/plugins/milestonestatus/milestonestatus.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/plugins/project/project.go
  vendor/k8s.io/test-infra/prow/plugins/projectmanager/projectmanager.go
  vendor/k8s.io/test-infra/prow/plugins/requiresig/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/requiresig/requiresig.go
  vendor/k8s.io/test-infra/prow/sidecar/options.go
  vendor/k8s.io/test-infra/prow/sidecar/run.go
  vendor/k8s.io/test-infra/prow/version/BUILD.bazel
  vendor/k8s.io/test-infra/prow/version/doc.go
  vendor/modules.txt
Labels: approved

#1493 ci-operator: update to new clonerefs location
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/source_test.go
Labels: approved, lgtm

#1494 ci-operator: use a managed clonerefs image
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
Labels: approved, lgtm

#1496 CI operator: Hearbeat namespace before creating secrets or rbac
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1497 registrySyncer: use RFC3339 to format soft-delete annotation
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
Labels: approved, lgtm

#1498 Make sure provided home is writeable
  pkg/steps/multi_stage.go
  pkg/steps/testdata/zz_fixture_TestGeneratePodReadonly.yaml
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#1488 CI operator: Disable klog
  cmd/ci-operator/main.go
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#1491 Make CI Registry configurable
  cmd/dptp-controller-manager/main.go
  pkg/api/domain.go
  pkg/api/domain_test.go
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
  pkg/controller/secretsyncer/secretsyncer.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1500 vendor: bump slack dependency
  go.mod
  go.sum
  pkg/slack/modals/incident/view.go
  vendor/github.com/slack-go/slack/.golangci.yml
  vendor/github.com/slack-go/slack/.travis.yml
  vendor/github.com/slack-go/slack/CHANGELOG.md
  vendor/github.com/slack-go/slack/README.md
  vendor/github.com/slack-go/slack/apps.go
  vendor/github.com/slack-go/slack/attachments.go
  vendor/github.com/slack-go/slack/block_action.go
  vendor/github.com/slack-go/slack/block_element.go
  vendor/github.com/slack-go/slack/block_object.go
  vendor/github.com/slack-go/slack/channels.go
  vendor/github.com/slack-go/slack/chat.go
  vendor/github.com/slack-go/slack/conversation.go
  vendor/github.com/slack-go/slack/dialog.go
  vendor/github.com/slack-go/slack/files.go
  vendor/github.com/slack-go/slack/go.sum
  vendor/github.com/slack-go/slack/groups.go
  vendor/github.com/slack-go/slack/im.go
  vendor/github.com/slack-go/slack/interactions.go
  vendor/github.com/slack-go/slack/logo.png
  vendor/github.com/slack-go/slack/messages.go
  vendor/github.com/slack-go/slack/misc.go
  vendor/github.com/slack-go/slack/reminders.go
  vendor/github.com/slack-go/slack/slack.go
  vendor/github.com/slack-go/slack/slackevents/inner_events.go
  vendor/github.com/slack-go/slack/slackevents/outer_events.go
  vendor/github.com/slack-go/slack/slash.go
  vendor/github.com/slack-go/slack/users.go
  vendor/modules.txt
Labels: approved, lgtm

#1502 Rename var apiCIRegistry to ciRegistry
  pkg/steps/input_image_tag.go
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1499 Add feature to automatically migrate openshift_installer jobs
  cmd/determinize-ci-operator/main.go
  cmd/determinize-ci-operator/main_test.go
Labels: approved, lgtm

#1426 ci-secret-bootstrap: validate config
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/api/secretbootstrap/secretboostrap_test.go
Labels: approved, lgtm

#1501 ipi-deprovision: fix failure report
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#1511 Migrate to non-loki upgrade workflow
  cmd/determinize-ci-operator/main.go
  cmd/determinize-ci-operator/main_test.go
Labels: approved, lgtm

#1508 e2e: verify that the boskos server started
  hack/lib/integration.sh
  test/e2e/lease.sh
Labels: approved, lgtm

#1505 registrySyncer: sync all images by default
  cmd/dptp-controller-manager/main.go
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
Labels: approved, lgtm

#1506 make: add simple targets to streamline e2e
  Makefile
Labels: approved, lgtm

#1514 Makefile: only setup E2E environment outside of CI
  Makefile
Labels: approved, do-not-merge/hold, lgtm

#1516 ci-operator: provide better errors when failing to resolve releases
  pkg/release/candidate/client.go
  pkg/release/official/client.go
  pkg/release/prerelease/client.go
Labels: approved, lgtm

#1512 ci-operator: allow marking post steps as best-effort
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/multi-stage.sh
  test/e2e/multi-stage/best-effort.yaml
Labels: approved, lgtm

#1515 Artifacts: Remove stack printing
  pkg/steps/artifacts.go
Labels: approved, lgtm

#1503 Promote images to app.ci
  pkg/api/domain.go
  pkg/api/domain_test.go
  pkg/steps/release/promote_test.go
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#1513 regSyncer: ingore images in ci-ln* namespaces
  pkg/controller/registrysyncer/registrysyncer.go
Labels: approved, lgtm

#1517 ci-operator multi-stage: add lease env once
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1520 Revert "Promote images to app.ci"
  pkg/api/domain.go
  pkg/api/domain_test.go
  pkg/steps/release/promote_test.go
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved

#1519 registry-replacer: recognize domain registry.ci.openshift.org
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
Labels: approved, lgtm

#1521 Revert "Revert "Promote images to app.ci""
  pkg/api/domain.go
  pkg/api/domain_test.go
  pkg/steps/release/promote_test.go
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#1510 prowgen: provide the GCS secret to tests
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_0.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_1.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_2.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_3.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_4.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_5.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_additional_args_and_secret_are_included_in_podspec.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_additional_args_are_included_in_podspec.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_multiple_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_private_job.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_standard_use_case.yaml
  test/integration/ci-operator-prowgen/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-job-release-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
Labels: approved, lgtm

#1523 Check app.ci's kubeconfig after loading InClusterConfig
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#1526 Fix test_images_distributor when app.ci is registry cluster
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#1509 [DPTP-1721] make repo-init tool to generate multi-stage jobs instead of templates
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  pkg/api/types.go
  test/integration/repo-init.sh
  test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/integration/repo-init/expected/ci-operator/config/org/third/org-third-nonstandard.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
Labels: approved, lgtm

#1530 config: document resource requests and limits
  pkg/api/types.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1527 pkg/steps/clusterinstall/template: Get region from Boskos lease
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#1531 vendor: bump test-infra
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/flagutil/github.go
  vendor/k8s.io/test-infra/prow/git/v2/client_factory.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/modules.txt
Labels: approved, lgtm

#1529 load: print response body from configresolver for literal configs
  pkg/load/load.go
Labels: approved, lgtm

#1532 autobumper: put credentials back in remote for MakeGitCommit
  cmd/autobumper/main.go
Labels: approved, lgtm

#1535 pkg/steps/clusterinstall/template: Add LEASED_RESOURCE parameter
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#1539 registerSyncer: Allow images pushed back to the original cluster
  pkg/controller/registrysyncer/registrysyncer.go
Labels: approved, lgtm

#1540 release-job-migrator: fix release-controller jobName replacement
  cmd/release-job-migrator/main.go
  test/integration/release-job-migrator/expected.txt
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
  test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.7-periodics.yaml
  test/integration/release-job-migrator/expected/releases/release-origin-4.7.json
  test/integration/release-job-migrator/input/jobs/openshift-release-release-4.6-periodics.yaml
  test/integration/release-job-migrator/input/jobs/openshift-release-release-4.7-periodics.yaml
  test/integration/release-job-migrator/input/releases/release-origin-4.7.json
Labels: approved, lgtm

#1542 Add Dockerfile for cvp-trigger
  images/cvp-trigger/Dockerfile
Labels: approved, lgtm

#1522 webreg: surface `from_image` in UI
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1541 secret-wrapper: do not log cancellations
  cmd/secret-wrapper/main.go
Labels: approved, lgtm

#1533 pkg/steps/clusterinstall/template: GCP region from the cluster
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#1538 e2e: implement tests in go
  Makefile
  hack/test-go.sh
  test/e2e/framework/framework.go
  test/e2e/simple.sh
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#1543 Wait for 10 secs for the IS to appear after creating it
  pkg/controller/registrysyncer/registrysyncer.go
Labels: approved, lgtm

#1544 test-images-distributor: ingore logging IsConflict errors
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#1545 release-job-migrator: don't add `base` to `base_images`
  cmd/release-job-migrator/main.go
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__okd-4.7.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.4-nightly-to-4.4-nightly.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.5-stable-to-4.6-ci.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6-to-4.7.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.7.yaml
Labels: approved, lgtm

#1548 prowgen: add CPaaS AWS profile
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cluster_profile.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cpaas_cluster_profile.yaml
  pkg/validation/test.go
Labels: approved, lgtm

#1549 test-images-distributor: no distribution to api.ci
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#1504 Adding the cluster profile for libvirt ppc64le
  pkg/prowgen/prowgen.go
Labels: approved, lgtm

#1550 pkg/defaults: deduplicate input images
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#1551 ci-operator: remove name_prefix fields
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/steps/release/release_images.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1553 webreg: parse base template in init()
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1552 webreg: tune spacing for h3
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1555 Retry oc image mirror when promoting
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
Labels: approved, lgtm

#1554 Registry syncer: Do not import from api.ci, app.ci is source of truth
  cmd/dptp-controller-manager/main.go
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
Labels: approved, lgtm

#1557 Promotion retrying: Remove wrong shift
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
Labels: approved

#1558 Revert ci-operator script: Use correct cluster
  hack/revert-ci-operator.sh
Labels: approved, lgtm

#1546 Secret generator: Install gcloud CLI
  images/ci-secret-generator/Dockerfile
  images/ci-secret-generator/google-cloud-sdk.repo
Labels: approved, lgtm

#1547 test: e2e: run multi-stage in Go
  cmd/ci-operator-configresolver/main.go
  hack/lint.sh
  pkg/load/load.go
  pkg/steps/multi_stage.go
  test/e2e/framework/ci-operator.go
  test/e2e/framework/framework.go
  test/e2e/framework/test.go
  test/e2e/multi-stage.sh
  test/e2e/multi-stage/e2e_test.go
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#1556 ci-secret-bootstrap: tolerate unused secrets for 7 days after modification
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli_test.go
Labels: approved, lgtm

#1560 ci-operator: resolve imported release image pullspec better
  Makefile
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  test/e2e/framework/framework.go
  test/e2e/simple/e2e_test.go
Labels: approved

#1562 e2e: idk what i am doing
  test/e2e/framework/framework.go
Labels: approved, lgtm

#1564 ci-operator: be more performant on promotion
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
Labels: approved, lgtm
