Repository openshift/ci-tools, pull requests merged in 2021-07, with the labels that each got.

#2132 cluster claims: override release payload images
  pkg/api/config.go
  pkg/defaults/defaults.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  test/e2e/multi-stage/cluster-claim.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#2122 Containertest: Add setting to clone
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
  pkg/validation/test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/multi-stage/configs/master/..2019_11_15_19_57_20.547184898/test-test-master.yaml
  test/e2e/multi-stage/e2e_test.go
  test/e2e/simple/config.yaml
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm, tide/merge-method-squash

#2134 Add `checkconfig` validation script
  Makefile
  test/validate-checkconfig.sh
Labels: approved, lgtm

#2140 validate-checkconfig: use `openshift` registry
  test/validate-checkconfig.sh
Labels: approved, lgtm

#2139 ci-operator-checkconfig: correct synchronization
  cmd/ci-operator-checkconfig/main.go
Labels: approved, lgtm

#2138 ci-operator: select best pool when there are more
  pkg/steps/utils/clusterpool.go
  pkg/steps/utils/clusterpool_test.go
Labels: approved, lgtm

#2101 pod-scaler: add an e2e test
  Makefile
  cmd/pod-scaler/producer.go
  cmd/pod-scaler/producer_test.go
  go.mod
  go.sum
  test/e2e/pod-scaler/e2e_test.go
  test/e2e/pod-scaler/kubernetes/kubernetes.go
  test/e2e/pod-scaler/local/main.go
  test/e2e/pod-scaler/prometheus/backfill.go
  test/e2e/pod-scaler/prometheus/prometheus.go
  test/e2e/pod-scaler/run/producer.go
  test/images/e2e-bin/Dockerfile
  vendor/github.com/prometheus/prometheus/LICENSE
  vendor/github.com/prometheus/prometheus/NOTICE
  vendor/github.com/prometheus/prometheus/pkg/value/value.go
  vendor/modules.txt
Labels: approved, lgtm

#2143 CI Operator: Make sure cloning is not disabled when cloning
  pkg/steps/artifacts.go
  pkg/steps/pod_test.go
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#2145 sprint-automation: digest issues ready for acceptance
  cmd/sprint-automation/main.go
  pkg/jira/issues.go
Labels: approved, lgtm

#2147 sprint-automation: add an image build
  images/sprint-automation/Dockerfile
Labels: approved, lgtm

#2146 dptp-controller-manager: distribute build caches even for repos with in-repo config
  cmd/dptp-controller-manager/main.go
  hack/run-dptp-controller-manager.sh
  pkg/api/helper/imageextraction.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/defaults/defaults.go
  pkg/load/agents/configAgent.go
Labels: approved, lgtm

#2133 DPTP-2347: do not mirror postsubmits and periodics
  cmd/ci-operator-config-mirror/main.go
  test/integration/ci-operator-config-mirror/input-to-clean/super/duper/super-duper-master.yaml
  test/integration/ci-operator-config-mirror/input/super/duper/super-duper-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super/duper/super-duper-master.yaml
  test/integration/ci-operator-config-mirror/output/super/duper/super-duper-master.yaml
Labels: approved, lgtm, tide/merge-method-squash

#2135 pkg/validation: also validate `from_image`
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#2136 prowgen: generate stricter `branch:` stanzas for presubmits
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_a_test_in_a_variant_config.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_standard_test.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified_and_clone.yaml
  test/integration/ci-operator-prowgen/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
Labels: approved, lgtm

#2148 ci-operator: don't use the root cache when building new caches
  pkg/defaults/defaults.go
Labels: approved, lgtm

#2152 Revert "prowgen: generate stricter `branch:` stanzas for presubmits"
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_a_test_in_a_variant_config.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_for_standard_test.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_job_release_specified_and_clone.yaml
  test/integration/ci-operator-prowgen/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
Labels: approved, lgtm

#2153 sprint-automation: search only private channels
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#2154 Archs: Add arm64
  pkg/api/types.go
  pkg/release/candidate/client.go
  pkg/release/candidate/client_test.go
  pkg/release/prerelease/client_test.go
  pkg/validation/release.go
  pkg/validation/release_test.go
Labels: approved, lgtm

#2155 sprint-automation: post information about rotating roles
  cmd/sprint-automation/main.go
  go.mod
  go.sum
  pkg/pagerdutyutil/options.go
  vendor/github.com/PagerDuty/go-pagerduty/.gitignore
  vendor/github.com/PagerDuty/go-pagerduty/.goreleaser.yml
  vendor/github.com/PagerDuty/go-pagerduty/CHANGELOG.md
  vendor/github.com/PagerDuty/go-pagerduty/Dockerfile
  vendor/github.com/PagerDuty/go-pagerduty/LICENSE.txt
  vendor/github.com/PagerDuty/go-pagerduty/Makefile
  vendor/github.com/PagerDuty/go-pagerduty/README.md
  vendor/github.com/PagerDuty/go-pagerduty/ability.go
  vendor/github.com/PagerDuty/go-pagerduty/addon.go
  vendor/github.com/PagerDuty/go-pagerduty/analytics.go
  vendor/github.com/PagerDuty/go-pagerduty/business_service.go
  vendor/github.com/PagerDuty/go-pagerduty/change_events.go
  vendor/github.com/PagerDuty/go-pagerduty/client.go
  vendor/github.com/PagerDuty/go-pagerduty/constants.go
  vendor/github.com/PagerDuty/go-pagerduty/escalation_policy.go
  vendor/github.com/PagerDuty/go-pagerduty/event.go
  vendor/github.com/PagerDuty/go-pagerduty/event_v2.go
  vendor/github.com/PagerDuty/go-pagerduty/extension.go
  vendor/github.com/PagerDuty/go-pagerduty/extension_schema.go
  vendor/github.com/PagerDuty/go-pagerduty/go.mod
  vendor/github.com/PagerDuty/go-pagerduty/go.sum
  vendor/github.com/PagerDuty/go-pagerduty/incident.go
  vendor/github.com/PagerDuty/go-pagerduty/log_entry.go
  vendor/github.com/PagerDuty/go-pagerduty/maintenance_window.go
  vendor/github.com/PagerDuty/go-pagerduty/notification.go
  vendor/github.com/PagerDuty/go-pagerduty/on_call.go
  vendor/github.com/PagerDuty/go-pagerduty/priorites.go
  vendor/github.com/PagerDuty/go-pagerduty/ruleset.go
  vendor/github.com/PagerDuty/go-pagerduty/schedule.go
  vendor/github.com/PagerDuty/go-pagerduty/service.go
  vendor/github.com/PagerDuty/go-pagerduty/service_dependency.go
  vendor/github.com/PagerDuty/go-pagerduty/tag.go
  vendor/github.com/PagerDuty/go-pagerduty/team.go
  vendor/github.com/PagerDuty/go-pagerduty/user.go
  vendor/github.com/PagerDuty/go-pagerduty/vendor.go
  vendor/github.com/PagerDuty/go-pagerduty/webhook.go
  vendor/modules.txt
Labels: approved, lgtm

#2130 Add a new cli: dptp-pools-cm
  cmd/dptp-pools-cm/main.go
  hack/run-dptp-pools-cm.sh
  pkg/controller/cluster_pools_pull_secret_provider/README.md
  pkg/controller/cluster_pools_pull_secret_provider/cluster_pools_pull_secret_provider.go
  pkg/controller/cluster_pools_pull_secret_provider/cluster_pools_pull_secret_provider_test.go
  pkg/util/secret.go
  pkg/util/secret_test.go
Labels: approved, lgtm

#2157 sprint-automation: manage user groups
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#2144 Release: Fix importing for non-amd64 architectures
  pkg/defaults/defaults.go
  pkg/release/official/client.go
  pkg/steps/release/import_release.go
  test/e2e/simple/dynamic-releases.yaml
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm, tide/merge-method-squash

#2156 [DPTP-2354] Fix flaky test TestWaitForConditionOnObject
  pkg/steps/artifacts_test.go
Labels: approved, lgtm

#2158 hack: make production installs verbose
  hack/install.sh
Labels: approved, lgtm

#2162 Testimagedistributor: Log error and ignore requestst w/o cluster in app.ci
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#2161 Save artifacts in cluster claim step
  cmd/ci-operator/main.go
  pkg/api/constant.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/cluster_claim.go
  pkg/steps/cluster_claim_test.go
Labels: approved, lgtm, tide/merge-method-squash

#2165 pkg/validation: reject duplicated image/test name
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#2167 e2e: backfill data into prometheus in a deterministic order
  test/e2e/pod-scaler/e2e_test.go
  test/e2e/pod-scaler/prometheus/backfill.go
Labels: approved, lgtm

#2169 vendor: bump test-infra
  go.mod
  go.sum
  vendor/github.com/andygrunwald/go-gerrit/.travis.yml
  vendor/github.com/andygrunwald/go-gerrit/Makefile
  vendor/github.com/andygrunwald/go-gerrit/README.md
  vendor/github.com/andygrunwald/go-gerrit/access.go
  vendor/github.com/andygrunwald/go-gerrit/changes.go
  vendor/github.com/andygrunwald/go-gerrit/go.mod
  vendor/github.com/andygrunwald/go-gerrit/go.sum
  vendor/github.com/andygrunwald/go-gerrit/gometalinter.json
  vendor/github.com/andygrunwald/go-gerrit/groups.go
  vendor/github.com/andygrunwald/go-gerrit/groups_member.go
  vendor/github.com/andygrunwald/go-gerrit/projects.go
  vendor/github.com/andygrunwald/go-gerrit/projects_access.go
  vendor/github.com/google/go-querystring/query/encode.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/config/agent.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/secret/agent.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/github/report/report.go
  vendor/k8s.io/test-infra/prow/pjutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pjutil/filter.go
  vendor/k8s.io/test-infra/prow/pjutil/help.go
  vendor/k8s.io/test-infra/prow/pluginhelp/hook/hook.go
  vendor/k8s.io/test-infra/prow/plugins/approve/approve.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/plugins/trigger/generic-comment.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/spyglass/README.md
  vendor/modules.txt
Labels: approved, lgtm

#2168 testhelper: allow configuring the file extension
  pkg/testhelper/testhelper.go
Labels: approved, lgtm

#2172 fix unittests
  pkg/testhelper/testhelper.go
Labels: approved, lgtm

#2170 util: add a function to load one kubeconfig
  cmd/ci-operator/main.go
  pkg/util/client.go
Labels: approved, lgtm

#2127 DPTP-2244, DPTP-2345: Registry-replacer should prune unused base images.
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Unused_base_images_are_pruned.yaml
  test/validate-checkconfig.sh
Labels: approved, lgtm

#2174 Bump test-infra to f8dbf1fd3d25
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
  vendor/modules.txt
Labels: approved, lgtm

#2176 sprint-automation: don't fail when no roles are found
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#2178 ci-operator: wait for 30min before giving up on Pods
  pkg/steps/template.go
Labels: approved, lgtm

#2177 ci-operator: tolerate existing CLI override import
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#2171 ci-operator: expose hive conditions on failure
  pkg/steps/cluster_claim.go
Labels: approved, lgtm

#2179 Add ibmcloud cluster profile
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_ibmcloud_cluster_profile.yaml
  pkg/validation/test.go
Labels: approved, lgtm

#2181 pod-scaler: turn off resource mutation by default
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/main.go
  test/e2e/pod-scaler/run/consumer.go
Labels: approved, lgtm

#2182 hack: fix script for test-infra validation
  hack/check-test-infra-version.sh
Labels: approved, lgtm

#2180 Vault proxy: Validate key conflicts
  cmd/vault-subpath-proxy/kv_update_transport.go
  cmd/vault-subpath-proxy/main.go
  cmd/vault-subpath-proxy/main_test.go
Labels: approved, lgtm, tide/merge-method-squash

#2175 azurestack: Add azurestack cluster profile for CI tests
  cmd/repo-init/main.go
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/validation/test.go
Labels: approved, lgtm

#2183 Remove duplicated params now that all steps should have cycled through.
  cmd/cvp-trigger/main.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#2186 Subpath proxy: Don't validate secrets with no target
  cmd/vault-subpath-proxy/kv_update_transport.go
  cmd/vault-subpath-proxy/main_test.go
Labels: approved, lgtm

#2185 pod-scaler: de-race startup
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/consumer.go
  cmd/pod-scaler/main.go
  cmd/pod-scaler/resources.go
Labels: approved, lgtm

#2188 Abuse determinize-prow-config to implement 4.9 FF (no merge)
  cmd/determinize-prow-config/main.go
Labels: approved

#2184 Abuse determinize-prow-config to implement 4.9 FF (no merge)
  cmd/determinize-prow-config/main.go
Labels: approved, do-not-merge/work-in-progress

#2189 Vault: Allow deleting secrets
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/main_test.go
Labels: approved, lgtm

#2190 Revert "Abuse determinize-prow-config to implement 4.9 FF (no merge) + FIX"
  cmd/determinize-prow-config/main.go
Labels: approved, lgtm

#2192 secret-bootstrap: fix a validation bug
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#2195 Disable e2e tests with claims
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#2187 testhelper: use a file to share port state
  pkg/testhelper/accessory.go
Labels: approved, lgtm

#2196 Actually skip hive testcases
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#2194 Bump test-infra to 01baa4728fcb
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/modules.txt
Labels: approved, lgtm

#2163 Add a new tool: promoted-image-governor
  Makefile
  cmd/promoted-image-governor/main.go
  cmd/promoted-image-governor/main_test.go
Labels: approved, lgtm

#2197 image-governor: Add some debug logs
  cmd/promoted-image-governor/main.go
Labels: approved, lgtm

#2200 pod-scaler: add created-by-ci label to builds
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_with_labels.yaml
  test/e2e/pod-scaler/e2e_test.go
  test/e2e/pod-scaler/testdata/zz_fixture_TestBuildPodAdmission_pod_associated_with_a_build_with_labels.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestBuildPodAdmission_pod_associated_with_a_build_with_labels_patch.yaml
Labels: approved, lgtm

#2201 pod-scaler: mutate resource requests by default
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/main.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add__limits_disabled.diff
  test/e2e/pod-scaler/run/consumer.go
Labels: approved, lgtm

#2202 Vault subpath proxy: Allow adding new values to secrets
  cmd/vault-subpath-proxy/kv_update_transport.go
  cmd/vault-subpath-proxy/main_test.go
Labels: approved, lgtm
