Repository openshift/ci-tools, pull requests merged in 2021-01, with the labels that each got.

#1567 Import: Add pull secret to $HOME/.docker
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#1559 e2e: move lease tests over to Go
  Makefile
  hack/test-e2e.sh
  pkg/steps/artifacts.go
  pkg/steps/lease.go
  pkg/steps/multi_stage_test.go
  test/e2e/lease.sh
  test/e2e/lease/e2e_test.go
Labels: approved, lgtm

#1536 Add controller to rotate old serviceaccount secrets
  cmd/dptp-controller-manager/main.go
  hack/run-dptp-controller-manager.sh
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher_test.go
Labels: approved, lgtm

#1573 TestCreateRBACs: Fix race
  pkg/util/rbacs_test.go
Labels: approved, lgtm

#1568 webreg: expose step environment variables
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1569 e2e: add a literal resolution test for release-controller image
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#1572 e2e: lock around access to testing logger
  test/e2e/framework/test.go
Labels: approved, lgtm

#1575 test: write out test JSON
  hack/test-go.sh
Labels: approved, lgtm

#1577 e2e: framework: wait for helper process exit in cleanup
  test/e2e/framework/framework.go
Labels: approved, lgtm

#1579 sa_secret_refresher: tolerate conflics
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
Labels: approved, lgtm

#1583 steps/import_release: Always use the correct pull configuration
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#1581 ServiceAccountSecretRefresher: Add graceperiod beetween creation and deletion
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher_test.go
Labels: approved, lgtm

#1582 determinize-ci-operator: Use TEST_TYPE instead of TEST_COMMAND
  cmd/determinize-ci-operator/main.go
  cmd/determinize-ci-operator/main_test.go
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6-to-4.7.yaml
  test/integration/release-job-migrator/input/jobs/openshift-release-release-4.7-periodics.yaml
Labels: approved, lgtm

#1561 Add signoff to autoowners
  cmd/autoowners/main.go
  go.mod
  go.sum
  pkg/github/prcreation/prcreation.go
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/commentpruner/commentpruner.go
  vendor/k8s.io/test-infra/prow/flagutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/flagutil/github.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/git/git.go
  vendor/k8s.io/test-infra/prow/git/localgit/localgit.go
  vendor/k8s.io/test-infra/prow/github/app_auth_roundtripper.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/github/report/report.go
  vendor/k8s.io/test-infra/prow/hook/server.go
  vendor/k8s.io/test-infra/prow/interrupts/interrupts.go
  vendor/k8s.io/test-infra/prow/plugins/approve/approve.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/dco/dco.go
  vendor/k8s.io/test-infra/prow/plugins/help/help.go
  vendor/k8s.io/test-infra/prow/plugins/lgtm/lgtm.go
  vendor/k8s.io/test-infra/prow/plugins/merge-method-comment/merge-method-comment.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/plugins/project/project.go
  vendor/k8s.io/test-infra/prow/plugins/releasenote/releasenote.go
  vendor/k8s.io/test-infra/prow/plugins/sigmention/sigmention.go
  vendor/k8s.io/test-infra/prow/plugins/slackevents/slackevents.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/generic-comment.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/k8s.io/test-infra/prow/pod-utils/clone/clone.go
  vendor/k8s.io/test-infra/robots/pr-creator/updater/updater.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash

#1585 CI secret boostrap: Verify dockerconfigjson can be parsed
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/kubernetes/pkg/credentialprovider/config.go
  pkg/kubernetes/pkg/credentialprovider/config_test.go
Labels: approved, lgtm

#1584 applyconfig: optionally allow server-side dry-runs with validation
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-version/LICENSE
  vendor/github.com/hashicorp/go-version/README.md
  vendor/github.com/hashicorp/go-version/constraint.go
  vendor/github.com/hashicorp/go-version/go.mod
  vendor/github.com/hashicorp/go-version/version.go
  vendor/github.com/hashicorp/go-version/version_collection.go
  vendor/modules.txt
Labels: approved, lgtm

#1588 Update test-infra to 45e4b3940d65
  go.mod
  go.sum
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/ghproxy/ghcache/coalesce.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghpath.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/bugzilla/fake.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
  vendor/k8s.io/test-infra/prow/flagutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/github/BUILD.bazel
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/trigger/push.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/k8s.io/test-infra/prow/spyglass/lenses/common/common.go
  vendor/k8s.io/test-infra/robots/pr-creator/updater/updater.go
  vendor/modules.txt
Labels: approved, lgtm

#1591 Increase e2e test timeout to 70m
  Makefile
Labels: approved, lgtm

#1589 [DPTP-1847] add key name in errors while constructing the secrets
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#1586 Builds: Include the log level env var for documentation
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
Labels: approved, lgtm

#1592 e2e: make sure we're as parallel as possible
  test/e2e/framework/test.go
Labels: approved, lgtm

#1593 DPDP CM: Exit on kubeconfig changes to pick them up
  cmd/ci-secret-bootstrap/main.go
  cmd/dptp-controller-manager/main.go
  cmd/pj-rehearse/main.go
  pkg/util/client.go
  pkg/util/client_test.go
Labels: approved, lgtm

#1594 release-job-migrator: support updating testgrid allowlist
  cmd/release-job-migrator/main.go
  test/integration/release-job-migrator.sh
  test/integration/release-job-migrator/expected/_allow-list.yaml
  test/integration/release-job-migrator/input/_allow-list.yaml
Labels: approved, lgtm

#1595 [DPTP-1852] fix auto bumper arguments while updating a pull request
  cmd/autobumper/main.go
  cmd/autoconfigbrancher/main.go
  cmd/autoowners/main.go
  cmd/autoperibolossync/main.go
  cmd/registry-replacer/main.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#1596 webreg: show steps' properties in UI
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1574 e2e: hold on to ci-operator logs as artifacts
  test/e2e/framework/ci-operator.go
Labels: approved, lgtm

#1590 applyconfig: use best detected dryrun by default
  cmd/applyconfig/applyconfig.go
Labels: approved, lgtm

#1597 Fix PR-Creating tools
  cmd/autobumper/main.go
  cmd/autoconfigbrancher/main.go
  cmd/autoowners/main.go
  cmd/autoperibolossync/main.go
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#1587 registry-replacer: use app.ci'registry in ci-op's configs
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
Labels: approved, lgtm

#1598 ocpbuilddata api: use app.ci's registry
  pkg/api/ocpbuilddata/types.go
  pkg/api/ocpbuilddata/types_test.go
Labels: approved, lgtm

#1578 [DPTP-1789] Ignore context cancelled errors from steps when the job is interrupted
  pkg/steps/run.go
  pkg/steps/run_test.go
Labels: approved, lgtm

#1602 [DPTP-1846] ci-secret-bootstrap: output valid yaml data when running on dry-run mode
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#1605 rehearsals: launch one job per changed step
  pkg/rehearse/jobs.go
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#1599 webreg: doc links for timeout properties
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1603 ci-operator: recreate ns watcher when necessary
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1600 webreg: collect and expose workflow/chain dependencies in UI
  pkg/webreg/webreg.go
  pkg/webreg/webreg_test.go
Labels: approved, lgtm

#1606 repo-init: copycat CVO merge criteria instead of origin
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  test/integration/repo-init/input/core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#1608 ci-operator: add support for interval field
  go.mod
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_specific_release_using_interval.yaml
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
  vendor/modules.txt
Labels: approved, lgtm

#1610 release-job-migrate: add ignore-release flag
  cmd/release-job-migrator/main.go
  test/integration/release-job-migrator.sh
  test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.8-periodics.yaml
  test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.9-periodics.yaml
  test/integration/release-job-migrator/input/jobs/openshift-release-release-4.8-periodics.yaml
  test/integration/release-job-migrator/input/jobs/openshift-release-release-4.9-periodics.yaml
Labels: approved, lgtm

#1617 Secret bootstrapper: Allow finding config entry for faulty dockercfg
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#1618 release-job-migrator: support interval
  cmd/release-job-migrator/main.go
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ocp-4.7.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__okd-4.7.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__origin-4.7.yaml
Labels: approved, lgtm

#1611 Add azure-arc cluster profile
  pkg/api/types.go
  pkg/prowgen/prowgen.go
Labels: approved, lgtm

#1616 prowgen: use rpms routes on app.ci
  pkg/api/domain.go
  pkg/api/domain_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_0.yaml
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
Labels: approved, lgtm

#1601 dptp-cm: add controller image_pusher
  cmd/dptp-controller-manager/main.go
  pkg/api/constant.go
  pkg/controller/imagepusher/imagepusher.go
  pkg/controller/imagepusher/imagepusher_test.go
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
  pkg/controller/util/secret.go
  pkg/controller/util/secret_test.go
Labels: approved, lgtm

#1615 Establish osd-ephemeral cluster type for SDE-791
  pkg/api/types.go
Labels: approved, lgtm

#1619 dptp-cm: fix an imagepusher's flag name
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#1622 Use the same label for CRs created by ci-tools
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/controller/secretsyncer/secretsyncer.go
Labels: approved, lgtm

#1625 dptp-cm: copy pull secret from ci namespace
  cmd/dptp-controller-manager/main.go
  pkg/controller/registrysyncer/registrysyncer.go
  pkg/controller/registrysyncer/registrysyncer_test.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1623 ci-operator: wait for image pull secrets to exist
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1620 ci-operator: releases: use artifact dir env
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#1621 ci-operator: release: use a configmap for data transfer
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#1626 dptp-cm: remove 2 unused flags
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#1628 Revert "ci-operator: release: use a configmap for data transfer"
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
Labels: approved

#1629 Try creating ConfigMaps again
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#1630 ci-operator: use a more resilient upsert on output ist
  pkg/steps/output_image_tag.go
Labels: approved, lgtm

#1631 pkg/github: fix UpsertPR
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm

#1609 ci-operator: optionally use pod-utils to push artifacts up
  cmd/ci-operator/main.go
  pkg/api/config.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/testdata/zz_fixture_TestAddPodUtils.yaml
Labels: approved, lgtm

#1624 Add Azure Arc cluster profile validation
  pkg/validation/test.go
Labels: approved, lgtm

#1632 validation: Support devices.kubevirt.io/kvm
  pkg/validation/config.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#1633 prowgen: use pod-utils for ci-tools repo
  pkg/prowgen/prowgen.go
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm

#1613 [DPTP-1836] ci-secret-bootstrap: allow recreating secrets on `--force` when an immutable field changes
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#1635 Fixes Azure Arc quota slice
  pkg/api/types.go
Labels: approved, lgtm

#1636 ci-operator: fix typo
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1637 Bump test-infra to e3a8e137c7b928824d358ee55be35806f7aaa8fa
  go.mod
  go.sum
  pkg/rehearse/configmaps.go
  vendor/github.com/felixge/fgprof/LICENSE.txt
  vendor/github.com/felixge/fgprof/README.md
  vendor/github.com/felixge/fgprof/fgprof.go
  vendor/github.com/felixge/fgprof/format.go
  vendor/github.com/felixge/fgprof/go.mod
  vendor/github.com/felixge/fgprof/go.sum
  vendor/github.com/felixge/fgprof/handler.go
  vendor/github.com/felixge/fgprof/pprof.go
  vendor/github.com/google/pprof/AUTHORS
  vendor/github.com/google/pprof/CONTRIBUTORS
  vendor/github.com/google/pprof/LICENSE
  vendor/github.com/google/pprof/profile/encode.go
  vendor/github.com/google/pprof/profile/filter.go
  vendor/github.com/google/pprof/profile/index.go
  vendor/github.com/google/pprof/profile/legacy_java_profile.go
  vendor/github.com/google/pprof/profile/legacy_profile.go
  vendor/github.com/google/pprof/profile/merge.go
  vendor/github.com/google/pprof/profile/profile.go
  vendor/github.com/google/pprof/profile/proto.go
  vendor/github.com/google/pprof/profile/prune.go
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/experiment/image-bumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/hook/BUILD.bazel
  vendor/k8s.io/test-infra/prow/kube/BUILD.bazel
  vendor/k8s.io/test-infra/prow/kube/metrics.go
  vendor/k8s.io/test-infra/prow/pjutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pjutil/pprof.go
  vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/approve/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/owners.go
  vendor/k8s.io/test-infra/prow/plugins/blunderbuss/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/heart/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/heart/heart.go
  vendor/k8s.io/test-infra/prow/plugins/lgtm/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/override/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/ownersconfig/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/ownersconfig/config.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/plugins/updateconfig/updateconfig.go
  vendor/k8s.io/test-infra/prow/plugins/verify-owners/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/verify-owners/verify-owners.go
  vendor/k8s.io/test-infra/prow/repoowners/BUILD.bazel
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/k8s.io/test-infra/prow/version/BUILD.bazel
  vendor/k8s.io/test-infra/prow/version/metrics.go
  vendor/modules.txt
Labels: approved, lgtm

#1638 Fix TestMergeAndPushToRemote to work when git has gpg signing enabled
  cmd/publicize/server.go
Labels: approved, lgtm

#1639 Secret generator: Refuse empty and 'null' as command output
  cmd/ci-secret-generator/main.go
Labels: approved, lgtm

#1642 Revert "test: write out test JSON"
  hack/test-go.sh
Labels: approved, lgtm

#1641 prowgen: explicitly opt out of pod-utils with artifact dir
  pkg/api/config.go
  pkg/config/load.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cluster_profile.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cpaas_cluster_profile.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/duper/super-priv-duper-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/trooper/super-priv-trooper-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/duper/super-priv-duper-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/trooper/super-priv-trooper-master.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-master.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-release-4.5.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-release-4.6.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-master.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-release-4.5.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-release-4.6.yaml
  test/integration/config-brancher/expected/org/new/org-new-release-4.5.yaml
  test/integration/config-brancher/expected/org/new/org-new-release-4.6.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ocp-4.7.yaml
  test/integration/repo-init/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
  test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/integration/repo-init/expected/ci-operator/config/org/third/org-third-nonstandard.yaml
Labels: approved, lgtm

#1643 ci-operator: gather artifacts only when needed
  pkg/steps/pod.go
Labels: approved, lgtm

#1645 secret generator: set default org and collections on create
  cmd/ci-secret-generator/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
  pkg/bitwarden/fake.go
Labels: approved, lgtm

#1647 config/load: do something with the VERSION file
  pkg/load/load.go
Labels: approved, lgtm

#1640 checkconfig: resolve configurations
  cmd/ci-operator-checkconfig/main.go
Labels: approved, lgtm

#1646 Bump test-infra to bc8196c5c352
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/experiment/image-bumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/verify-owners/verify-owners.go
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/k8s.io/test-infra/robots/pr-creator/updater/updater.go
  vendor/modules.txt
Labels: approved, lgtm

#1649 deprovisioner: do not fail when there is nothing to cleanup
  cmd/ipi-deprovision/ipi-deprovision.sh
Labels: approved, lgtm

#1650 publicize: use default censoring
  cmd/publicize/main.go
  cmd/publicize/server.go
  cmd/publicize/server_test.go
Labels: approved, lgtm

#1648 backport-verifier: a new Prow plugin for forks
  cmd/backport-verifier/main.go
  cmd/backport-verifier/server.go
  cmd/backport-verifier/server_test.go
  images/backport-verifier/Dockerfile
Labels: approved, lgtm

#1653 backport-verifier: only comment about missing config when explicit
  cmd/backport-verifier/server.go
  cmd/backport-verifier/server_test.go
Labels: approved, lgtm

#1652 backport-verifier: update wording to be more clear
  cmd/backport-verifier/server.go
  cmd/backport-verifier/server_test.go
Labels: approved, lgtm

#1644 ci-operator: upload artifacts with pod-utils by default
  Makefile
  cmd/ci-operator/main.go
  pkg/steps/multi_stage.go
  test/e2e/framework/ci-operator.go
  test/e2e/framework/framework.go
  test/e2e/framework/test.go
  test/e2e/lease/e2e_test.go
  test/e2e/multi-stage/e2e_test.go
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#1654 backport-verifier: use correct SHA field
  cmd/backport-verifier/server.go
  cmd/backport-verifier/server_test.go
Labels: approved, lgtm

#1655 ci-operator-prowgen: stop special-casing ci-tools
  pkg/prowgen/prowgen.go
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
Labels: approved, lgtm
