Repository openshift/ci-tools, pull requests merged in 2021-09, with the labels that each got.

#2317 Explain why a tag on a promoted image stream exists
  Makefile
  cmd/promoted-image-governor/main.go
Labels: approved, lgtm

#2307 pkg/registry: add test for independent leases
  pkg/registry/resolver_test.go
Labels: approved, lgtm

#2320 Generalize image revert script
  hack/revert-any-ci-image.sh
  hack/revert-ci-operator.sh
Labels: approved, lgtm

#2319 (DPTP-2412): Cluster init secret generator
  cmd/cluster-init/main.go
  cmd/cluster-init/update_sanitize_prow_jobs.go
  cmd/cluster-init/update_sanitize_prow_jobs_test.go
  cmd/cluster-init/update_secret_generator.go
  cmd/cluster-init/update_secret_generator_test.go
  test/integration/cluster-init/expected/core-services/ci-secret-generator/_config.yaml
  test/integration/cluster-init/input/core-services/ci-secret-generator/_config.yaml
Labels: approved, tide/merge-method-squash, lgtm

#2318 Fix typo in packet-edge boskos slice name
  pkg/api/types.go
Labels: approved, lgtm

#2323 Add cluster profile for the 2nd azure account
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_a_ure_2_cluster_profile.yaml
  pkg/validation/test.go
Labels: approved, lgtm

#2326 pod-scaler: admission: improve error messages for rehearsals
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  pkg/testhelper/testhelper.go
  pkg/testhelper/testhelper_test.go
Labels: approved, lgtm

#2322 pod-scaler: improve component labels in logs
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/consumer.go
  cmd/pod-scaler/frontend.go
  cmd/pod-scaler/resources.go
Labels: approved, lgtm

#2304 ci-operator-prowgen: read/write jobs only once
  cmd/ci-operator-prowgen/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  pkg/config/options.go
  pkg/config/options_test.go
  pkg/deprecatetemplates/allowlist.go
  pkg/jobconfig/files.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/slack/events/joblink/link.go
  pkg/testhelper/fs.go
Labels: approved, lgtm

#2321 Upgrade test-infra to 00bc5aa56077
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/kube/BUILD.bazel
  vendor/k8s.io/test-infra/prow/kube/constants.go
  vendor/k8s.io/test-infra/prow/kube/dry_run_client.go
  vendor/k8s.io/test-infra/prow/kube/metrics.go
  vendor/k8s.io/test-infra/prow/kube/prowjob.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/generic-comment.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/modules.txt
Labels: approved, lgtm

#2328 promoted-image-governor: error out if a destination occurs more than …
  cmd/promoted-image-governor/main.go
  cmd/promoted-image-governor/main_test.go
Labels: approved, lgtm

#2331 promoted-image-governor: less verbose while explaining
  Makefile
  cmd/promoted-image-governor/main.go
Labels: approved, lgtm

#2332 clusterimaget-updater: change version labels
  cmd/clusterimageset-updater/main.go
  test/integration/clusterimageset-updater/input/imagesets/ocp-release-4.5.40-x86_64-for-4.5.0-0-to-4.6.0-0_clusterimageset.yaml
  test/integration/clusterimageset-updater/input/imagesets/ocp-release-sha256-2c22e1c56831935a24efb827d2df572855ccd555c980070f77c39729526037d5-for-4.5.0-to-4.6.0_clusterimageset.yaml
  test/integration/clusterimageset-updater/input/pools/4-5-auto_clusterpool.yaml
  test/integration/clusterimageset-updater/output/imagesets/ocp-release-4.5.41-x86_64-for-4.5.0-0-to-4.6.0-0_clusterimageset.yaml
  test/integration/clusterimageset-updater/output/pools/4-5-auto_clusterpool.yaml
Labels: approved, lgtm

#2299 Make private jobs to use the oauth volume defined in decoration config
  pkg/api/constant.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobBase_private_jobs_that_clone_should_contain_oauth_token_secret_config.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_private_job_with_skip_cloning_false.yaml
  test/integration/ci-operator-prowgen/input/config/private-org/super/private-org-super-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/private-org/super/private-org-super-master-presubmits.yaml
Labels: approved, lgtm

#2295 ci-operator: include images into release explicitly
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/snapshot.go
  pkg/validation/release.go
  pkg/validation/release_test.go
  test/e2e/multi-stage/assembled-release-no-injection.yaml
  test/e2e/multi-stage/assembled-release.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#2339 pkg/steps: revert project image changes
  pkg/steps/project_image.go
Labels: approved, lgtm

#2341 Add a specification for optional jobs in ci-operator configuration
  pkg/api/types.go
  pkg/jobconfig/files.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_optional_presubmit.yaml
  pkg/validation/test.go
  pkg/validation/test_test.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
Labels: approved, lgtm

#2335 clusterimageset-updater: fix generated k8s values
  cmd/clusterimageset-updater/main.go
  test/integration/clusterimageset-updater/input/imagesets/ocp-release-4.5.40-x86-64-for-4.5.0-0-to-4.6.0-0_clusterimageset.yaml
  test/integration/clusterimageset-updater/input/imagesets/ocp-release-sha256-2c22e1c56831935a24efb827d2df572855ccd555c980070f77c39729526037d5-for-4.5.0-to-4.6.0_clusterimageset.yaml
  test/integration/clusterimageset-updater/input/pools/4-5-auto_clusterpool.yaml
  test/integration/clusterimageset-updater/output/imagesets/ocp-release-4.5.41-x86-64-for-4.5.0-0-to-4.6.0-0_clusterimageset.yaml
  test/integration/clusterimageset-updater/output/pools/4-5-auto_clusterpool.yaml
Labels: approved, lgtm

#2336 clusterimageset-updater: add diffutils to image
  images/clusterimageset-updater/Dockerfile
Labels: approved, lgtm

#2334 pod-scaler: admission: ignore non-ci-operator rehearsals
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
Labels: approved, lgtm

#2272 Add a bugzilla config manager
  cmd/branchingconfigmanagers/bugzilla-config-manager/README.md
  cmd/branchingconfigmanagers/bugzilla-config-manager/main.go
  cmd/branchingconfigmanagers/bugzilla-config-manager/main_test.go
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/lifecycle_combined.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/lifecycle_multiple_ga.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/lifecycle_multiple_ga_411_biger_41.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/lifecycle_onega.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/lifecycle_open.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/lifecycle_open_and_codefreeze.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_combined.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_multiple_ga.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_multiple_ga_411_biger_41.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_onega.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_open.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_open_and_codefree_e.yaml.yaml
  pkg/api/ocplifecycle/ocplifecycle.go
Labels: approved, lgtm

#2344 pod-scaler: ui: store data in files, not memory
  cmd/pod-scaler/frontend.go
  cmd/pod-scaler/main.go
  test/e2e/pod-scaler/run/consumer.go
Labels: approved, lgtm

#2338 cluster-display: Use flagutil.KubernetesOptions
  cmd/cluster-display/main.go
Labels: approved, lgtm

#2327 (DPTP-2412) Cluster init jobs
  cmd/cluster-init/main.go
  cmd/cluster-init/main_test.go
  cmd/cluster-init/update_jobs.go
  cmd/cluster-init/update_secret_generator.go
  cmd/cluster-init/update_secret_generator_test.go
  pkg/api/metadata.go
  test/integration/cluster-init/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/input/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, tide/merge-method-squash, lgtm

#2347 Tolerate neither of `skip_if/run_if` changes in jobs if one is set in ci-op config
  pkg/jobconfig/files.go
Labels: approved, lgtm

#2324 add cluster profiles for AWS C2S/China/GovCloud
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/validation/test.go
Labels: approved, lgtm

#2330 validate: remove wrong test and improve message
  pkg/validation/test.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#2345 Update test-infra to c1043ab1c1ff
  go.mod
  go.sum
  test/integration/cluster-init/expected/clusters/build-clusters/newCluster/common
  test/integration/cluster-init/expected/clusters/build-clusters/newCluster/common_except_app.ci
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
  test/integration/pj-rehearse/expected.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/label/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/label/label.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/modules.txt
Labels: approved, lgtm

#2351 Shard labels.restricted_labels
  pkg/prowconfigsharding/prowconfigsharding.go
  pkg/prowconfigsharding/prowconfigsharding_test.go
Labels: approved, lgtm

#2349 pod-scaler: Use flagutil.KubernetesOptions
  cmd/pod-scaler/main.go
Labels: approved, lgtm

#2329 dptp-pools-cm: use inClusterConfig
  cmd/dptp-pools-cm/main.go
Labels: approved, lgtm

#2348 pj-rehearse: Use flagutil.KubernetesOptions
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#2355 config-brancher: honor releases.integration
  cmd/config-brancher/main.go
  test/integration/config-brancher/expected/org/bump/org-bump-master__releases.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-release-4.5__releases.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-release-4.6__releases.yaml
  test/integration/config-brancher/input/org/bump/org-bump-master__releases.yaml
Labels: approved, lgtm

#2358 bump test-infra to 7cf307fffca5
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/modules.txt
Labels: approved, lgtm

#2359 ci-operator-config-mirror: honor releases.integration
  cmd/ci-operator-config-mirror/main.go
  cmd/ci-operator-config-mirror/main_test.go
  test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/input/foo/barry-white/foo-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/output/foo/barry-white/foo-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-official__releases.yaml
Labels: approved, lgtm

#2357 repo-init: use releases.integration instead of tag_spec
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  test/integration/repo-init/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
  test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
Labels: approved, lgtm

#2253 Add ClusterProfileVSphereDiscon
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/validation/test.go
Labels: approved, lgtm

#2294 prowgen: support overriding prowjob timeout
  cmd/ci-operator-prowgen/main_test.go
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Custom_test_timeout.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Custom_test_timeout.yaml
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/validation/test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#2356 serviceaccount-secret-rotation-trigger: Use flagutil.KubernetesOptions
  cmd/serviceaccount-secret-rotation-trigger/main.go
Labels: approved, lgtm

#2360 validation: allow releases as well as tag_spec
  pkg/validation/test.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#2337 ci-secret-bootstrap: Use flagutil.KubernetesOptions
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#2350 branching: add a schedule generator utility
  cmd/branchingconfigmanagers/schedule-generator/main.go
  cmd/branchingconfigmanagers/schedule-generator/main_test.go
  cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.1.yaml
  cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.2.yaml
  cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.3.yaml
  cmd/branchingconfigmanagers/schedule-generator/testdata/zz_fixture_TestReadSchedules.yaml
  cmd/branchingconfigmanagers/schedule-generator/types.go
  cmd/branchingconfigmanagers/schedule-generator/types_test.go
Labels: approved, lgtm

#2273 DPTP-2452 [ci-secret-bootstrap] Delete the stale keys from the existing secrets
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#2365 validation: correctly populate releases
  pkg/validation/config.go
Labels: approved, lgtm

#2364 test-images-distributor: stop generating requests for disabled clusters
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#2367 sa-secret-rotation-trigger: move Fatal logs to the main function
  cmd/serviceaccount-secret-rotation-trigger/main.go
Labels: approved, lgtm

#2368 vault-subpath-proxy: Use flagutil.KubernetesOptions
  cmd/vault-subpath-proxy/main.go
Labels: approved, lgtm

#2362 add lease type for the azure-2 cluster profile and its missing references
  cmd/repo-init/main.go
  pkg/api/types.go
Labels: approved, lgtm

#2371 test/e2e: remove resource limits in ci-op configs
  test/e2e/lease/config.yaml
  test/e2e/multi-stage/assembled-release-no-injection.yaml
  test/e2e/multi-stage/assembled-release.yaml
  test/e2e/multi-stage/best-effort.yaml
  test/e2e/multi-stage/cluster-claim.yaml
  test/e2e/multi-stage/config.yaml
  test/e2e/multi-stage/configs/master/..2019_11_15_19_57_20.547184898/test-test-master.yaml
  test/e2e/multi-stage/dependencies.yaml
  test/e2e/multi-stage/integration-releases.yaml
  test/e2e/multi-stage/names.yaml
  test/e2e/optional-operators/optional-operators.yaml
  test/e2e/simple/config.yaml
  test/e2e/simple/dynamic-releases.yaml
  test/e2e/simple/template-config.yaml
Labels: approved, lgtm

#2353 (DPTP: 2412): Cluster-init secret-bootstrap
  cmd/cluster-init/main.go
  cmd/cluster-init/update_bootstrap_secrets.go
  cmd/cluster-init/update_bootstrap_secrets_test.go
  pkg/api/types.go
  test/integration/cluster-init.sh
  test/integration/cluster-init/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/input/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, tide/merge-method-squash, lgtm

#2373 (DPTP-2412): Create self-merging pr for cluster-init
  cmd/cluster-init/main.go
  test/integration/cluster-init.sh
Labels: approved, tide/merge-method-squash, lgtm

#2354 dptp-cm: Use flagutil.KubernetesOptions
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#2369 Remove LoadKubeConfigs function
  pkg/util/client.go
  pkg/util/client_test.go
Labels: approved, lgtm

#2374 dptp-cm: add logging for InClusterConfig
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#2372 import_release: wait for CLI tag to import
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#2377 pod-scaler: fix a round-tripping bug in the UI
  cmd/pod-scaler/frontend.go
  cmd/pod-scaler/frontend_test.go
Labels: approved, lgtm

#2376 OWNERS: Prune crawford
  pkg/steps/clusterinstall/OWNERS
Labels: approved

#2379 (DPTP-2412) Allow cluster-init tool to update the clusters that it generates jobs
  cmd/cluster-init/build_clusters.go
  cmd/cluster-init/main.go
  cmd/cluster-init/main_test.go
  test/integration/cluster-init.sh
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/create/expected/clusters/build-clusters/cluster-init.yaml
  test/integration/cluster-init/create/expected/clusters/build-clusters/common/README.md
  test/integration/cluster-init/create/expected/clusters/build-clusters/common_except_app.ci/README.md
  test/integration/cluster-init/create/expected/clusters/build-clusters/existingCluster/common/README.md
  test/integration/cluster-init/create/expected/clusters/build-clusters/existingCluster/common_except_app.ci/README.md
  test/integration/cluster-init/create/expected/clusters/build-clusters/newCluster/common/README.md
  test/integration/cluster-init/create/expected/clusters/build-clusters/newCluster/common_except_app.ci/README.md
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/create/expected/core-services/ci-secret-generator/_config.yaml
  test/integration/cluster-init/create/expected/core-services/sanitize-prow-jobs/_config.yaml
  test/integration/cluster-init/create/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/create/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/create/input/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/create/input/clusters/build-clusters/cluster-init.yaml
  test/integration/cluster-init/create/input/clusters/build-clusters/common/README.md
  test/integration/cluster-init/create/input/clusters/build-clusters/common_except_app.ci/README.md
  test/integration/cluster-init/create/input/clusters/build-clusters/existingCluster/common/README.md
  test/integration/cluster-init/create/input/clusters/build-clusters/existingCluster/common_except_app.ci/README.md
  test/integration/cluster-init/create/input/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/create/input/core-services/ci-secret-generator/_config.yaml
  test/integration/cluster-init/create/input/core-services/sanitize-prow-jobs/_config.yaml
  test/integration/cluster-init/expected/clusters/build-clusters/newCluster/common
  test/integration/cluster-init/expected/clusters/build-clusters/newCluster/common_except_app.ci
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/update/expected/clusters/build-clusters/cluster-init.yaml
  test/integration/cluster-init/update/expected/clusters/build-clusters/common/README.md
  test/integration/cluster-init/update/expected/clusters/build-clusters/common_except_app.ci/README.md
  test/integration/cluster-init/update/expected/clusters/build-clusters/existingCluster/common/README.md
  test/integration/cluster-init/update/expected/clusters/build-clusters/existingCluster/common_except_app.ci/README.md
  test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/update/input/clusters/build-clusters/cluster-init.yaml
  test/integration/cluster-init/update/input/clusters/build-clusters/common/README.md
  test/integration/cluster-init/update/input/clusters/build-clusters/common_except_app.ci/README.md
  test/integration/cluster-init/update/input/clusters/build-clusters/existingCluster/common/README.md
  test/integration/cluster-init/update/input/clusters/build-clusters/existingCluster/common_except_app.ci/README.md
Labels: approved, tide/merge-method-squash, lgtm

#2370 promoted-image-governor: prune images on build farm
  Makefile
  cmd/dptp-controller-manager/main.go
  cmd/promoted-image-governor/main.go
  cmd/promoted-image-governor/main_test.go
Labels: approved, lgtm

#2380 Regulate the existing applyconfig jobs
  cmd/cluster-init/update_jobs.go
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/create/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/create/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
Labels: approved, lgtm

#2385 e2e: stop using obsolete OCP in simple tests
  test/e2e/simple/artifacts/junit_operator.xml
  test/e2e/simple/dynamic-releases.yaml
  test/e2e/simple/e2e_test.go
  test/e2e/simple/template-config.yaml
Labels: approved, lgtm

#2386 create readme for cluster-init tool
  cmd/cluster-init/README.md
Labels: approved, lgtm

#2387 create image for cluster-init tool
  images/cluster-init/Dockerfile
Labels: approved, lgtm

#2389 add diffutils to cluster-init image
  images/cluster-init/Dockerfile
Labels: approved, lgtm

#2366 Add a README for config manager authors
  cmd/branchingconfigmanagers/README.md
Labels: approved, tide/merge-method-squash, lgtm

#2388 pkg/steps: remove unreliable test
  pkg/steps/run_test.go
Labels: approved, lgtm

#2390 stop collecting disruption from jobs that don't have disruption data
  pkg/jobrunaggregator/jobtableprimer/jobs.go
  pkg/jobrunaggregator/jobtableprimer/migration_test.go
Labels: approved, lgtm

#2393 Rename test-platform github team name
  cmd/autoconfigbrancher/main.go
  cmd/autoowners/README.md
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
  cmd/autotestgridgenerator/main.go
Labels: approved, lgtm

#2394 Add cluster-init update step to breaking-changes
  Makefile
  test/validate-generation-breaking-changes.sh
Labels: approved, lgtm

#2395 skip empty files for junit aggregation
  pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Labels: approved, lgtm

#2398 Make m(github_login)=kerberos_id as ci-op-xxxx's admin
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/api/constant.go
Labels: approved, lgtm

#2400 add new ovn job to aggregate
  pkg/jobrunaggregator/jobtableprimer/jobs.go
Labels: approved, lgtm

#2399 ignore jobs we're aggregating that time out
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/types.go
Labels: approved, lgtm

#2404 ignore the sub-aggregation from any openshift-e2e-test container test…
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#2406 provide more context on aggregated test success
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#2397 Generate the mapping m(github_login)=kerberos_id
  cmd/ldap-users-from-github-owners-files/README.md
  cmd/ldap-users-from-github-owners-files/main.go
  cmd/ldap-users-from-github-owners-files/main_test.go
Labels: approved, lgtm

#2405 a new tool: github-ldap-user-group-creator
  Makefile
  cmd/github-ldap-user-group-creator/README.md
  cmd/github-ldap-user-group-creator/main.go
  cmd/github-ldap-user-group-creator/main_test.go
Labels: approved, lgtm

#2407 write html status for aggregator
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go
Labels: approved, lgtm
