Repository openshift/ci-tools, pull requests merged in 2021-06, with the labels that each got.

#2014 Vault: Retry more to account for temporary down single active replica
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/secrets/vault.go
  pkg/vaultclient/vaultclient.go
  pkg/vaultclient/vaultclient_test.go
Labels: approved, lgtm

#2015 Bump test-infra to ea6aa4eb2942e2f
  Makefile
  cmd/repo-init/main.go
  go.mod
  go.sum
  vendor/github.com/GoogleCloudPlatform/testgrid/config/BUILD.bazel
  vendor/github.com/GoogleCloudPlatform/testgrid/config/config.go
  vendor/github.com/GoogleCloudPlatform/testgrid/pb/config/config.pb.go
  vendor/github.com/GoogleCloudPlatform/testgrid/pb/config/config.proto
  vendor/github.com/GoogleCloudPlatform/testgrid/pb/state/state.pb.go
  vendor/github.com/GoogleCloudPlatform/testgrid/pb/state/state.proto
  vendor/github.com/GoogleCloudPlatform/testgrid/util/gcs/BUILD.bazel
  vendor/github.com/GoogleCloudPlatform/testgrid/util/gcs/gcs.go
  vendor/github.com/GoogleCloudPlatform/testgrid/util/gcs/read.go
  vendor/github.com/GoogleCloudPlatform/testgrid/util/gcs/sort.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/cmd/generic-autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/gcsupload/BUILD.bazel
  vendor/k8s.io/test-infra/prow/gcsupload/run.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/hook/events.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/modules.txt
Labels: approved, lgtm

#2007 Test Image distributor: Consider TestImageImports from all clusters
  pkg/api/testimagestreamtagimport/v1/types.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#2004 Vault Secret Collection Manager Edit Members: Allow filtering
  cmd/vault-secret-collection-manager/index.template.html
  cmd/vault-secret-collection-manager/index.ts
Labels: approved, lgtm

#2018 autoconfigbrancher: respect prow config sharding
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#2019 Revert "Get build arg from a secret"
  cmd/ci-operator/main_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/steps/project_image.go
  pkg/steps/project_image_test.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/testdata/zz_fixture_TestBuildFromSource.yaml
  pkg/steps/testdata/zz_fixture_TestBuildFromSource_build_args.yaml
  pkg/util/secret.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#2020 Testimagestreamtagimport: Replace colons in label values
  pkg/api/testimagestreamtagimport/v1/types.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#2021 Add .ci-operator.yaml
  .ci-operator.yaml
Labels: approved, lgtm

#2022 Ci-Operator testimagestreamtagimports: Use correct name when waiting
  pkg/defaults/defaults.go
Labels: approved, lgtm

#2024 Determinize Prow config: Fix dir for additional plugin configs
  cmd/determinize-prow-config/main.go
Labels: approved, lgtm

#2025 Add a tool to create PR for .ci-operator.yaml of all art-built components
  cmd/ci-operator-yaml-creator/README.md
  cmd/ci-operator-yaml-creator/main.go
  cmd/ci-operator-yaml-creator/main_test.go
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm, tide/merge-method-squash

#2026 CI-Operator-Yaml-Creator: Set build_root.from_repository if config is current
  cmd/ci-operator-yaml-creator/README.md
  cmd/ci-operator-yaml-creator/main.go
  cmd/ci-operator-yaml-creator/main_test.go
Labels: approved, lgtm

#2016 rehearse periodics affected by changed ci-op configs
  cmd/pj-rehearse/main.go
  pkg/config/jobs.go
  pkg/config/jobs_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
Labels: approved, lgtm

#2028 Fix release-controller url in e2e
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#2027 Autoconfigbrancher: Add ci-operator-yaml-creator
  cmd/autoconfigbrancher/main.go
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#2030 vendor: bump histogram library for pod-scaler
  cmd/pod-scaler/producer.go
  cmd/pod-scaler/producer_test.go
  cmd/pod-scaler/types.go
  go.mod
  go.sum
  vendor/github.com/openhistogram/circonusllhist/LICENSE
  vendor/github.com/openhistogram/circonusllhist/LICENSE.OpenHistogram
  vendor/github.com/openhistogram/circonusllhist/README.md
  vendor/github.com/openhistogram/circonusllhist/circonusllhist.go
  vendor/modules.txt
Labels: approved, lgtm

#2031 add ci-operator-yaml-creator binary in autoconfigbrancher image
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm

#2032 Limit ci-operator-yaml-creator concurrency to one
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#2035 pod-scaler: allow choosing log style
  cmd/pod-scaler/main.go
Labels: approved, lgtm

#2036 Use filepath.WalkDir instead of filepath.Walk
  cmd/ci-operator/main.go
  cmd/generate-registry-metadata/main.go
  cmd/ldap-users-from-github-owners-files/main.go
  cmd/prow-job-dispatcher/main.go
  cmd/release-job-migrator/main.go
  cmd/sanitize-prow-jobs/main.go
  cmd/testgrid-config-generator/main.go
  pkg/api/ocpbuilddata/types.go
  pkg/config/load.go
  pkg/jobconfig/files.go
  pkg/load/load.go
  pkg/rehearse/configmaps.go
Labels: approved, lgtm

#2037 pod-scaler: handle read errors
  cmd/pod-scaler/producer.go
Labels: approved, lgtm

#2042 ci-operator-yaml-creator: Resolve absolute path first
  cmd/ci-operator-yaml-creator/main.go
Labels: approved, lgtm

#2044 Misc updates to the pod-scaler
  cmd/pod-scaler/main.go
  cmd/pod-scaler/producer.go
  cmd/pod-scaler/storage.go
Labels: approved, lgtm

#2045 Repo-Init: Write out sharded plugin config
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
  cmd/pj-rehearse/main.go
  cmd/repo-init/main.go
  pkg/prowconfigsharding/prowconfigsharding.go
  pkg/prowconfigsharding/prowconfigsharding_test.go
  test/integration/repo-init.sh
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/openshift/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/openshift/origin/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/other/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/repo/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/third/_pluginconfig.yaml
  test/integration/repo-init/input/core-services/prow/02_config/_config.yaml
  test/integration/repo-init/input/core-services/prow/02_config/_plugins.yaml
  test/integration/repo-init/input/core-services/prow/02_config/openshift/_pluginconfig.yaml
  test/integration/repo-init/input/core-services/prow/02_config/openshift/origin/_pluginconfig.yaml
Labels: approved, lgtm

#2046 DPTP-2266: Pass OO_ params to ci-operator as multi-stage-param.
  cmd/cvp-trigger/main.go
  cmd/cvp-trigger/main_test.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#2048 pod-scaler: misc flag improvements
  cmd/pod-scaler/main.go
  cmd/pod-scaler/producer.go
Labels: approved, lgtm

#2049 make: allow opting out of verbosity
  Makefile
Labels: approved, lgtm

#2052 ci-operator: log multi-line together
  cmd/ci-operator/main.go
  pkg/steps/template.go
Labels: approved, lgtm

#2054 Prow Yaml creator: Fix chdir issues
  cmd/ci-operator-yaml-creator/main.go
Labels: approved, lgtm

#2056 Add flag for base branch
  cmd/autoowners/main.go
Labels: approved, lgtm

#2053 Optimize the sanitize tool
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml
Labels: approved, lgtm

#2058 Use forked cmp version that does not trim the diff
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/modules.txt
Labels: approved, lgtm

#2059 vendor: bump test-infra
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
  vendor/k8s.io/test-infra/prow/logrusutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/logrusutil/logrusutil.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/modules.txt
Labels: approved, lgtm

#2047 ci-operator: propagate contexts as necessary
  pkg/steps/multi_stage.go
  pkg/steps/pod.go
  pkg/steps/template.go
Labels: approved, lgtm

#2057 Test-Image-Distributor: Distribute images for new config
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/load/agents/configAgent.go
  pkg/load/agents/configAgent_test.go
Labels: approved, lgtm

#2051 DPTP-2266: Update parameter names to be consistent with changes already made to openshift/release repo.
  cmd/cvp-trigger/main.go
  cmd/cvp-trigger/main_test.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#2063 Re-Add test-image-distributor distributes images from new config instantly
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/load/agents/configAgent.go
  pkg/load/agents/configAgent_test.go
Labels: approved, lgtm

#2064 ci-operator-yaml-creator: Ignore variants
  cmd/ci-operator-yaml-creator/main.go
  cmd/ci-operator-yaml-creator/main_test.go
Labels: approved, lgtm

#2038 DPTP-2244: Registry-replacer should also prune unused base images.
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Unused_base_images_are_pruned.yaml
Labels: approved, lgtm

#2068 Update test-infra
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/modules.txt
Labels: approved, lgtm

#2072 Add cluster profile for openstack-vh-mecha
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/validation/test.go
Labels: approved, lgtm

#2073 DPTP-2244: Modify autoconfigbrancher to provide registry dir to registry-replacer.
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#2070 Allow `skip_if_only_changed` in jobs
  pkg/jobconfig/files.go
  test/integration/ci-operator-prowgen/input/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#2067 DPTP-2269: Add dependency overrides at test level.
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/api/types.go
  pkg/registry/resolver.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#2071 claims: log duration for the successful claim
  pkg/steps/cluster_claim.go
Labels: approved, lgtm, tide/merge-method-squash

#2066 DPTP-2268: Remove custom OO_ code in favor of multi-stage parameters
  cmd/cvp-trigger/main.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/optional_operators.go
  pkg/steps/optional_operators_test.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#2069 pkg/validation: add a `struct` for field paths
  pkg/validation/field.go
  pkg/validation/test.go
Labels: approved, lgtm

#2076 Revert "DPTP-2244: Registry-replacer should also prune unused base images."
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Unused_base_images_are_pruned.yaml
Labels: approved, lgtm

#2065 [CVP-1467]add support for the kube objects
  cmd/cvp-trigger/README.md
  cmd/cvp-trigger/main.go
Labels: approved, lgtm

#2078 Bump test-infra to 2443b17c6b6196f6f380464f1cb30ab9ed8b502e
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/modules.txt
Labels: approved, lgtm

#2077 Revert "DPTP-2244: Modify autoconfigbrancher to provide registry dir to registry-replacer."
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#2082 Private config mirror: Shard plugin config
  cmd/autoconfigbrancher/main.go
  cmd/private-prow-configs-mirror/main.go
Labels: approved, lgtm

#2080 Add Emil to root OWNERS
  OWNERS
Labels: approved, lgtm

#2083 Name claim's secrets by test
  pkg/steps/cluster_claim.go
  pkg/steps/cluster_claim_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/testdata/zz_fixture_envTestGetPodObjectMounts_with_cluster_claim.yaml
  pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_cluster_claim.yaml
  pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_cluster_claim.yaml
  pkg/steps/utils/labels.go
  test/e2e/multi-stage/cluster-claim.yaml
Labels: approved, lgtm

#2084 DPTP-2209: prowconfigsharding: add bugzilla sharding
  pkg/prowconfigsharding/prowconfigsharding.go
  pkg/prowconfigsharding/prowconfigsharding_test.go
Labels: approved, lgtm

#2075 Add a new tool: cluster-displayer
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
  pkg/api/constant.go
  pkg/api/types.go
Labels: approved, lgtm

#2060 ci-operator: pre-censor fields before encoding output
  cmd/ci-operator/main.go
  pkg/api/env.go
  pkg/junit/censor.go
  pkg/junit/censor_test.go
  pkg/junit/testdata/zz_fixture_TestCensorTestSuite.yaml
Labels: approved, lgtm

#2086 Registry-Replacer: Handle dockerfile_literal
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Use_dockerfile_literal_if_present.yaml
Labels: approved, lgtm

#2085 Test imagestream distributor config change: Cope with imagestream
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#2081 Run integration tests 25 times in CI to detect flakes
  Makefile
Labels: approved, lgtm

#2079 Shard tide queries
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
Labels: approved, lgtm

#2087 DPTP-2270: Merge dependency_overrides from workflow in resolver.
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
Labels: approved, lgtm

#2088 Update test-infra vendors
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/modules.txt
Labels: approved, lgtm

#2090 Shard lgtm plugin config
  Makefile
  pkg/prowconfigsharding/prowconfigsharding.go
  pkg/prowconfigsharding/prowconfigsharding_test.go
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/openshift/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/other/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/repo/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/third/_pluginconfig.yaml
Labels: approved, lgtm

#2074 DPTP-2262: Support importing cluster claim release streams
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/bundle_source.go
  pkg/steps/cluster_claim.go
  pkg/steps/index_generator.go
  pkg/steps/multi_stage.go
  pkg/steps/utils/clusterpool.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/multi-stage/cluster-claim.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#2092 Revert "DPTP-2262: Support importing cluster claim release streams"
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/bundle_source.go
  pkg/steps/cluster_claim.go
  pkg/steps/index_generator.go
  pkg/steps/multi_stage.go
  pkg/steps/utils/clusterpool.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/multi-stage/cluster-claim.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#2093 private-org-sync: include output when git ls-remote fails
  cmd/private-org-sync/main.go
Labels: approved, lgtm

#2094 Test Image distributor: Don't log notfound in configchange handler
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#2011 Remove/rename all bitwarden references
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/api/secretbootstrap/secretboostrap_test.go
  pkg/api/secretbootstrap/testdata/TestLoadConfigFromFile/basic_base.yaml
  pkg/api/secretbootstrap/testdata/TestLoadConfigFromFile/dup_key.yaml
  pkg/secrets/client.go
  pkg/secrets/flags_test.go
  pkg/secrets/vault.go
Labels: approved, lgtm

#2098 DPTP-2270: Make CVP produce OO_ params again as this will lessen the migration burden for ci workflows.
  cmd/cvp-trigger/main.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#2099 Revert "Merge pull request #2092 from openshift/revert-2074-import-claim-release"
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/bundle_source.go
  pkg/steps/cluster_claim.go
  pkg/steps/index_generator.go
  pkg/steps/multi_stage.go
  pkg/steps/utils/clusterpool.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/multi-stage/cluster-claim.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#2096 Minor fixes
  pkg/defaults/defaults.go
  pkg/steps/input_env.go
  pkg/steps/input_env_test.go
  pkg/steps/output_image_tag.go
  pkg/steps/release/import_release.go
  pkg/validation/test.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#2095 Shard the external-plugins configuration
  go.mod
  go.sum
  pkg/prowconfigsharding/prowconfigsharding.go
  pkg/prowconfigsharding/prowconfigsharding_test.go
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/openshift/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/other/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/repo/_pluginconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/third/_pluginconfig.yaml
  vendor/github.com/gomodule/redigo/LICENSE
  vendor/github.com/gomodule/redigo/redis/conn.go
  vendor/github.com/gomodule/redigo/redis/doc.go
  vendor/github.com/gomodule/redigo/redis/go16.go
  vendor/github.com/gomodule/redigo/redis/log.go
  vendor/github.com/gomodule/redigo/redis/pool.go
  vendor/github.com/gomodule/redigo/redis/pool17.go
  vendor/github.com/gomodule/redigo/redis/pubsub.go
  vendor/github.com/gomodule/redigo/redis/redis.go
  vendor/github.com/gomodule/redigo/redis/reply.go
  vendor/github.com/gomodule/redigo/redis/scan.go
  vendor/github.com/gomodule/redigo/redis/script.go
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/modules.txt
Labels: approved, lgtm

#2104 add only one lgtm configuration on a sharded config
  pkg/prowconfigsharding/prowconfigsharding.go
Labels: approved, lgtm

#2097 *: Add ClusterProfileAWSArm64
  cmd/repo-init/main.go
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/validation/test.go
Labels: approved, lgtm

#2105 pod-scaler: factor out types for reuse
  cmd/pod-scaler/producer.go
  cmd/pod-scaler/producer_test.go
  cmd/pod-scaler/storage.go
  cmd/pod-scaler/types.go
  pkg/pod-scaler/types.go
  pkg/pod-scaler/types_test.go
Labels: approved, lgtm

#2102 Remove deprecated fields from secret-generator
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
  pkg/api/secretgenerator/secretgenerator.go
  pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/no_parameters.yaml
  pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/single_parameter.yaml
  pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/single_parameter_with_multiple_values.yaml
  pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/two_parameters_with_multiple_values.yaml
  pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_no_parameters.yaml
  pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_single_parameter.yaml
  pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_single_parameter_with_multiple_values.yaml
  pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_two_parameters_with_multiple_values.yaml
  test/e2e/secret-generator/bootstrap.yaml
  test/e2e/secret-generator/generator.yaml
Labels: approved, lgtm

#2106 build_root: use new image
  .ci-operator.yaml
Labels: approved, lgtm

#2108 e2e: move optional operators into their own package
  Makefile
  test/e2e/optional-operators/e2e_test.go
  test/e2e/optional-operators/optional-operators.yaml
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#2107 ci-operator: skip censoring for $SHARED_DIR secrets
  pkg/steps/secretrecordingclient/client.go
  pkg/steps/secretrecordingclient/client_test.go
Labels: approved, lgtm

#2116 testhelper: expose some useful functions
  pkg/testhelper/accessory.go
Labels: approved, lgtm

#2117 e2e: use a separate tag for e2e framework
  Makefile
  test/e2e/framework/ci-operator.go
  test/e2e/framework/framework.go
  test/e2e/framework/test.go
Labels: approved

#2115 e2e: don't run OO e2e by default
  Makefile
  hack/lint.sh
Labels: approved

#2111 pod-scaler: fix --produce-once behavior
  cmd/pod-scaler/main.go
Labels: approved, lgtm

#2113 pod-scaler: log how much we gathered in one query
  cmd/pod-scaler/producer.go
Labels: approved, lgtm

#2062 pkg/validation: validate all pipeline image inputs
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/field.go
  pkg/validation/test.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#2103 Remove unused and deprecated fields from ci-secret-bootstrap
  cmd/ci-secret-bootstrap/main_test.go
  pkg/api/secretbootstrap/secretboostrap.go
  test/e2e/secret-generator/bootstrap.yaml
Labels: approved, lgtm

#2109 pod-scaler: don't double count data on query edges
  cmd/pod-scaler/producer.go
Labels: approved, lgtm

#2110 pod-scaler: ignore NaN values from Prometheus
  pkg/pod-scaler/types.go
Labels: approved, lgtm

#2112 pod-scaler: correctly compute start of query range
  cmd/pod-scaler/producer.go
Labels: approved, lgtm

#2114 pod-scaler: correctly detect the end of query range
  cmd/pod-scaler/producer.go
Labels: approved, lgtm

#2118 Revert "pkg/validation: also validate `from_image`"
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#2119 cvp-trigger: pass index & bundle as dep overrides, not params
  cmd/cvp-trigger/main.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#2120 make: remove unused targets, script
  Makefile
  hack/build-go.sh
Labels: approved, lgtm

#2121 private-org-sync: retry ls-remote with exponential backoff
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#2124 Dependency overrides are not taken into account when performing fail-fast test step dependency validations.
  pkg/validation/config_test.go
  pkg/validation/test.go
Labels: approved, lgtm

#2128 cmd/autoowners/README: Fix -config-subdirs -> -config-subdir references and update help text
  cmd/autoowners/README.md
Labels: approved, lgtm

#2129 cmd/autoowners: Don't pull OWNERS_ALIASES when there is no OWNERS
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm

#2091 [CVP-2012] Make the cvp-trigger utility resistent to refused Prow connections
  cmd/cvp-trigger/main.go
Labels: approved, lgtm

#2131 Remove BitWarden cli in the built images
  images/ci-secret-bootstrap/Dockerfile
  images/ci-secret-generator/Dockerfile
Labels: approved, lgtm
