Repository openshift/ci-tools, pull requests merged in 2021-02, with the labels that each got.

#1656 backport-verifier: print commit messages in output
  cmd/backport-verifier/server.go
  cmd/backport-verifier/server_test.go
Labels: approved, lgtm

#1651 prow-job-dispatcher: add a flag to create a PR
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  hack/run-prow-job-dispatcher.sh
  images/prowjobdispatcher/Dockerfile
  pkg/dispatcher/prometheus.go
Labels: approved, lgtm

#1658 Update controller-runtime to fix source.Channel
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
Labels: approved, lgtm

#1659 Add osd-ephemeral to cluster_profile list
  pkg/validation/test.go
Labels: approved, lgtm

#1660 Revert "test-images-distributor: no distribution to api.ci"
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#1662 steps/clusterinstall: Upgrade template is out of date
  pkg/steps/clusterinstall/template.go
Labels: approved, lgtm

#1663 backport-verifier: only use the first line of a commit
  cmd/backport-verifier/server.go
  cmd/backport-verifier/server_test.go
Labels: approved, lgtm

#1664 CI-Operator: Stop writing step graph out
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1665 Add tooling to trigger SA secret rotation
  cmd/serviceaccount-secret-rotation-trigger/README.md
  cmd/serviceaccount-secret-rotation-trigger/main.go
  cmd/serviceaccount-secret-rotation-trigger/main_test.go
  images/serviceaccount-secret-rotation-trigger/Dockerfile
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher_test.go
Labels: approved, lgtm

#1667 Do not require configmap for osd-ephemeral
  pkg/api/types.go
  pkg/prowgen/prowgen.go
Labels: lgtm

#1668 Fix the entrypoint of the prow-job-dispatch image
  images/prowjobdispatcher/Dockerfile
Labels: approved, lgtm

#1672 Use ocp/4.8:cli image for promotion pod
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
Labels: approved, lgtm

#1671 SA secret rotation trigger: Use patch to avoid conflicts
  cmd/serviceaccount-secret-rotation-trigger/main.go
Labels: approved, lgtm

#1674 Bump test-infra to 5e490580b8a6
  cmd/private-prow-configs-mirror/main_test.go
  go.mod
  go.sum
  pkg/steps/artifacts_test.go
  vendor/k8s.io/test-infra/experiment/autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/flagutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/flagutil/github.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/jira/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/jira/jira.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/spyglass/artifacts.go
  vendor/modules.txt
Labels: approved, lgtm

#1670 prow-job-dispatcher: fix the PR creation
  cmd/prow-job-dispatcher/main.go
  hack/run-prow-job-dispatcher.sh
Labels: approved, lgtm

#1675 ci-operator: add flag --lease-server-username-file
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1678 [DPTP-1433] Add the registry-replacer step in the autoconfigbrancher tool
  cmd/autoconfigbrancher/main.go
  images/autoconfigbrancher/Dockerfile
Labels: approved, lgtm

#1677 [DPTP-1909] Improve logging of unused elements in bw items
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm

#1661 [DPTP-1902] Add the ability to load gzipped ci-operator configuration
  cmd/backport-verifier/main.go
  cmd/bugzilla-backporter/main.go
  cmd/ci-secret-generator/main.go
  cmd/determinize-peribolos/main.go
  cmd/dptp-controller-manager/main.go
  cmd/generate-registry-metadata/main.go
  cmd/group-auto-updater/main.go
  cmd/private-org-peribolos-sync/main.go
  cmd/prow-job-dispatcher/main.go
  cmd/publicize/main.go
  cmd/release-job-migrator/main.go
  cmd/sanitize-prow-jobs/main.go
  cmd/testgrid-config-generator/main.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/config/load.go
  pkg/config/whitelist.go
  pkg/controller/secretsyncer/config/config.go
  pkg/deprecatetemplates/allowlist.go
  pkg/dispatcher/config.go
  pkg/jobconfig/files.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/rehearse/configmaps.go
  pkg/util/gzip/gzip.go
Labels: approved, lgtm

#1679 Allow steps to create roles
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1681 Update boskos version
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/config.go
  vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/credentials.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/shared_credentials_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/assume_role_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/credentials/stscreds/web_identity_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/service.go
  vendor/github.com/aws/aws-sdk-go/aws/ec2metadata/token_provider.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/v3model.go
  vendor/github.com/aws/aws-sdk-go/aws/request/connection_reset_error.go
  vendor/github.com/aws/aws-sdk-go/aws/session/custom_transport.go
  vendor/github.com/aws/aws-sdk-go/aws/session/custom_transport_go1.12.go
  vendor/github.com/aws/aws-sdk-go/aws/session/custom_transport_go1.5.go
  vendor/github.com/aws/aws-sdk-go/aws/session/custom_transport_go1.6.go
  vendor/github.com/aws/aws-sdk-go/aws/session/doc.go
  vendor/github.com/aws/aws-sdk-go/aws/session/env_config.go
  vendor/github.com/aws/aws-sdk-go/aws/session/session.go
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/aws/aws-sdk-go/internal/ini/ini_parser.go
  vendor/github.com/aws/aws-sdk-go/internal/s3shared/arn/accesspoint_arn.go
  vendor/github.com/aws/aws-sdk-go/internal/s3shared/arn/arn.go
  vendor/github.com/aws/aws-sdk-go/internal/s3shared/arn/outpost_arn.go
  vendor/github.com/aws/aws-sdk-go/internal/s3shared/endpoint_errors.go
  vendor/github.com/aws/aws-sdk-go/internal/s3shared/resource_request.go
  vendor/github.com/aws/aws-sdk-go/internal/s3shared/s3err/error.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi/reader.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/header.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/message.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/host.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/timestamp.go
  vendor/github.com/aws/aws-sdk-go/service/s3/api.go
  vendor/github.com/aws/aws-sdk-go/service/s3/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/s3/doc_custom.go
  vendor/github.com/aws/aws-sdk-go/service/s3/endpoint.go
  vendor/github.com/aws/aws-sdk-go/service/s3/endpoint_builder.go
  vendor/github.com/aws/aws-sdk-go/service/s3/endpoint_errors.go
  vendor/github.com/aws/aws-sdk-go/service/s3/errors.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/bucket_region.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/pool.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go
  vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload_input.go
  vendor/github.com/aws/aws-sdk-go/service/s3/sse.go
  vendor/github.com/aws/aws-sdk-go/service/sts/api.go
  vendor/github.com/aws/aws-sdk-go/service/sts/doc.go
  vendor/github.com/jmespath/go-jmespath/.travis.yml
  vendor/github.com/jmespath/go-jmespath/Makefile
  vendor/github.com/jmespath/go-jmespath/go.mod
  vendor/github.com/jmespath/go-jmespath/go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/boskos/client/client.go
  vendor/sigs.k8s.io/boskos/common/config.go
Labels: approved, lgtm

#1683 ci-operator: support credentials file for boskos
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/lease/client.go
Labels: approved, lgtm

#1657 pkg/registry: merge test/workflow list/dict fields
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
Labels: approved, lgtm

#1666 cvp-trigger: supply parameters to namespace hash
  cmd/cvp-trigger/main.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#1634 applyconfig: handle nonexisting namespaces in server-side dry-run
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
  cmd/ci-operator/main.go
  pkg/api/nsttl/const.go
Labels: approved, lgtm

#1686 applyconfig: more robust missing namespace detection
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
Labels: approved, lgtm

#1676 prowgen: generate flag --lease-server-credentials-file
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cluster_profile.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cpaas_cluster_profile.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_1.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_2.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_3.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_4.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_5.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
Labels: approved, lgtm

#1673 Remove code supporting obsolete templates
  cmd/determinize-ci-operator/main.go
  cmd/determinize-ci-operator/main_test.go
  pkg/api/types.go
  pkg/load/load_test.go
  pkg/prowgen/prowgen.go
  pkg/validation/test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1688 ci-secret-bootstrap: process allowed unused records soon enough
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm

#1682 ci-operator: set TTL annotations before everything else
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1687 ci-operator: remove boskos username and password-file flags
  Makefile
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  test/e2e/framework/framework.go
Labels: approved, lgtm

#1690 configresolver: output log as JSON
  cmd/ci-operator-configresolver/main.go
Labels: approved, lgtm

#1692 slack-bot: show off everything we can do when user asks
  pkg/slack/events/mention/mention.go
  pkg/slack/events/mention/testdata/zz_fixture_TestRespnseFor_unrelated_text_gets_a_sad_response.yaml
Labels: approved, lgtm

#1697 Update vendor for go 1.16
  Makefile
  go.sum
Labels: approved, lgtm

#1698 Upgrade to go 1.16
  go.mod
Labels: approved, lgtm

#1701 Bump test-infra to 84128728123e
  go.mod
  go.sum
  vendor/github.com/bazelbuild/buildtools/LICENSE
  vendor/github.com/bazelbuild/buildtools/build/build_defs.bzl
  vendor/github.com/bazelbuild/buildtools/build/lex.go
  vendor/github.com/bazelbuild/buildtools/build/parse.y
  vendor/github.com/bazelbuild/buildtools/build/parse.y.go
  vendor/github.com/bazelbuild/buildtools/build/print.go
  vendor/github.com/bazelbuild/buildtools/build/quote.go
  vendor/github.com/bazelbuild/buildtools/build/rewrite.go
  vendor/github.com/bazelbuild/buildtools/build/rule.go
  vendor/github.com/bazelbuild/buildtools/build/syntax.go
  vendor/github.com/bazelbuild/buildtools/build/walk.go
  vendor/github.com/bazelbuild/buildtools/tables/jsonparser.go
  vendor/github.com/bazelbuild/buildtools/tables/tables.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/jira/BUILD.bazel
  vendor/k8s.io/test-infra/prow/jira/jira.go
  vendor/k8s.io/test-infra/prow/jira/metrics.go
  vendor/k8s.io/test-infra/prow/plugins/approve/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/owners.go
  vendor/k8s.io/test-infra/prow/plugins/buildifier/buildifier.go
  vendor/k8s.io/test-infra/prow/plugins/jira/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/jira/jira.go
  vendor/k8s.io/test-infra/prow/plugins/project/project.go
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/k8s.io/test-infra/prow/spyglass/lenses/BUILD.bazel
  vendor/k8s.io/test-infra/prow/spyglass/write-a-lens.md
  vendor/k8s.io/test-infra/robots/pr-creator/updater/updater.go
  vendor/modules.txt
Labels: approved, lgtm

#1691 secret-wrapper: handle writable home
  cmd/secret-wrapper/main.go
  test/secret-wrapper-integration.sh
Labels: approved, lgtm

#1693 secret-wrapper: populate a unique, writable KUBECONFIG
  cmd/secret-wrapper/main.go
  test/secret-wrapper-integration.sh
Labels: approved, lgtm

#1702 blocking-issue-creator: sort branch tokens
  cmd/blocking-issue-creator/main.go
Labels: approved, lgtm

#1704 Add DockerfileLiteral option to images
  pkg/api/types.go
  pkg/steps/git_source.go
  pkg/steps/project_image.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1700 registry-replacer: add flag -maxConcurrency
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#1689 result-aggregator: support --passwd-file
  cmd/result-aggregator/main.go
  cmd/result-aggregator/main_test.go
  cmd/result-aggregator/validator.go
Labels: approved, lgtm

#1707 [DPTP-2001] fix autopublicizeconfig pr creating function arguments
  cmd/autopublicizeconfig/main.go
Labels: approved, lgtm

#1708 blocking-issue-creator: sort branches everywhere
  cmd/blocking-issue-creator/main.go
Labels: approved, lgtm

#1695 ci-operator: add flag -report-credentials-file
  pkg/results/report.go
  pkg/results/report_test.go
Labels: approved, lgtm

#1709 ci-operator: remove 2min from every test's runtime
  pkg/steps/multi_stage.go
  pkg/steps/release/create_release.go
  pkg/util/rbacs.go
Labels: approved, lgtm

#1710 ci-operator: handle explicit imagestreams in step from
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  test/e2e/multi-stage/e2e_test.go
  test/e2e/multi-stage/names.yaml
Labels: approved, lgtm

#1706 prowgen: use flag --report-credentials-file
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_postsubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Input_is_YAML_and_it_is_correctly_processed.yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_Using_a_variant_config__one_test_and_images__one_existing_job._Expect_one_presubmit__pre_post_submit_images_jobs._Existing_job_should_not_be_changed..yaml
  cmd/ci-operator-prowgen/testdata/zz_fixture_presubmit_TestFromCIOperatorConfigToProwYaml_one_test_and_images__no_previous_jobs._Expect_test_presubmit__pre_post_submit_images_jobs.yaml
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_Promotion_configuration_causes_promote_job_with_unique_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cluster_profile.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_cpaas_cluster_profile.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_0.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_1.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_2.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_3.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_4.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecTemplate_testcase_5.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_additional_args_and_secret_are_included_in_podspec.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_additional_args_are_included_in_podspec.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_multiple_targets.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_private_job.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpec_standard_use_case.yaml
  test/integration/ci-operator-prowgen/output/jobs/private-org/duper/private-org-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/subdir/repo/subdir-repo-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-job-release-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-removed-promotion-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-release-3.11-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/ci-tools/openshift-ci-tools-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/other/org-other-nonstandard-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
Labels: approved, lgtm

#1713 stop using user/password for result-aggregator
  cmd/ci-operator/main.go
  cmd/result-aggregator/main.go
  pkg/results/report.go
  pkg/results/report_test.go
Labels: approved, lgtm

#1711 ci-operator: be more intelligent with grace periods
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1715 ci-operator: improve user experience for timeouts
  pkg/api/types.go
  pkg/load/load.go
  pkg/steps/multi_stage.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/multi-stage/e2e_test.go
  test/e2e/multi-stage/registry/timeout/timeout-ref.yaml
Labels: approved, lgtm

#1716 ci-operator: show that new timeout fields work
  test/e2e/multi-stage/registry/timeout/timeout-ref.yaml
Labels: approved, lgtm

#1717 ci-operator: remove old timing fields
  pkg/api/types.go
  pkg/load/load.go
  pkg/webreg/webreg.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1719 ci-operator: stop munging bash
  pkg/steps/multi_stage.go
  pkg/steps/testdata/zz_fixture_TestGeneratePodReadonly.yaml
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#1721 release-job-migrated: add ignore-unresolved flag
  cmd/release-job-migrator/main.go
  test/integration/release-job-migrator.sh
  test/integration/release-job-migrator/expected2.txt
  test/integration/release-job-migrator/expected2/_allow-list.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__ocp-4.7.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__okd-4.7.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__origin-4.7.yaml
  test/integration/release-job-migrator/expected2/config.yaml
  test/integration/release-job-migrator/expected2/jobs/openshift-release-master-periodics.yaml
  test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.4-periodics.yaml
  test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.6-periodics.yaml
  test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.7-periodics.yaml
  test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.8-periodics.yaml
  test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.9-periodics.yaml
  test/integration/release-job-migrator/expected2/releases/release-ocp-4.7.json
  test/integration/release-job-migrator/expected2/releases/release-origin-4.7.json
Labels: approved, lgtm

#1718 ci-operator: always use secret-wrapper
  pkg/api/types.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/testdata/zz_fixture_TestGeneratePodReadonly.yaml
  pkg/webreg/webreg.go
  test/e2e/lease/step-registry/check-leased-resource/check-leased-resource-ref.yaml
  test/e2e/lease/step-registry/check-leases/check-leases-ref.yaml
  test/e2e/lease/step-registry/declare-and-check-leases-with-count/declare-and-check-leases-with-count-ref.yaml
  test/e2e/lease/step-registry/declare-and-check-leases/declare-and-check-leases-ref.yaml
Labels: approved, lgtm

#1722 Add / to regex generated by dispatcher
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
Labels: approved, lgtm

#1724 [DPTP-2013] Pass an empty map when creating a new image builder instead of nil
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#1712 secret-bootstrapper: check the attribute value in config validation
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/api/secretbootstrap/secretboostrap_test.go
Labels: approved, lgtm

#1726 secret-wrapper: move the underlying dir while keeping previous one
  cmd/entrypoint-wrapper/main.go
  cmd/secret-wrapper/main.go
  images/entrypoint-wrapper/Dockerfile
Labels: approved, lgtm

#1725 ci-operator: use the renamed entrypoint wrapper
  pkg/steps/multi_stage.go
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#1728 Update test-infra vendors and refactor tools to use the newest prow plugin library
  cmd/private-prow-configs-mirror/main.go
  cmd/private-prow-configs-mirror/main_test.go
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  go.mod
  go.sum
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  vendor/k8s.io/test-infra/prow/entrypoint/run.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/git/git.go
  vendor/k8s.io/test-infra/prow/git/v2/adapter.go
  vendor/k8s.io/test-infra/prow/git/v2/publisher.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/pluginhelp/hook/hook.go
  vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/spyglass/lenses/BUILD.bazel
  vendor/modules.txt
Labels: approved, do-not-merge/hold, lgtm

#1727 cmd/testgrid-config-generator: All release periodics should appear in testgrid
  cmd/testgrid-config-generator/main.go
  test/integration/testgrid-config-generator/expected/redhat-openshift-informing.yaml
Labels: approved, lgtm

#1729 Improve Unit Tests
  cmd/vault-subpath-proxy/main_test.go
  pkg/steps/template_test.go
  pkg/steps/testdata/zz_fixture_TestGetPodFromObject_empty_object__expect_nothing.yaml
  pkg/steps/testdata/zz_fixture_TestGetPodFromObject_object_is_a_Pod__expect_to_get_a_pod_struct.yaml
  pkg/steps/testdata/zz_fixture_TestInjectLabelsToTemplate_jobspec_with_refs__label_injection_expected.yaml
  pkg/steps/testdata/zz_fixture_TestInjectLabelsToTemplate_nil_refs_in_jobspec__no_injection_expected.yaml
  pkg/steps/testdata/zz_fixture_TestInjectResourcesToPod_both_default_and_template_s_resource_requests_are_defined__pod_has_container_named_test__and_is_changed.yaml
  pkg/steps/testdata/zz_fixture_TestInjectResourcesToPod_no_resource_requests_are_defined__container_named_test__exists__expect_no_changes.yaml
  pkg/steps/testdata/zz_fixture_TestInjectResourcesToPod_only_the_default_resource_requests_are_defined__pod_has_container_named_test__and_is_changed.yaml
  pkg/steps/testdata/zz_fixture_TestInjectResourcesToPod_resource_requests_are_defined__no_container_named_test__exists__expect_no_changes.yaml
  pkg/steps/testdata/zz_fixture_TestOperateOnTemplatePods_only_default_resources_defined_in_the_config_no_existing_resources_in_the_container__changes_are_expected.yaml
  pkg/steps/testdata/zz_fixture_TestOperateOnTemplatePods_resources_defined_in_the_config_but_the_test_container_has_existing_resources__no_changes_expected.yaml
  pkg/steps/testdata/zz_fixture_TestOperateOnTemplatePods_resources_defined_in_the_config_no_existing_resources_in_the_container__changes_are_expected.yaml
  pkg/steps/testdata/zz_fixture_TestOperateOnTemplatePods_template_with_no_pod__no_changes_expected.yaml
  pkg/steps/testdata/zz_fixture_TestOperateOnTemplatePods_template_with_pod_but_with_no_artifacts_Volume_VolumeMount__no_changes_expected.yaml
  pkg/steps/testdata/zz_fixture_TestOperateOnTemplatePods_template_with_pod_with_artifacts_Volume_VolumeMount_and_artifacts_dir_defined__changes_expected.yaml
  pkg/steps/testdata/zz_fixture_TestOperateOnTemplatePods_template_with_pod_with_artifacts_Volume_VolumeMount_but_not_artifacts_dir_defined__no_changes_expected.yaml
Labels: approved, lgtm

#1730 release-job-migrator: support new naming scheme
  cmd/release-job-migrator/main.go
  cmd/release-job-migrator/main_test.go
  test/integration/release-job-migrator/expected.txt
  test/integration/release-job-migrator/expected/_allow-list.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ci-4.6.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__ci-4.7.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__nightly-4.7.yaml
  test/integration/release-job-migrator/expected/jobs/openshift-release-master-periodics.yaml
  test/integration/release-job-migrator/expected/jobs/openshift-release-release-4.4-periodics.yaml
  test/integration/release-job-migrator/expected/releases/release-ocp-4.7.json
  test/integration/release-job-migrator/expected/releases/release-origin-4.7.json
  test/integration/release-job-migrator/expected2.txt
  test/integration/release-job-migrator/expected2/_allow-list.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__ci-4.6.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__ci-4.7.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__nightly-4.7.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__origin-4.6.yaml
  test/integration/release-job-migrator/expected2/jobs/openshift-release-master-periodics.yaml
  test/integration/release-job-migrator/expected2/jobs/openshift-release-release-4.4-periodics.yaml
  test/integration/release-job-migrator/expected2/releases/release-ocp-4.7.json
  test/integration/release-job-migrator/input/ci-operator/openshift/release/openshift-release-master__nightly-4.7.yaml
  test/integration/release-job-migrator/input/jobs/openshift-release-master-periodics.yaml
  test/integration/release-job-migrator/input/jobs/openshift-release-release-4.4-periodics.yaml
Labels: approved, lgtm

#1733 dispatcher: Run PRCreationOptions.Finalize when needed
  cmd/prow-job-dispatcher/main.go
Labels: approved, lgtm

#1735 ci-operator: stop allowing users to set artifact dir for pods
  pkg/api/config.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/load/load_test.go
  pkg/prowgen/prowgen_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/duper/super-priv-duper-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/trooper/super-priv-trooper-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/duper/super-priv-duper-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/trooper/super-priv-trooper-master.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-master.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-release-4.5.yaml
  test/integration/config-brancher/expected/org/bump/org-bump-release-4.6.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-master.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-release-4.5.yaml
  test/integration/config-brancher/expected/org/existing/org-existing-release-4.6.yaml
  test/integration/config-brancher/expected/org/new/org-new-release-4.5.yaml
  test/integration/config-brancher/expected/org/new/org-new-release-4.6.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/release-job-migrator/expected/ci-operator/openshift/release/openshift-release-master__nightly-4.7.yaml
  test/integration/release-job-migrator/expected2/ci-operator/openshift/release/openshift-release-master__nightly-4.7.yaml
  test/integration/repo-init/expected/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/integration/repo-init/expected/ci-operator/config/openshift/origin/openshift-origin-master.yaml
  test/integration/repo-init/expected/ci-operator/config/org/other/org-other-nonstandard.yaml
  test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-master.yaml
  test/integration/repo-init/expected/ci-operator/config/org/third/org-third-nonstandard.yaml
Labels: approved, lgtm
