Repository openshift/ci-tools, pull requests merged in 2021-03, with the labels that each got.

#1736 ci-operator: don't allow setting artifact dir for steps
  pkg/api/config.go
  pkg/api/types.go
  pkg/steps/multi_stage_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1738 Vault subpath proxy: ListenTLS when certificate is passed
  cmd/vault-subpath-proxy/main.go
Labels: approved, lgtm

#1737 Add a vault client
  pkg/vaultclient/types.go
  pkg/vaultclient/vaultclient.go
  pkg/vaultclient/vaultclient_test.go
Labels: approved, lgtm

#1740 remove unused secret-wrapper image
  Makefile
  cmd/secret-wrapper/main.go
  images/secret-wrapper/Dockerfile
  test/entrypoint-wrapper-integration.sh
Labels: approved, lgtm

#1741 Allow using Accessory in normal unit tests
  pkg/testhelper/accessory.go
  test/e2e/framework/framework.go
  test/e2e/framework/test.go
Labels: approved, lgtm

#1739 ci-operator: remove deprecated flags nobody uses
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1742 prowgen: generate kvm label
  pkg/api/constant.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_kvm_label.yaml
Labels: approved, lgtm

#1723 Check sanitize's config if it can dispatch jobs determinically
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  cmd/sanitize-prow-jobs/main.go
  cmd/sanitize-prow-jobs/main_test.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/dispatcher/prometheus_test.go
  pkg/dispatcher/testdata/TestLoadConfig/good_config.yaml
  pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml
Labels: approved, lgtm

#1734 Vault secret manager
  cmd/vault-secret-collection-manager/README.md
  cmd/vault-secret-collection-manager/dex-dev.yaml
  cmd/vault-secret-collection-manager/docker-compose.yaml
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/main_test.go
  cmd/vault-secret-collection-manager/types.go
  go.mod
  go.sum
  pkg/testhelper/accessory.go
  pkg/testhelper/vault.go
  pkg/vaultclient/vaultclient.go
  pkg/vaultclient/vaultclient_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/test.go
  vendor/github.com/julienschmidt/httprouter/.travis.yml
  vendor/github.com/julienschmidt/httprouter/LICENSE
  vendor/github.com/julienschmidt/httprouter/README.md
  vendor/github.com/julienschmidt/httprouter/params_go17.go
  vendor/github.com/julienschmidt/httprouter/params_legacy.go
  vendor/github.com/julienschmidt/httprouter/path.go
  vendor/github.com/julienschmidt/httprouter/router.go
  vendor/github.com/julienschmidt/httprouter/tree.go
  vendor/modules.txt
Labels: approved, lgtm, tide/merge-method-squash

#1743 sanitize: use kvm label
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/dispatcher/testdata/TestLoadConfig/good_config_with_build_farm_with_jobs.yaml
Labels: approved, lgtm

#1745 make: update location of kubeconfig
  Makefile
Labels: approved, lgtm

#1746 pkg/registry: emit less arcane error messages
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/registry/stack.go
Labels: approved, lgtm

#1749 Use embedd instead of bindata for embedding
  go.mod
  go.sum
  hack/tools.go
  hack/update-codegen.sh
  pkg/lenses/stepgraph/bindata.go
  pkg/lenses/stepgraph/stepgraph.go
  vendor/github.com/go-bindata/go-bindata/v3/.drone.yml
  vendor/github.com/go-bindata/go-bindata/v3/.gitignore
  vendor/github.com/go-bindata/go-bindata/v3/CONTRIBUTING.md
  vendor/github.com/go-bindata/go-bindata/v3/LICENSE
  vendor/github.com/go-bindata/go-bindata/v3/Makefile
  vendor/github.com/go-bindata/go-bindata/v3/README.md
  vendor/github.com/go-bindata/go-bindata/v3/_config.yml
  vendor/github.com/go-bindata/go-bindata/v3/asset.go
  vendor/github.com/go-bindata/go-bindata/v3/bytewriter.go
  vendor/github.com/go-bindata/go-bindata/v3/config.go
  vendor/github.com/go-bindata/go-bindata/v3/convert.go
  vendor/github.com/go-bindata/go-bindata/v3/debug.go
  vendor/github.com/go-bindata/go-bindata/v3/doc.go
  vendor/github.com/go-bindata/go-bindata/v3/file.go
  vendor/github.com/go-bindata/go-bindata/v3/go-bindata/.gitignore
  vendor/github.com/go-bindata/go-bindata/v3/go-bindata/AppendSliceValue.go
  vendor/github.com/go-bindata/go-bindata/v3/go-bindata/main.go
  vendor/github.com/go-bindata/go-bindata/v3/go-bindata/version.go
  vendor/github.com/go-bindata/go-bindata/v3/go.mod
  vendor/github.com/go-bindata/go-bindata/v3/go.sum
  vendor/github.com/go-bindata/go-bindata/v3/release.go
  vendor/github.com/go-bindata/go-bindata/v3/restore.go
  vendor/github.com/go-bindata/go-bindata/v3/stringwriter.go
  vendor/github.com/go-bindata/go-bindata/v3/toc.go
  vendor/github.com/go-bindata/go-bindata/v3/tools.go
  vendor/github.com/kisielk/errcheck/.travis.yml
  vendor/github.com/kisielk/errcheck/LICENSE
  vendor/github.com/kisielk/errcheck/README.md
  vendor/github.com/kisielk/errcheck/go.mod
  vendor/github.com/kisielk/errcheck/go.sum
  vendor/github.com/kisielk/errcheck/internal/errcheck/embedded_walker.go
  vendor/github.com/kisielk/errcheck/internal/errcheck/errcheck.go
  vendor/github.com/kisielk/errcheck/main.go
  vendor/modules.txt
Labels: approved, lgtm

#1744 [DPTP-1969] Implement a more sophisticated way to chooses a subset of jobs when there is a rehearsal limit
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  pkg/config/jobs.go
  pkg/config/jobs_test.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#1750 Vault subpath proxy: Use testhelper machinery
  cmd/vault-subpath-proxy/main_test.go
Labels: approved, lgtm

#1720 [DPTP-2014] Refactor blocking-issue-creator to use the prow github client
  cmd/blocking-issue-creator/main.go
  cmd/blocking-issue-creator/main_test.go
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#1747 Add basic secret manager frontend
  .gitignore
  Makefile
  cmd/vault-secret-collection-manager/README.md
  cmd/vault-secret-collection-manager/docker-compose.yaml
  cmd/vault-secret-collection-manager/frontend.go
  cmd/vault-secret-collection-manager/index.template.html
  cmd/vault-secret-collection-manager/index.ts
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/main_test.go
  cmd/vault-secret-collection-manager/style.css
  cmd/vault-secret-collection-manager/tsconfig.json
  hack/lint.sh
  hack/pr-deploy-vault-secret-manager.yaml
  hack/test-go.sh
Labels: approved, lgtm, tide/merge-method-squash

#1752 Vault secret manager: Add request logging
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/middleware.go
Labels: approved, lgtm

#1754 Revert "Revert "test-images-distributor: no distribution to api.ci""
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#1753 Vault secret collection manager: Add backend for Deletion
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/main_test.go
  pkg/vaultclient/vaultclient.go
  pkg/vaultclient/vaultclient_test.go
Labels: approved, lgtm

#1755 Ignore ocp/builder constraint in unpromoted configs
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_OCP_builder_pruning_happens.yaml
Labels: approved, lgtm

#1757 ci-secret-generator: minor fixes
  cmd/ci-secret-generator/README.md
  cmd/ci-secret-generator/main.go
  pkg/bitwarden/cli.go
Labels: approved, lgtm

#1756 Vault secret manager: Add frontend for deletions
  Makefile
  cmd/vault-secret-collection-manager/index.template.html
  cmd/vault-secret-collection-manager/index.ts
  cmd/vault-secret-collection-manager/style.css
  cmd/vault-secret-collection-manager/tsconfig.json
Labels: approved, lgtm

#1762 hack: add a no-op script to pass test
  hack/check-test-infra-version.sh
Labels: approved, lgtm

#1758 Secret collection manager: Add instrumentation
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/middleware.go
Labels: approved, lgtm

#1765 make: use dummy data for front-end without a compiler
  Makefile
  hack/compile-typescript.sh
  hack/test-go.sh
Labels: approved, lgtm

#1767 ci-operator: really do verbose logging
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1768 ci-operator: default both timeout and grace period
  pkg/steps/multi_stage.go
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#1769 hack: check vendor vs ci-chat-bot, too
  hack/check-test-infra-version.sh
Labels: approved, lgtm

#1766 ci-operator: censor all secret data in sidecar
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/testdata/zz_fixture_TestAddPodUtils.yaml
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#1773 ci-operator: remove support for legacy promotion
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/release/promote.go
Labels: approved, lgtm

#1781 Reduce pod polling from once per second to once per 10s
  pkg/steps/artifacts.go
  pkg/steps/template.go
Labels: approved

#1774 ci-operator: unite the logic for choosing images to promote
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm

#1783 Revert "Merge pull request #1774 from stevekuznetsov/skuznets/unify-promotion-lists"
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm

#1786 CI-Operator: Create immutable secrets to avoid scaling issues
  cmd/ci-operator/main.go
  pkg/util/secret.go
Labels: approved, lgtm

#1789 DPTP-2006 check in the step execution error if the context is cancelled properly
  pkg/steps/run.go
Labels: approved, lgtm

#1748 ci-operator: add support for operator upgrade tests
  cmd/ci-operator/main_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/prowgen/prowgen.go
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
  pkg/steps/project_image.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/simple/e2e_test.go
  test/e2e/simple/optional-operators.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/manifests/bundle.Dockerfile
  test/manifests/metadata/annotations.yaml
Labels: approved, lgtm

#1772 Vault secret collection manager: Add edit members functionality
  cmd/vault-secret-collection-manager/docker-compose.yaml
  cmd/vault-secret-collection-manager/index.template.html
  cmd/vault-secret-collection-manager/index.ts
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/main_test.go
  cmd/vault-secret-collection-manager/style.css
  hack/compile-typescript.sh
  hack/pr-deploy-vault-secret-manager.yaml
  pkg/vaultclient/vaultclient.go
Labels: approved, lgtm, tide/merge-method-squash

#1775 ci-operator: always promote the build cache
  pkg/defaults/defaults.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm

#1793 image-distributor: replace api.ci images with app.ci ones
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#1771 Add the OO_BUNDLE env var to the optional_operators step
  cmd/cvp-trigger/main.go
  pkg/steps/optional_operators.go
  pkg/steps/optional_operators_test.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
Labels: approved, lgtm

#1794 Add watching ctrlruntimeclient wrapper and use it to wait for pods
  cmd/ci-operator/main_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/bundle_source_test.go
  pkg/steps/index_generator_test.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/loggingclient/loggingclient.go
  pkg/steps/multi_stage_test.go
  pkg/steps/output_image_tag_test.go
  pkg/steps/pod_test.go
  pkg/util/watchingclient/client_cache.go
  pkg/util/watchingclient/fake/fake.go
  pkg/util/watchingclient/watchingclient.go
  vendor/k8s.io/client-go/tools/watch/informerwatcher.go
  vendor/k8s.io/client-go/tools/watch/retrywatcher.go
  vendor/k8s.io/client-go/tools/watch/until.go
  vendor/modules.txt
Labels: approved, lgtm

#1795 Revert "ci-operator: add support for operator upgrade tests"
  cmd/ci-operator/main_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/prowgen/prowgen.go
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
  pkg/steps/project_image.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/simple/e2e_test.go
  test/e2e/simple/optional-operators.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/manifests/bundle.Dockerfile
  test/manifests/metadata/annotations.yaml
Labels: approved

#1796 Reuse metav1.ListOptions when watching
  pkg/steps/artifacts.go
Labels: approved, lgtm

#1782 Add vault support to secret bootstrapper
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  cmd/ci-secret-bootstrap/vault.go
  pkg/vaultclient/vaultclient.go
Labels: approved, lgtm

#1790 secretsyncer: tolerate conflicts without polluting logs
  pkg/controller/secretsyncer/secretsyncer.go
Labels: approved, lgtm

#1798 testgrid-config-generator: Store more historical results
  cmd/testgrid-config-generator/main.go
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
Labels: approved, lgtm

#1799 Autoowners: Add support for custom owners{,aliases} filenames
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm

#1792 Reintroduce Build Cache
  cmd/ci-operator-checkconfig/main.go
  cmd/registry-replacer/main.go
  pkg/api/types.go
  pkg/controller/promotionreconciler/reconciler.go
  pkg/defaults/defaults.go
  pkg/steps/input_image_tag.go
  pkg/steps/output_image_tag.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/webreg/webreg.go
Labels: approved, lgtm

#1800 ci-operator: add support for operator upgrade tests
  cmd/ci-operator/main_test.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/prowgen/prowgen.go
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
  pkg/steps/multi_stage.go
  pkg/steps/project_image.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/simple/e2e_test.go
  test/e2e/simple/optional-operators.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/manifests/bundle.Dockerfile
  test/manifests/metadata/annotations.yaml
Labels: approved, lgtm

#1777 ci-operator: allow overriding registry for promotions
  cmd/ci-operator-checkconfig/main.go
  pkg/api/types.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1805 Iterate through pods during multi-stage delete
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1806 ci-operator: allow opting out of build cache promotion
  pkg/api/types.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm

#1803 ci-operator: label digest of image we built on top of
  pkg/steps/bundle_source.go
  pkg/steps/git_source.go
  pkg/steps/index_generator.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#1802 multi_stage: update PATH for cli using entrypoint-wrapper
  cmd/entrypoint-wrapper/main.go
  test/entrypoint-wrapper-integration.sh
Labels: approved, lgtm

#1807 multi_stage: stop setting path in multi_stage.go
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1809 ci-operator: correctly mount source volumes
  pkg/steps/project_image.go
  pkg/steps/project_image_test.go
Labels: approved, lgtm

#1812 ci-operator: allow loading cache field
  pkg/api/types.go
Labels: approved, lgtm

#1804 Conform to the new `secretutil` semantics
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  cmd/ci-secret-generator/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/cli_test.go
  pkg/secrets/censor.go
  pkg/secrets/censor_test.go
Labels: approved, lgtm

#1811 Clean up root image tech-debt
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/validation/config.go
Labels: approved, lgtm

#1810 remove ipi-deprovision tool and its related image
  cmd/ipi-deprovision/ipi-deprovision.sh
  images/ipi-deprovision/Dockerfile
  images/ipi-deprovision/azure-cli.repo
  images/ipi-deprovision/google-cloud-sdk.repo
Labels: approved, lgtm

#1776 [DPTP-2057] multi_stage: write commands.sh to configmap
  pkg/api/types.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/multi-stage/config.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#1808 ci-operator: optionally use build cache for the root
  cmd/ci-operator/main.go
  pkg/api/helper/imageextraction.go
  pkg/api/helper/imageextraction_test.go
  pkg/api/metadata.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/steps/source.go
Labels: approved, lgtm

#1814 Stop retries in promotion
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
Labels: approved, lgtm

#1816 Revert "Stop retries in promotion"
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
Labels: approved, lgtm

#1815 ci-operator: make the cache work
  pkg/defaults/defaults.go
Labels: approved, lgtm

#1819 pj-rehearse: copy custom config to refs
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs_with_custom_config.yaml
Labels: approved, lgtm

#1818 DPTP-1996 Add cluster profile for the second AWS
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_aws_2_cluster_profile.yaml
  pkg/validation/test.go
Labels: approved, lgtm

#1822 ci-operator: show timestamps on build log lines
  pkg/steps/artifacts.go
Labels: approved, lgtm

#1820 ci-operator: set higher build loglevel
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
Labels: approved, lgtm

#1817 Fix the line breaks of the command in promotion pod
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
Labels: approved, lgtm

#1821 test: add index content test for optional operator e2e
  test/e2e/simple/e2e_test.go
  test/e2e/simple/optional-operators.yaml
Labels: approved, lgtm

#1823 Wait for pod deletion during cleanup
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1825 ci-operator: stop censoring SA secrets
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1813 ci-operator: initialize a more intelligent logger
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/secretrecordingclient/client.go
  vendor/github.com/sirupsen/logrus/hooks/writer/README.md
  vendor/github.com/sirupsen/logrus/hooks/writer/writer.go
  vendor/modules.txt
Labels: approved, lgtm

#1824 Vault subpath proxy: Verify keys to be valid kube secret keys
  cmd/vault-subpath-proxy/kv_key_validator.go
  cmd/vault-subpath-proxy/main.go
  cmd/vault-subpath-proxy/main_test.go
  pkg/api/vault/vault.go
Labels: approved, lgtm

#1828 Revert "Merge pull request #1813 from stevekuznetsov/skuznets/logrusu…
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/secretrecordingclient/client.go
  vendor/github.com/sirupsen/logrus/hooks/writer/README.md
  vendor/github.com/sirupsen/logrus/hooks/writer/writer.go
  vendor/modules.txt
Labels: approved, lgtm

#1827 ci-operator: create logfile
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/steps/secretrecordingclient/client.go
  vendor/github.com/sirupsen/logrus/hooks/writer/README.md
  vendor/github.com/sirupsen/logrus/hooks/writer/writer.go
  vendor/modules.txt
Labels: approved, lgtm

#1829 ci-operator: use logrus in main.go
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1832 ci-operator: use logrus everywhere
  pkg/api/job_spec.go
  pkg/api/parameters.go
  pkg/bitwarden/cli_test.go
  pkg/defaults/defaults.go
  pkg/lease/client.go
  pkg/load/load.go
  pkg/prowgen/prowgen_test.go
  pkg/release/candidate/client.go
  pkg/release/official/client.go
  pkg/release/prerelease/client.go
  pkg/steps/artifacts.go
  pkg/steps/bundle_source.go
  pkg/steps/input_image_tag.go
  pkg/steps/lease.go
  pkg/steps/multi_stage.go
  pkg/steps/output_image_tag.go
  pkg/steps/pod.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/write_params.go
  test/e2e/lease/e2e_test.go
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#1833 Cleanup registry code
  pkg/registry/graph.go
Labels: approved, lgtm

#1831 rehearse: discover periodics affected by step registry changes
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
  pkg/config/jobs.go
  pkg/config/load.go
  pkg/diffs/diffs.go
  pkg/registry/graph.go
  pkg/rehearse/jobs.go
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm, tide/merge-method-squash
