Repository openshift/ci-tools, pull requests merged in 2021-12, with the labels that each got.

#2541 job-trigger-cm: fix options
  cmd/job-trigger-controller-manager/main.go
Labels: approved, lgtm

#2543 job-trigger-cm: code structure refactor
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case__prowjob_already_exists__no_updates.yaml
Labels: approved, lgtm

#2545 double standard deviation for aggregated disruption mean test
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#2547 refactor the disruption aggregation to be easier to extend
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#2498 add cluster profile for multizone vSphere CI pool
  pkg/api/types.go
  pkg/prowgen/podspec.go
  pkg/validation/test.go
Labels: approved, lgtm

#2548 add disruption P95 cap
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatorlib/disruption.go
Labels: approved, lgtm

#2546 Note /validate-backports in commit validation messages
  cmd/backport-verifier/server.go
  cmd/backport-verifier/server_test.go
Labels: approved, lgtm

#2550 Update the test-infra vendors
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/flagutil/jira.go
  vendor/k8s.io/test-infra/prow/jira/jira.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/label/label.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/k8s.io/test-infra/prow/plugins/releasenote/releasenote.go
  vendor/modules.txt
Labels: approved, lgtm

#2554 resolver: base images only conflict when different
  pkg/api/config.go
  pkg/api/config_test.go
Labels: approved, lgtm

#2556 add aggregated disruption latch for zero-disruption job percentiles
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/disruption_stats.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go
Labels: approved, lgtm

#2552 add option to skip disruption evaluation
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved

#2551 Cluster onboarding: Automate populating configMaps
  cmd/cluster-init/main.go
  cmd/cluster-init/update_prow_plugin_config.go
  cmd/cluster-init/update_prow_plugin_config_test.go
  test/integration/cluster-init/create/expected/core-services/prow/02_config/_plugins.yaml
  test/integration/cluster-init/create/input/core-services/prow/02_config/_plugins.yaml
  test/integration/cluster-init/update/expected/core-services/prow/02_config/_plugins.yaml
  test/integration/cluster-init/update/input/core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#2530 Generate cloud label on Prow jobs
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  pkg/api/constant.go
  pkg/api/types.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/prowgen/jobbase.go
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_multi_stage_test_with_cluster_profile.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
Labels: approved, lgtm

#2557 Claim: support labels for pool selection
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/steps/utils/clusterpool.go
  pkg/steps/utils/clusterpool_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#2549 dispatch: remove duplicated flags in the test script
  hack/run-prow-job-dispatcher.sh
Labels: approved, lgtm

#2559 report failure summaries for jobs that dont' have enough attempts
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go
Labels: approved, lgtm

#2558 Renaming cluster_profile for Alibaba to alibabacloud
  cmd/repo-init/api.go
  cmd/repo-init/main.go
  pkg/api/types.go
  pkg/prowgen/jobbase_test.go
  pkg/prowgen/podspec.go
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftAnsibleClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftAnsibleCustomClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerCustomTestImageClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerUPIClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_multi_stage_test_with_cluster_profile.yaml
  pkg/validation/test.go
Labels: approved, lgtm

#2524 Apply a condition when all jobs are finished in the pjstatussyncer controller
  pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go
  pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer_test.go
  pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_job_is_still_running.yaml
  pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_previous_condition_exists.yaml
Labels: approved, lgtm

#2555 [DPTP-2650]Dispatch jobs to the e2e cloud
  cmd/prow-job-dispatcher/main.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm

#2564 [payload-testing-prow-plugin] Include aggregated job count information in PRPQR creation
  cmd/payload-testing-prow-plugin/rcjobresolver_test.go
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
  pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml
  pkg/api/pullrequestpayloadqualification/v1/types.go
  pkg/release/config/client.go
Labels: approved, lgtm

#2565 prowgen: hash-spread @daily periodics
  pkg/prowgen/prowgen.go
Labels: approved, lgtm

#2563 cluster-init: updateClusterDisplay
  cmd/cluster-init/main.go
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/create/input/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/input/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#2560 Azure mag cluster profile
  pkg/api/types.go
  pkg/prowgen/podspec.go
  pkg/validation/test.go
Labels: approved, lgtm

#2566 skip disrupt tests
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Labels: approved, lgtm

#2568 sanitize: keep jobs from the same PR on the same cluster
  pkg/dispatcher/config.go
Labels: approved, lgtm

#2561 [DPTP-2635]cluster-display: add endpont for clusters
  Makefile
  cmd/ci-operator/main.go
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
  pkg/api/domain.go
Labels: approved, lgtm

#2569 prowgen: stop tolerating changes to `optional` fields
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
Labels: approved, lgtm

#2570 Honor semver when comparing clone target/source
  pkg/backporter/backporter.go
  pkg/backporter/backporter_test.go
Labels: approved, lgtm

#2572 Write a README for autoconfigbrancher
  cmd/autoconfigbrancher/README.md
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm, do-not-merge/hold

#2574 autoconfigbrancher: use a permanent link in README
  cmd/autoconfigbrancher/README.md
Labels: approved, lgtm

#2578 Share ReleaseController's config
  cmd/promoted-image-governor/main.go
  cmd/promoted-image-governor/main_test.go
  cmd/testgrid-config-generator/main.go
  pkg/release/config/client.go
  pkg/release/config/config.go
Labels: approved, lgtm

#2576 Add aggregating job results to testgrid
  cmd/testgrid-config-generator/main.go
  pkg/release/config/client.go
  pkg/release/config/config.go
  test/integration/testgrid-config-generator/config/_allow-list.yaml
  test/integration/testgrid-config-generator/config/jobs/org/repo/org-repo-master-periodics.yaml
  test/integration/testgrid-config-generator/config/release/ocp-4.10.json
  test/integration/testgrid-config-generator/expected/groups.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.10-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.10-informing.yaml
Labels: approved, tide/merge-method-squash, lgtm

#2579 Updating auto-include logic for OpenStack jobs
  cmd/testgrid-config-generator/main.go
Labels: approved, lgtm

#2581 [DPTP-2660]payload-testing-prow-plugin: format errors
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
Labels: approved, lgtm

#2573 handle missing history for aggregated disruption
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#2582 Create the Jobs table used by job-run-aggregation
  cmd/job-run-aggregator/README.md
  pkg/jobrunaggregator/cmd.go
  pkg/jobrunaggregator/jobrunaggregatorapi/bypass_linter.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go
  pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go
  pkg/jobrunaggregator/releasebigqueryloader/table_creator.go
  pkg/jobrunaggregator/tablescreator/cmd.go
  pkg/jobrunaggregator/tablescreator/table_creator.go
Labels: approved, lgtm
