Repository openshift/ci-tools, pull requests merged in 2021-04, with the labels that each got.

#1834 ci-operator: reduce log spam
  cmd/ci-operator/main.go
  pkg/steps/input_image_tag.go
  pkg/steps/lease.go
  pkg/steps/multi_stage.go
  pkg/steps/template.go
  test/e2e/framework/ci-operator.go
  test/e2e/lease/e2e_test.go
  test/e2e/multi-stage/e2e_test.go
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#1841 entrypoint-wrapper: label secret to be ignored in censor
  cmd/entrypoint-wrapper/main.go
  test/entrypoint-wrapper-integration.sh
Labels: approved, lgtm

#1836 ci-operator: format user output and debug log differently
  cmd/ci-operator/main.go
  vendor/github.com/sirupsen/logrus/hooks/writer/README.md
  vendor/github.com/sirupsen/logrus/hooks/writer/writer.go
  vendor/modules.txt
Labels: approved, lgtm

#1842 Minor Output Tweaks
  pkg/results/report.go
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
Labels: approved, lgtm

#1846 rehearse: refresh integration tests
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
Labels: approved, lgtm

#1779 ci-secret-generator: support Vault
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
  cmd/vault-secret-collection-manager/main_test.go
  pkg/secrets/bitwarden.go
  pkg/secrets/client.go
  pkg/secrets/flags.go
  pkg/secrets/vault.go
  test/e2e/secret-generator/bootstrap.yaml
  test/e2e/secret-generator/e2e_test.go
  test/e2e/secret-generator/generator.yaml
  test/e2e/secret-generator/kubeconfig
Labels: approved, lgtm

#1848 rehearse: do not create imports on app.ci
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/main_test.go
Labels: approved, lgtm

#1830 CI-Secret-Bootstrap: Sync user secrets from Vault
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/api/vault/vault.go
  pkg/bitwarden/fake.go
  pkg/secrets/bitwarden.go
  pkg/secrets/client.go
  pkg/secrets/vault.go
Labels: approved, lgtm

#1847 rehearse: properly deduplicate rehearsed periodics
  cmd/generate-registry-metadata/main_test.go
  cmd/pj-rehearse/main.go
  pkg/load/load_test.go
  test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
  test/multistage-registry/registry/ipi-changed/OWNERS
  test/multistage-registry/registry/ipi-changed/ipi-changed-workflow.metadata.json
  test/multistage-registry/registry/ipi-changed/ipi-changed-workflow.yaml
  test/multistage-registry/registry2/ipi-changed/OWNERS
  test/multistage-registry/registry2/ipi-changed/ipi-changed-workflow.metadata.json
  test/multistage-registry/registry2/ipi-changed/ipi-changed-workflow.yaml
Labels: approved, lgtm

#1838 Expose tests.cluster_claim in ci-op's configuration
  hack/generate-ci-op-reference.sh
  pkg/api/config.go
  pkg/api/types.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1851 Vault subpath proxy: Fix secret key validation
  cmd/vault-subpath-proxy/kv_key_validator.go
  cmd/vault-subpath-proxy/main_test.go
Labels: approved, lgtm

#1845 Expose tests.cluster in ci-op's config
  cmd/prow-job-dispatcher/main_test.go
  pkg/api/constant.go
  pkg/api/domain.go
  pkg/api/types.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label.yaml
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1852 ci-operator: update the label set we use on Pods
  cmd/ci-operator/main.go
  pkg/api/job_spec.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
  pkg/steps/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
Labels: approved, lgtm

#1853 ci-operator: use compact censoring volume names
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm

#1856 Bumper: Bump Makefile as well
  cmd/autobumper/main.go
Labels: approved, lgtm

#1843 [DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist
  cmd/ci-secret-bootstrap/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/fake.go
  pkg/secrets/client.go
  pkg/secrets/vault.go
Labels: approved, lgtm

#1854 ci-operator: don't record SA namespaces for censoring
  pkg/steps/secretrecordingclient/client.go
Labels: approved, lgtm

#1859 Revert "[DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist"
  cmd/ci-secret-bootstrap/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/fake.go
  pkg/secrets/client.go
  pkg/secrets/vault.go
Labels: approved, lgtm

#1857 Add support for Vault Kubernetes auth to secret flag and fix validation
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  cmd/ci-secret-generator/main.go
  pkg/secrets/flags.go
  pkg/secrets/flags_test.go
  pkg/vaultclient/vaultclient.go
Labels: approved, lgtm

#1860 Vaultclient: Send jwt argument as string not as []byte
  pkg/vaultclient/vaultclient.go
Labels: approved, lgtm

#1835 Revert "CI-Operator: Stop writing step graph out"
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/api/env.go
  pkg/steps/secretrecordingclient/client.go
  test/e2e/multi-stage/config.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#1861 Support the cluster field for presubmits and periodics
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_periodic.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_postsubmit.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_presubmit.yaml
Labels: approved, lgtm

#1863 Revert "Revert "[DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist""
  cmd/ci-secret-bootstrap/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/fake.go
  pkg/secrets/client.go
  pkg/secrets/vault.go
Labels: approved, lgtm

#1864 Revert "Revert "Revert "[DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist"""
  cmd/ci-secret-bootstrap/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/fake.go
  pkg/secrets/client.go
  pkg/secrets/vault.go
Labels: approved

#1862 Support cluster_claim in container tests
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/testdata/zz_fixture_envTestGetPodObjectMounts_with_cluster_claim.yaml
  pkg/steps/testdata/zz_fixture_mountsTestGetPodObjectMounts_with_cluster_claim.yaml
  pkg/steps/testdata/zz_fixture_volumesTestGetPodObjectMounts_with_cluster_claim.yaml
Labels: approved, lgtm

#1866 [DPTP-2094] ci-secret-bootstrap: validate if the given items/field/attachments exist
  cmd/ci-secret-bootstrap/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/fake.go
  pkg/secrets/client.go
  pkg/secrets/vault.go
Labels: approved, lgtm

#1867 Fix the graph issues from a cluster_claim step
  cmd/ci-operator/main.go
  pkg/api/graph.go
  pkg/defaults/defaults.go
  pkg/steps/cluster_claim.go
  pkg/steps/multi_stage.go
  pkg/steps/pod.go
Labels: approved, lgtm

#1868 Fix the condition of ClusterClaim being running
  pkg/steps/cluster_claim.go
  pkg/steps/cluster_claim_test.go
Labels: approved, lgtm

#1869 Determinize Prow config: Shard prow config
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
  pkg/config/release.go
Labels: approved, lgtm

#1870 Fix the identifier of clusterClaimLink
  pkg/api/graph.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/cluster_claim.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
Labels: approved, lgtm

#1872 Add cluster profile for the second GCP account
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_gcp_2_cluster_profile.yaml
  pkg/validation/test.go
Labels: approved, lgtm

#1873 prowgen: incldue ci-pull-credentials for tests with cluster-claim
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_cluster_claim.yaml
Labels: approved, lgtm

#1871 Improve the logs for the cluster_claim step
  pkg/defaults/defaults_test.go
  pkg/steps/cluster_claim.go
Labels: approved, lgtm

#1876 fix prowgen to generate cluster profile for the 2nd GCP account
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_gcp_2_cluster_profile.yaml
Labels: approved, lgtm

#1840 prowgen: generate the hive-kubeconfig arg
  pkg/api/constant.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_cluster_claim.yaml
Labels: approved, lgtm

#1877 change the lease type for the second GCP account
  pkg/api/types.go
Labels: approved, lgtm

#1879 DPTP-2145 allow step run to gather the context cancelation errors but don't report them
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/steps/run.go
Labels: approved, lgtm

#1883 ci-operator: disable caching on empty input SHAs
  cmd/ci-operator/main.go
Labels: approved, lgtm

#1880 HOSTEDCP-103: Add cluster profile for HyperShift
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePodSpecMultiStage_hypershift_cluster_profile.yaml
  pkg/validation/test.go
Labels: approved, lgtm

#1885 Replace the dots in secret name when used as volume name
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm

#1886 Bump test-infra to 11466b54a34c
  cmd/cvp-trigger/main.go
  cmd/cvp-trigger/main_test.go
  cmd/determinize-prow-config/main.go
  cmd/dptp-controller-manager/main.go
  cmd/lensserver/main.go
  cmd/private-prow-configs-mirror/main.go
  cmd/repo-init/main.go
  cmd/slack-bot/main.go
  cmd/template-deprecator/main.go
  go.mod
  go.sum
  pkg/config/release.go
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  vendor/github.com/GoogleCloudPlatform/testgrid/config/config.go
  vendor/github.com/GoogleCloudPlatform/testgrid/metadata/junit/junit.go
  vendor/github.com/GoogleCloudPlatform/testgrid/pb/config/config.pb.go
  vendor/github.com/GoogleCloudPlatform/testgrid/pb/config/config.proto
  vendor/k8s.io/test-infra/experiment/image-bumper/bumper/bumper.go
  vendor/k8s.io/test-infra/ghproxy/ghcache/ghcache.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghmetrics.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/bugzilla/fake.go
  vendor/k8s.io/test-infra/prow/bugzilla/types.go
  vendor/k8s.io/test-infra/prow/cmd/generic-autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/config/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/agent.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/deck/jobs/jobs.go
  vendor/k8s.io/test-infra/prow/flagutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/flagutil/config/BUILD.bazel
  vendor/k8s.io/test-infra/prow/flagutil/config/config.go
  vendor/k8s.io/test-infra/prow/flagutil/github.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/report/BUILD.bazel
  vendor/k8s.io/test-infra/prow/github/report/report.go
  vendor/k8s.io/test-infra/prow/kube/constants.go
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/owners.go
  vendor/k8s.io/test-infra/prow/plugins/blockade/blockade.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/bugzilla.go
  vendor/k8s.io/test-infra/prow/plugins/buildifier/buildifier.go
  vendor/k8s.io/test-infra/prow/plugins/shrug/shrug.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/repoowners/repoowners.go
  vendor/k8s.io/test-infra/prow/sidecar/BUILD.bazel
  vendor/k8s.io/test-infra/prow/sidecar/censor.go
  vendor/k8s.io/test-infra/prow/sidecar/options.go
  vendor/k8s.io/test-infra/prow/spyglass/BUILD.bazel
  vendor/k8s.io/test-infra/prow/spyglass/README.md
  vendor/k8s.io/test-infra/prow/spyglass/lenses/BUILD.bazel
  vendor/k8s.io/test-infra/prow/spyglass/podlogartifact.go
  vendor/k8s.io/test-infra/prow/spyglass/storageartifact.go
  vendor/modules.txt
Labels: approved, lgtm

#1888 Fix a typo: RuntimeObjectIgnoreRvTypeMeta
  cmd/ci-secret-bootstrap/main_test.go
  pkg/controller/imagepusher/imagepusher_test.go
  pkg/controller/registrysyncer/registrysyncer_test.go
  pkg/controller/util/secret_test.go
  pkg/steps/cluster_claim_test.go
  pkg/steps/output_image_tag_test.go
  pkg/testhelper/testhelper.go
  pkg/testhelper/testhelper_test.go
Labels: approved, lgtm

#1887 Secret-bootstrap: Add option to base64-decode
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/api/secretbootstrap/secretboostrap.go
Labels: approved, lgtm

#1889 Vault secret collection manager: Add Kubernetes auth support
  cmd/vault-secret-collection-manager/main.go
Labels: approved, lgtm

#1878 pod-scaler: a server for automated resource requests
  cmd/pod-scaler/main.go
  cmd/pod-scaler/producer.go
  cmd/pod-scaler/producer_test.go
  cmd/pod-scaler/storage.go
  cmd/pod-scaler/types.go
  go.mod
  go.sum
  images/pod-scaler/Dockerfile
  pkg/steps/template.go
  vendor/github.com/openhistogram/circonusllhist/LICENSE
  vendor/github.com/openhistogram/circonusllhist/LICENSE.OpenHistogram
  vendor/github.com/openhistogram/circonusllhist/README.md
  vendor/github.com/openhistogram/circonusllhist/circonusllhist.go
  vendor/github.com/openhistogram/circonusllhist/go.mod
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/doc.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route.go
  vendor/github.com/openshift/client-go/route/clientset/versioned/typed/route/v1/route_client.go
  vendor/modules.txt
Labels: approved, lgtm

#1891 pod-scaler: allow kubeconfig through env
  cmd/pod-scaler/main.go
Labels: approved, lgtm

#1890 Configresolver: Remove unused prow config flags
  cmd/ci-operator-configresolver/main.go
  hack/lib/integration.sh
  hack/pr-deploy.yaml
  hack/run-step-registry.sh
  test/e2e/framework/framework.go
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#1892 Bump test-infra to 0512a33e0336
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/flagutil/config/config.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/plugins/releasenote/releasenote.go
  vendor/k8s.io/test-infra/prow/plugins/updateconfig/updateconfig.go
  vendor/modules.txt
Labels: approved, lgtm

#1893 Switching to base64.StdEncoding.DecodeString() for decoding binary file content
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm

#1894 Secret client: Handle errors in HasItem check
  cmd/ci-secret-bootstrap/main.go
  pkg/bitwarden/bitwarden.go
  pkg/bitwarden/cli.go
  pkg/bitwarden/fake.go
  pkg/secrets/client.go
  pkg/secrets/vault.go
Labels: approved, lgtm

#1896 dptp-cm: bump GH API budget 300->600
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#1897 autoowners: allow placing OWNERS files in other dirs
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
  cmd/autoowners/testdata/test3/ci-operator/jobs/kubevirt/hostpath-provisioner/.gitignore
  cmd/autoowners/testdata/test3/ci-operator/jobs/kubevirt/kubevirt/.gitignore
  cmd/autoowners/testdata/test3/ci-operator/jobs/kubevirt/project-infra/.gitignore
  cmd/autoowners/testdata/test3/core-services/prow/02_config/kubevirt/kubevirt/.gitignore
Labels: approved, lgtm

#1899 Secret collection manager: Fix cleanup on delete
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/main_test.go
  pkg/vaultclient/vaultclient.go
  pkg/vaultclient/vaultclient_test.go
Labels: approved, lgtm

#1901 Vault secret collection manager: Show collection through index file
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/main_test.go
  pkg/vaultclient/vaultclient.go
Labels: approved, lgtm

#1900 Bump test-infra to 28747eb818b8
  go.mod
  go.sum
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghpath.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/modules.txt
Labels: approved, lgtm

#1904 Vault accessory: Use testing.T instead of testhelper.T
  cmd/ci-secret-generator/main_test.go
  cmd/vault-secret-collection-manager/main_test.go
  cmd/vault-subpath-proxy/main_test.go
  pkg/testhelper/accessory.go
  pkg/testhelper/vault.go
  pkg/vaultclient/vaultclient.go
  pkg/vaultclient/vaultclient_test.go
  test/e2e/framework/test.go
  test/e2e/secret-generator/e2e_test.go
Labels: approved, lgtm

#1903 validate-test-infra: emit all failures on first pass
  hack/check-test-infra-version.sh
Labels: approved, lgtm

#1881 ci-operator multi-stage: truncate duration message
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#1895 pod-scaler: add labels to Build Pods via admission
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/main.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_not_a_pod.yaml
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_that_has_no_labels.yaml
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_with_labels.yaml
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_not_associated_with_a_build.yaml
  vendor/github.com/openshift/client-go/build/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/doc.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_build_client.go
  vendor/github.com/openshift/client-go/build/clientset/versioned/typed/build/v1/fake/fake_buildconfig.go
  vendor/modules.txt
Labels: approved, lgtm

#1908 pod-scaler: use our own flag set
  cmd/pod-scaler/main.go
Labels: approved

#1906 Support buildArgs for image building
  pkg/api/types.go
  pkg/steps/bundle_source.go
  pkg/steps/git_source.go
  pkg/steps/index_generator.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/testdata/zz_fixture_TestBuildFromSource.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#1909 ci-operator: label release pods with their release name
  pkg/steps/pod.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/release_images.go
  pkg/steps/source.go
Labels: approved, lgtm

#1907 applyconfig: support ignore-file
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
Labels: approved, lgtm

#1913 pod-scaler: use standalone webhook handlers
  cmd/pod-scaler/admission.go
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go
Labels: approved, lgtm

#1914 testhelper: attempt to make global map global
  pkg/testhelper/accessory.go
Labels: approved, lgtm

#1910 Add CLI to get ldap IDs from Owners file
  cmd/ldap-users-from-github-owners-files/README.md
  cmd/ldap-users-from-github-owners-files/main.go
  cmd/ldap-users-from-github-owners-files/main_test.go
  cmd/ldap-users-from-github-owners-files/testdata/ldapsearch.out
  cmd/ldap-users-from-github-owners-files/testdata/test-repo/OWNERS
  cmd/ldap-users-from-github-owners-files/testdata/test-repo/OWNERS_ALIASES
Labels: approved, lgtm

#1911 pod-scaler: store data for three types of Pods
  cmd/dptp-controller-manager/main.go
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/main.go
  cmd/pod-scaler/producer.go
  cmd/pod-scaler/producer_test.go
  cmd/pod-scaler/types.go
  cmd/slack-bot/main.go
  go.mod
  go.sum
  pkg/jobconfig/files.go
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
  test/integration/pj-rehearse/expected.yaml
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/flagutil/instrumentation.go
  vendor/k8s.io/test-infra/prow/kube/prowjob.go
  vendor/k8s.io/test-infra/prow/pjutil/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pjutil/pprof.go
  vendor/k8s.io/test-infra/prow/pjutil/pprof/BUILD.bazel
  vendor/k8s.io/test-infra/prow/pjutil/pprof/pprof.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/sidecar/BUILD.bazel
  vendor/k8s.io/test-infra/prow/sidecar/run.go
  vendor/modules.txt
Labels: approved, lgtm

#1917 test/e2e: log ports we acquire for debugging
  pkg/testhelper/accessory.go
Labels: approved, lgtm

#1919 pod-scaler: expect serving cert and key for admission
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/main.go
Labels: approved, lgtm

#1875 Use gs-prefixed link rather than gcs in testgrid-generator
  cmd/testgrid-config-generator/main.go
  test/integration/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.3-broken.yaml
Labels: approved, lgtm

#1905 [DPTP-2119] steps: clean up cluster claims when test ends
  pkg/api/graph.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/cluster_claim.go
  pkg/steps/cluster_claim_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
Labels: approved, lgtm, tide/merge-method-squash

#1920 pod-scaler: log more in admission
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/main.go
Labels: approved, lgtm

#1882 prowgen: add release-informing job type
  pkg/api/types.go
  pkg/jobconfig/files.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_release_controller_job.yaml
  pkg/validation/test.go
  pkg/validation/test_test.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
Labels: approved, lgtm

#1916 Vaultclient: Refresh token when using kubernetes auth
  cmd/vault-secret-collection-manager/main.go
  pkg/vaultclient/vaultclient.go
Labels: approved, lgtm

#1922 ci-operator: label namespaces for auto-scaling pods
  cmd/ci-operator/main.go
  pkg/api/constant.go
Labels: approved, lgtm

#1925 ci-operator: better report error
  pkg/results/report.go
Labels: approved, lgtm

#1927 pkg/release/official: Allow explicit version choices
  pkg/defaults/defaults_test.go
  pkg/release/official/client.go
  pkg/release/official/client_test.go
Labels: approved, lgtm

#1928 ci-op: patch ist instead of update to override conflicts
  pkg/steps/output_image_tag.go
Labels: approved, lgtm

#1923 DPTP-2012: Best effort/timeout and trap/grace period validations.
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/rehearse/jobs_test.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  test/e2e/multi-stage/best-effort.yaml
  test/e2e/simple/optional-operators.yaml
  test/multistage-registry/best-effort-without-timeout/best-effort-without-timeout.sh
  test/multistage-registry/best-effort-without-timeout/best-effort-without-timeout.yaml
  test/multistage-registry/trap-without-graceperiod/trap-without-grace-period-commands.sh
  test/multistage-registry/trap-without-graceperiod/trap-without-grace-period-ref.yaml
Labels: approved, lgtm, tide/merge-method-squash

#1929 rehearsal: label the context we're rehearsing
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs_with_custom_config.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#1915 [DPTP-2155] Skip item existance validation that exist in ci-secret-generator configuration
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
  pkg/api/secretgenerator/secretgenerator.go
  pkg/api/secretgenerator/secretgenerator_test.go
  pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/no_parameters.yaml
  pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/single_parameter.yaml
  pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/single_parameter_with_multiple_values.yaml
  pkg/api/secretgenerator/testdata/TestLoadConfigFromPath/two_parameters_with_multiple_values.yaml
  pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_no_parameters.yaml
  pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_single_parameter.yaml
  pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_single_parameter_with_multiple_values.yaml
  pkg/api/secretgenerator/testdata/zz_fixture_TestLoadConfigFromPath_two_parameters_with_multiple_values.yaml
Labels: approved, lgtm

#1924 Shard tide merge method
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
  go.mod
  go.sum
  pkg/steps/artifacts.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghpath.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/clonerefs/run.go
  vendor/k8s.io/test-infra/prow/cmd/generic-autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/config/BUILD.bazel
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
  vendor/k8s.io/test-infra/prow/flagutil/github.go
  vendor/k8s.io/test-infra/prow/gcsupload/run.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/initupload/run.go
  vendor/k8s.io/test-infra/prow/plugins/golint/suggestion/golint_suggestion.go
  vendor/k8s.io/test-infra/prow/plugins/plugins.go
  vendor/k8s.io/test-infra/prow/plugins/yuks/yuks.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/k8s.io/test-infra/prow/sidecar/censor.go
  vendor/k8s.io/test-infra/prow/sidecar/run.go
  vendor/k8s.io/test-infra/prow/simplifypath/simplify.go
  vendor/k8s.io/test-infra/prow/spyglass/artifacts.go
  vendor/k8s.io/test-infra/prow/spyglass/lenses/common/common.go
  vendor/k8s.io/test-infra/prow/spyglass/storageartifact_fetcher.go
  vendor/modules.txt
Labels: approved, lgtm

#1930 Revert "Shard tide merge method"
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
Labels: approved

#1931 ci-op: retry on conflicts when we patch ists
  pkg/steps/output_image_tag.go
Labels: approved, lgtm

#1932 ci-op: swallow AlreadyExists errors on upserting ists
  pkg/steps/output_image_tag.go
Labels: approved, lgtm

#1933 Re-add tide merge method sharding
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
Labels: approved, lgtm

#1937 Disable tide merge method sharding
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
Labels: approved, lgtm

#1934 Use the trimLabels function to trim labels
  pkg/steps/cluster_claim.go
Labels: approved, lgtm

#1936 pod-scaler: correctly format output logs
  cmd/pod-scaler/main.go
Labels: approved, lgtm

#1942 ci-secret-bootstrap: log what we're doing w.r.t. vault
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm

#1940 Delete autobumper, we use the upstream one now
  cmd/autobumper/main.go
  images/autobumper/Dockerfile
Labels: approved, lgtm

#1935 Bump test infra to a8de1a965bad0faf5b30e300753111b44d84385d
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/cmd/generic-autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/config/agent.go
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/flagutil/config/config.go
  vendor/k8s.io/test-infra/prow/io/providers/providers.go
  vendor/k8s.io/test-infra/prow/spyglass/artifacts.go
  vendor/modules.txt
Labels: approved, lgtm

#1943 Fix ci-secret-bootstrap user sync
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/api/secretbootstrap/secretboostrap_test.go
Labels: approved, lgtm

#1921 pkg/steps/lease: Log acquired leases at info level
  pkg/steps/lease.go
  test/e2e/lease/e2e_test.go
Labels: approved, lgtm

#1941 Add a reason maker: acquiring_cluster_claim
  pkg/steps/cluster_claim.go
Labels: approved, lgtm

#1944 Fix secret-generator validation to still work with vault_dptp_prefix
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
Labels: approved, lgtm

#1946 Revert "Merge pull request #1945 from stevekuznetsov/skuznets/revert-…
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
Labels: approved, lgtm

#1939 Re-Enable tide merge method config sharding
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
Labels: approved, lgtm
