Repository openshift/ci-tools, pull requests merged in 2022-07, with the labels that each got.

#2880 Require workflow use in #forum-testplatform
  cmd/slack-bot/README.md
  cmd/slack-bot/main.go
  hack/local-slack-bot.sh
  pkg/slack/events/helpdesk/helpdesk-message.go
  pkg/slack/events/router/router.go
Labels: approved, tide/merge-method-squash, lgtm

#2886 verify user is non-nil before posting reply
  pkg/slack/events/helpdesk/helpdesk-message.go
Labels: approved, lgtm

#2887 Allow a greater version of b02 than b01
  cmd/sprint-automation/main.go
  cmd/sprint-automation/main_test.go
Labels: approved, lgtm

#2893 dptp-cm: use git-sync
  cmd/ci-operator-configresolver/main.go
  cmd/dptp-controller-manager/main.go
Labels: approved, tide/merge-method-squash, lgtm

#2894 use git-sync in pr-deploy-configresolver
  Makefile
  hack/pr-deploy.yaml
Labels: approved, lgtm

#2895 Support for ARM01 build cluster
  pkg/api/constant.go
Labels: approved, lgtm

#2883 Pod Scaler e2e: reload cache after initial subscribe
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/consumer.go
  cmd/pod-scaler/resources.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add.diff
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add__limits_disabled.diff
  pkg/testhelper/accessory.go
  test/e2e/pod-scaler/run/consumer.go
Labels: approved, tide/merge-method-squash, lgtm

#2897 Refactor code to re-order functions in their related package and files
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage/run.go
  pkg/steps/pod.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/steps/template_test.go
  pkg/util/errors.go
  pkg/util/notifier.go
  pkg/util/pods.go
  pkg/util/pods_test.go
Labels: approved, lgtm

#2899 Update job names list for 4.12 after SDN job rename
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Labels: approved, lgtm

#2896 pkg/registry: correct `retryablehttp` logger
  pkg/registry/server/client.go
Labels: approved, lgtm

#2904 Fix issues found by snyk-deps
  .snyk
Labels: approved, lgtm

#2905 `check-gh-automation`: don't check repos in presubmit if more than 10 have been modified
  cmd/check-gh-automation/main.go
Labels: approved, lgtm

#2869 integration: test kubeconfig upload on interrupt
  test/integration/entrypoint-wrapper.sh
Labels: approved, lgtm

#2907 [pj-rehearse] output the required imagestream tags for each job
  pkg/api/helper/imageextraction.go
  pkg/rehearse/jobs.go
Labels: approved, lgtm

#2906 Fix snyk code scan warnings
  .snyk-ignore
  Makefile
Labels: approved, lgtm

#2908 Create unit tests for helpdesk-message
  pkg/slack/events/helpdesk/helpdesk-message_test.go
  pkg/slack/events/helpdesk/testdata/zz_fixture_TestGetContactedHelpdeskResponse_botId_like_review_workflow.yaml
  pkg/slack/events/helpdesk/testdata/zz_fixture_TestGetContactedHelpdeskResponse_empty_botId.yaml
  pkg/slack/events/helpdesk/testdata/zz_fixture_TestGetContactedHelpdeskResponse_random_botId.yaml
Labels: approved, lgtm

#2911 Observer pods
  pkg/registry/resolver.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/multi_stage/run.go
  pkg/validation/config.go
  pkg/validation/test.go
  test/e2e/observer/artifacts/junit_operator.xml
  test/e2e/observer/boskos.yaml
  test/e2e/observer/config.yaml
  test/e2e/observer/configs/empty
  test/e2e/observer/registry/observer/observer-commands.sh
  test/e2e/observer/registry/observer/observer-observer.yaml
Labels: approved, tide/merge-method-squash, lgtm

#2912 Add OpenStack Operators on Vexxhost cluster profile
  pkg/api/types.go
Labels: approved, lgtm, ok-to-test

#2909 Call out specific failure in e2e TestBuildPodAdmission flakes
  test/e2e/pod-scaler/kubernetes/kubernetes.go
Labels: approved, lgtm

#2913 Better snyk code outputs
  Makefile
Labels: approved, lgtm

#2914 Add oc_sa_create_kubeconfig.sh
  images/ci-secret-generator/Dockerfile
  images/ci-secret-generator/oc_sa_create_kubeconfig.sh
Labels: approved, tide/merge-method-squash, lgtm

#2915 PDB Client: v1beta1 to v1
  cmd/ci-operator/main.go
Labels: approved, lgtm

#2920 ci-secret-generator: add unit tests for executeCommand
  cmd/ci-secret-generator/main_test.go
Labels: approved, lgtm

#2923 `pr-reminder`: extend to the org
  cmd/pr-reminder/README.md
  cmd/pr-reminder/main.go
  cmd/pr-reminder/main_test.go
  hack/local-pr-reminder.sh
  hack/pr-reminder-config.yaml
Labels: approved, tide/merge-method-squash, lgtm, do-not-merge/hold
