Repository openshift/ci-tools, pull requests merged in 2022-03, with the labels that each got.

#2698 ci-operator: some dragons were defeated
  pkg/steps/template.go
Labels: approved, lgtm

#2696 cmd/ci-operator: Trust suite names in writeJUnit
  cmd/ci-operator/main.go
  pkg/steps/run.go
  test/e2e/simple/artifacts/junit_operator.xml
Labels: approved, lgtm

#2699 github-ldap-user-group-creator: manange group/openshift-priv-admins
  cmd/github-ldap-user-group-creator/main.go
  cmd/github-ldap-user-group-creator/main_test.go
Labels: approved, lgtm

#2697 pkg/steps/multi_stage: Add subTests for phase completion
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm

#2702 Do not include sub-tasks in Intake card digest (DPTP-2757)
  cmd/sprint-automation/main.go
Labels: approved, lgtm, ok-to-test

#2701 Fixing prerelease support for multiarch
  pkg/release/prerelease/client.go
  pkg/release/prerelease/client_test.go
Labels: approved, lgtm

#2706 pkg/steps/multi_stage: Log phase result
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#2703 censor access tokens in repo-init
  cmd/repo-init/api.go
Labels: approved, lgtm

#2707 ci-operator: improve error message for invalid `.ci-operator.yaml`
  pkg/defaults/defaults.go
  pkg/validation/config.go
Labels: approved, lgtm

#2709 local-slack-bot: use jira bearer token, and modify certs to work on mac
  hack/local-slack-bot.sh
Labels: approved, lgtm

#2708 Extract sort logic for SelectJobsForChangedRegistry
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, tide/merge-method-squash, lgtm, ok-to-test

#2713 sprint-automation: add created and last updated to the card digests
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#2711 ci-operator-configresolver: remove defunct URLs
  cmd/ci-operator-configresolver/main.go
Labels: approved, lgtm

#2718 Stop managing secrets for the non_app_ci_x86 group
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/create/input/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/input/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#2717 Fix details link for qe-private deck periodic rehearsals
  pkg/rehearse/jobs.go
  test/integration/pj-rehearse/expected.yaml
Labels: approved, tide/merge-method-squash, lgtm

#2712 sprint-automation: add a role digest for the following week
  cmd/sprint-automation/README.md
  cmd/sprint-automation/main.go
  hack/local-sprint-automation.sh
Labels: approved, tide/merge-method-squash, lgtm

#2716 create QE dedicated azure cluster profiles
  pkg/api/types.go
  pkg/prowgen/podspec.go
  pkg/validation/test.go
Labels: approved, lgtm

#2720 return correct ClusterType for QE's cluster profiles
  pkg/api/types.go
Labels: approved, lgtm

#2719 update test-infra
  go.mod
  go.sum
  vendor/k8s.io/test-infra/ghproxy/ghcache/ghcache.go
  vendor/k8s.io/test-infra/ghproxy/ghmetrics/ghmetrics.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/bugzilla/OWNERS
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/flagutil/bugzilla.go
  vendor/k8s.io/test-infra/prow/flagutil/strings.go
  vendor/k8s.io/test-infra/prow/gcsupload/run.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/io/opener.go
  vendor/k8s.io/test-infra/prow/jira/OWNERS
  vendor/k8s.io/test-infra/prow/pjutil/filter.go
  vendor/k8s.io/test-infra/prow/plugins/bugzilla/OWNERS
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/jira/OWNERS
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/k8s.io/test-infra/prow/sidecar/censor.go
  vendor/k8s.io/test-infra/prow/spyglass/BUILD.bazel
  vendor/k8s.io/test-infra/prow/spyglass/api/spyglass.go
  vendor/k8s.io/test-infra/prow/spyglass/podlogartifact.go
  vendor/k8s.io/test-infra/prow/spyglass/storageartifact.go
  vendor/k8s.io/test-infra/prow/spyglass/storageartifact_fetcher.go
  vendor/k8s.io/test-infra/prow/version/metrics.go
  vendor/modules.txt
Labels: approved, tide/merge-method-squash, lgtm

#2721 provide different secrets for QE dedicated cluster profiles
  pkg/api/types.go
  pkg/prowgen/podspec.go
Labels: approved, lgtm

#2723 only provide one secret for QE cluster profiles without configmap
  pkg/prowgen/podspec.go
Labels: approved, lgtm

#2725 Skip step graph tests in aggregation.
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#2715 repo-init: create repo's prow configuration
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  pkg/config/release.go
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/openshift/ci-tools/_prowconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/openshift/cluster-version-operator/_prowconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/other/_prowconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/repo/_prowconfig.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/org/third/_prowconfig.yaml
  test/integration/repo-init/input/core-services/prow/02_config/_config.yaml
  test/integration/repo-init/input/core-services/prow/02_config/openshift/ci-tools/_prowconfig.yaml
  test/integration/repo-init/input/core-services/prow/02_config/openshift/cluster-version-operator/_prowconfig.yaml
Labels: approved, lgtm

#2714 Creating more relevant sorting logic for SelectJobsForChangedRegistry
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, tide/merge-method-squash, lgtm, ok-to-test

#2724 Create QE dedicated AWS cluster profiles
  pkg/api/types.go
  pkg/prowgen/podspec.go
  pkg/validation/test.go
Labels: approved, lgtm

#2727 Create QE dedicated GCP cluster profile "gcp-qe"
  pkg/api/types.go
  pkg/prowgen/podspec.go
  pkg/validation/test.go
Labels: approved, lgtm

#2731 Add Nutanix Cluster Profile
  cmd/repo-init/main.go
  pkg/api/types.go
  pkg/prowgen/podspec.go
  pkg/validation/test.go
Labels: approved, lgtm

#2729 Change retestOrBackoff functionality: Added option enable-on-repo
  cmd/better-retester/main.go
  cmd/better-retester/main_test.go
  cmd/better-retester/retester.go
Labels: approved, lgtm, ok-to-test

#2740 pod-scaler: ignore pods with the `ci-workload-autoscaler.openshift.io/scale`=false annotation
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_marked_with_ignore_annotation.yaml
Labels: approved, lgtm

#2738 Create QE dedicated GCP cluster profile "gcp-qe" (using "SecretVolumeSource")
  pkg/prowgen/podspec.go
Labels: approved, lgtm

#2735 DPTP-2760 Resolve console host url while completing options
  cmd/ci-operator/main.go
  pkg/results/report.go
Labels: approved, lgtm

#2743 Revert "DPTP-2760 Resolve console host url while completing options"
  cmd/ci-operator/main.go
  pkg/results/report.go
Labels: approved, lgtm

#2744 Pod Scaler: decrease the interval for querying
  cmd/pod-scaler/producer.go
Labels: approved, lgtm

#2739 guarantee that `BASETMPDIR` starts with `TMPDIR/openshift/...`
  test/integration/entrypoint-wrapper.sh
Labels: approved, lgtm

#2737 Register AWSOSDMSP ClusterProfile with openshift ci
  cmd/repo-init/api.go
  pkg/api/types.go
  pkg/prowgen/podspec.go
  pkg/validation/test.go
Labels: approved, lgtm
