Repository openshift/ci-tools, pull requests merged in 2022-04, with the labels that each got.

#2748 Secret sync: Allow targeting multiple namespaces
  cmd/ci-secret-bootstrap/main_test.go
  cmd/vault-subpath-proxy/kv_update_transport.go
  cmd/vault-subpath-proxy/main_test.go
  pkg/secrets/vault.go
Labels: approved, lgtm

#2746 Generate-Registry-Metadata: Collect errors rather than bailing on the first
  cmd/generate-registry-metadata/main.go
  cmd/generate-registry-metadata/main_test.go
  cmd/generate-registry-metadata/testdata/a/generate-registry-metadata-a-chain.yaml
  cmd/generate-registry-metadata/testdata/b/generate-registry-metadata-b-chain.yaml
Labels: approved, lgtm

#2752 pkg/validation: reuse cluster profile list
  pkg/api/graph.go
  pkg/api/types.go
  pkg/load/agents/configAgent.go
  pkg/validation/config.go
  pkg/validation/test.go
Labels: approved, lgtm

#2753 pkg/prowgen: invert profile `ConfigMap` list
  pkg/prowgen/podspec.go
Labels: approved, lgtm

#2750 Add new cluster type for OpenStack HW offload platform
  pkg/api/types.go
Labels: approved, lgtm

#2755 Add an unknown value in console host when it is not resolved
  pkg/results/report.go
Labels: approved, lgtm

#2749 Create event handler for message.channel event
  pkg/slack/events/helpdesk/helpdesk-message.go
  pkg/slack/events/router/router.go
Labels: approved, lgtm, ok-to-test

#2756 pkg/prowgen: rework profile volume generation
  pkg/api/types.go
  pkg/prowgen/podspec.go
Labels: approved, lgtm

#2754 During aggregation test, do not consider 'initialize' test as a failure
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#2751 repo-init: use correct list of cluster profiles
  cmd/repo-init/api.go
  cmd/repo-init/api_test.go
  cmd/repo-init/main.go
Labels: approved, lgtm

#2734 Change retestOrBackoff functionality: Added method createComment, Edited retestOrBackoff funcionality
  cmd/better-retester/main.go
  cmd/better-retester/retester.go
  cmd/better-retester/retester_test.go
Labels: approved, lgtm, ok-to-test

#2758 aggregation: open test run links in new windows
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go
Labels: approved, lgtm

#2761 sync-rover-group: cannot use the group name openshift-priv-admins
  cmd/github-ldap-user-group-creator/main.go
  cmd/github-ldap-user-group-creator/main_test.go
  pkg/group/config.go
  pkg/group/config_test.go
  pkg/group/testdata/TestLoadConfig/openshift_priv_admins.yaml
Labels: approved, lgtm

#2762 Deprecate Incident and Request issue jira types from slack-bot integration
  pkg/jira/issues.go
  pkg/slack/modals/consultation/view.go
  pkg/slack/modals/consultation/view_test.go
  pkg/slack/modals/incident/view.go
  pkg/slack/modals/incident/view_test.go
Labels: approved, lgtm

#2763 change the jira query to match with the new workflow changes
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#2757 prow-job-dispatcher: add options for enabling/disabling clusters
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm

#2765 wait for five minutes for the cli image
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#2767 Post ephemeral reply to the messaging user in forum-tesplatform channel
  pkg/slack/events/helpdesk/helpdesk-message.go
  pkg/slack/events/router/router.go
Labels: approved, lgtm

#2769 bugzilla-config-manager: do not resolve cluster groups
  cmd/branchingconfigmanagers/bugzilla-config-manager/main.go
Labels: approved, lgtm

#2770 bugzilla-config-manager: fix 4.9/4.10 sorting issue
  cmd/branchingconfigmanagers/bugzilla-config-manager/main.go
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/lifecycle_multiple_ga_410_bigger_49.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_multiple_ga_410_bigger_49.yaml.yaml
  pkg/api/ocplifecycle/ocplifecycle.go
Labels: approved, lgtm

#2766 ci-operator multi-stage: fetch credentials once
  pkg/steps/multi_stage.go
Labels: approved, lgtm

#2768 Add READMEs for branch management tools
  cmd/blocking-issue-creator/README.md
  cmd/config-brancher/README.md
  cmd/repo-brancher/README.md
Labels: approved, lgtm

#2772 Change ephemeral reply to threaded reply
  pkg/slack/events/helpdesk/helpdesk-message.go
Labels: approved, lgtm

#2641 promotion: treat promoting to `origin` as promoting official images
  cmd/autopublicizeconfig/main.go
  cmd/blocking-issue-creator/main.go
  cmd/ci-operator-config-mirror/main.go
  cmd/config-brancher/main.go
  cmd/payload-testing-prow-plugin/server.go
  cmd/private-org-peribolos-sync/main.go
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
  cmd/private-prow-configs-mirror/main.go
  cmd/repo-brancher/main.go
  pkg/promotion/promotion.go
  pkg/promotion/promotion_test.go
  pkg/prowgen/prowgen.go
Labels: approved, lgtm

#2773 Don't add testimagestreamimportcleaner twice to manager
  pkg/controller/testimagestreamimportcleaner/testimagestreamimportcleaner.go
Labels: approved, lgtm

#2774 slack-bot: add extra debug logging to helpdesk-message handler
  pkg/slack/events/helpdesk/helpdesk-message.go
Labels: approved, lgtm

#2778 update helpdesk mention string with a correct one
  pkg/slack/events/helpdesk/helpdesk-message.go
Labels: approved, lgtm

#2779 Merge branch 'shift-week-better-retester' into master
  cmd/retester/main.go
  cmd/retester/main_test.go
  cmd/retester/retester.go
  cmd/retester/retester_test.go
  go.mod
  vendor/k8s.io/test-infra/prow/tide/BUILD.bazel
  vendor/k8s.io/test-infra/prow/tide/OWNERS
  vendor/k8s.io/test-infra/prow/tide/blockers/BUILD.bazel
  vendor/k8s.io/test-infra/prow/tide/blockers/blockers.go
  vendor/k8s.io/test-infra/prow/tide/history/BUILD.bazel
  vendor/k8s.io/test-infra/prow/tide/history/history.go
  vendor/k8s.io/test-infra/prow/tide/search.go
  vendor/k8s.io/test-infra/prow/tide/status.go
  vendor/k8s.io/test-infra/prow/tide/tide.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#2781 Create QE dedicated Alibabacloud cluster profile "alibabacloud-qe"
  pkg/api/types.go
Labels: approved, lgtm

#2775 ci-operator: do not hide reporting log line
  pkg/results/report.go
Labels: approved, lgtm

#2776 General refactoring
  cmd/entrypoint-wrapper/main.go
  cmd/vault-subpath-proxy/kv_update_transport.go
  pkg/api/constant.go
  pkg/api/secretbootstrap/secretboostrap.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/kubernetes/client.go
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/cluster_claim.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/input_image_tag.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage_test.go
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/run.go
  pkg/steps/secretrecordingclient/client.go
  pkg/steps/source.go
  pkg/steps/template.go
  pkg/testhelper/pod.go
  pkg/validation/test.go
Labels: approved, lgtm

#2785 Update slackbot readme
  cmd/slack-bot/README.md
Labels: approved, lgtm

#2585 fail on disruption now that history is complete
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Labels: approved, lifecycle/rotten, lgtm

#2777 ci-operator multi-stage: move to separate package
  pkg/defaults/defaults.go
  pkg/steps/multi_stage.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/multi_stage/gen_test.go
  pkg/steps/multi_stage/init.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/multi_stage/multi_stage_test.go
  pkg/steps/multi_stage/run.go
  pkg/steps/multi_stage/run_test.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/multi_stage_test.go
Labels: approved, lgtm

#2784 Extend the ocplifecycle config code and introduce the event timeline operations
  pkg/api/ocplifecycle/ocplifecycle.go
Labels: approved, lgtm

#2789 Create QE dedicated Alibabacloud cluster profile "alibabacloud-cn-qe"
  pkg/api/types.go
Labels: approved, lgtm

#2786 Initial implementation of the fast-forwarding config manager tool
  cmd/branchingconfigmanagers/fast-forwarding-config-manager/README.md
  cmd/branchingconfigmanagers/fast-forwarding-config-manager/main.go
  cmd/branchingconfigmanagers/fast-forwarding-config-manager/main_test.go
Labels: approved, lgtm

#2791 Extract shardProwConfig and refactor it to re-use in tide shard branch cut tool
  cmd/determinize-prow-config/main.go
  cmd/determinize-prow-config/main_test.go
  pkg/api/shardprowconfig/shardprowconfig.go
Labels: approved, tide/merge-method-squash, lgtm

#2788 Upgrade to go 1.18
  .ci-operator.yaml
  Makefile
  go.mod
  go.sum
  pkg/html/html.go
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/modern-go/reflect2/.travis.yml
  vendor/github.com/modern-go/reflect2/Gopkg.lock
  vendor/github.com/modern-go/reflect2/Gopkg.toml
  vendor/github.com/modern-go/reflect2/go_above_118.go
  vendor/github.com/modern-go/reflect2/go_above_17.go
  vendor/github.com/modern-go/reflect2/go_above_19.go
  vendor/github.com/modern-go/reflect2/go_below_118.go
  vendor/github.com/modern-go/reflect2/go_below_17.go
  vendor/github.com/modern-go/reflect2/go_below_19.go
  vendor/github.com/modern-go/reflect2/reflect2.go
  vendor/github.com/modern-go/reflect2/test.sh
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/modern-go/reflect2/unsafe_link.go
  vendor/github.com/modern-go/reflect2/unsafe_map.go
  vendor/k8s.io/client-go/third_party/forked/golang/LICENSE
  vendor/k8s.io/client-go/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/modules.txt
Labels: approved, lgtm

#2796 pkgs/steps/lease: log resources before acquiring
  pkg/steps/lease.go
Labels: approved, lgtm

#2794 Remove Petr and Emil from OWNERS reviewers
  OWNERS
Labels: approved, lgtm

#2783 Split some aggregator code into common library
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/required-pass-rate.py
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/spyglass_summary.go
  pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator_per_pr_jobs.go
  pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator_release_jobs.go
  pkg/jobrunaggregator/jobrunaggregatorlib/spyglass_summary.go
  pkg/jobrunaggregator/jobrunaggregatorlib/util.go
Labels: approved, lgtm

#2798 sprint-automation: reminder to view triage handover doc at beginning of week
  cmd/sprint-automation/main.go
Labels: approved, lgtm
