Repository openshift/ci-tools, pull requests merged in 2022-10, with the labels that each got.

#3018 [prowgen] override the ci-operator image for the arm01 cluster
  pkg/prowgen/jobbase.go
  pkg/prowgen/jobbase_test.go
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_container_based_test_with_arm01_cluster.yaml
Labels: approved, lgtm

#3058 Add observers suffix
  pkg/config/release.go
Labels: approved, lgtm

#3059 Mutate image when generating postsubmits for multi-arch and fix cluster references on test
  pkg/prowgen/jobbase.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_periodic.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_postsubmit.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_cluster_label_for_presubmit.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_container_based_test_with_arm01_cluster.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_container_based_test_with_cluster.yaml
Labels: approved, lgtm

#3060 retester: adding metrics
  cmd/retester/main.go
Labels: approved, needs-ok-to-test, lgtm

#3062 Use token file in secret test-credentials/ci-operator
  cmd/cluster-init/main.go
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#3022 New jobrunanalyzer historicaldata cmd
  hack/run-job-aggregator-analyzer.sh
  pkg/jobrunaggregator/cmd.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/cmd.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/pr_message_template.md
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/types.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/util.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
Labels: approved, lgtm

#3061 Treat observers as references in graph
  cmd/pj-rehearse/main.go
  pkg/load/load.go
  pkg/registry/graph.go
  pkg/registry/graph_test.go
Labels: approved, lgtm

#3054 ci-operator multi-stage: log observer errors
  pkg/steps/multi_stage/run.go
Labels: approved, lgtm

#3067 `pj-rehearse`: refactor in place to allow for use in prow plugin
  cmd/pj-rehearse/main.go
  pkg/rehearse/rehearse.go
  pkg/rehearse/rehearse_test.go
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#3065 pod-scaler admission: filter out workloads with 0 configured memory
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
Labels: approved, lgtm

#3070 Revert timeouts needed to land k8s bump
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3073 Unify approvers/reviewers in root OWNERS file
  OWNERS
Labels: approved, lgtm

#3072 `pj-rehearse`: don't report failure when there are no jobs to rehearse
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#3064 Update formatting to prep for golang version 1.19
  cmd/cluster-init/update_secret_generator.go
  cmd/config-brancher/main.go
  cmd/prow-job-dispatcher/main.go
  pkg/backporter/httpcache_test.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go
  pkg/kubernetes/pkg/credentialprovider/config.go
  pkg/release/official/client.go
  pkg/results/error.go
  pkg/util/sync.go
  pkg/webreg/webreg.go
  test/e2e/framework/ci-operator.go
  test/e2e/framework/test.go
Labels: approved, lgtm

#3071 pkg/api: demote architecture log message to debug
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/release/promote.go
  pkg/util/multi_arch.go
Labels: approved, lgtm

#3074 `pj-rehearse`: do not error when all jobs have been filtered out
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3078 Satisfy new linter warnings
  cmd/entrypoint-wrapper/main.go
  cmd/pr-reminder/main.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/multi_stage/multi_stage_test.go
Labels: approved, lgtm

#3080 DPTP-2428 Don't send acknowledged cards to Intake
  cmd/sprint-automation/main.go
  cmd/sprint-automation/main_test.go
Labels: approved, lgtm

#3083 test/e2e: remove source code lines from output
  test/e2e/observer/artifacts/failing-observer-junit_operator.xml
  test/e2e/observer/artifacts/multi-observers-junit_operator.xml
  test/e2e/observer/e2e_test.go
Labels: approved, lgtm

#3084 ci-op: add the authors field in the logging
  cmd/ci-operator/main.go
Labels: approved, lgtm

#3052 feat: add support for commit message being different than pr body
  cmd/prcreator/main.go
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm

#3081 Add the Azure Arm64 QE Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#3087 sprint-automation: address another linter warning
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#2943 pkg/release/prerelease: Add 'stream' property
  pkg/api/types.go
  pkg/release/prerelease/client.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3093 `pj-rehearse`: don't validate or rehearse when all jobs have been filtered out
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#3095 add ibmcloud qe cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3096 Add new members to OWNERS
  OWNERS
Labels: approved, lgtm

#3075 `pj-rehearse`: create external plugin server
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  pkg/config/jobs.go
  pkg/rehearse/rehearse.go
Labels: approved, tide/merge-method-squash, lgtm

#3089 DPTP-2929: determine prowjob name based on labels
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
Labels: approved, lgtm

#3091 Rename the cluster label on applyconfig jobs
  cmd/cluster-init/update_jobs.go
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/create/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/update/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
  test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
  test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/update/input/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#3098 Update roles and definitions links
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#3086 pr-reminder: show when the latest pr update is less than a day old
  cmd/pr-reminder/main.go
Labels: approved, lgtm

#3101 `pj-rehearse`: fix incorrect ref issues with plugin
  cmd/pj-rehearse/server.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3102 fix logging when promoting images for different architectures
  pkg/steps/release/promote.go
Labels: approved, lgtm

#3085 Remove the deprecated oc-create-kubeconfig cmd in local-exe
  Makefile
Labels: approved, lgtm

#3036 cluster-init: add flag use-token-file-in-kubeconfig
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#3105 [OKD/SCOS] Adding okd-scos as a ReleaseStream for the OKD ReleaseProduct
  pkg/api/types.go
  pkg/validation/release.go
  pkg/validation/release_test.go
Labels: approved, lgtm

#3106 `pj-rehearse`: plugin: rebase the branch onto the current master
  cmd/pj-rehearse/server.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3100 Only include disruption NURPs if we have 100 rows.
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/types.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/util.go
Labels: approved, lgtm

#3031 Fix topology value for hypershift jobs
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/job_typer.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
Labels: approved, lgtm

#3115 Add another AWS QE profile for local zone testing
  pkg/api/types.go
Labels: approved, lgtm

#3107 Create a dedicated aws cluster profile for cspi qe
  pkg/api/types.go
Labels: approved, lgtm

#3094 Add hyershift jobs to test grid
  cmd/testgrid-config-generator/OWNERS
  cmd/testgrid-config-generator/main.go
Labels: approved, lgtm

#3076 retester: adding metrics for counting retests
  pkg/retester/retester.go
Labels: approved, tide/merge-method-squash, lgtm, ok-to-test

#3088 pkg/config: add test for registry change detection
  pkg/config/release.go
  pkg/config/release_test.go
  pkg/registry/graph.go
Labels: approved, lgtm

#3109 `slack-bot`: post job links for storage.googleapis.com links
  pkg/api/domain.go
  pkg/api/domain_test.go
  pkg/slack/events/joblink/link.go
  pkg/slack/events/joblink/link_test.go
Labels: approved, lgtm

#3116 `pj-rehearse`: plugin: don't comment empty job table and streamline acknowledgement
  cmd/pj-rehearse/server.go
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#3112 integration: `pj-rehearse` cleanup
  hack/test-integration.sh
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/OWNERS
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi-changed/OWNERS
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi-changed/ipi-changed-workflow.metadata.json
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi-changed/ipi-changed-workflow.yaml
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.yaml
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/deprovision/ipi-deprovision-chain.yaml
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/deprovision/must-gather/ipi-deprovision-must-gather-commands.sh
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/deprovision/must-gather/ipi-deprovision-must-gather-ref.yaml
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/install/install/ipi-install-install-ref.yaml
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/install/ipi-install-chain.yaml
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/install/rbac/ipi-install-rbac-commands.sh
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/install/rbac/ipi-install-rbac-ref.yaml
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/ipi/ipi-workflow.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-ciop-cfg-change-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-periodics.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/README.md
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/OWNERS
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/OWNERS
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/deprovision/OWNERS
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-commands.sh
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.metadata.json
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/deprovision/ipi-deprovision-deprovision-ref.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/ipi-deprovision-chain.metadata.json
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/ipi-deprovision-chain.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/must-gather/OWNERS
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/must-gather/ipi-deprovision-must-gather-commands.sh
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/must-gather/ipi-deprovision-must-gather-ref.metadata.json
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/deprovision/must-gather/ipi-deprovision-must-gather-ref.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/OWNERS
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/install/OWNERS
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/install/ipi-install-install-ref.metadata.json
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/install/ipi-install-install-ref.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/ipi-install-chain.metadata.json
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/ipi-install-chain.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/rbac/OWNERS
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/rbac/ipi-install-rbac-commands.sh
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/rbac/ipi-install-rbac-ref.metadata.json
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/install/rbac/ipi-install-rbac-ref.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/ipi-workflow.metadata.json
  test/integration/pj-rehearse/master/ci-operator/step-registry/ipi/ipi-workflow.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/resourcewatcher/OWNERS
  test/integration/pj-rehearse/master/ci-operator/step-registry/resourcewatcher/resourcewatcher-commands.sh
  test/integration/pj-rehearse/master/ci-operator/step-registry/resourcewatcher/resourcewatcher-observer.metadata.json
  test/integration/pj-rehearse/master/ci-operator/step-registry/resourcewatcher/resourcewatcher-observer.yaml
Labels: approved, lgtm

#3117 fix empty platforms
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/job_typer.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
Labels: approved, lgtm
