Repository openshift/ci-tools, pull requests merged in 2022-11, with the labels that each got.

#3124 Also skip okd jobs for gathering disruption/alert data.
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
Labels: approved, lgtm

#3108 serviceaccount_secret_refresher: stop handling SA's token secrets
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher.go
  pkg/controller/serviceaccount_secret_refresher/serviceaccount_secret_refresher_test.go
Labels: approved, lgtm

#3127 `pj-rehearse` plugin: fix comment-on-pr-creation
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#3123 pod-scaler admission: add workload type
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/result-aggregator/main.go
  cmd/result-aggregator/main_test.go
  pkg/results/report.go
  pkg/results/report_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3128 pr-reminder: add 'updated' emoji to legend
  cmd/pr-reminder/main.go
Labels: approved, lgtm

#3129 cluster-display: add #standby for pools
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
Labels: approved, lgtm

#3131 feat: update render output to account for new release data
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/pr_message_template.md
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/types.go
Labels: approved, lgtm

#3133 private-org-sync: add prefix argument for testing
  cmd/private-org-sync/README.md
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#3132 test-images-distributor: distribute multiarch IS
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#3130 `pj-rehearse` plugin: day 1 fixes
  cmd/pj-rehearse/server.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/rehearse.go
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_hidden_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_different_org_repo_than_refs_with_custom_config.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_but_different_repo_than_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_job_that_belong_to_the_same_org_repo_with_refs.yaml
  pkg/rehearse/testdata/zz_fixture_TestMakeRehearsalPresubmit_reporting_configuration_is_stripped_from_rehearsals_to_avoid_polluting.yaml
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#3121 fix aws-outpost slice
  pkg/api/types.go
Labels: approved, lgtm, ok-to-test

#3137 [prowgen] merge configuration defaults when both org and repo configs are specified
  cmd/ci-operator-prowgen/main.go
  pkg/config/load.go
Labels: approved, lgtm

#3138 `check-gh-automation`: stop mis-categorizing the prowgen config as a repo
  cmd/check-gh-automation/main.go
Labels: approved, lgtm

#3126 skip okd jobs 2
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
Labels: approved, lgtm

#3141 `pj-rehearse` plugin: stop importing build-cache imagestreamtags
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3144 `pj-rehearse` plugin: Add a way to remove the `rehearsals-ack` label
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3145 improve logging when requesting a release payload
  pkg/release/candidate/client.go
  pkg/release/config/client.go
  pkg/release/official/client.go
  pkg/release/prerelease/client.go
Labels: approved, lgtm

#3148 `pj-rehearse` plugin: allow for refreshing the affected job list
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3149 Create a dedicated aws cluster profile for interop testing
  pkg/api/types.go
Labels: approved, lgtm, ok-to-test

#3153 [prowgen] merge additional_architectures when repo defines them
  pkg/config/load.go
Labels: approved, lgtm

#3155 Simplify variable names in mutateGlobalPullSecret
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm

#3159 `pr-reminder`: add 'accepted' and 'lgtm' labels to output
  cmd/pr-reminder/main.go
Labels: approved, lgtm

#3156 dptp-controller-manager: use universal watcher
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#3158 test/e2e: fix optional operator tests
  test/e2e/optional-operators/optional-operators.yaml
Labels: approved, lgtm

#3163 `pj-rehearse` plugin: accept commands in the PR body
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3140 Allow sharding of slack reporter configs
  cmd/determinize-prow-config/main_test.go
  pkg/api/shardprowconfig/shardprowconfig.go
Labels: approved, lgtm

#2815 Before branching day: step 1
  cmd/branchingconfigmanagers/rpm-deps-mirroring-services/.gitignore
  cmd/branchingconfigmanagers/rpm-deps-mirroring-services/README.md
  cmd/branchingconfigmanagers/rpm-deps-mirroring-services/main.go
  go.mod
  pkg/branchcuts/bumper/bumper.go
  pkg/branchcuts/bumper/repo-bumper.go
  pkg/branchcuts/bumper/repo-bumper_test.go
Labels: approved, lgtm

#3164 cluster-init: automate members of osd_global_pull_secret group
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/input/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#3167 `pj-rehearse` plugin: add auto-ack command
  cmd/pj-rehearse/server.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3170 `pod-scaler` producer: parse retention duration out of full result
  cmd/pod-scaler/producer.go
Labels: approved, lgtm

#3171 Failed the build upon a file-based catalog index (2)
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
  pkg/steps/testdata/isTags/pipeline_malformed_istag.yaml
  pkg/steps/testdata/isTags/pipeline_no_bytes_istag.yaml
  pkg/steps/testdata/isTags/pipeline_no_label_istag.yaml
  pkg/steps/testdata/isTags/pipeline_v4.10_istag.yaml
  pkg/steps/testdata/isTags/pipeline_v4.11_istag.yaml
Labels: approved, lgtm

#3161 ci-operator: allow grace period to be configured in observers
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/multi_stage/gen_test.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm, ok-to-test

#3172 Add `rehearsals-ack` label on uninterested `openshift-bot` PRs
  cmd/autoconfigbrancher/main.go
  cmd/autoowners/main.go
  cmd/pj-rehearse/server.go
  cmd/prow-job-dispatcher/main.go
  pkg/github/prcreation/prcreation.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm
