Repository openshift/ci-tools, pull requests merged in 2022-08, with the labels that each got.

#2868 retester: Adding config file to retester
  cmd/retester/main.go
  cmd/retester/main_test.go
  cmd/retester/retester.go
  cmd/retester/retester_test.go
  cmd/retester/testdata/testconfig/config.yaml
  cmd/retester/testdata/testconfig/default.yaml
  cmd/retester/testdata/testconfig/empty.yaml
  cmd/retester/testdata/testconfig/no-config.yaml
  cmd/retester/testdata/testconfig/openshift-config.yaml
Labels: approved, tide/merge-method-squash, lgtm, ok-to-test

#2922 executeCommand doesn't mix std streams anymore
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
Labels: approved, tide/merge-method-squash, lgtm

#2916 Update yaml.v3 to v3.0.1
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: approved, lgtm

#2930 ci-operator: allow multi-stage steps to opt out of SA credentials
  cmd/entrypoint-wrapper/main.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/steps/multi_stage/gen.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/multi-stage/no-kubeconfig.yaml
Labels: approved, lgtm

#2932 ci-operator: allow promoting images with commit sha tag
  pkg/api/types.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#2925 `pr-reminder`: include PRs where user is assigned
  cmd/pr-reminder/main.go
  cmd/pr-reminder/main_test.go
Labels: approved, lgtm

#2935 Enhance oc_sa_create_kubeconfig.sh
  images/ci-secret-generator/oc_sa_create_kubeconfig.sh
Labels: approved, lgtm

#2939 waitForBuild: use watch instead of get
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm

#2941 Fix a copy/paste error
  pkg/steps/source_test.go
Labels: approved, lgtm

#2940 Add Nutanix QE Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#2942 `pr-reminder`: add some additional logging
  cmd/pr-reminder/main.go
Labels: approved, lgtm

#2945 ci-operator: handle promotion with no refs
  pkg/steps/release/promote.go
Labels: approved, lgtm

#2948 config-shard-validator: further break `misc` CM
  cmd/config-shard-validator/main.go
  pkg/api/metadata.go
  pkg/api/metadata_test.go
Labels: approved, lgtm

#2937 [DPTP-3028] Resolve all input image tag namespace based on the runtime architecture
  cmd/repo-init/api.go
  pkg/api/helper/imageextraction.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/zz_generated.deepcopy.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
Labels: approved, lgtm

#2952 Resolve the entrypoint and clonerefs image namespace based on the os architecture
  pkg/defaults/defaults.go
  pkg/steps/multi_stage/gen.go
  pkg/util/multi_arch.go
Labels: approved, lgtm

#2947 entrypoint-wrapper: add renaming kubeconfig
  cmd/entrypoint-wrapper/main.go
Labels: approved, lgtm

#2951 Add metrics to pod-scaler-admission
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
Labels: approved, tide/merge-method-squash, lgtm

#2944 retester: Extract functional code into packages.
  cmd/retester/main.go
  pkg/retester/retester.go
  pkg/retester/retester_test.go
  pkg/retester/testdata/loadFromDiskNow/basic_case.yaml
  pkg/retester/testdata/loadFromDiskNow/wrong_format.yaml
  pkg/retester/testdata/testconfig/config.yaml
  pkg/retester/testdata/testconfig/default.yaml
  pkg/retester/testdata/testconfig/empty.yaml
  pkg/retester/testdata/testconfig/no-config.yaml
  pkg/retester/testdata/testconfig/openshift-config.yaml
Labels: approved, lgtm, ok-to-test

#2955 add more logging when resolving namespace for multi architecture
  pkg/api/types.go
  pkg/util/multi_arch.go
Labels: approved, lgtm

#2956 oc_sa_create_kubeconfig.sh: oc_cmd as var
  images/ci-secret-generator/oc_sa_create_kubeconfig.sh
Labels: approved, lgtm

#2962 vsphere: no need to use --insecure-skip-tls-verify
  images/ci-secret-generator/oc_sa_create_kubeconfig.sh
Labels: approved, lgtm

#2963 add cluster profile vsphere-connected for QE testing
  pkg/api/types.go
Labels: approved, lgtm

#2964 Add gh-pull-through-cache image
  images/gh-pull-through-cache/Dockerfile
  images/gh-pull-through-cache/nginx.conf
Labels: approved, lgtm

#2966 improve logging when resolving namespace for the os architecture
  pkg/api/types.go
  pkg/util/multi_arch.go
Labels: approved, lgtm

#2927 add upgrade filter for install test groups
  Makefile
  go.mod
  go.sum
  hack/update-mocks.sh
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer_test.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
  vendor/github.com/golang/mock/AUTHORS
  vendor/github.com/golang/mock/CONTRIBUTORS
  vendor/github.com/golang/mock/LICENSE
  vendor/github.com/golang/mock/gomock/call.go
  vendor/github.com/golang/mock/gomock/callset.go
  vendor/github.com/golang/mock/gomock/controller.go
  vendor/github.com/golang/mock/gomock/matchers.go
  vendor/modules.txt
Labels: approved, lgtm

#2960 Copy /usr/bin/oc411 in the ci-secret-generator image
  images/ci-secret-generator/Dockerfile
Labels: approved, lgtm

#2968 Bump test-infra
  go.mod
  go.sum
  vendor/github.com/andygrunwald/go-gerrit/.gitignore
  vendor/github.com/andygrunwald/go-gerrit/CHANGELOG.md
  vendor/github.com/andygrunwald/go-gerrit/LICENSE
  vendor/github.com/andygrunwald/go-gerrit/Makefile
  vendor/github.com/andygrunwald/go-gerrit/README.md
  vendor/github.com/andygrunwald/go-gerrit/access.go
  vendor/github.com/andygrunwald/go-gerrit/accounts.go
  vendor/github.com/andygrunwald/go-gerrit/authentication.go
  vendor/github.com/andygrunwald/go-gerrit/changes.go
  vendor/github.com/andygrunwald/go-gerrit/changes_edit.go
  vendor/github.com/andygrunwald/go-gerrit/changes_reviewer.go
  vendor/github.com/andygrunwald/go-gerrit/changes_revision.go
  vendor/github.com/andygrunwald/go-gerrit/config.go
  vendor/github.com/andygrunwald/go-gerrit/doc.go
  vendor/github.com/andygrunwald/go-gerrit/events.go
  vendor/github.com/andygrunwald/go-gerrit/gerrit.go
  vendor/github.com/andygrunwald/go-gerrit/groups.go
  vendor/github.com/andygrunwald/go-gerrit/groups_include.go
  vendor/github.com/andygrunwald/go-gerrit/groups_member.go
  vendor/github.com/andygrunwald/go-gerrit/plugins.go
  vendor/github.com/andygrunwald/go-gerrit/projects.go
  vendor/github.com/andygrunwald/go-gerrit/projects_access.go
  vendor/github.com/andygrunwald/go-gerrit/projects_branch.go
  vendor/github.com/andygrunwald/go-gerrit/projects_childproject.go
  vendor/github.com/andygrunwald/go-gerrit/projects_commit.go
  vendor/github.com/andygrunwald/go-gerrit/projects_dashboard.go
  vendor/github.com/andygrunwald/go-gerrit/projects_tag.go
  vendor/github.com/andygrunwald/go-gerrit/types.go
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/gerrit/client/syncer.go
  vendor/k8s.io/test-infra/prow/github/app_auth_roundtripper.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/hook/events.go
  vendor/k8s.io/test-infra/prow/plugins/blunderbuss/blunderbuss.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/jira/jira.go
  vendor/k8s.io/test-infra/prow/tide/codereview.go
  vendor/k8s.io/test-infra/prow/tide/gerrit.go
  vendor/k8s.io/test-infra/prow/tide/github.go
  vendor/k8s.io/test-infra/prow/tide/tide.go
  vendor/modules.txt
Labels: approved, lgtm

#2971 gh-pull-through-cache: make nginx unprivileged
  images/gh-pull-through-cache/Dockerfile
  images/gh-pull-through-cache/nginx.conf
Labels: approved, lgtm

#2972 Change base image to internal unpriv nginx
  images/gh-pull-through-cache/Dockerfile
  images/gh-pull-through-cache/nginx.conf
Labels: approved, lgtm

#2959 Observer pods: manage kubeconfig and shared_dir features on entrypoint-wrapper
  cmd/entrypoint-wrapper/main.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/multi_stage/gen_test.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/multi_stage/run.go
Labels: approved, lgtm

#2974 resolve namespace in imagestream tag name method for multi arch images
  pkg/api/types.go
Labels: approved, lgtm

#2977 Resolve multi-arch namespace when overriding the cli image for the release payload
  pkg/defaults/defaults.go
Labels: approved, lgtm

#2961 `check-gh-automation`: check that app is installed in repo
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
Labels: approved, lgtm

#2970 `check-gh-automation`: allow repo to be passed in and create local dev script
  cmd/check-gh-automation/README.md
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
  hack/local-check-gh-automation.sh
Labels: approved, tide/merge-method-squash, lgtm

#2983 Add IgnoreE2EByJobAssignment option to gradually enable colocation
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm
