Repository openshift/ci-tools, pull requests merged in 2022-02, with the labels that each got.

#2634 ci-operator: wait longer for `cli` image to appear
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#2636 ci-tools: use centos stream8 instead of centos:8
  images/applyconfig/Dockerfile
  images/autoconfigbrancher/Dockerfile
  images/autoowners/Dockerfile
  images/autoperibolossync/Dockerfile
  images/autopublicizeconfig/Dockerfile
  images/autotestgridgenerator/Dockerfile
  images/backport-verifier/Dockerfile
  images/blocking-issue-creator/Dockerfile
  images/bugzilla-backporter/Dockerfile
  images/ci-operator-checkconfig/Dockerfile
  images/ci-operator-config-mirror/Dockerfile
  images/ci-operator-configresolver/Dockerfile
  images/ci-operator-prowgen/Dockerfile
  images/ci-operator/Dockerfile
  images/ci-secret-bootstrap/Dockerfile
  images/ci-secret-generator/Dockerfile
  images/cluster-init/Dockerfile
  images/clusterimageset-updater/Dockerfile
  images/config-brancher/Dockerfile
  images/config-change-trigger/Dockerfile
  images/config-shard-validator/Dockerfile
  images/cvp-trigger/Dockerfile
  images/determinize-ci-operator/Dockerfile
  images/determinize-peribolos/Dockerfile
  images/determinize-prow-config/Dockerfile
  images/dptp-controller-manager/Dockerfile
  images/entrypoint-wrapper/Dockerfile
  images/generate-registry-metadata/Dockerfile
  images/group-auto-updater/Dockerfile
  images/job-run-aggregator/Dockerfile
  images/ocp-build-data-enforcer/Dockerfile
  images/pj-rehearse/Dockerfile
  images/pod-scaler/Dockerfile
  images/private-org-peribolos-sync/Dockerfile
  images/private-org-sync/Dockerfile
  images/private-prow-configs-mirror/Dockerfile
  images/prowjobdispatcher/Dockerfile
  images/publicize/Dockerfile
  images/registry-replacer/Dockerfile
  images/repo-brancher/Dockerfile
  images/repo-init/Dockerfile
  images/result-aggregator/Dockerfile
  images/sanitize-prow-jobs/Dockerfile
  images/serviceaccount-secret-rotation-trigger/Dockerfile
  images/slack-bot/Dockerfile
  images/sprint-automation/Dockerfile
  images/template-deprecator/Dockerfile
  images/testgrid-config-generator/Dockerfile
  images/vault-subpath-proxy/Dockerfile
Labels: approved, lgtm

#2635 cluster-init: update sync-rover-groups' config
  cmd/cluster-init/main.go
  cmd/cluster-init/update_sync_rover_groups.go
  test/integration/cluster-init/create/expected/core-services/sync-rover-groups/_config.yaml
  test/integration/cluster-init/create/input/core-services/sync-rover-groups/_config.yaml
  test/integration/cluster-init/update/expected/core-services/sync-rover-groups/_config.yaml
  test/integration/cluster-init/update/input/core-services/sync-rover-groups/_config.yaml
Labels: approved, lgtm

#2637 Update openshift-goimports module path to new location
  Makefile
  go.mod
  go.sum
  hack/tools.go
  vendor/github.com/openshift-eng/openshift-goimports/.gitignore
  vendor/github.com/openshift-eng/openshift-goimports/LICENSE
  vendor/github.com/openshift-eng/openshift-goimports/Makefile
  vendor/github.com/openshift-eng/openshift-goimports/README.md
  vendor/github.com/openshift-eng/openshift-goimports/cmd/root.go
  vendor/github.com/openshift-eng/openshift-goimports/main.go
  vendor/github.com/openshift-eng/openshift-goimports/pkg/imports/imports.go
  vendor/github.com/openshift-eng/openshift-goimports/pkg/util/util.go
  vendor/modules.txt
Labels: approved, lgtm

#2633 Refactor the aggregator job to be generated by an unresolved ci-op config
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Labels: approved, lgtm

#2639 update job definitions for aggregator
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Labels: approved, lgtm

#2640 fix logging for aggregation
  pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator_per_pr_jobs.go
Labels: approved, lgtm

#2646 pkg/source: retry on `GenericBuildFailed`
  pkg/steps/source.go
Labels: approved, lgtm

#2643 autoowners: include source and date feched in header comment
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm

#2647 repo-init: do not resolve cluster groups
  cmd/repo-init/main.go
  test/integration/repo-init/expected/core-services/prow/02_config/_plugins.yaml
  test/integration/repo-init/input/core-services/prow/02_config/_plugins.yaml
Labels: approved, lgtm

#2645 sync-rover-groups: generate github/ldap mapping
  Makefile
  cmd/github-ldap-user-group-creator/README.md
  cmd/sync-rover-groups/README.md
  cmd/sync-rover-groups/ldap.go
  cmd/sync-rover-groups/ldap_test.go
  cmd/sync-rover-groups/main.go
Labels: approved, lgtm

#2650 sync-rover-groups: exclude gitlab users
  cmd/sync-rover-groups/ldap.go
  cmd/sync-rover-groups/ldap_test.go
Labels: approved, lgtm

#2648 ci-operator: retry infra-failed builds immediately
  pkg/steps/source.go
Labels: approved, lgtm, do-not-merge/hold

#2649 Adding Multiarch platforms
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go
  pkg/jobrunaggregator/jobtableprimer/job_typer.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
Labels: approved, lgtm

#2656 Revert "ci-operator: retry infra-failed builds immediately"
  pkg/steps/source.go
Labels: approved, lgtm

#2653 Fix test data
  cmd/ci-operator-prowgen/main_test.go
  test/integration/repo-init/input/ci-operator/config/openshift/ci-tools/openshift-ci-tools-master.yaml
  test/integration/repo-init/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#2642 add promoted-image-governor/README.md
  cmd/promoted-image-governor/README.md
Labels: approved, lgtm

#2628 pkg/config: use generic pipeline function
  pkg/config/load.go
  pkg/util/sync.go
  pkg/util/sync_test.go
Labels: approved, lgtm

#2662 configresolver client: retry http requests
  pkg/registry/server/client.go
Labels: approved, lgtm

#2661 Update cluster type to packet-edge for Assisted and SNO profiles
  pkg/api/types.go
Labels: approved, lgtm

#2652 Remove old ignore that expired based on time
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#2663 override job_url_prefix for rehearsals
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  test/integration/pj-rehearse/candidate/core-services/prow/02_config/_config.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/core-services/prow/02_config/_config.yaml
Labels: approved, lgtm

#2631 ci-operator-prowgen: use generic pipeline function
  cmd/ci-operator-prowgen/main.go
Labels: approved, lgtm

#2671 update url
  Makefile
Labels: approved, lgtm

#2665 refactor to utilize jobConfigurer
  cmd/pj-rehearse/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
Labels: approved, lgtm

#2670 query PRs to merge
  cmd/better-retester/main.go
  go.mod
  vendor/k8s.io/test-infra/prow/tide/BUILD.bazel
  vendor/k8s.io/test-infra/prow/tide/OWNERS
  vendor/k8s.io/test-infra/prow/tide/blockers/BUILD.bazel
  vendor/k8s.io/test-infra/prow/tide/blockers/blockers.go
  vendor/k8s.io/test-infra/prow/tide/history/BUILD.bazel
  vendor/k8s.io/test-infra/prow/tide/history/history.go
  vendor/k8s.io/test-infra/prow/tide/search.go
  vendor/k8s.io/test-infra/prow/tide/status.go
  vendor/k8s.io/test-infra/prow/tide/tide.go
  vendor/modules.txt
Labels: approved, lgtm

#2673 Better retester: make a controller
  cmd/better-retester/main.go
  cmd/better-retester/retester.go
Labels: approved, lgtm

#2630 pkg/jobconfig: use generic pipeline function
  pkg/jobconfig/files.go
Labels: approved, lgtm

#2672 Modify repo-init-apiserver logging to provide finer-grained info
  cmd/repo-init/api.go
  cmd/repo-init/api_test.go
Labels: approved, lgtm

#2674 pkg/load: use correct registry metric
  pkg/load/agents/registryAgent.go
Labels: approved, lgtm

#2676 Add committer info to repo-init-ui commit
  cmd/repo-init/api.go
  cmd/repo-init/api_test.go
  cmd/repo-init/repo_manager.go
Labels: approved, lgtm

#2677 Filter prs with failing required jobs
  cmd/better-retester/main.go
  cmd/better-retester/retester.go
Labels: approved, tide/merge-method-squash, lgtm

#2680 Fixed missing platform for s390x/ppc64le
  pkg/jobrunaggregator/jobtableprimer/job_typer.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
Labels: approved, lgtm

#2678 Retest backoff
  cmd/better-retester/main.go
  cmd/better-retester/retester.go
Labels: approved, lgtm

#2683 [autoowners] trim body when it exceeds more than 65536 characters
  cmd/autoowners/main.go
Labels: approved, lgtm

#2684 e2e: properly wait for Prometheus
  test/e2e/pod-scaler/prometheus/prometheus.go
Labels: approved, lgtm

#2682 better-retester: persist cache
  cmd/better-retester/main.go
  cmd/better-retester/retester.go
Labels: approved, lgtm

#2679 use the logrusutil to set the component and formatter in repo-init-apiserver
  cmd/repo-init/api.go
  cmd/repo-init/frontend.go
Labels: approved, lgtm

#2685 better-retester: fix the default value of cache-record-age
  cmd/better-retester/main.go
Labels: approved, lgtm

#2686 better-retester: use the same dir for the temp file
  cmd/better-retester/retester.go
Labels: approved, lgtm

#2687 (repo-init-api) fix logic for locking and unlocking repos
  cmd/repo-init/api.go
  cmd/repo-init/repo_manager.go
Labels: approved, lgtm

#2669 e2e: correct package selection
  Makefile
Labels: approved, lgtm

#2666 cluster-init: stop updating github_client_id for build0{1|2}
  cmd/cluster-init/update_bootstrap_secrets.go
  cmd/cluster-init/update_jobs.go
Labels: approved, lgtm

#2658 fix sharding plugin configs that contain trigger plugin configuration
  pkg/prowconfigsharding/prowconfigsharding.go
Labels: approved, lgtm

#2689 github-id-group contains only kerberos_id
  cmd/github-ldap-user-group-creator/main.go
  cmd/github-ldap-user-group-creator/main_test.go
Labels: approved, lgtm

#2629 ci-operator-checkconfig: use generic pipeline fn.
  cmd/ci-operator-checkconfig/main.go
Labels: approved, lgtm

#2632 sanitize-prow-jobs: use generic pipeline function
  cmd/sanitize-prow-jobs/main.go
Labels: approved, lgtm

#2667 entrypoint-wrapper: separate cmd. `Start`/`Wait`
  cmd/entrypoint-wrapper/main.go
  test/integration/entrypoint-wrapper.sh
Labels: approved, lgtm

#2690 autoowners: stop putting fetch time into header
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm

#2688 repo init ui: run 'make jobs' prior to commit
  cmd/repo-init/api.go
  cmd/repo-init/frontend/src/app/Common/Messaging.tsx
  cmd/repo-init/frontend/src/app/Generate/Generate.tsx
  images/repo-init/Dockerfile
Labels: approved, lgtm

#2693 use tool binaries directly to mimic 'make jobs'
  cmd/repo-init/api.go
  images/repo-init/Dockerfile
Labels: approved, lgtm

#2691 repo-init-ui: add info about gh oauth
  cmd/repo-init/README.md
Labels: approved, lgtm

#2695 determinize-prow-config: use strict mode to fail when there is an unknown key
  cmd/determinize-prow-config/main.go
Labels: approved, lgtm
