Repository openshift/ci-tools, pull requests merged in 2022-09, with the labels that each got.

#2967 Observer pods: e2e test
  test/e2e/observer/artifacts/failing-observer-junit_operator.xml
  test/e2e/observer/artifacts/junit_operator.xml
  test/e2e/observer/artifacts/multi-observers-junit_operator.xml
  test/e2e/observer/artifacts/simple-observer-junit_operator.xml
  test/e2e/observer/boskos.yaml
  test/e2e/observer/config.yaml
  test/e2e/observer/e2e_test.go
  test/e2e/observer/failing-observer.yaml
  test/e2e/observer/multi-observers.yaml
  test/e2e/observer/registry/failing-observer/failing-observer-commands.sh
  test/e2e/observer/registry/failing-observer/failing-observer-observer.yaml
  test/e2e/observer/registry/observer/observer-commands.sh
  test/e2e/observer/simple-observer.yaml
Labels: approved, lgtm

#2985 promoted-image-governor: don't delete images tagged by sha
  cmd/promoted-image-governor/main.go
Labels: approved, lgtm

#2979 `prowgen`: disable rehearsals via the .config.prowgen file
  pkg/api/types.go
  pkg/config/load.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_disabled_rehearsals_at_job_level.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_disabled_rehearsals_at_repo_level.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_with_disabled_rehearsal.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_rehearsal_disabled.yaml
  test/integration/ci-operator-prowgen/input/config/norehearsals/duper/.config.prowgen
  test/integration/ci-operator-prowgen/input/config/norehearsals/duper/norehearsals-duper-master.yaml
  test/integration/ci-operator-prowgen/input/config/norehearsals/stuper/.config.prowgen
  test/integration/ci-operator-prowgen/input/config/norehearsals/stuper/norehearsals-stuper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/norehearsals/duper/norehearsals-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/norehearsals/duper/norehearsals-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/norehearsals/stuper/norehearsals-stuper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/norehearsals/stuper/norehearsals-stuper-master-presubmits.yaml
Labels: approved, tide/merge-method-squash, lgtm

#2984 Support promoting images based on their architecture and resolve build cache
  cmd/ci-operator-checkconfig/main.go
  cmd/promoted-image-governor/main.go
  cmd/registry-replacer/main.go
  pkg/api/helper/imageextraction.go
  pkg/api/metadata.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm

#2990 resolve arm01 service domain registry address
  pkg/api/domain.go
  pkg/api/domain_test.go
Labels: approved, lgtm

#2987 Revert "Copy /usr/bin/oc411 in the ci-secret-generator image"
  images/ci-secret-generator/Dockerfile
Labels: approved, lgtm

#2991 autoconfigbrancher: explicitly choose merge method
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#2988 `slack-bot`: clarify how to use workflow in forum
  pkg/slack/events/helpdesk/helpdesk-message.go
Labels: approved, lgtm

#2994 Change release minor 8 to current
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#2995 update default cleanup duration
  cmd/ci-operator/main.go
Labels: approved, lgtm

#2980 Add test config minimum_interval
  cmd/release-job-migrator/main.go
  go.mod
  go.sum
  pkg/api/config.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_using_minimum_interval.yaml
  pkg/steps/release/promote.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  vendor/k8s.io/test-infra/prow/config/cache.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/jobs.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/flagutil/config/config.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/initupload/run.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/jira/jira.go
  vendor/k8s.io/test-infra/prow/plugins/lgtm/lgtm.go
  vendor/k8s.io/test-infra/prow/plugins/milestone/milestone.go
  vendor/k8s.io/test-infra/prow/plugins/milestonestatus/milestonestatus.go
  vendor/k8s.io/test-infra/prow/plugins/override/override.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/plugins/updateconfig/updateconfig.go
  vendor/k8s.io/test-infra/prow/pod-utils/downwardapi/jobspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/metadata.go
  vendor/k8s.io/test-infra/prow/sidecar/run.go
  vendor/k8s.io/test-infra/prow/tide/codereview.go
  vendor/k8s.io/test-infra/prow/tide/gerrit.go
  vendor/k8s.io/test-infra/prow/tide/github.go
  vendor/k8s.io/test-infra/prow/tide/tide.go
  vendor/modules.txt
Labels: approved, lgtm

#2996 Fix an issue caused by gotestsum
  pkg/steps/source_test.go
Labels: approved, lgtm

#2992 Result-aggregator: handle pod-scaler admission requests
  cmd/result-aggregator/main.go
  cmd/result-aggregator/main_test.go
Labels: approved, tide/merge-method-squash, lgtm

#2998 add quay.io pull credentials when generating the bootstrap secrets for build clusters
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#3005 Revert "add quay.io pull credentials when generating the bootstrap secrets for build clusters"
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#3000 bump test-infra to v0.0.0-20220913010905-3bc71e6c7a20
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/bugzilla/client.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/initupload/run.go
  vendor/k8s.io/test-infra/prow/io/opener.go
  vendor/k8s.io/test-infra/prow/io/providers/providers.go
  vendor/k8s.io/test-infra/prow/kube/config.go
  vendor/k8s.io/test-infra/prow/pjutil/filter.go
  vendor/k8s.io/test-infra/prow/plugins/approve/approvers/owners.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/dco/dco.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/pod-utils/downwardapi/jobspec.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/k8s.io/test-infra/prow/spyglass/artifacts.go
  vendor/k8s.io/test-infra/prow/tide/codereview.go
  vendor/k8s.io/test-infra/prow/tide/gerrit.go
  vendor/k8s.io/test-infra/prow/tide/github.go
  vendor/k8s.io/test-infra/prow/tide/tide.go
  vendor/modules.txt
Labels: approved, lgtm

#3006 Use only one constant for registry-pull-credentials
  cmd/ci-operator/main.go
  pkg/prowgen/podspec.go
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm

#3008 [cluster-init] remove the implementation of the registry-pull-credentials-all secret
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/create/input/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/input/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#3011 Update hive api to include inventory
  go.mod
  go.sum
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/alibabacloud/doc.go
  vendor/github.com/openshift/hive/apis/hive/v1/alibabacloud/machinepool.go
  vendor/github.com/openshift/hive/apis/hive/v1/alibabacloud/platform.go
  vendor/github.com/openshift/hive/apis/hive/v1/alibabacloud/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
  vendor/github.com/openshift/hive/apis/hive/v1/azure/disk.go
  vendor/github.com/openshift/hive/apis/hive/v1/azure/machinepool.go
  vendor/github.com/openshift/hive/apis/hive/v1/azure/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterclaim_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeploymentcustomization_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeprovision_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterinstall_conditions.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterprovision_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/conditions.go
  vendor/github.com/openshift/hive/apis/hive/v1/dnszone_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/metricsconfig/doc.go
  vendor/github.com/openshift/hive/apis/hive/v1/metricsconfig/durationMetrics.go
  vendor/github.com/openshift/hive/apis/hive/v1/metricsconfig/metricsConfig.go
  vendor/github.com/openshift/hive/apis/hive/v1/metricsconfig/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/none/doc.go
  vendor/github.com/openshift/hive/apis/hive/v1/none/platform.go
  vendor/github.com/openshift/hive/apis/hive/v1/none/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/syncset_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#3012 [cluster-init] add the quay.io secret when generating the registry-pull-credentials secret
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#3014 Fix missing job names for disruption data uploading.
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Labels: approved, lgtm

#3013 Change minimum number of jobs to 6 instead of 3 for more accurate aggregation
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go
Labels: approved, lgtm

#2999 DPTP-3081 prReminder add held label
  cmd/pr-reminder/main.go
  cmd/pr-reminder/main_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3015 Add script oc_create_kubeconfig.sh
  images/ci-secret-generator/Dockerfile
  images/ci-secret-generator/oc_create_kubeconfig.sh
Labels: approved, lgtm

#3007 DPTP-3106 Create PodScalerReporter
  cmd/result-aggregator/main.go
  cmd/result-aggregator/main_test.go
  pkg/results/report.go
  pkg/results/report_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3020 remove the google cloud sdk repo in ci-secret-generator image
  images/ci-secret-generator/Dockerfile
  images/ci-secret-generator/google-cloud-sdk.repo
Labels: approved, lgtm

#3017 Add title for test analyzer variant to enhance readability
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunaggregatorlib/spyglass_summary.go
  pkg/jobrunaggregator/jobrunaggregatorlib/util.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
Labels: approved, lgtm

#3021 quay.io pull through cache image
  images/quayio-pull-through-cache/Dockerfile
  images/quayio-pull-through-cache/config.yml
  images/quayio-pull-through-cache/docker-entrypoint.sh
Labels: approved

#3028 Increase progress deadline for rpm server
  pkg/steps/rpm_server.go
Labels: approved, lgtm

#3029 Add owners to aggregator folder
  pkg/jobrunaggregator/OWNERS
Labels: approved, lgtm

#3024 Correct various misconfiguration problems in quay cache image
  images/quayio-pull-through-cache/Dockerfile
  images/quayio-pull-through-cache/config.yml
  images/quayio-pull-through-cache/docker-entrypoint.sh
Labels: approved, lgtm

#3016 feat: expose pr message and assignee to prcreator cli
  cmd/prcreator/main.go
Labels: approved, lgtm

#3030 ARMOCP-453: Adding the Packet QE Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#3027 DPTP-3106 add reporter to admission
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/main.go
  pkg/results/report.go
  pkg/results/report_test.go
  test/e2e/pod-scaler/run/consumer.go
Labels: approved, tide/merge-method-squash, lgtm

#3033 DPTP-3106 register pod-scaler metrics
  cmd/result-aggregator/main.go
Labels: approved, lgtm

#3034 Defaulting "metal" `/payload` jobs to `build05`
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3037 Fix replicas constant value
  pkg/steps/rpm_server.go
Labels: approved, lgtm

#3040 Observer Pods: fix null pointer dereference
  pkg/api/helper/imageextraction.go
Labels: approved, lgtm

#3041 Fixing panic caused by timeout bump logic
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
Labels: approved, lgtm

#3042 Initializing periodic.DecorationConfig
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
Labels: approved, lgtm

#3046 Bump aggregator to 6h at least temporarily.
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3043 Drop parsing of disruption data from junit test results.
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption_junit.go
Labels: approved, lgtm

#3047 sanitize-prow-jobs: operate on subdirectories
  cmd/sanitize-prow-jobs/main.go
Labels: approved, lgtm

#2965 retester: Add tests for retester
  cmd/retester/main.go
  cmd/retester/main_test.go
  pkg/retester/retester.go
  pkg/retester/retester_test.go
  pkg/retester/testdata/NewController/basic_case.yaml
  pkg/retester/testdata/jobconfig/simple.yaml
  pkg/retester/testdata/prowconfig/simple.yaml
  pkg/retester/testdata/testconfig/wrong_format.yaml
Labels: approved, lgtm, ok-to-test

#3026 add aws-outpost profile
  pkg/api/types.go
Labels: approved, lgtm, ok-to-test

#3019 Pods acquiring imagePullSecrets: race condition mitigation
  pkg/steps/multi_stage/init.go
  pkg/steps/release/create_release.go
  pkg/util/rbacs.go
Labels: approved, lgtm

#3053 Prowgen: multiarch postsubmit images
  cmd/ci-operator-prowgen/main.go
  pkg/api/types.go
  pkg/config/load.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
Labels: approved, lgtm

#3055 doc: get the members of a collection's group
  cmd/vault-secret-collection-manager/README.md
Labels: approved, lgtm
