Repository openshift/ci-tools, pull requests merged in 2023-09, with the labels that each got.

#3593 ci-operator-checkconfig: add README
  cmd/ci-operator-checkconfig/README.md
Labels: approved, lgtm

#3599 Disable aggregated testing for new disruption backends
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Labels: approved, lgtm

#3602 OPRUN-1873: promotion: allow configuring additional targets
  cmd/autopublicizeconfig/main.go
  cmd/ci-operator-config-mirror/main.go
  cmd/private-org-peribolos-sync/main.go
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
  cmd/private-prow-configs-mirror/main.go
  pkg/api/promotion.go
  pkg/api/promotion_test.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/promotion/promotion.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm, jira/valid-reference

#3578 TRT-932: Adding alert query for known alerts
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client_mock.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#3608 Revert "OPRUN-1873: promotion: allow configuring additional targets"
  cmd/autopublicizeconfig/main.go
  cmd/ci-operator-config-mirror/main.go
  cmd/private-org-peribolos-sync/main.go
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
  cmd/private-prow-configs-mirror/main.go
  pkg/api/promotion.go
  pkg/api/promotion_test.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/promotion/promotion.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm, jira/valid-reference

#3610 Revert "Merge pull request #3608 from hongkailiu/revert-3602-skuznets/multiple-promotion-targets"
  cmd/autopublicizeconfig/main.go
  cmd/ci-operator-config-mirror/main.go
  cmd/private-org-peribolos-sync/main.go
  cmd/private-org-sync/main.go
  cmd/private-org-sync/main_test.go
  cmd/private-prow-configs-mirror/main.go
  pkg/api/promotion.go
  pkg/api/promotion_test.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/promotion/promotion.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3605 SPLAT-1175: enable vsphere02 as a target for vSphere CI jobs
  pkg/api/types.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm, jira/valid-reference

#3613 [sanitize-prow-jobs] configure a different ci-operator image for the arm01 cluster
  cmd/sanitize-prow-jobs/main.go
Labels: approved, lgtm

#3612 map vsphere-8-vpn to cluster-profile-vsphere
  pkg/api/types.go
Labels: approved, lgtm

#3607 Remove envoyproxy old image
  images/envoyproxy/Dockerfile
  images/envoyproxy/config.yml
Labels: approved, lgtm

#3614 [sanitize-prow-jobs] configure a different ci-operator image for the arm01 cluster in postsubmits
  cmd/sanitize-prow-jobs/main.go
  cmd/sanitize-prow-jobs/main_test.go
Labels: approved, lgtm

#3618 Add GCP arm64 cluster profile: gcp-arm64
  pkg/api/types.go
Labels: approved, lgtm

#3604 Fix issue DPTP-3621 Add unmanaged flag to cluster-init
  cmd/cluster-init/build_clusters.go
  cmd/cluster-init/main.go
  cmd/cluster-init/main_test.go
  cmd/cluster-init/update_bootstrap_secrets.go
  cmd/cluster-init/update_secret_generator.go
Labels: approved, lgtm

#3620 `multi-arch-builder-controller`: add manifest-tool
  images/multi-arch-builder-controller/Dockerfile
Labels: approved, lgtm

#3619 add the sanitize-prow-jobs binary in the ci-operator-prowgen image
  images/ci-operator-prowgen/Dockerfile
Labels: approved, lgtm

#3617 Makefile: determinize input ci-operator configs
  Makefile
  test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/foo/barry-white/foo-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/barry-white/super-priv-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/barry-white/super-priv-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/deprecated-repo/super-priv-deprecated-repo-master.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super-priv/trooper/super-priv-trooper-deprecated.yaml
  test/integration/ci-operator-config-mirror/input-to-clean/super/looper/super-looper-master.yaml
  test/integration/ci-operator-config-mirror/input/foo/barry-white/foo-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/input/foo/barry-white/foo-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/input/foo/barry-white/foo-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/input/super/looper/super-looper-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output-only-super/foo/barry-white/foo-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super/looper/super-looper-master.yaml
  test/integration/ci-operator-config-mirror/output/foo/barry-white/foo-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output/foo/barry-white/foo-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output/foo/barry-white/foo-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output/super-priv/barry-white/super-priv-barry-white-official__releases.yaml
  test/integration/ci-operator-config-mirror/output/super/looper/super-looper-master.yaml
  test/integration/ci-operator-prowgen/input/config/legacy/branches-separate-files/legacy-branches-separate-files-branch.yaml
  test/integration/ci-operator-prowgen/input/config/legacy/branches-separate-files/legacy-branches-separate-files-master.yaml
  test/integration/ci-operator-prowgen/input/config/legacy/random-file/legacy-random-file-master.yaml
  test/integration/ci-operator-prowgen/input/config/norehearsals/duper/norehearsals-duper-master.yaml
  test/integration/ci-operator-prowgen/input/config/norehearsals/stuper/norehearsals-stuper-master.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-job-release.yaml
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/config-brancher/expected/org/new/org-new-master.yaml
  test/integration/config-brancher/input/org/bump/org-bump-master.yaml
  test/integration/config-brancher/input/org/bump/org-bump-master__releases.yaml
  test/integration/config-brancher/input/org/existing/org-existing-master.yaml
  test/integration/config-brancher/input/org/existing/org-existing-release-4.5.yaml
  test/integration/config-brancher/input/org/existing/org-existing-release-4.6.yaml
  test/integration/config-brancher/input/org/new/org-new-master.yaml
  test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/candidate/ci-operator/config/uses/observer/uses-observer-master.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/config/super/trooper/super-trooper-master.yaml
  test/integration/pj-rehearse/master/ci-operator/config/uses/observer/uses-observer-master.yaml
  test/integration/repo-init/input/ci-operator/config/openshift/origin/openshift-origin-master.yaml
Labels: approved, lgtm

#3621 TRT-1243: add release-ocp-4.15.json to include control-plane-machine-…
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
Labels: approved, lgtm, jira/valid-reference

#3622 TRT-1243: manual update for generated_job_names.txt
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Labels: approved, lgtm, jira/valid-reference

#3623 select vsphere build cluster to use based on cluster-profile
  pkg/api/types.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm

#3583 ci-images-mirror: reconcile on the tags of test input
  cmd/ci-images-mirror/main.go
  hack/run-ci-images-mirror.sh
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3582 Add prow job wait mechanism using informers from CI cluster
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go
  pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client_mock.go
  pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go
  pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator_per_pr_jobs.go
  pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator_release_jobs.go
  pkg/jobrunaggregator/jobrunaggregatorlib/util.go
  pkg/jobrunaggregator/jobrunaggregatorlib/util_test.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
  vendor/k8s.io/test-infra/prow/client/informers/externalversions/factory.go
  vendor/k8s.io/test-infra/prow/client/informers/externalversions/generic.go
  vendor/k8s.io/test-infra/prow/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/test-infra/prow/client/informers/externalversions/prowjobs/interface.go
  vendor/k8s.io/test-infra/prow/client/informers/externalversions/prowjobs/v1/interface.go
  vendor/k8s.io/test-infra/prow/client/informers/externalversions/prowjobs/v1/prowjob.go
  vendor/k8s.io/test-infra/prow/client/listers/prowjobs/v1/expansion_generated.go
  vendor/k8s.io/test-infra/prow/client/listers/prowjobs/v1/prowjob.go
  vendor/modules.txt
Labels: approved, lgtm

#3624 quay_io_ci_images_distributor: generate mirror tasks
  cmd/ci-images-mirror/main.go
  hack/run-ci-images-mirror.sh
  pkg/api/promotion.go
  pkg/controller/quay_io_ci_images_distributor/mirror.go
  pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3637 Revert "add the sanitize-prow-jobs binary in the ci-operator-prowgen image"
  images/ci-operator-prowgen/Dockerfile
Labels: approved, lgtm

#3633 testgrid-config-generator: allow OLM tests
  cmd/testgrid-config-generator/main.go
  cmd/testgrid-config-generator/main_test.go
Labels: approved, lgtm

#3627 quay_io_ci_images_distributor: consume mirroring tasks
  cmd/ci-images-mirror/main.go
  pkg/controller/quay_io_ci_images_distributor/mirror.go
  pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3642 run-prow-job-dispatcher.sh: overwrite RELEASE path
  hack/run-prow-job-dispatcher.sh
Labels: approved, lgtm

#3639 `observer pods`: add StepParameters
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/steps/multi_stage/gen.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3645 Updating Owners
  OWNERS
Labels: approved, lgtm

#3630 TRT-1243: All changes to get 4.15 in sync as well as prior 4.14 && 4.…
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Labels: approved, lgtm, jira/valid-reference

#3653 aggregation: pods should never panic
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#3646 Fix make-cluster-display
  Makefile
Labels: approved, lgtm

#3656 Bump test-infra to v0.0.0-20230928115035-61f80eaf9972
  go.mod
  go.sum
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
  vendor/github.com/cjwagner/httpcache/.travis.yml
  vendor/github.com/cjwagner/httpcache/LICENSE.txt
  vendor/github.com/cjwagner/httpcache/README.md
  vendor/github.com/cjwagner/httpcache/diskcache/diskcache.go
  vendor/github.com/cjwagner/httpcache/httpcache.go
  vendor/github.com/cjwagner/httpcache/redis/redis.go
  vendor/k8s.io/test-infra/ghproxy/ghcache/ghcache.go
  vendor/k8s.io/test-infra/prow/config/agent.go
  vendor/k8s.io/test-infra/prow/config/cache.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/inrepoconfig.go
  vendor/k8s.io/test-infra/prow/config/moonraker.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/secret/reloader.go
  vendor/k8s.io/test-infra/prow/flagutil/config/config.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/gerrit/adapter/adapter.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/git/v2/adapter.go
  vendor/k8s.io/test-infra/prow/git/v2/client_factory.go
  vendor/k8s.io/test-infra/prow/git/v2/interactor.go
  vendor/k8s.io/test-infra/prow/git/v2/remote.go
  vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/hook/events.go
  vendor/k8s.io/test-infra/prow/jira/jira.go
  vendor/k8s.io/test-infra/prow/kube/config.go
  vendor/k8s.io/test-infra/prow/moonraker/client.go
  vendor/k8s.io/test-infra/prow/moonraker/moonraker.go
  vendor/k8s.io/test-infra/prow/pod-utils/downwardapi/jobspec.go
  vendor/k8s.io/test-infra/prow/secretutil/censor.go
  vendor/k8s.io/test-infra/prow/tide/gerrit.go
  vendor/k8s.io/test-infra/prow/tide/tide.go
  vendor/modules.txt
Labels: approved, lgtm

#3417 Fix issue DPTP-3440 Add server-side apply support
  cmd/applyconfig/README.md
  cmd/applyconfig/applyconfig.go
  cmd/applyconfig/applyconfig_test.go
Labels: tide/merge-method-rebase, approved, lgtm

#3654 cluster-display: cache page data
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
Labels: approved, lgtm
