Repository openshift/ci-tools, pull requests merged in 2023-05, with the labels that each got.

#3403 Fix bug for deleting base domain
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#3390 pkg/steps: add build pending timeout period
  cmd/ci-operator/main_test.go
  pkg/defaults/defaults.go
  pkg/kubernetes/client.go
  pkg/steps/bundle_source.go
  pkg/steps/git_source.go
  pkg/steps/index_generator.go
  pkg/steps/multi_stage/run_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/testhelper/kubernetes/pod.go
  pkg/util/builds.go
  pkg/util/pods.go
Labels: approved, lgtm

#3398 test/e2e: relax pending test check
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#3406 [LPTOCPCI-210] Add New aws-cspi-qe-vpn Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#3405 sync-rover-groups: collect users' cost center
  Makefile
  cmd/sync-rover-groups/ldap.go
  cmd/sync-rover-groups/ldap_test.go
  cmd/sync-rover-groups/main.go
Labels: approved, lgtm

#3407 `payload-testing`: force telco5g jobs to build05
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
Labels: approved, lgtm

#3408 github-ldap-user-group-creator: upload users to bigquery
  cmd/github-ldap-user-group-creator/main.go
  cmd/sync-rover-groups/ldap.go
  cmd/sync-rover-groups/main.go
  pkg/rover/bigquery.go
  pkg/rover/types.go
Labels: approved, lgtm

#3409 Revert "pkg/steps: add build pending timeout period"
  cmd/ci-operator/main_test.go
  pkg/defaults/defaults.go
  pkg/kubernetes/client.go
  pkg/steps/bundle_source.go
  pkg/steps/git_source.go
  pkg/steps/index_generator.go
  pkg/steps/multi_stage/run_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/testhelper/kubernetes/pod.go
  pkg/util/builds.go
  pkg/util/pods.go
Labels: approved, priority/critical-urgent, lgtm

#3399 one build for aggregate jobs (V7)
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3410 trt-945: fix to use NullString for MasterNodesUpdated
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go
  pkg/jobrunaggregator/jobrunbigqueryloader/types.go
Labels: approved, lgtm, jira/valid-reference

#3411 Revert "one build for aggregate jobs (V7)"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3412 Fix a lint issue
  pkg/prowgen/podspec_test.go
Labels: approved, lgtm

#3414 [image-graph-generator] include multiple inputs on all images in the graph as parents
  cmd/image-graph-generator/types.graphql
  pkg/image-graph-generator/images.go
  pkg/image-graph-generator/images_test.go
  pkg/image-graph-generator/manifests.go
Labels: approved, lgtm

#3413 sync-rover-group: remove flag/mapping-file
  cmd/sync-rover-groups/ldap.go
  cmd/sync-rover-groups/main.go
Labels: approved, lgtm

#3416 `pr-reminder`: Replace --github-mapping-config-path
  cmd/pr-reminder/README.md
  cmd/pr-reminder/main.go
  hack/local-pr-reminder.sh
  hack/pr-reminder-config.yaml
  pkg/rover/types.go
Labels: approved, lgtm

#3419 Ensure sippy-config-generator is deterministic
  cmd/sippy-config-generator/main.go
Labels: approved, lgtm

#3421 `payload-testing`: allow for aborting all payload jobs for a PR with a command
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3424 `payload-testing`: bug fix and cleanup
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
Labels: approved, lgtm

#3423 Improve test case analyzer titles
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
Labels: approved, lgtm

#3426 `pod-scaler`: add logging when determined amount smaller than configured
  cmd/pod-scaler/admission.go
Labels: approved, lgtm

#3425 `payload-testing`: continue on failure to get prowjob
  cmd/payload-testing-prow-plugin/server.go
Labels: approved, lgtm

#3430 ignore etcd
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#3415 `payload-testing`: One build for aggregate jobs
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Labels: approved, lgtm

#3433 Improve test case analyzer titles, part 2
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
Labels: approved, lgtm

#3434 Append timestamp to job-run-summary HTML
  pkg/jobrunaggregator/jobrunaggregatorlib/util.go
Labels: approved, lgtm

#3435 Revert "`payload-testing`: One build for aggregate jobs"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Labels: approved, lgtm

#3439 Revert "Append timestamp to job-run-summary HTML"
  pkg/jobrunaggregator/jobrunaggregatorlib/util.go
Labels: approved, lgtm

#3440 `sprint-automation`: remove secondary triage roles
  cmd/sprint-automation/README.md
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#3438 Stop building image/quayio-pull-through-cache in ci-tools
  images/quayio-pull-through-cache/Dockerfile
  images/quayio-pull-through-cache/config.yml
  images/quayio-pull-through-cache/docker-entrypoint.sh
Labels: approved, lgtm

#3442 split the job-config-master-* config maps into master and main
  pkg/api/metadata.go
  pkg/api/metadata_test.go
  pkg/jobconfig/files.go
  pkg/jobconfig/files_test.go
Labels: approved, lgtm

#3443 Revert "Increase timeouts for payload jobs to land k8s 1.27"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3444 pod-scaler: use non-preempting priority class
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_with_labels.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data_patch.yaml
Labels: approved, lgtm

#3441 `prowgen`: promote on `multi01`
  pkg/config/load.go
  pkg/prowgen/podspec.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForPromotion_default_cluster_only.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForPromotion_spawn_on_multi01_and_arm01.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForPromotion_spawn_on_multi01_cluster.yaml
Labels: approved, tide/merge-method-squash, lgtm

#3447 Add new profile: aws-perf-qe
  pkg/api/types.go
Labels: approved, lgtm

#3431 ci-operator: do not log cancelled observers
  pkg/steps/multi_stage/run.go
  pkg/steps/pod.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/template.go
  pkg/util/pods.go
  pkg/util/util.go
Labels: approved, lgtm

#3427 pkg/steps: add build pending timeout period
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/defaults/defaults.go
  pkg/kubernetes/client.go
  pkg/steps/bundle_source.go
  pkg/steps/git_source.go
  pkg/steps/index_generator.go
  pkg/steps/multi_stage/run_test.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/testhelper/kubernetes/pod.go
  pkg/util/builds.go
  pkg/util/pods.go
Labels: approved, lgtm

#3325 ci-operator: print pruned graph
  cmd/ci-operator/main.go
  hack/graphviz.sh
Labels: approved, lgtm

#3391 pkg/steps: add error reason for pending pods
  pkg/api/constant.go
  pkg/util/builds.go
  pkg/util/pods.go
Labels: approved, lgtm

#3451 ci-operator: log events when pods are deleted
  pkg/util/pods.go
Labels: approved, lgtm

#3455 [ci-operator] pass a null logger to controllerruntime when the verbose option is false
  cmd/ci-operator/main.go
  go.mod
Labels: approved, lgtm
