Repository openshift/ci-tools, pull requests merged in 2023-03, with the labels that each got.

#3309 Change adjustment for required passes from -2 to -1
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
Labels: approved, lgtm

#3307 Revert timeouts
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3311 Exclude ci cluster backend when aggregate disruption tests
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Labels: approved, lgtm

#3312 test/e2e: use latest OCP releases
  test/e2e/simple/dynamic-releases.yaml
Labels: approved, lgtm

#3257 Enable possibility to change cloud assignment during dispatch
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm

#3317 Skip disruption aggregation for azure jobs for now
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Labels: approved, lgtm

#3314 DPTP-3326: Allow clusterpools to specify a release stream to select the release version from
  cmd/clusterimageset-updater/main.go
  pkg/api/types.go
  pkg/release/prerelease/client.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm, jira/valid-reference

#3318 Create a dedicated aws cluster profile for managed aws cspi qe
  pkg/api/types.go
Labels: approved, lgtm

#3291 `pod-scaler`: add priority scheduling class when CPU request is above a certain amount
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/main.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_with_labels.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data_patch.yaml
Labels: approved, tide/merge-method-squash, lgtm

#3313 Operate on builds based on the list of architectures supported in the cluster
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/build_client.go
  pkg/steps/bundle_source.go
  pkg/steps/git_source.go
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm

#3321 Revert "`pod-scaler`: add priority scheduling class when CPU request is above a certain amount"
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/main.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_with_labels.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data_patch.yaml
Labels: approved, lgtm

#3316 `pj-rehearse`: downgrade useless warning to debug
  pkg/rehearse/jobs.go
Labels: approved, lgtm

#3324 Sprint Automation: Handle nil Jira assignee
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#3322 SPLAT-980: introduce vSphere IBM 7 dedicated lease slice
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#3281 pkg/util: use a watch to wait for pods
  pkg/kubernetes/client.go
  pkg/kubernetes/client_test.go
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/cluster_claim.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/source.go
  pkg/testhelper/kubernetes/pod.go
  pkg/util/pods.go
  pkg/util/pods_test.go
  pkg/util/util.go
  test/e2e/multi-stage/config.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#3326 `pj-rehearse`: properly bubble up errors from loading configuration
  cmd/config-change-trigger/main.go
  pkg/config/release.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3327 oo-testing: opt out building index image
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3329 Revert "oo-testing: opt out building index image"
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3333 [azure] add QE dedicated azure cluster profile for marketplace image testing
  pkg/api/types.go
Labels: approved, lgtm

#3334 Stop resolving the namespace on images for different os architectures
  cmd/ci-operator-checkconfig/main.go
  cmd/promoted-image-governor/main.go
  cmd/registry-replacer/main.go
  cmd/repo-init/api.go
  pkg/api/helper/imageextraction.go
  pkg/api/metadata.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/zz_generated.deepcopy.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm

#3331 Revert "Revert "oo-testing: opt out building index image""
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_operator_section_creates_ci_index_my_bundle_presubmit_job.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_operator_section_without_index_creates_ci_index_my_bundle_presubmit_job.yaml
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/framework/ci-operator.go
  test/e2e/optional-operators/e2e_test.go
  test/e2e/optional-operators/optional-operators.yaml
Labels: approved, lgtm

#3335 Pod-scaler admission: Better prow job names
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
Labels: approved, lgtm

#3330 `pj-rehearse`: better error output
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3320 Fall back to older releases disruption data during release transition
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
Labels: approved, lgtm

#3336 SPLAT-728: added AWS local zones profile
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#3337 Add support for updating alert/disruption data for a past release.
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/cmd.go
Labels: approved, lgtm

#3339 SPLAT-728: fix/adding dedicated quota slice to the aws-local-zones
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#3340 Remove index from input-hash to facilitate a single build for aggregated jobs
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Labels: approved, lgtm

#3341 Revert "Remove index from input-hash to facilitate a single build for aggregated jobs"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Labels: approved, lgtm

#3343 One build for aggregate payload jobs
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Labels: approved, tide/merge-method-squash, lgtm

#3344 Update generated jobnames files
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Labels: approved, lgtm

#3346 Revert "One build for aggregate payload jobs"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
Labels: approved, lgtm

#3348 `pj-rehearse`: fix error comment format
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3342 retester: interfacing backoffCache
  pkg/retester/cache.go
  pkg/retester/fileBackOffCache.go
  pkg/retester/retester.go
  pkg/retester/retester_test.go
Labels: approved, lgtm

#3355 `ci-operator`: Add helper to set target-additional-suffix
  pkg/prowgen/podspec.go
  pkg/prowgen/podspec_test.go
  pkg/prowgen/testdata/zz_fixture_TestTargetAdditionalSuffix_target_additional_suffix_is_added.yaml
Labels: approved, lgtm

#3350 OTA-925: pkg/steps/release/import_release: Set release.openshift.io/config name annotation
  pkg/steps/release/import_release.go
Labels: approved, lgtm, jira/valid-reference

#3358 Add new Power VS leases to control zoning
  pkg/api/types.go
Labels: approved, lgtm

#3353 promotionreconciler: ignore imagestreams
  cmd/dptp-controller-manager/main.go
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
Labels: approved, lgtm
