Repository openshift/ci-tools, pull requests merged in 2023-01, with the labels that each got.

#3217 Add new cluster profiles for OpenShift Virtualization
  pkg/api/types.go
Labels: approved, lgtm

#3134 private-org-sync: document merge conflict policy
  cmd/private-org-sync/README.md
  cmd/private-org-sync/main_test.go
Labels: approved, lgtm

#3215 `pj-rehearse`: dump affected jobs list to GCS when there are more than 35 jobs affected
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3214 pkg/release: process relative pre-releases
  cmd/clusterimageset-updater/main.go
  cmd/payload-testing-prow-plugin/rcjobresolver.go
  cmd/release-job-migrator/main.go
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/branchcuts/bumper/gen-release-jobs-bumper.go
  pkg/prowgen/jobbase_test.go
  pkg/release/candidate/client.go
  pkg/release/candidate/client_test.go
  pkg/release/config/client.go
  pkg/release/config/client_test.go
  pkg/release/prerelease/client.go
  pkg/release/prerelease/client_test.go
  pkg/validation/release_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3195 SPLAT-910: introduce vsphere 8 cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3221 Standardize check for periodic
  cmd/ci-operator-config-mirror/main.go
  cmd/config-brancher/main.go
  cmd/payload-testing-prow-plugin/filetestresolver.go
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/rehearse/jobs.go
Labels: approved, lgtm

#3218 Increase timeouts for payload jobs to land k8s 1.26
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3224 `pj-rehearse`: double wait for ist creation
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3225 ci-secret-bootstrap: log some stats of secrets
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/secretstats.go
  cmd/ci-secret-bootstrap/secretstats_test.go
Labels: approved, lgtm

#3229 secret-bootstrap: update secrets only when needed
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#3157 pkg/steps: handle missing secret in index step
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
Labels: approved, lgtm

#3068 Allow setting always_run in the ci-operator config
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_always_run_false.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3232 secret-bootstrap: reduce #API calls to get namespaces
  cmd/ci-secret-bootstrap/main.go
Labels: approved, lgtm

#3233 Specify initial `localgit` branch
  cmd/ci-operator-yaml-creator/main_test.go
  cmd/publicize/server_test.go
Labels: approved, lgtm

#3230 `repo-init`: don't duplicate plugins that are already configured at the org level
  cmd/repo-init/main.go
  cmd/repo-init/main_test.go
Labels: approved, lgtm

#3234 dptp-pools-cm: recognize controller hypershift_namespace_reconciler
  cmd/dptp-pools-cm/main.go
Labels: approved, lgtm

#3220 cluster-display: update error handling for cluster list
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
Labels: approved, lgtm

#3239 `pj-rehearse`: clarify where to obtain usage info
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3241 cluster-display: return zero value when err!=nil
  cmd/cluster-display/main.go
Labels: approved, lgtm

#3242 oo testing: skip building index images when file-based index is used
  pkg/steps/index_generator.go
Labels: approved, tide/merge-method-squash, lgtm

#3245 First pass at logging improvements for job run analyzer
  pkg/jobrunaggregator/cmd.go
  pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
  pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Labels: approved, lgtm

#3213 Change the way clusters are disabled during failover
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
Labels: approved, lgtm

#3248 `pj-rehearse`: change logging to info for non-platform errors
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3240 Include test grid url for non payload jobs on the informing dashboard
  cmd/sippy-config-generator/main.go
  cmd/testgrid-config-generator/main.go
  pkg/util/testgrid.go
Labels: approved, lgtm

#3247 Limit concurrency of bigquery job uploads, fix memory spikes
  pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go
  pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
  pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Labels: approved, lgtm

#3250 Makefile: add Hive token target for `local-e2e`
  Makefile
Labels: approved, lgtm

#3251 Fix missing default log level
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
Labels: approved, lgtm

#2888 junit: fix xml.Name for testsuite properties
  pkg/junit/types.go
  pkg/junit/types_test.go
  test/e2e/observer/artifacts/failing-observer-junit_operator.xml
  test/e2e/observer/artifacts/multi-observers-junit_operator.xml
  test/e2e/observer/artifacts/simple-observer-junit_operator.xml
  test/e2e/simple/artifacts/junit_operator.xml
Labels: approved, lgtm

#3252 pkg/util: improve pod pending check
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/kubernetes/client.go
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage/run_test.go
  pkg/steps/pod_test.go
  pkg/testhelper/kubernetes/pod.go
  pkg/util/pods.go
  pkg/util/pods_test.go
Labels: approved, lgtm

#3255 More logging to identify deadlock
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Labels: approved, lgtm

#3259 `pj-rehearse`: add usage details to the response from refresh command
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3261 Add cluster-control-plane-machine-set-operator to sippy/testgrid
  pkg/util/testgrid.go
Labels: approved, lgtm

#3265 promoted-image-governor: log err when unable to delete an IS
  cmd/promoted-image-governor/main.go
Labels: approved, lgtm

#3268 promoted-image-governor: do not log succecss deleting on errors
  cmd/promoted-image-governor/main.go
Labels: approved, lgtm

#3266 Use ocp/4.12:cli to promote images
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
Labels: approved, lgtm

#3263 Use Testplatform BigQuery for ProwJobs to upload alert/disruption/test data from
  pkg/branchcuts/bumper/release-controller-config-bumper.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
  pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cidataclient_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3226 payload-testing: renamed jobs name, add requestor, link to docs, links for release controller and its config
  cmd/payload-testing-ui/server.go
Labels: approved, lgtm, ok-to-test

#3267 `pod-scaler`: modify pruning logic to only keep 25 fingerprints
  pkg/pod-scaler/types.go
  pkg/pod-scaler/types_test.go
  test/e2e/pod-scaler/prometheus/backfill.go
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data_patch.yaml
Labels: approved, tide/merge-method-squash, lgtm
