Repository openshift/ci-tools, pull requests merged in 2023-04, with the labels that each got.

#3359 Revert "test-images-distributor: distribute multiarch IS"
  pkg/controller/test-images-distributor/test_images_distributor.go
Labels: approved, lgtm

#3347 Add nutanix disconnected profile
  pkg/api/types.go
Labels: approved, lgtm

#3360 Revert "Update generated jobnames files"
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Labels: approved, lgtm

#3362 fix: update to ref 4.13 and 4.14 hypershift file
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
Labels: approved, lgtm

#3361 Revert "Skip disruption aggregation for azure jobs for now"
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Labels: approved, lgtm

#3365 Add envoyproxy and configs
  images/envoyproxy/Dockerfile
  images/envoyproxy/config.yml
Labels: approved, lgtm

#3363 `ci-operator`: trim target-additional-suffix for input resolution
  cmd/ci-operator/main.go
Labels: approved, lgtm

#3367 Revert "One build for aggregate jobs v.4"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3366 PowerVS: remove old powervs
  pkg/api/types.go
Labels: approved, lgtm

#3368 Add grpc headers in envoyproxy
  images/envoyproxy/config.yml
Labels: approved, lgtm

#3369 fix nutanix disconnected profile
  pkg/api/types.go
Labels: approved, lgtm

#3374 Changes to enable configuration with API access
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_standard_test_with_api_access_enabled.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3373 Increase timeouts for payload jobs to land k8s 1.27
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3377 Upgrade test-infra
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_combined.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_multiple_ga.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_multiple_ga_410_bigger_49.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_multiple_ga_411_biger_41.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_onega.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_open.yaml.yaml
  cmd/branchingconfigmanagers/bugzilla-config-manager/testdata/zz_fixture_TestRun_lifecycle_open_and_codefree_e.yaml.yaml
  cmd/determinize-prow-config/main_test.go
  cmd/private-prow-configs-mirror/main.go
  cmd/private-prow-configs-mirror/main_test.go
  go.mod
  go.sum
  pkg/api/shardprowconfig/shardprowconfig.go
  pkg/prowconfigsharding/prowconfigsharding_test.go
  pkg/prowconfigutils/tide.go
  pkg/prowconfigutils/tide_test.go
  vendor/k8s.io/test-infra/prow/cache/cache.go
  vendor/k8s.io/test-infra/prow/config/cache.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/gangway.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/flagutil/config/config.go
  vendor/k8s.io/test-infra/prow/flagutil/controller_manager.go
  vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
  vendor/k8s.io/test-infra/prow/gerrit/adapter/adapter.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/git/v2/adapter.go
  vendor/k8s.io/test-infra/prow/git/v2/client_factory.go
  vendor/k8s.io/test-infra/prow/git/v2/interactor.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/github/types.go
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/pull-request.go
  vendor/k8s.io/test-infra/prow/tide/codereview.go
  vendor/k8s.io/test-infra/prow/tide/gerrit.go
  vendor/k8s.io/test-infra/prow/tide/github.go
  vendor/k8s.io/test-infra/prow/tide/status.go
  vendor/k8s.io/test-infra/prow/tide/tide.go
  vendor/modules.txt
Labels: approved, tide/merge-method-squash, lgtm

#3375 One build for payload aggregate command (v.5)
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3380 Revert "One build for payload aggregate command (v.5)"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3378 sprint-automation: opt out sending b02's upgrade notifications
  cmd/sprint-automation/main.go
Labels: approved, lgtm

#3379 `pj-rehearse` use the synchronize event to auto refresh job list
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
Labels: approved, tide/merge-method-squash, lgtm

#3383 include multi01 cluster on registry domain resolving
  pkg/api/domain.go
  pkg/api/domain_test.go
  pkg/api/types.go
Labels: approved, lgtm

#3154 cmd/release: initial commit
  cmd/release/README.md
  cmd/release/main.go
  pkg/cmd/release/config.go
  pkg/cmd/release/jobs.go
  pkg/cmd/release/profile.go
  pkg/cmd/release/registry.go
  pkg/cmd/release/release.go
  pkg/cmd/release/util.go
  pkg/cmd/release/util_test.go
  pkg/config/load.go
  pkg/load/agents/registryAgent.go
  pkg/registry/resolver.go
  pkg/util/util.go
Labels: approved, lgtm

#3384 cmd/release: correct example
  cmd/release/README.md
Labels: approved, lgtm

#3382 `ci-operator`: trim target-additional-suffix from profile secret name
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/multi_stage/gen_test.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/multi_stage/multi_stage_test.go
  pkg/steps/multi_stage/run_test.go
Labels: approved, lgtm

#3381 Support creating testgrid dashboards automatically for manged service…
  cmd/testgrid-config-generator/main.go
Labels: approved, lgtm

#3386 Fix issue DPTP-3312 Remove Route53 zones
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm, do-not-merge/hold

#3389 one build for aggregate runs (V6)
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3392 Revert "one build for aggregate runs (V6)"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3385 pkg/steps: emit detailed build errors in debug log
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm

#3393 Change prowgen param name from api to remote_api
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3395 apply global git configuration to private-org-sync Dockerfile
  images/private-org-sync/Dockerfile
Labels: approved, lgtm

#3396 [private-org-sync] update potential errors to try to fetch a deeper history
  cmd/private-org-sync/main.go
Labels: approved, lgtm

#3323 `pod-scaler`: add priorityClassName when CPU above 8
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/main.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_with_labels.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data_patch.yaml
Labels: approved, tide/merge-method-squash, lgtm

#3387 Fix issue DPTP-3312 Clean up base domain in Route53
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#3397 trt-945: support MasterNodesUpdated indicator
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go
  pkg/jobrunaggregator/jobrunaggregatorlib/disruption.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
Labels: approved, lgtm, jira/valid-reference

#3401 Revert "trt-945: support MasterNodesUpdated indicator"
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go
  pkg/jobrunaggregator/jobrunaggregatorlib/disruption.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
Labels: approved, lgtm, jira/valid-reference
