Repository openshift/ci-tools, pull requests merged in 2023-07, with the labels that each got.

#3524 promotionreconciler considers isTag with manifests
  pkg/api/helper/imagestreamtag.go
  pkg/api/types.go
  pkg/config/load.go
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/steps/index_generator.go
  pkg/steps/index_generator_test.go
  pkg/steps/source.go
Labels: approved, lgtm

#3527 Revert "Change prowgen param name from api to remote_api"
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_for_standard_test_with_api_access_enabled.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3528 Modify fileresolver to allow payload plugin to trigger all openshift periodics
  cmd/payload-testing-prow-plugin/filetestresolver.go
  cmd/payload-testing-prow-plugin/filetestresolver_test.go
Labels: approved, lgtm

#3319 ci-operator: optionally decorate test pods
  pkg/steps/artifacts.go
  pkg/steps/multi_stage/gen_test.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
  pkg/steps/testdata/zz_fixture_envTestGetPodObjectMounts_with_cluster_claim.yaml
  pkg/util/util.go
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#3530 Revert "ci-operator: optionally decorate test pods"
  pkg/steps/artifacts.go
  pkg/steps/multi_stage/gen_test.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/pod.go
  pkg/steps/pod_test.go
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
  pkg/steps/testdata/zz_fixture_envTestGetPodObjectMounts_with_cluster_claim.yaml
  pkg/util/util.go
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#3531 add etcd_golang-1.19 to streams to ignore mirror=false from
  pkg/api/ocpbuilddata/types.go
Labels: approved, lgtm

#3526 pkg/util: warn when directory is ignored in secret
  pkg/util/secret.go
Labels: approved, lgtm

#3533 vSphere 8: add vpn cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3512 OTA-905: cincinnati client: query integration & staging instances
  pkg/release/official/client.go
Labels: approved, lgtm, jira/valid-reference

#3522 Include registry in the target name
  pkg/api/promotion.go
  pkg/api/promotion_test.go
  pkg/defaults/defaults.go
  pkg/steps/release/promote.go
Labels: approved, lgtm

#3491 pkg/util: demote msg. to debug log when skipped
  pkg/util/pods.go
Labels: approved, lgtm

#3457 ci-operator: remove claim release image from input
  pkg/defaults/defaults.go
  pkg/steps/release/import_release.go
  pkg/steps/release/source.go
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm

#3538 pkg/defaults: correct release steps for claims
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#3525 `agents`: initialization failures do not result in an error
  cmd/ci-operator-checkconfig/main.go
  cmd/ci-operator-configresolver/main.go
  cmd/dptp-controller-manager/main.go
  cmd/payload-testing-prow-plugin/filetestresolver_test.go
  cmd/payload-testing-prow-plugin/main.go
  pkg/config/load.go
  pkg/load/agents/configAgent.go
  pkg/load/agents/registryAgent.go
  pkg/load/agents/utils.go
  pkg/load/load.go
Labels: approved, lgtm, ok-to-test

#3537 add QE perf profiles: aws-perfscale-qe and aws-perfscale-lrc-qe
  pkg/api/types.go
Labels: approved, lgtm

#3532 TRT-1120: Support single pass to collect gcs files
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go
  pkg/jobrunaggregator/jobrunaggregatorapi/interfaces.go
  pkg/jobrunaggregator/jobrunaggregatorapi/jobruninfo_mock.go
  pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Labels: approved, lgtm, jira/valid-reference

#3542 Add CCO prefix to testgrid informing
  pkg/util/testgrid.go
Labels: approved, lgtm

#3546 test/e2e: wait for fake Kubernetes server
  test/e2e/pod-scaler/kubernetes/kubernetes.go
Labels: approved, lgtm

#3543 Include Renamed Managed OpenShift Jobs To TestGrid Dashboards
  cmd/testgrid-config-generator/main.go
Labels: approved, lgtm

#3547 Remove vsphere-discon profile
  pkg/api/types.go
Labels: approved, lgtm

#3540 create aws-terraform-qe profile
  pkg/api/types.go
Labels: approved, lgtm

#3487 multi-stage: properly name role binding
  pkg/steps/multi_stage/init.go
Labels: approved, lgtm

#3506 ci-operator: use a single PDB
  cmd/ci-operator/main.go
Labels: approved, lgtm

#3544 test/e2e: mark logging wrapper as helpers
  pkg/testhelper/accessory.go
Labels: approved, lgtm

#3545 update references to `forum-testplatform` to `forum-ocp-testplatform`
  cmd/ci-operator-yaml-creator/main.go
  cmd/slack-bot/README.md
  cmd/slack-bot/main.go
  cmd/vault-subpath-proxy/kv_update_transport.go
  pkg/controller/hypershift_namespace_reconciler/README.md
  pkg/slack/events/helpdesk/helpdesk-message.go
Labels: approved, lgtm

#3552 Bump test-infra
  go.mod
  go.sum
  pkg/steps/artifacts.go
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/inrepoconfig.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/entrypoint/options.go
  vendor/k8s.io/test-infra/prow/entrypoint/run.go
  vendor/k8s.io/test-infra/prow/gerrit/adapter/adapter.go
  vendor/k8s.io/test-infra/prow/git/v2/executor.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/modules.txt
Labels: approved, lgtm

#3555 Increase timeouts for payload jobs to land k8s 1.28
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3556 Fix issue DPTP-3312 Remove broken clusters
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm
