Repository openshift/ci-tools, pull requests merged in 2023-08, with the labels that each got.

#3539 ci-operator: add reason for missing dependencies
  cmd/ci-operator/main.go
Labels: approved, lgtm

#3564 include the whitelisted repositories on different organization than --only-org
  cmd/ci-operator-config-mirror/main.go
  pkg/config/load.go
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-master.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-official.yaml
  test/integration/ci-operator-config-mirror/output-only-super/super-priv/barry-white/super-priv-barry-white-official__releases.yaml
Labels: approved, lgtm

#3572 test/e2e: update error message
  test/e2e/observer/artifacts/failing-observer-junit_operator.xml
  test/e2e/observer/artifacts/multi-observers-junit_operator.xml
Labels: approved, lgtm

#3565 Fix issue DPTP-3312 Add oc and hypershift CLI
  images/dptp-3312-hypershift-leaks-cleaner/Dockerfile
Labels: approved, lgtm

#3574 Revert "Replace use of JobRuns tables in ci data client"
  pkg/jobrunaggregator/cmd.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
Labels: approved, lgtm

#3560 `observer pods`: propagate the entrypoint's child exit code
  pkg/steps/artifacts.go
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/pod.go
  pkg/steps/testdata/zz_fixture_TestAddPodUtils.yaml
Labels: approved, lgtm, ok-to-test

#3549 Add new AWS chaos profile
  pkg/api/types.go
Labels: approved, lgtm

#3575 `observer pods` : propagate the entrypoint's child exit code 2
  pkg/steps/multi_stage/gen.go
Labels: approved, lgtm, ok-to-test

#3561 `entrypoint-wrapper`: exit with wrapped exit code
  cmd/entrypoint-wrapper/main.go
Labels: approved, lgtm, ok-to-test

#3569 Initial implementation of the multi-arch builder controller
  cmd/multi-arch-builder-controller/README.md
  cmd/multi-arch-builder-controller/main.go
  hack/update-codegen.sh
  images/multi-arch-builder-controller/Dockerfile
  pkg/api/multiarchbuildconfig/v1/ci.openshift.io_multiarchbuildconfigs.yaml
  pkg/api/multiarchbuildconfig/v1/doc.go
  pkg/api/multiarchbuildconfig/v1/register.go
  pkg/api/multiarchbuildconfig/v1/types.go
  pkg/api/multiarchbuildconfig/v1/types_test.go
  pkg/api/multiarchbuildconfig/v1/zz_generated.deepcopy.go
  pkg/controller/multiarchbuildconfig/buildsreconciler/buildsreconciler.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
Labels: approved, lgtm

#3576 bump test-infra
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/cmd/generic-autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/cache.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/gerrit/adapter/adapter.go
  vendor/k8s.io/test-infra/prow/gerrit/client/client.go
  vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
  vendor/modules.txt
Labels: approved, lgtm

#3577 Fix issue DPTP-3312 Fix hypershift CLI path
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#3562 TRT-930: Including previous release data in ci-tools
  hack/run-job-aggregator-analyzer.sh
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_historical_data.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/pr_message_template.md
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/types.go
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/util.go
Labels: approved, lgtm, jira/valid-reference

#3585 Revert "Add possibility to dely some of required jobs by marking them…
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_always_run_but_optional_true.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_always_run_but_run_if_changed_set.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_always_run_false.yaml
Labels: approved

#3586 Two new events in tide config manager: ackCriticalFixes and revertCriticalFixes
  cmd/branchingconfigmanagers/tide-config-manager/main.go
  cmd/branchingconfigmanagers/tide-config-manager/main_test.go
Labels: approved, lgtm

#3592 `multi-arch-builder-controller`: remove manifest-tool from dockerfile
  images/multi-arch-builder-controller/Dockerfile
Labels: approved, lgtm

#3594 autoconfigbrancher: ignore openshift/linuxptp-daemon
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#3595 Add vsphere02
  pkg/api/domain.go
  pkg/api/types.go
Labels: approved, lgtm

#3596 promoted-image-governor: process each promoted tag only once
  cmd/promoted-image-governor/main.go
Labels: approved, lgtm

#3588 remove unused cluster profile azure_marketplace_qe
  pkg/api/types.go
Labels: approved, lgtm
