Repository openshift/ci-tools, pull requests merged in 2023-10, with the labels that each got.

#3650 autoconfigbrancher: remove unnecessary slices
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#3660 Revert "Increase timeouts for payload jobs to land k8s 1.28"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3658 pipeline-controller to support 2-staged pipelines
  cmd/pipeline-controller/config_data_provider.go
  cmd/pipeline-controller/config_data_provider_test.go
  cmd/pipeline-controller/main.go
  cmd/pipeline-controller/reconciler.go
  cmd/pipeline-controller/reconciler_test.go
Labels: approved, lgtm

#3587 Include the manifest list on the output images on all builds
  cmd/multi-arch-builder-controller/main.go
  images/ci-operator/Dockerfile
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
  pkg/manifestpusher/manifestpusher.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/project_image.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  test/e2e/framework/ci-operator.go
Labels: approved, lgtm

#3666 ci-images-mirroring: fix digest comparism
  hack/run-ci-images-mirror.sh
  pkg/controller/quay_io_ci_images_distributor/mirror.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3651 Ignore known infra-files in `prowgen` warnings
  cmd/ci-operator-prowgen/main.go
  cmd/config-shard-validator/main.go
  pkg/cmd/release/jobs.go
  pkg/config/options.go
  pkg/config/options_test.go
  pkg/jobconfig/files.go
  test/integration/ci-operator-prowgen.sh
  test/integration/ci-operator-prowgen/input/jobs/infra-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/infra-periodics.yaml
Labels: approved, tide/merge-method-squash, lgtm

#3668 fix resolving the root image when manifest list exists
  pkg/defaults/defaults.go
Labels: approved, lgtm

#3669 fix build cache: specify the missing namespace
  pkg/defaults/defaults.go
Labels: approved, lgtm

#3670 fix resolving the root cached image from a manifest list
  pkg/defaults/defaults.go
Labels: approved, lgtm

#3672 respect the output image labels on all ci-operator builds
  pkg/steps/source.go
  pkg/steps/source_test.go
Labels: approved, lgtm

#3673 Add build09 to update_jobs
  cmd/cluster-init/update_jobs.go
  pkg/api/types.go
Labels: approved, lgtm

#3644 `config-brancher`: skip promotion targets when branching
  cmd/config-brancher/main.go
  cmd/config-brancher/main_test.go
Labels: approved, lgtm

#3600 Bump Golang version to `v1.21.0`
  .ci-operator.yaml
  Makefile
  go.mod
  go.sum
  hack/pr-deploy-prpqr-ui.yaml
Labels: approved, lgtm

#3661 cluster-display: support disabled clusters
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
  pkg/prowconfigutils/config.go
Labels: approved, lgtm

#3665 direct generated vSphere jobs to vsphere02
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
Labels: approved, lgtm

#3671 MULTIARCH-3788: Add hypershift-powervs cluster profile and lease
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#3662 dptp-cm: support disabled clusters
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#3675 No duplication on cluster information
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
Labels: approved, lgtm

#3678 `pj-rehearse`: surface specific error that caused changes to not rebase
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3679 dptp-cm: logging the managers with their cluster names
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#3680 dptp-cm: fix ProwDisabledClusters
  pkg/prowconfigutils/config.go
Labels: approved, lgtm

#3677 create aws-rhtap-qe profile
  pkg/api/types.go
Labels: approved, lgtm

#3641 ci-secret-generator: support disabled clusters
  cmd/ci-secret-generator/main.go
  cmd/ci-secret-generator/main_test.go
  cmd/ci-secret-generator/testdata/TestValidateConfig/no_cluster_param.yaml
  cmd/ci-secret-generator/testdata/TestValidateConfig/valid.yaml
  pkg/api/secretgenerator/secretgenerator.go
Labels: approved, lgtm

#3684 Add cmd/ci-images-mirror/README.md
  cmd/ci-images-mirror/README.md
Labels: approved, lgtm

#3685 PowerVS: create powervs-3
  pkg/api/types.go
Labels: approved, lgtm

#3688 PowerVS: Add missing PowerVS3
  pkg/api/types.go
Labels: approved, lgtm

#3690 2-staged pipeline controller: fix branches bug
  cmd/pipeline-controller/reconciler.go
  cmd/pipeline-controller/reconciler_test.go
Labels: approved, lgtm

#3691 Add possibility to mark deprecated bundles as optional
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/integration/ci-operator-prowgen/input/config/super/duper/super-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
Labels: approved, lgtm

#3693 fork v1 git client for use in `pj-rehearse`
  cmd/pj-rehearse/main.go
  pkg/git/git.go
  pkg/git/git_unit_test.go
  pkg/git/options.go
Labels: approved, tide/merge-method-squash, lgtm

#3701 applyconfig: support disabled clusters
  cmd/applyconfig/applyconfig.go
Labels: approved, lgtm

#3702 Increase aggregator timeout from 4h15m to 5h15m
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3706 Remove list of missing data from origin synthetic test update PRs
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/pr_message_template.md
Labels: approved, lgtm

#3517 TRT-1281: single command multiple uploaders
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
  pkg/jobrunaggregator/jobrunbigqueryloader/test_run_uploader.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Labels: approved, lgtm, jira/valid-reference

#3697 add a retry mechanism while pushing the manifest list image
  pkg/manifestpusher/manifestpusher.go
Labels: approved, lgtm

#3581 TRT-1204: Support static list of JobRuns
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_test.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go
  pkg/jobrunaggregator/jobrunaggregatorlib/jobrun_locator.go
  pkg/jobrunaggregator/jobrunaggregatorlib/util.go
  pkg/jobrunaggregator/jobrunaggregatorlib/util_test.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
Labels: approved, lgtm, jira/valid-reference

#3709 continue retrying on manifest list push error
  pkg/manifestpusher/manifestpusher.go
Labels: approved, lgtm

#3710 pr-reminder: improve error handling
  cmd/pr-reminder/main.go
Labels: approved, lgtm

#3711 opendatahub: register aws-opendatahub cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3686 Add the ability to merge multiple `ci-operator` configs to the `ci-operator-configresolver`
  cmd/ci-operator-configresolver/main.go
  pkg/api/helper/imageextraction_test.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/registry/server/server.go
  pkg/validation/config.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/integration/ci-operator-configresolver.sh
  test/integration/ci-operator-configresolver/configs/master/openshift-console-master.yaml
  test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json
Labels: approved, tide/merge-method-squash, lgtm

#3682 `github-ldap-user-group-creator`: Delete users not in rover
  cmd/github-ldap-user-group-creator/main.go
  cmd/github-ldap-user-group-creator/main_test.go
Labels: approved, lgtm

#3712 quay_io_ci_images_distributor: use the right log handler
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3465 `e2e`: mitigate observer pods tests flakiness - 3rd attempt
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage/run_test.go
  pkg/steps/source_test.go
  pkg/testhelper/kubernetes/pod.go
  test/e2e/observer/artifacts/failing-observer-junit_operator.xml
  test/e2e/observer/e2e_test.go
  test/e2e/observer/failing-observer.yaml
Labels: lifecycle/stale, approved, lgtm

#3700 Calm Aggregated Disruption Testing
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail_test.go
Labels: approved, lgtm

#3683 Override cluster allocation for agent jobs
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
Labels: approved, lgtm

#3714 Enable retries on image mirroring
  cmd/ci-images-mirror/main.go
  pkg/controller/quay_io_ci_images_distributor/mirror.go
  pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go
Labels: approved, lgtm

#3716 trt-1320: update trt approvers
  cmd/sippy-config-generator/OWNERS
  cmd/testgrid-config-generator/OWNERS
  pkg/api/sippy/OWNERS
  pkg/jobrunaggregator/OWNERS
Labels: approved, lgtm, jira/valid-reference

#3720 Specify ci namespace when listening for prowjob change
  pkg/jobrunaggregator/jobrunaggregatorlib/util.go
Labels: approved, lgtm

#3699 chore(RHTAP-1805): add cluster profile for RHTAP performance testing on AWS
  pkg/api/types.go
Labels: approved, lgtm

#3724 Name check in pr payload aggregate run is incorrect
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#3725 ci-images-mirror: use oc-image-info for the source image
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3726 `pr-reminder`: escape text in slack message
  cmd/pr-reminder/README.md
  cmd/pr-reminder/main.go
Labels: approved, lgtm

#3727 Fix issue DPTP-3720 Add CM to gcp-3
  pkg/api/types.go
Labels: approved, lgtm

#3729 ci-images-mirror: ignore images with invalid manifest v2
  cmd/ci-images-mirror/main.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3731 ci-images-mirror: fix Take function of memoryMirrorStore
  pkg/controller/quay_io_ci_images_distributor/mirror.go
Labels: approved, lgtm

#3733 ci-images-mirror: sync images with schema version 1 only once
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3734 ci-images-mirror: ignore tags
  cmd/ci-images-mirror/main.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#3732 Chaos profile for aws cluster type
  pkg/api/types.go
Labels: approved, lgtm
