Repository openshift/ci-tools, pull requests merged in 2023-11, with the labels that each got.

#3737 ci-images-mirror: add metrics
  cmd/ci-images-mirror/main.go
  pkg/controller/quay_io_ci_images_distributor/metrics.go
  pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go
Labels: approved, lgtm

#3728 `ci-operator-configresolver`: merge additional configs for multi-pr payload testing
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/registry/server/server.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json
Labels: approved, tide/merge-method-squash, lgtm

#3742 quay_io_ci_images_distributor: fix memoryMirrorStore's Take function
  pkg/controller/quay_io_ci_images_distributor/mirror.go
Labels: approved, lgtm

#3741 ci-images-mirror: add metric/mirror_queue_depth
  pkg/controller/quay_io_ci_images_distributor/metrics.go
  pkg/controller/quay_io_ci_images_distributor/mirror.go
Labels: approved, lgtm

#3743 Do not delete user/backplane-cluster-admin
  cmd/github-ldap-user-group-creator/main.go
Labels: approved, lgtm

#3746 vault-secret-collection-manager: escape <> in ReadMe
  cmd/vault-secret-collection-manager/README.md
Labels: approved, lgtm

#3676 `MultiArchBuilderController`: push to external registries
  cmd/multi-arch-builder-controller/main.go
  images/multi-arch-builder-controller/Dockerfile
  pkg/api/multiarchbuildconfig/v1/ci.openshift.io_multiarchbuildconfigs.yaml
  pkg/api/multiarchbuildconfig/v1/types.go
  pkg/api/multiarchbuildconfig/v1/zz_generated.deepcopy.go
  pkg/controller/multiarchbuildconfig/mirror.go
  pkg/controller/multiarchbuildconfig/mirror_test.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3745 [LPTOCPCI-992] Add ibmcloud-cspi-qe Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#3723 Add openshift-cherrypick-robot org membership verification for cherrypick plugin
  cmd/check-gh-automation/README.md
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
Labels: approved, lgtm, ok-to-test

#3750 `ci-operator-configresolver`: handle a few simple `raw_step` ref substitutions
  pkg/registry/server/server.go
Labels: approved, tide/merge-method-squash, lgtm

#3735 Fix issue DPTP-3711 add common_cert_manager
  cmd/cluster-init/main.go
  cmd/cluster-init/testdata/clusters/build-clusters/common_cert_manager/.gitkeep
  cmd/cluster-init/testdata/clusters/build-clusters/existingCluster/common_cert_manager
  test/integration/cluster-init/create/expected/clusters/build-clusters/common_cert_manager/.gitkeep
  test/integration/cluster-init/create/expected/clusters/build-clusters/existingCluster/common_cert_manager
  test/integration/cluster-init/create/expected/clusters/build-clusters/newCluster/common_cert_manager
  test/integration/cluster-init/create/input/clusters/build-clusters/common_cert_manager/.gitkeep
  test/integration/cluster-init/create/input/clusters/build-clusters/existingCluster/common_cert_manager
  test/integration/cluster-init/update/expected/clusters/build-clusters/common_cert_manager/.gitkeep
  test/integration/cluster-init/update/expected/clusters/build-clusters/existingCluster/common_cert_manager
  test/integration/cluster-init/update/input/clusters/build-clusters/common_cert_manager/.gitkeep
  test/integration/cluster-init/update/input/clusters/build-clusters/existingCluster/common_cert_manager
Labels: approved, lgtm

#3755 [multiarchbuildconfig] treat the image targetRef as the default location for all external registries
  pkg/controller/multiarchbuildconfig/mirror.go
  pkg/controller/multiarchbuildconfig/mirror_test.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go
Labels: approved, lgtm

#3739 `ClusterProfiles`: add Name() method
  pkg/api/types.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#3606 Cluster profile changes
  cmd/ci-operator-checkconfig/main.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/validation/config.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/candidate/core-services/cluster-profiles/_config.yaml
  test/integration/pj-rehearse/master/core-services/cluster-profiles/_config.yaml
Labels: approved, tide/merge-method-squash, lgtm

#3758 add cluster-profiles-config to validate-checkconfig.sh
  test/validate-checkconfig.sh
Labels: approved, lgtm

#3760 Add gcp cluster profile for opendatahub
  pkg/api/types.go
Labels: approved, lgtm

#3762 check-gh-automation bug resolution
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
  hack/local-check-gh-automation.sh
Labels: approved, lgtm, ok-to-test

#3749 Allow `ci-operator` to utilize multiple source refs to assemble a release
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/api/metadata.go
  pkg/api/pullrequestpayloadqualification/v1/types_test.go
  pkg/api/testimagestreamtagimport/v1/types.go
  pkg/api/types.go
  pkg/api/types_test.go
  pkg/api/utils/labels.go
  pkg/api/utils/labels_test.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/registry/server/client.go
  pkg/rehearse/jobs.go
  pkg/steps/cluster_claim.go
  pkg/steps/git_source.go
  pkg/steps/git_source_test.go
  pkg/steps/project_image.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/validation/test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/e2e/framework/ci-operator.go
Labels: approved, tide/merge-method-squash, lgtm

#3764 `ci-operator`: only determine the absolute path to `.ci-operator.yaml` when a ref has been defined
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3768 Init QCI-APPCI
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3770 Add simple config watcher to pipeline-controller
  cmd/pipeline-controller/config_watcher.go
  cmd/pipeline-controller/main.go
  cmd/pipeline-controller/reconciler.go
Labels: approved, lgtm

#3769 OSSM maistra adds a new cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3757 `check-gh-automation`: introduce 'tide' mode
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
  hack/local-check-gh-automation.sh
Labels: approved, lgtm

#3773 qci-appci: podman works for authenticated users
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3781 qci-appci: fix health check
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3783 qci-appci: fix the renew function
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3782 `ci-operator-configresolver`: merge '*' resources when merging configs, and remove limits
  pkg/registry/server/server.go
  test/integration/ci-operator-configresolver/configs/master/openshift-console-master.yaml
  test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json
Labels: approved, tide/merge-method-squash, lgtm

#3784 qci-appci: ensure to get a valid token
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3785 Fix wrong ossm quota name
  pkg/api/types.go
Labels: approved, lgtm

#3787 Update script name in README
  cmd/branchingconfigmanagers/rpm-deps-mirroring-services/README.md
Labels: approved, lgtm

#3789 `payload-testing-prow-plugin`: use new `PullRequests` list
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3790 `ci-operator`: add labels for specific ref to the build when provided
  pkg/steps/bundle_source.go
  pkg/steps/git_source.go
  pkg/steps/index_generator.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/project_image.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/testdata/zz_fixture_TestBuildFromSource_ref_specified.yaml
Labels: approved, tide/merge-method-squash, lgtm

#3780 Add cmd/qci-appci/README.md
  cmd/qci-appci/README.md
Labels: approved, lgtm

#3759 Update OpenStack cluster profiles
  pkg/api/types.go
Labels: approved, lgtm

#3792 qci-appci: add sar check on users
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3793 `payload-testing-ui`: properly display pull requests list
  cmd/payload-testing-ui/server.go
Labels: approved, tide/merge-method-squash, lgtm

#3761 `multi-arch-builder-controller`: Remove the builds reconciler
  pkg/api/multiarchbuildconfig/v1/ci.openshift.io_multiarchbuildconfigs.yaml
  pkg/api/multiarchbuildconfig/v1/types.go
  pkg/api/multiarchbuildconfig/v1/zz_generated.deepcopy.go
  pkg/controller/multiarchbuildconfig/buildsreconciler/buildsreconciler.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
  pkg/manifestpusher/manifestpusher.go
  pkg/steps/source.go
Labels: approved, tide/merge-method-squash, lgtm

#3796 qci-appci: get token with the scope param
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3791 Create aws-devfile profile
  pkg/api/types.go
Labels: approved, lgtm

#3797 qci-appci: log auth header in response upon 401
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3799 increase default timeout for multi-pr payload tests
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_multiple_PRs_from_different_repositories.yaml
Labels: approved, lgtm

#3794 OSSM adds a new cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3803 qci-appci: support robot's Access to QCI-APPCI
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3804 qci-appci: reuse variable username
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3805 `multi-arch-builder-controller`: Improve logs and add deep copy
  pkg/api/multiarchbuildconfig/v1/types.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3808 qci-appci: better test coverage
  cmd/qci-appci/main.go
  cmd/qci-appci/main_test.go
Labels: approved, lgtm

#3809 `manifest-pusher`: fix push args
  pkg/manifestpusher/manifestpusher.go
  pkg/manifestpusher/manifestpusher_test.go
Labels: approved, lgtm

#3810 vSphere - remove unused cluster profiles
  pkg/api/types.go
  pkg/dispatcher/config.go
Labels: approved, lgtm

#3800 Add cluster profile for OCP Telco group
  pkg/api/types.go
Labels: approved, lgtm

#3813 cluster-display: return Hypershift's supported versions
  cmd/cluster-display/main.go
Labels: approved, lgtm

#3752 `hypershift-leaks-cleaner`: Support multiple cluster profiles
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm
