Repository openshift/ci-tools, pull requests merged in 2024-03, with the labels that each got.

#3998 qci-appci: generate jwt token
  cmd/qci-appci/main.go
  cmd/qci-appci/main_test.go
  go.mod
Labels: approved, lgtm

#4000 NO-JIRA: Use RHEL8 oc explicitly
  pkg/steps/multi_stage/gen.go
  test/e2e/multi-stage/assembled-release-no-injection.yaml
  test/e2e/multi-stage/assembled-release.yaml
  test/e2e/multi-stage/dependencies.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm, jira/valid-reference

#3987 Update cluster profiles config paths
  cmd/ci-operator-checkconfig/README.md
  pkg/load/load.go
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/candidate/ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
  test/integration/pj-rehearse/master/ci-operator/step-registry/cluster-profiles/cluster-profiles-config.yaml
  test/validate-checkconfig.sh
Labels: approved, tide/merge-method-squash, lgtm

#4002 Revert "NO-JIRA: Use RHEL8 oc explicitly"
  pkg/steps/multi_stage/gen.go
  test/e2e/multi-stage/assembled-release-no-injection.yaml
  test/e2e/multi-stage/assembled-release.yaml
  test/e2e/multi-stage/dependencies.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm, jira/valid-reference

#4003 qci-appci: logging duration of app.ci token validation
  cmd/qci-appci/main.go
Labels: approved, lgtm

#4008 Add pull secret for quay.io/openshift/ci
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm

#4005 Use aws as the CLUSTER_TYPE
  pkg/api/types.go
Labels: approved, lgtm

#3972 ci-op: pipeline imports images from QCI-APPCI
  pkg/api/domain.go
  pkg/api/promotion.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
  pkg/steps/release/snapshot.go
  pkg/util/imagestream.go
  test/e2e/multi-stage/dependencies.yaml
  test/e2e/observer/e2e_test.go
  test/e2e/simple/e2e_test.go
Labels: approved, tide/merge-method-squash, lgtm

#4015 MULTIARCH-4510: Updated dnsConfig to always overwrite from highest order set value (job > workflow > step).
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
Labels: approved, lgtm, jira/valid-reference

#4014 `pj-rehearse`: Retry git checkout to mitigate transient failures
  pkg/config/release.go
Labels: approved, lgtm

#4017 DPTP-3312 Change to ubi image
  images/dptp-3312-hypershift-leaks-cleaner/Dockerfile
Labels: approved, lgtm

#4019 cleaner: add AWS_SHARED_CREDENTIALS_FILE ENV
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#4021 snapshot: use ImageStreamImage for cluster-bot jobs
  pkg/steps/release/snapshot.go
Labels: approved, tide/merge-method-squash, lgtm

#4022 Add new profile aws-autorelease-qe
  pkg/api/types.go
Labels: approved, lgtm

#3961 Pipeline controller: add info about repo being managed by pipeline ctrl
  cmd/pipeline-controller/main.go
Labels: approved, lgtm

#3905 test pipelines
  cmd/pipeline-controller/main.go
Labels: approved

#4018 `check-gh-automation`: fix branch-protection determination logic
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
Labels: approved, tide/merge-method-squash, lgtm

#4016 Removing unused cluster-profile
  pkg/api/types.go
Labels: approved, lgtm

#4024 Fix TestInputImageStreamTagsFromResolvedConfig function
  pkg/api/helper/imageextraction.go
  pkg/api/helper/imageextraction_test.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/rehearse/jobs.go
Labels: approved, tide/merge-method-squash, lgtm

#4025 `check-gh-automation`: add org/repo to failing list when branch-protection reqs are not met
  cmd/check-gh-automation/main.go
Labels: approved, lgtm

#4028 cleaner: fix aws credential issue
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#4027 Handle error better in TestInputImageStreamTagsFromResolvedConfig
  pkg/api/helper/imageextraction.go
  pkg/api/helper/imageextraction_test.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#4032 cleaner: remove whitespaces
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#4029 owners: add Prucek & remove bbguimaraes
  OWNERS
Labels: approved, lgtm

#4036 Mirror CI supplemental images
  cmd/ci-images-mirror/main.go
  hack/run-ci-images-mirror.sh
  pkg/controller/quay_io_ci_images_distributor/mirror.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#4034 TRT-1497: Remove job name generator as it is not longer required
  pkg/jobrunaggregator/cmd.go
  pkg/jobrunaggregator/jobtableprimer/create_jobs.go
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/generated_job_names.txt
  pkg/jobrunaggregator/jobtableprimer/job_name_generator.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
  pkg/jobrunaggregator/jobtableprimer/jobs_test.go
Labels: approved, lgtm, jira/valid-reference

#4042 default values to gh event server in pipeline ctrl
  cmd/pipeline-controller/main.go
Labels: approved, lgtm

#4043 ci-images-mirror: fix a few things
  cmd/ci-images-mirror/main.go
  hack/run-ci-images-mirror.sh
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
Labels: approved, lgtm

#4038 TRT-1541: Skip single job fetch error when getting all jobs to analyze
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#4046 ci-images-mirror: add a log when mirroring supplemental CI images
  cmd/ci-images-mirror/main.go
Labels: approved, lgtm

#4047 bump `test-infra` dependency
  go.mod
  go.sum
  pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml
  test/integration/repo-init/expected/core-services/prow/02_config/_config.yaml
  test/integration/repo-init/input/core-services/prow/02_config/_config.yaml
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/cmd/generic-autobumper/bumper/bumper.go
  vendor/k8s.io/test-infra/prow/cmd/generic-autobumper/updater/updater.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/scheduler.go
  vendor/k8s.io/test-infra/prow/gerrit/adapter/adapter.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/trigger/trigger.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/k8s.io/test-infra/prow/tide/tide.go
  vendor/modules.txt
Labels: approved, lgtm

#4048 `helpdesk-faq`: server that provides an endpoint with a list of all faq items
  cmd/helpdesk-faq/main.go
  images/helpdesk-faq/Dockerfile
Labels: approved, lgtm

#4049 `check-gh-automation`: create an option to skip the branch protection access check.
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
Labels: approved, lgtm

#4050 input_image_tag: use ImageStreamImage for cluster-bot jobs
  pkg/steps/input_image_tag.go
Labels: approved, lgtm

#4052 Skip NULL start and completion time in jobs table
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
Labels: approved, lgtm

#4054 Fix the channel to have proper capacity for all job runs
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
Labels: approved, lgtm

#4006 OCPBUGS-20097: Use RHEL8 oc explicitly
  pkg/steps/multi_stage/gen.go
  test/e2e/multi-stage/assembled-release-no-injection.yaml
  test/e2e/multi-stage/assembled-release.yaml
  test/e2e/multi-stage/dependencies.yaml
  test/e2e/multi-stage/e2e_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#4011 deprecate the additional architectures in prowgen config, refactor multi_arch
  pkg/api/types.go
  pkg/config/load.go
  pkg/jobconfig/files.go
  pkg/prowgen/jobbase.go
  pkg/prowgen/jobbase_test.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_container_based_test_with_arm01_cluster.yaml
Labels: approved, lgtm

#4055 Determine the cli version in the promotion pod
  pkg/release/candidate/client.go
  pkg/release/prerelease/client.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm

#4056 Add retries on importing the input images
  pkg/steps/input_image_tag.go
  pkg/steps/release/create_release.go
  pkg/steps/release/snapshot.go
  pkg/steps/utils/image.go
  pkg/steps/utils/image_test.go
Labels: approved, lgtm
