Repository openshift/ci-tools, pull requests merged in 2024-01, with the labels that each got.

#3866 user-group-creator: support disabled clusters
  cmd/github-ldap-user-group-creator/main.go
Labels: approved, lgtm

#3868 `payload testing`: remove deprecated `pullRequest` field
  pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml
  pkg/api/pullrequestpayloadqualification/v1/types.go
  pkg/api/pullrequestpayloadqualification/v1/zz_generated.deepcopy.go
  pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_job_is_still_running.yaml
  pkg/controller/prpqr_reconciler/pjstatussyncer/testdata/zz_fixture_prpqr_TestReconcile_previous_condition_exists.yaml
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case__prowjob_already_exists__no_updates.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_multiple_PRs_from_different_repositories.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
Labels: approved, lgtm

#3869 user-group-creator: fix ensureGroups for disabled clusters
  cmd/github-ldap-user-group-creator/main.go
  cmd/github-ldap-user-group-creator/main_test.go
Labels: approved, lgtm

#3870 `payload testing ui`: remove deprecated pullRequest field from UI
  cmd/payload-testing-ui/server.go
Labels: approved, lgtm

#3871 github-ldap-user-group-creator: recognize a new rebot Id
  cmd/github-ldap-user-group-creator/main.go
Labels: approved, lgtm

#3873 fix the image registry route resolving on local e2e tests
  Makefile
Labels: approved, lgtm

#3872 Add che-aws cluster profile for eclipse-che jobs
  pkg/api/types.go
Labels: approved, lgtm

#3814 DPTP 3481 - Enhance check-gh-automation with Admin Bot Access Verification
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
  hack/local-check-gh-automation.sh
Labels: approved, lgtm

#3882 Add AWS Outpost QE profile
  pkg/api/types.go
Labels: approved, lgtm

#3880 Handle pipeline_run_if_changed when previously run_if_changed or skip_only_if_changed set
  pkg/jobconfig/files.go
Labels: approved, lgtm

#3884 Never set NoSchedule for spot.io nodes
  cmd/ci-scheduling-webhook/prioritization.go
Labels: approved, lgtm

#3862 Fix issue DPTP-3609 Use new bucket name
  cmd/ci-operator-checkconfig/README.md
  cmd/cvp-trigger/main_test.go
  cmd/job-runtime-analyzer/main.go
  cmd/pj-rehearse/main.go
  cmd/testgrid-config-generator/main.go
  hack/run-lens.sh
  pkg/api/graph.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/cmd.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/junit.go
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail_test.go
  pkg/jobrunaggregator/jobrunaggregatorapi/gcs_jobrun.go
  pkg/jobrunaggregator/jobrunaggregatorlib/gcs_client.go
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/cmd.go
  pkg/jobrunaggregator/jobrunbigqueryloader/disruption.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
  pkg/jobrunaggregator/jobtableprimer/cmd.go
  pkg/slack/events/joblink/link.go
  pkg/slack/events/joblink/link_test.go
  test/e2e/lease/e2e_test.go
  test/e2e/multi-stage/e2e_test.go
  test/e2e/observer/e2e_test.go
  test/e2e/optional-operators/e2e_test.go
  test/e2e/simple/e2e_test.go
  test/integration/ci-operator-configresolver/config.yaml
  test/integration/cvp-trigger/config.yaml
  test/integration/cvp-trigger/periodic-ipi-deprovision.expected
  test/integration/pj-rehearse/candidate/core-services/prow/02_config/_config.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/core-services/prow/02_config/_config.yaml
  test/integration/template-deprecator/input/config.yaml
  test/integration/testgrid-config-generator/config/testgrid/redhat-openshift-okd-release-1.1-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.1-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.10-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.10-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-blocking.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.2-informing.yaml
  test/integration/testgrid-config-generator/expected/redhat-openshift-ocp-release-4.3-broken.yaml
Labels: tide/merge-method-rebase, approved, lgtm

#3802 merge ci-operator configs for all payload tests
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator/main.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/registry/server/client.go
  pkg/registry/server/server.go
Labels: approved, lgtm

#3687 OCPBUGS-23211: Fix propagation of DNSConfig from Test configuration to Pod creation
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/registry/stack.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3889 Enable pipeline_run_if_changed for optional jobs
  cmd/pipeline-controller/config_data_provider.go
  cmd/pipeline-controller/config_data_provider_test.go
  cmd/pipeline-controller/reconciler.go
Labels: approved, lgtm

#3877 Add build cluster and asterisks for relative duration in aggregated jobs
  pkg/jobrunaggregator/jobrunaggregatorlib/spyglass_summary.go
Labels: approved, lgtm

#3888 Add OpenShift Local (OSL) cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3890 OCPNODE-1897: Revert "OCPNODE-1888: Increase timeouts for payload jobs to land k8s 1.29"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#3895 `ci-operator`: revert observers unit test
  pkg/steps/artifacts_test.go
  pkg/steps/multi_stage/run_test.go
  pkg/steps/source_test.go
  pkg/testhelper/kubernetes/pod.go
Labels: approved, lgtm

#3892 TRT-1440: Allow prcreator to have comma separated assignee list
  cmd/prcreator/main.go
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm, jira/valid-reference

#3896 Add nutanix zone profile
  pkg/api/types.go
Labels: approved, lgtm

#3893 add devsandboxci-aws cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3898 `ci-operator`: simplify observer pods unit test
  pkg/defaults/defaults.go
  pkg/steps/multi_stage/gen_test.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/multi_stage/multi_stage_test.go
  pkg/steps/multi_stage/run_test.go
Labels: approved, lgtm

#3899 Add new cluster profile for quay
  pkg/api/types.go
Labels: approved, lgtm

#3901 `payload-testing-prow-plugin`: add the ability to support multiple PRs
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
  pkg/release/config/config.go
  pkg/release/config/config_test.go
Labels: approved, lgtm

#3903 `payload-testing-prow-plugin`: use correct field for author on additional PRs
  cmd/payload-testing-prow-plugin/server.go
Labels: approved, lgtm

#3894 Add aws-edge-infa cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3904 Add cluster profile powervs-multi-1
  pkg/api/types.go
Labels: approved, lgtm

#3911 Add the missing cluster profile for powervs-multi-1
  pkg/api/types.go
Labels: approved, lgtm

#3907 `payload-testing-prow-plugin`: comment made on each additional PR included in payload test
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3837 Trigger first promotion automatically if isTag does not exist
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3912 `payload-testing-prow-plugin`: allow additional PRs to be included with "payload" command
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
Labels: approved, lgtm

#3909 `payload-testing-prow-plugin`: complete the plugin help section
  cmd/payload-testing-prow-plugin/server.go
Labels: approved, lgtm

#3910 `multi-arch-builder-controller`: Better logging and tests
  pkg/api/multiarchbuildconfig/v1/types.go
  pkg/controller/multiarchbuildconfig/mirror_test.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig.go
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
Labels: approved, lgtm

#3915 `payload-testing-prow-plugin`: only add each distinct pr to the PRPQR once
  cmd/payload-testing-prow-plugin/server.go
Labels: approved, lgtm

#3917 promotionreconciler: ignore istags from ns/build-cache
  Makefile
  pkg/controller/promotionreconciler/reconciler.go
  pkg/controller/promotionreconciler/reconciler_test.go
Labels: approved, lgtm

#3916 `payload-testing-prow-plugin`: payload aggregate with prs command
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3906 Add Unit Tests for manageHome + manageCLI
  cmd/entrypoint-wrapper/main_test.go
Labels: approved, lgtm

#3922 prowgen: fix a corner case
  pkg/jobconfig/files.go
Labels: approved, lgtm
