Repository openshift/ci-tools, pull requests merged in 2024-02, with the labels that each got.

#3913 Add Unit Tests for replacement.go in registery-replacer
  cmd/registry-replacer/replacement_test.go
Labels: approved, lgtm

#3927 `gpu-scheduling-webhook`: First implementation
  cmd/gpu-scheduling-webhook/README.md
  cmd/gpu-scheduling-webhook/main.go
  cmd/gpu-scheduling-webhook/main_test.go
  images/gpu-scheduling-webhook/Dockerfile
Labels: approved, lgtm

#3926 Add libvirt-s390x-amd64 cluster profile to LeaseFromClusterType()
  pkg/api/types.go
Labels: approved, lgtm

#3929 promotion: upgrade the oc version to 4.14
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__arm64_only.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__multi_architecture.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_promotion_quay.yaml
Labels: approved, lgtm

#3897 Change clusterProfiles from list to map
  cmd/ci-operator-checkconfig/main.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/validation/config.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#3938 `ci-operator`: Add env var `OVERRIDE_IMAGE_*` to override component images with provided name
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/utils/env.go
  pkg/steps/utils/env_test.go
Labels: approved, tide/merge-method-squash, lgtm

#3939 `payload-testing`: Add overriding image tag functionality to PRPQR
  pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml
  pkg/api/pullrequestpayloadqualification/v1/types.go
  pkg/api/pullrequestpayloadqualification/v1/zz_generated.deepcopy.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/prowgen/podspec.go
Labels: approved, lgtm

#3936 added cluster-profile rosa-aws
  pkg/api/types.go
Labels: approved, lgtm

#3942 move payload jobs off of build01 during outage
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_multiple_PRs_from_different_repositories.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml
Labels: approved, lgtm

#3944 Disable ci-operator-yaml-creator
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#3941 `ci-operator`: Remove old promotion fields
  cmd/ci-operator-config-mirror/main.go
  cmd/ci-operator-prowgen/main_test.go
  cmd/config-brancher/main.go
  cmd/config-brancher/main_test.go
  cmd/determinize-ci-operator/main.go
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Context_dir_gets_fixed_up.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_Dockerfile_gets_fixed_up.yaml
  cmd/registry-replacer/testdata/zz_fixture_TestReplacer_OCP_builder_pruning_happens.yaml
  pkg/api/promotion.go
  pkg/api/promotion_test.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/registry/server/testdata/zz_fixture_TestConfig_getting_config_works.yaml
  pkg/registry/server/testdata/zz_fixture_TestConfigserved_config.yaml
  pkg/validation/config.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#3946 Handle `ocp-build-data` stream aliases
  pkg/api/ocpbuilddata/types.go
  pkg/api/ocpbuilddata/types_test.go
Labels: approved, lgtm

#3940 `ci-operator`: ensure ist is available on the build cluster for image tag override
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#3753 Add cluster_profile for redhat-openshift-ecosystem
  pkg/api/types.go
Labels: approved, lgtm

#3950 `registry-replacer`: Don't use disabled configs
  pkg/api/ocpbuilddata/types.go
Labels: approved, lgtm

#3951 DPTP-3826: Adding ODF cluster profile
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#3953 trt-1400: replace : in branch name
  pkg/github/prcreation/prcreation.go
Labels: approved, lgtm, jira/valid-reference

#3955 TRT-1476: Exclude all network liveness backends
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_disruption.go
Labels: approved, lgtm, jira/valid-reference

#3949 include the multi_arch field on images for the graph generation
  cmd/ci-operator-prowgen/main.go
  cmd/image-graph-generator/types.graphql
  pkg/config/load.go
  pkg/image-graph-generator/images.go
  pkg/image-graph-generator/images_test.go
  pkg/image-graph-generator/operator.go
Labels: approved, lgtm

#3945 cron can be with run_if_changed if presubmit is true
  pkg/validation/test.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#3954 `payload-testing`: allow multiple PRs from a single repo to be provided
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_PRs_from_different_repositories.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_PRs_from_the_same_repository.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_multiple_PRs_from_different_repositories.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_multiple_PRs_from_the_same_repository.yaml
Labels: approved, tide/merge-method-squash, lgtm

#3957 `ci-operator`: Add lock to FakePodExecutor
  pkg/testhelper/kubernetes/pod.go
Labels: approved, lgtm

#3963 Fix issue DPTP-3711 Remove common_cert_manager
  cmd/cluster-init/main.go
  test/integration/cluster-init/create/expected/clusters/build-clusters/common_cert_manager/.gitkeep
  test/integration/cluster-init/create/expected/clusters/build-clusters/existingCluster/common_cert_manager
  test/integration/cluster-init/create/expected/clusters/build-clusters/newCluster/common_cert_manager
  test/integration/cluster-init/create/input/clusters/build-clusters/common_cert_manager/.gitkeep
  test/integration/cluster-init/create/input/clusters/build-clusters/existingCluster/common_cert_manager
  test/integration/cluster-init/update/expected/clusters/build-clusters/common_cert_manager/.gitkeep
  test/integration/cluster-init/update/expected/clusters/build-clusters/existingCluster/common_cert_manager
  test/integration/cluster-init/update/input/clusters/build-clusters/common_cert_manager/.gitkeep
  test/integration/cluster-init/update/input/clusters/build-clusters/existingCluster/common_cert_manager
Labels: approved, lgtm

#3947 OpenStack: Add openstack-nerc-dev cluster-profile
  pkg/api/types.go
Labels: approved, lgtm

#3921 TRT-1425: Automatically sync jobs with release table when priming job tables
  go.mod
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_release.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client_mock.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobtableprimer/cmd.go
  pkg/jobrunaggregator/jobtableprimer/create_jobs.go
  pkg/jobrunaggregator/jobtableprimer/generate_jobnames.go
  pkg/jobrunaggregator/jobtableprimer/job_name_generator.go
  pkg/jobrunaggregator/jobtableprimer/job_typer.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
  pkg/jobrunaggregator/jobtableprimer/jobs_test.go
  pkg/jobrunaggregator/releasebigqueryloader/release_uploader.go
  pkg/jobrunaggregator/releasebigqueryloader/table_creator.go
Labels: approved, lgtm, jira/valid-reference

#3959 `ci-operator-configresolver`: guarantee unique metadata when merging configs from multiple sources
  pkg/registry/server/server.go
  test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json
Labels: approved, tide/merge-method-squash, lgtm

#3965 Fix issue DPTP-3711 Replace hardcoded cluster names in applyconfig
  cmd/cluster-init/main.go
  cmd/cluster-init/update_jobs.go
Labels: approved, lgtm

#3964 DPTP-3786: Adding the QCI credentials into the registry pull secret
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm, jira/valid-reference

#3962 `payload-testing-prow-plugin`: add blanket response when user has mis-formatted payload command
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
Labels: approved, lgtm

#3968 schedule multi_arch jobs to build10 and remove multi01 references
  cmd/cluster-init/update_bootstrap_secrets.go
  cmd/cluster-init/update_jobs.go
  pkg/api/domain.go
  pkg/api/domain_test.go
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForPromotion_spawn_on_build10_cluster.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForPromotion_spawn_on_multi01_and_arm01.yaml
Labels: approved, lgtm

#3967 Fix lease type for openstack-nerc-dev
  pkg/api/types.go
Labels: approved, lgtm

#3969 ci-op: increase the default pod-pending-timeout to 60m
  cmd/ci-operator/main.go
Labels: approved, lgtm

#3943 Revert "added cluster-profile rosa-aws"
  pkg/api/types.go
Labels: approved, lgtm

#3971 `PRPQR`: Allow testing specified commits
  cmd/payload-testing-prow-plugin/server.go
  cmd/payload-testing-prow-plugin/server_test.go
  pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml
  pkg/api/pullrequestpayloadqualification/v1/types.go
  pkg/api/pullrequestpayloadqualification/v1/zz_generated.deepcopy.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_without_PR__testing_specified_base.yaml
Labels: approved, lgtm

#3977 `payload-testing-ui`: handle base commits rather than assume PRs
  cmd/payload-testing-ui/server.go
Labels: approved, lgtm

#3933 Add cluster-profiles-config arg to README
  cmd/ci-operator-checkconfig/README.md
Labels: approved, lgtm

#3978 Create aws-serverless cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#3766 `github-ldap-user-group-creator`: update README.md
  cmd/github-ldap-user-group-creator/README.md
Labels: approved, lgtm

#3966 pj-rehearse: tell the user when you're ignoring them
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#3983 local-e2e: specify context when getting LOCAL_REGISTRY_DNS
  Makefile
Labels: approved, lgtm

#3985 qci-appci: add more logging fields for debugging
  cmd/qci-appci/main.go
Labels: approved, lgtm

#3812 `rehearsals`: Add image mirroring to quay
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  images/pj-rehearse/Dockerfile
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/rehearse.go
  pkg/rehearse/rehearse_test.go
Labels: approved, lgtm

#3980 Private cluster pools
  cmd/ci-operator-checkconfig/main.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/load/load.go
  pkg/load/load_test.go
  pkg/validation/config.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/candidate/core-services/cluster-pools/_config.yaml
  test/validate-checkconfig.sh
Labels: approved, lgtm

#3989 qci-appci: add retries on renewing robot's token
  cmd/qci-appci/main.go
  cmd/qci-appci/main_test.go
  go.mod
  go.sum
  vendor/github.com/felixge/httpsnoop/.gitignore
  vendor/github.com/felixge/httpsnoop/LICENSE.txt
  vendor/github.com/felixge/httpsnoop/Makefile
  vendor/github.com/felixge/httpsnoop/README.md
  vendor/github.com/felixge/httpsnoop/capture_metrics.go
  vendor/github.com/felixge/httpsnoop/docs.go
  vendor/github.com/felixge/httpsnoop/wrap_generated_gteq_1.8.go
  vendor/github.com/felixge/httpsnoop/wrap_generated_lt_1.8.go
  vendor/modules.txt
Labels: approved, lgtm

#3990 pj-rehearse: mirror the images only once
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#3992 TRT-1425: filter out old releases when priming job tables
  pkg/jobrunaggregator/jobtableprimer/create_jobs.go
Labels: approved, lgtm, jira/valid-reference

#3991 Private cluster pools: fix config in integration tests
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/master/core-services/cluster-pools/_config.yaml
Labels: approved, lgtm

#3948 remove ClusterProfileOpenStack (not used)
  pkg/api/types.go
  pkg/prowgen/podspec_test.go
Labels: approved, lgtm
