Repository openshift/ci-tools, pull requests merged in 2024-12, with the labels that each got.

#4433 Add sort to achieve determinism in job dispatching/sanitizing
  pkg/dispatcher/config.go
Labels: approved, lgtm

#4435 Improve logging in registry-replacer
  cmd/registry-replacer/main.go
Labels: approved, lgtm

#4434 adding the telcov10n ci/cd cluster profile
  pkg/api/types.go
Labels: approved, needs-ok-to-test, lgtm

#4437 CNTRLPLANE-1: Increase timeouts for payload jobs to land k8s 1.32
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_cluster_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_url_not_found_in_created_job.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#4438 `sprint-automation`: Assign incoming intake cards to the engineer in the intake role
  cmd/sprint-automation/main.go
  cmd/sprint-automation/main_test.go
  go.mod
  go.sum
  vendor/github.com/andygrunwald/go-jira/.gitignore
  vendor/github.com/andygrunwald/go-jira/Makefile
  vendor/github.com/andygrunwald/go-jira/README.md
  vendor/github.com/andygrunwald/go-jira/authentication.go
  vendor/github.com/andygrunwald/go-jira/board.go
  vendor/github.com/andygrunwald/go-jira/customer.go
  vendor/github.com/andygrunwald/go-jira/group.go
  vendor/github.com/andygrunwald/go-jira/issue.go
  vendor/github.com/andygrunwald/go-jira/issuelinktype.go
  vendor/github.com/andygrunwald/go-jira/jira.go
  vendor/github.com/andygrunwald/go-jira/organization.go
  vendor/github.com/andygrunwald/go-jira/request.go
  vendor/github.com/andygrunwald/go-jira/request_context.go
  vendor/github.com/andygrunwald/go-jira/request_legacy.go
  vendor/github.com/andygrunwald/go-jira/servicedesk.go
  vendor/github.com/andygrunwald/go-jira/sprint.go
  vendor/github.com/andygrunwald/go-jira/user.go
  vendor/github.com/andygrunwald/go-jira/version.go
  vendor/github.com/golang-jwt/jwt/v4/.gitignore
  vendor/github.com/golang-jwt/jwt/v4/LICENSE
  vendor/github.com/golang-jwt/jwt/v4/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v4/VERSION_HISTORY.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/doc.go
  vendor/github.com/golang-jwt/jwt/v4/ecdsa.go
  vendor/github.com/golang-jwt/jwt/v4/ecdsa_utils.go
  vendor/github.com/golang-jwt/jwt/v4/ed25519.go
  vendor/github.com/golang-jwt/jwt/v4/ed25519_utils.go
  vendor/github.com/golang-jwt/jwt/v4/errors.go
  vendor/github.com/golang-jwt/jwt/v4/hmac.go
  vendor/github.com/golang-jwt/jwt/v4/map_claims.go
  vendor/github.com/golang-jwt/jwt/v4/none.go
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/parser_option.go
  vendor/github.com/golang-jwt/jwt/v4/rsa.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_utils.go
  vendor/github.com/golang-jwt/jwt/v4/signing_method.go
  vendor/github.com/golang-jwt/jwt/v4/staticcheck.conf
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/github.com/golang-jwt/jwt/v4/types.go
  vendor/modules.txt
Labels: approved, lgtm

#4439 Implement additional controller parameters
  cmd/job-trigger-controller-manager/main.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#4441 Capabilities in prowgen
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGeneratePeriodicForTest_periodic_with_capabilities.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePostSubmitForTest_postsubmit_with_capabilities.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_capabilities_added.yaml
  pkg/prowgen/testdata/zz_fixture_TestGeneratePresubmitForTest_presubmit_with_always_run_but_pipeline_run_if_changed_set2.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#4442 [DPTP-4239] Verifying branch protection on public repos or paid plans
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
Labels: approved, lgtm

#4076 clear profile aws-perfscale
  pkg/api/types.go
Labels: approved, lifecycle/rotten, lgtm

#4445 `check-gh-automation`: log on error level when repo doesn't give the cherrypick-bot the proper perms
  cmd/check-gh-automation/main.go
Labels: approved, lgtm

#4446 AGENT-1045: Add OCI Agent QE Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4447 Cluster profile for IBM Cloud RHOAI QE
  pkg/api/types.go
Labels: approved, lgtm

#4443 [DPTP-3546] Verifying if issues are enable for automated branching
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
  hack/local-check-gh-automation.sh
Labels: approved, lgtm

#4448 `pj-rehearse`: ignore the cluster-profile-config.yaml file when attempting to get changed registry content
  pkg/config/release.go
Labels: approved, lgtm

#4451 `pj-rehearse`: fix the check to only look for the 'cluster-profile-config.yaml' base
  pkg/config/release.go
Labels: approved, lgtm

#4452 OCPQE-27657: add new cluster profile azurestack-dev
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4454 `pj-rehearse`: add better logging when rebase is retried
  cmd/pj-rehearse/server.go
Labels: approved, lgtm
