Repository openshift/ci-tools, pull requests merged in 2024-06, with the labels that each got.

#4149 Resolve observer pods from workflow
  cmd/generate-registry-metadata/main_test.go
  pkg/load/load_test.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  test/integration/ci-operator-configresolver/configs/release-4.2/openshift-installer-release-4.2.yaml
  test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-golang111.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-injected.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2.json
  test/integration/pj-rehearse/expected.yaml
  test/multistage-registry/registry/ipi-observers/OWNERS
  test/multistage-registry/registry/ipi-observers/ipi-observers-workflow.metadata.json
  test/multistage-registry/registry/ipi-observers/ipi-observers-workflow.yaml
Labels: approved, lgtm

#4154 quay_io_ci_images_distributor: fix the isNotFound function
  pkg/controller/quay_io_ci_images_distributor/oc_quay_io_image_helper.go
Labels: approved, lgtm

#4158 Use centos:stream9
  images/applyconfig/Dockerfile
  images/autoconfigbrancher/Dockerfile
  images/autoowners/Dockerfile
  images/autoperibolossync/Dockerfile
  images/autopublicizeconfig/Dockerfile
  images/autotestgridgenerator/Dockerfile
  images/backport-verifier/Dockerfile
  images/blocking-issue-creator/Dockerfile
  images/bugzilla-backporter/Dockerfile
  images/check-gh-automation/Dockerfile
  images/ci-operator-checkconfig/Dockerfile
  images/ci-operator-config-mirror/Dockerfile
  images/ci-operator-configresolver/Dockerfile
  images/ci-operator-prowgen/Dockerfile
  images/ci-operator/Dockerfile
  images/ci-scheduling-webhook/Dockerfile
  images/ci-secret-bootstrap/Dockerfile
  images/ci-secret-generator/Dockerfile
  images/cluster-init/Dockerfile
  images/clusterimageset-updater/Dockerfile
  images/config-brancher/Dockerfile
  images/config-change-trigger/Dockerfile
  images/config-shard-validator/Dockerfile
  images/cvp-trigger/Dockerfile
  images/determinize-ci-operator/Dockerfile
  images/determinize-peribolos/Dockerfile
  images/determinize-prow-config/Dockerfile
  images/dptp-controller-manager/Dockerfile
  images/entrypoint-wrapper/Dockerfile
  images/generate-registry-metadata/Dockerfile
  images/gpu-scheduling-webhook/Dockerfile
  images/group-auto-updater/Dockerfile
  images/job-run-aggregator/Dockerfile
  images/multi-arch-builder-controller/Dockerfile
  images/ocp-build-data-enforcer/Dockerfile
  images/payload-testing-ui/Dockerfile
  images/pipeline-controller/Dockerfile
  images/pj-rehearse/Dockerfile
  images/pod-scaler/Dockerfile
  images/pr-reminder/Dockerfile
  images/private-org-peribolos-sync/Dockerfile
  images/private-org-sync/Dockerfile
  images/private-prow-configs-mirror/Dockerfile
  images/prowjobdispatcher/Dockerfile
  images/publicize/Dockerfile
  images/registry-replacer/Dockerfile
  images/repo-brancher/Dockerfile
  images/repo-init/Dockerfile
  images/result-aggregator/Dockerfile
  images/sanitize-prow-jobs/Dockerfile
  images/serviceaccount-secret-rotation-trigger/Dockerfile
  images/slack-bot/Dockerfile
  images/sprint-automation/Dockerfile
  images/template-deprecator/Dockerfile
  images/testgrid-config-generator/Dockerfile
  images/tide-config-manager/Dockerfile
  images/vault-subpath-proxy/Dockerfile
Labels: approved, lgtm

#4157 ci-op: fix the getEvaluator function
  pkg/steps/utils/image.go
  pkg/steps/utils/image_test.go
Labels: approved, lgtm

#4150 DPTP-3742: Add pull secret for qci-pull-through-cache
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm, jira/valid-reference

#4152 OCPQE-22599: Create QE dedicated GCP cluster profile "gcp-autorelease-qe"
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4109 Add new cluster profiles for Telco5G and PTP jobs
  pkg/api/types.go
Labels: approved, lgtm

#4051 `helpdesk-faq`: slack handler to add FAQ items
  cmd/helpdesk-faq/main.go
  cmd/slack-bot/main.go
  hack/local-slack-bot.sh
  pkg/helpdesk-faq/client.go
  pkg/helpdesk-faq/types.go
  pkg/slack/events/helpdesk/helpdesk-faq.go
  pkg/slack/events/helpdesk/helpdesk-message.go
  pkg/slack/events/router/router.go
Labels: approved, lgtm

#4163 add cnf image streams to configsolver
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
Labels: approved, lgtm

#4156 pr-reminder: allow omitting bots
  cmd/pr-reminder/main.go
  cmd/pr-reminder/main_test.go
Labels: approved, lgtm

#4159 ci-images-mirror: update readme
  cmd/ci-images-mirror/README.md
Labels: approved, lgtm

#4153 OCPQE-22600: add new cluster profile azure-autorelease-qe
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4164 Adding new image for ci-operator with ubi base image
  images/ci-operator-minimal/Dockerfile
Labels: approved, lgtm

#4161 qci-appci: fix SubjectAccessReviewSpec for human users
  cmd/qci-appci/main.go
Labels: approved, lgtm

#4162 `ci-operator`: add SecretClient interface in order to mitigate DataRace issues from using fakecrtlruntimeclient
  pkg/steps/ip_pool.go
  pkg/steps/ip_pool_test.go
Labels: approved, lgtm

#4166 qci-appci: improve logging for debugging
  cmd/qci-appci/main.go
Labels: approved, lgtm

#4168 Update qci-appci's readme
  cmd/qci-appci/README.md
Labels: approved, lgtm

#4167 `helpdesk-faq`: add: topic, subject, and body fields to question
  pkg/helpdesk-faq/types.go
  pkg/slack/events/helpdesk/helpdesk-faq.go
Labels: approved, lgtm

#4170 Update qci-appci's readme (2)
  cmd/qci-appci/README.md
Labels: approved, lgtm

#4172 Add missing prcreator to the job-run-aggregator
  images/job-run-aggregator/Dockerfile
Labels: approved, lgtm

#4139 API-1783: Revert payload timeout increase
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#4173 ci-op: waitForTagInSpec
  pkg/steps/input_image_tag.go
  pkg/steps/utils/image.go
Labels: approved, lgtm

#4174 `helpdesk-faq`: remove special slack formatting from links
  pkg/slack/events/helpdesk/helpdesk-faq.go
  pkg/slack/events/helpdesk/helpdesk-faq_test.go
Labels: approved, lgtm

#4151 Improve the tags for the pruner
  pkg/api/promotion.go
  pkg/api/promotion_test.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_promotion_quay.yaml
Labels: approved, tide/merge-method-squash, lgtm

#4178 ci-images-mirror: create agents when needed
  cmd/ci-images-mirror/main.go
Labels: approved, lgtm

#4177 Improve logging for promotion
  pkg/release/candidate/client.go
  pkg/release/prerelease/client.go
Labels: approved, lgtm

#4179 ci-images-mirror: reload config file
  cmd/ci-images-mirror/main.go
Labels: approved, lgtm

#4169 Add aws and gcp cluster profiles for SD CICD's Managed OpenShift
  pkg/api/types.go
Labels: approved, lgtm

#4182 OSASINFRA-3477: openstack: Add new location for OpenStack periodics to Sippy
  pkg/util/testgrid.go
Labels: approved, lgtm, jira/valid-reference

#4180 `helpdesk-faq`: add contributing-info to faq-items
  cmd/helpdesk-faq/main.go
  cmd/slack-bot/main.go
  hack/local-slack-bot.sh
  pkg/helpdesk-faq/client.go
  pkg/helpdesk-faq/types.go
  pkg/helpdesk-faq/types_test.go
  pkg/slack/events/helpdesk/helpdesk-faq.go
  pkg/slack/events/helpdesk/helpdesk-faq_test.go
  pkg/slack/events/router/router.go
Labels: approved, lgtm

#4186 Remove aws-centos-40 cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#4185 install git for job-run-aggregator for weekly disruption PR
  images/job-run-aggregator/Dockerfile
Labels: approved, lgtm

#4188 Remove gcp-40 cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#4189 `helpdesk-faq`: sort items when returning a serialized list
  pkg/helpdesk-faq/client.go
  pkg/helpdesk-faq/client_test.go
Labels: approved, lgtm

#4190 Remove gcp-logging-journald, gcp-logging-json-file, gcp-logging-crio profiles
  pkg/api/types.go
Labels: approved, lgtm

#4193 Adding missing commands
  images/ci-operator/Dockerfile
Labels: approved, lgtm

#4175 Fix issue DPTP-4032 Add flag to restrict tests accessing RH intranet
  cmd/ci-operator/main.go
  go.mod
  pkg/api/egressfirewall/NOTE.md
  pkg/api/egressfirewall/v1/apis/applyconfiguration/egressfirewall/v1/egressfirewall.go
  pkg/api/egressfirewall/v1/apis/applyconfiguration/egressfirewall/v1/egressfirewalldestination.go
  pkg/api/egressfirewall/v1/apis/applyconfiguration/egressfirewall/v1/egressfirewallport.go
  pkg/api/egressfirewall/v1/apis/applyconfiguration/egressfirewall/v1/egressfirewallrule.go
  pkg/api/egressfirewall/v1/apis/applyconfiguration/egressfirewall/v1/egressfirewallspec.go
  pkg/api/egressfirewall/v1/apis/applyconfiguration/egressfirewall/v1/egressfirewallstatus.go
  pkg/api/egressfirewall/v1/apis/applyconfiguration/internal/internal.go
  pkg/api/egressfirewall/v1/apis/applyconfiguration/utils.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/clientset.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/fake/clientset_generated.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/fake/doc.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/fake/register.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/scheme/doc.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/scheme/register.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/typed/egressfirewall/v1/doc.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/typed/egressfirewall/v1/egressfirewall.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/typed/egressfirewall/v1/egressfirewall_client.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/typed/egressfirewall/v1/fake/doc.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/typed/egressfirewall/v1/fake/fake_egressfirewall.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/typed/egressfirewall/v1/fake/fake_egressfirewall_client.go
  pkg/api/egressfirewall/v1/apis/clientset/versioned/typed/egressfirewall/v1/generated_expansion.go
  pkg/api/egressfirewall/v1/apis/informers/externalversions/egressfirewall/interface.go
  pkg/api/egressfirewall/v1/apis/informers/externalversions/egressfirewall/v1/egressfirewall.go
  pkg/api/egressfirewall/v1/apis/informers/externalversions/egressfirewall/v1/interface.go
  pkg/api/egressfirewall/v1/apis/informers/externalversions/factory.go
  pkg/api/egressfirewall/v1/apis/informers/externalversions/generic.go
  pkg/api/egressfirewall/v1/apis/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/api/egressfirewall/v1/apis/listers/egressfirewall/v1/egressfirewall.go
  pkg/api/egressfirewall/v1/apis/listers/egressfirewall/v1/expansion_generated.go
  pkg/api/egressfirewall/v1/doc.go
  pkg/api/egressfirewall/v1/register.go
  pkg/api/egressfirewall/v1/types.go
  pkg/api/egressfirewall/v1/zz_generated.deepcopy.go
Labels: approved, lgtm

#4187 Remove aws-outpost cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#4195 Remove gcp-ha, gcp-crio, gcp-logging
  pkg/api/types.go
Labels: approved, lgtm

#4191 `helpdesk-faq`: create tests for slack handler
  pkg/slack/events/helpdesk/helpdesk-faq.go
  pkg/slack/events/helpdesk/helpdesk-faq_test.go
Labels: approved, lgtm

#4196 DPTP-4073: Updating for build09/build10 cloudfront distribution map
  hack/cloudfront/lambda_function.py
Labels: approved, lgtm, jira/valid-reference

#4197 add tools to `pr-reminder` image
  images/pr-reminder/Dockerfile
Labels: approved, lgtm

#4199 `autoowners`: prune '@' from OWNERS file contents
  cmd/autoowners/main.go
  cmd/autoowners/main_test.go
Labels: approved, lgtm

#4198 Disable ensureImageStreamTag() on the root tag
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#4202 Remove aws-atomic, aws-centos, aws-gluster cluster profiles
  pkg/api/types.go
  pkg/validation/test_test.go
Labels: approved, lgtm

#4204 TRT-1650: Use Jobs instead of JobsWithVariants table to find existing jobs when priming jobs
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client_mock.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer_test.go
Labels: approved, lgtm, jira/valid-reference
