Repository openshift/ci-tools, pull requests merged in 2024-04, with the labels that each got.

#4062 add cluster profile for konflux workspaces
  pkg/api/types.go
Labels: approved, lgtm

#4058 `rehearsal`: add supplemental images config
  cmd/ci-images-mirror/main.go
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  pkg/controller/quay_io_ci_images_distributor/supplemental_images.go
  pkg/rehearse/rehearse.go
  pkg/rehearse/rehearse_test.go
Labels: approved, tide/merge-method-squash, lgtm

#4065 PowerVS: Create new powervs-5 type
  pkg/api/types.go
Labels: approved, lgtm

#4066 SPLAT-1581: Created new "vsphere-multi-vcenter" cluster profile.
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4067 publicize: construct the user credentials while reloving the external remote
  cmd/publicize/server.go
Labels: approved, lgtm

#4068 `pj-rehearse`: acknowledge that a request is being processed
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#4071 ci-scheduling-webhook: don't overwrite `.spec.nodeSelector`
  cmd/ci-scheduling-webhook/mutation.go
Labels: approved, lgtm

#4073 `pj-rehearse`: don't wait for job success on standard rehearsal runs
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#4072 import_release: add more debug logs
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#4075 schedule the multi arch jobs to the build10 cluster instead
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
Labels: approved, lgtm

#4077 Update the name of the hive cluster: hosted-mgmt
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
  cmd/github-ldap-user-group-creator/main_test.go
  pkg/api/types.go
Labels: approved, lgtm

#4084 prowgen: introduce the multi-arch branch filtering configuration
  pkg/config/load.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered__cluster_change.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered__no_cluster_change.yaml
Labels: approved, lgtm

#4078 TRT-1593: Add compliance tests to sippy config
  pkg/util/testgrid.go
Labels: approved, lgtm, jira/valid-reference

#4081 ci-secret-bootstrap: fix nil pointer on missing cluster
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm

#4083 PERFSCALE-2945: New metal-perfscale-cpt cloud profile
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4086 include the PreserveOriginal import mode on output image tags
  pkg/steps/output_image_tag.go
  pkg/steps/output_image_tag_test.go
Labels: approved, lgtm

#4088 cluster-display: no resolving image registry host on hosted-mgmt
  cmd/cluster-display/main.go
Labels: approved, lgtm

#4087 cluster-display: set cache duration 1m
  cmd/cluster-display/main.go
Labels: approved, lgtm

#4060 [CVP-4045] Add optional hybridoverlay parameter to cvp-trigger
  cmd/cvp-trigger/README.md
  cmd/cvp-trigger/main.go
  cmd/cvp-trigger/main_test.go
Labels: approved, lgtm

#4085 inputImageTagStep: reference images in QCI
  pkg/api/clusterbotjob.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/steps/release/snapshot.go
Labels: approved, lgtm

#4089 Share api.ReleaseConfigAnnotation among tools
  pkg/api/constant.go
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/release_images.go
  pkg/steps/release/snapshot.go
Labels: approved, lgtm

#4090 Fix observer e2e
  test/e2e/observer/artifacts/multi-observers-junit_operator.xml
Labels: approved, lgtm

#4070 Reuse utils.ImportTagWithRetries in step/import_release
  pkg/steps/release/import_release.go
  pkg/steps/utils/image.go
  pkg/steps/utils/image_test.go
Labels: approved, lgtm

#4091 configresolver: add an endpoint integratedStream
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
Labels: approved, lgtm

#4093 Revert "configresolver: add an endpoint integratedStream"
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
Labels: approved, lgtm

#4092 TRT-1621: Reduce initial aggregator wait
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#4094 Revert "Revert "configresolver: add an endpoint integratedStream""
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
Labels: approved, lgtm
