Repository openshift/ci-tools, pull requests merged in 2024-10, with the labels that each got.

#4352 fix the unit tests of the registry replacer tool
  cmd/registry-replacer/main_test.go
Labels: approved, lgtm

#4351 [DPTP-4192] adjust bundle image builds to exclude manifest list
  cmd/registry-replacer/main_test.go
  pkg/api/config_test.go
  pkg/api/types.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/diffs/diffs.go
  pkg/steps/project_image.go
Labels: approved, lgtm

#4356 Remove `template-deprecator` dangling references
  cmd/autoconfigbrancher/README.md
  cmd/autoconfigbrancher/main.go
  images/autoconfigbrancher/Dockerfile
  images/template-deprecator/Dockerfile
  test/integration/template-deprecator.sh
Labels: approved, lgtm

#4338 DPTP-4183: Fix automation to include candidate release
  cmd/config-brancher/main.go
  cmd/config-brancher/main_test.go
Labels: approved, lgtm, jira/valid-reference

#4355 `pj-rehearse`: allow the ability to rehearse tests with `network_access_restricted`: 'false'
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#4358 update prow dependency
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/prow/pkg/config/prow-config-documented.yaml
  vendor/sigs.k8s.io/prow/pkg/config/tide.go
  vendor/sigs.k8s.io/prow/pkg/ghcache/ghcache.go
  vendor/sigs.k8s.io/prow/pkg/github/client.go
  vendor/sigs.k8s.io/prow/pkg/github/ghmetrics/ghpath.go
  vendor/sigs.k8s.io/prow/pkg/github/report/report.go
  vendor/sigs.k8s.io/prow/pkg/plugins/override/override.go
  vendor/sigs.k8s.io/prow/pkg/simplifypath/simplify.go
  vendor/sigs.k8s.io/prow/pkg/tide/github.go
  vendor/sigs.k8s.io/prow/pkg/tide/tide.go
Labels: approved, lgtm

#4359 `pj-rehearse`: A couple of typo fixes in the output
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#4362 Move the prowgen promotion to build11
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered__cluster_change.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
Labels: approved, lgtm

#4363 Revert "Move the prowgen promotion to build11"
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered__cluster_change.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
Labels: approved, lgtm

#4361 Add retry for payload creation
  pkg/steps/release/create_release.go
Labels: approved, lgtm

#4360 `multi-pr-prow-plugin`: Create a prow plugin to handle multi-pr presubmit testing
  cmd/multi-pr-prow-plugin/main.go
  cmd/multi-pr-prow-plugin/report.go
  cmd/multi-pr-prow-plugin/report_test.go
  cmd/multi-pr-prow-plugin/server.go
  cmd/multi-pr-prow-plugin/server_test.go
  cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestGenerateProwJob_additional_PR_from_the_same_repo.yaml
  cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestGenerateProwJob_multiple_additional_PRs.yaml
  cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestHandle_trigger_a_single_multi_pr_job_run_with_additional_PR_from_a_different_repo.yaml
  cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestHandle_trigger_a_single_multi_pr_job_run_with_additional_PR_from_the_same_repo.yaml
  cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestHandle_trigger_multiple_multi_pr_job_runs_with_diverse_additional_PRs.yaml
  images/multi-pr-prow-plugin/Dockerfile
  pkg/api/types.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
Labels: approved, lgtm

#4364 OCPQE-26170: Add cluster profiles for Azure HCP QE
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4112 Update how ci-operator gets cluster profile secrets
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/api/types.go
Labels: approved, tide/merge-method-squash, lgtm

#4367 Revert "Update how ci-operator gets cluster profile secrets"
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/api/types.go
Labels: approved, lgtm

#4353 Fixes for dispatcher: flags, logging, event handler
  cmd/prow-job-dispatcher/main.go
  pkg/dispatcher/server.go
Labels: approved, lgtm

#4370 [ci-operator] add configuration for specifying architectures in image builds
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/steps/project_image.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#4373 `pj-rehearse`: abort active rehearsal jobs when new commit is pushed
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#4365 WRKLDS-1449: Revert "Increase timeouts for payload jobs to land k8s 1.31"
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_cluster_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#4374 set ORIGINAL_* env vars whenever a release is resolved
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/release/import_release.go
Labels: approved, tide/merge-method-squash, lgtm

#4377 update prow dependency
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/certwatcher/certwatcher.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil/controllerutil.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/prow/pkg/config/prow-config-documented.yaml
  vendor/sigs.k8s.io/prow/pkg/config/tide.go
  vendor/sigs.k8s.io/prow/pkg/flagutil/kubernetes_cluster_clients.go
Labels: approved, tide/merge-method-squash, lgtm

#4379 [PERFSCALE-3524] Add OVN PerfScale AWS Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#4366 `multi-pr-prow-plugin`: add a readme
  cmd/multi-pr-prow-plugin/README.md
Labels: approved, lgtm

#4372 [registry-replacer] Skip disabled configs
  pkg/api/ocpbuilddata/types.go
Labels: approved, lgtm

#4381 clean up a couple of TODOs that are no longer relevant, and add plugin description
  cmd/multi-pr-prow-plugin/server.go
  pkg/helpdesk-faq/types.go
  pkg/steps/source.go
Labels: approved, lgtm

#4382 Adding gcp chaos
  pkg/api/types.go
Labels: approved, lgtm

#4383 `multi-pr`: handle the common case that the user has copy/pasted the command
  cmd/multi-pr-prow-plugin/server.go
  cmd/multi-pr-prow-plugin/server_test.go
Labels: approved, lgtm

#4386 Update s390x quota slice definitions for lease groupings
  pkg/api/types.go
Labels: approved, lgtm

#4388 Adding new s390x cluster profile entries
  pkg/api/types.go
Labels: approved, lgtm

#4261 Remove cluster profile secrets from ci tools (& from `prowgen`)
  cmd/check-cluster-profiles-config/main.go
  pkg/api/types.go
  pkg/cmd/release/profile.go
  pkg/prowgen/jobbase.go
  pkg/prowgen/podspec.go
  pkg/prowgen/podspec_test.go
  pkg/prowgen/testdata/zz_fixture_TestClusterProfile_aws.yaml
  pkg/prowgen/testdata/zz_fixture_TestClusterProfile_aws_cpaas.yaml
  pkg/prowgen/testdata/zz_fixture_TestClusterProfile_gcp.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftAnsibleClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftAnsibleCustomClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerCustomTestImageClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_OpenshiftInstallerUPIClusterTestConfiguration.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_multi_stage_test_with_cluster_profile.yaml
  pkg/prowgen/testdata/zz_fixture_TestReleaseRpms_envvar_additional_envvar_generated_for_template.yaml
  pkg/prowgen/testdata/zz_fixture_TestTemplate_different_template_with_command.yaml
  pkg/prowgen/testdata/zz_fixture_TestTemplate_template_with_a_custom_test_image.yaml
  pkg/prowgen/testdata/zz_fixture_TestTemplate_template_with_command.yaml
  pkg/prowgen/testdata/zz_fixture_TestTemplate_template_with_different_command.yaml
  pkg/rehearse/configmaps_test.go
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/private/duper/private-duper-master-presubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/integration/pj-rehearse/candidate/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/integration/pj-rehearse/candidate/ci-operator/templates/subdir/test-template.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-cluster-profile-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-master-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/duper/super-duper-periodics.yaml
  test/integration/pj-rehearse/master/ci-operator/jobs/super/trooper/super-trooper-master-presubmits.yaml
  test/integration/pj-rehearse/master/ci-operator/templates/subdir/test-template.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-master-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/third/org-third-nonstandard-presubmits.yaml
Labels: approved, tide/merge-method-squash, lgtm

#4389 Add retry during extraction
  pkg/steps/release/create_release.go
Labels: approved, lgtm

#4384 SUSTAINING-328: Add new profile for aws-sustaining-autorelease-412
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference
