Repository openshift/ci-tools, pull requests merged in 2024-07, with the labels that each got.

#4183 OSASINFRA-3477: openstack: Remove legacy location for OpenStack periodics from Sippy
  pkg/util/testgrid.go
Labels: approved, lgtm, jira/valid-reference

#4207 Add new profile: equinix-ocp-hcp
  pkg/api/types.go
Labels: approved, lgtm

#4209 Modify lambda_function to support multiple regions
  hack/cloudfront/lambda_function.py
Labels: approved, lgtm

#4210 `slack-bot`: fix review request workflow response
  cmd/slack-bot/main.go
  pkg/slack/events/helpdesk/helpdesk-message.go
  pkg/slack/events/helpdesk/helpdesk-message_test.go
  pkg/slack/events/router/router.go
Labels: approved, lgtm

#4213 fix linter issue
  .golangci.yml
  cmd/qci-appci/main.go
Labels: approved, lgtm

#4206 Add default secret logic for cluster profiles
  pkg/api/types.go
  pkg/load/load.go
  pkg/load/load_test.go
Labels: approved, lgtm

#4216 Add retries to normal promotion flow
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__arm64_only.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__multi_architecture.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_promotion_quay.yaml
Labels: approved, lgtm

#4215 `ci-operator`: pass `ORIGINAL_*` env vars to the multi-stage steps
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/multi_stage/multi_stage_test.go
Labels: approved, lgtm

#4211 Change test-infra to kubernetes-sigs/prow
  hack/check-prow-version.sh
Labels: approved, lgtm

#4217 `prowgen`: allow the ability to configure the slack reporter config
  pkg/config/load.go
  pkg/config/load_test.go
  pkg/jobconfig/files.go
  pkg/prowgen/jobbase.go
  pkg/prowgen/jobbase_test.go
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_with_slack_reporter_config.yaml
  test/integration/ci-operator-prowgen/input/config/slack-report/duper/.config.prowgen
  test/integration/ci-operator-prowgen/input/config/slack-report/duper/slack-report-duper-master.yaml
  test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-presubmits.yaml
Labels: approved, tide/merge-method-squash, lgtm

#4219 `prowgen`: add the option to exclude variants from having a slack reporter config added
  pkg/config/load.go
  pkg/config/load_test.go
  pkg/prowgen/jobbase.go
  test/integration/ci-operator-prowgen/input/config/slack-report/duper/.config.prowgen
  test/integration/ci-operator-prowgen/input/config/slack-report/duper/slack-report-duper-master__exclude.yaml
  test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-periodics.yaml
  test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-postsubmits.yaml
  test/integration/ci-operator-prowgen/output/jobs/slack-report/duper/slack-report-duper-master-presubmits.yaml
Labels: approved, lgtm

#4155 branchingconfigmanagers: remove deprecated schedule-generator
  cmd/branchingconfigmanagers/README.md
  cmd/branchingconfigmanagers/schedule-generator/main.go
  cmd/branchingconfigmanagers/schedule-generator/main_test.go
  cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.1.yaml
  cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.2.yaml
  cmd/branchingconfigmanagers/schedule-generator/testdata/schedules/4.3.yaml
  cmd/branchingconfigmanagers/schedule-generator/testdata/zz_fixture_TestReadSchedules.yaml
  cmd/branchingconfigmanagers/schedule-generator/types.go
  cmd/branchingconfigmanagers/schedule-generator/types_test.go
Labels: approved, lgtm

#4220 `ci-operator`: promote to all registries in parallel
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
Labels: approved, lgtm

#4222 `ci-operator`: fix potential goroutine leak when one of the promotion steps fails
  cmd/ci-operator/main.go
Labels: approved, lgtm

#4221 Image registry blob cache redirects to R2
  hack/cloudfront/lambda_r2_redirect_blobs.py
Labels: approved, lgtm

#4223 Build clusters image registry redirect to R2
  hack/cloudfront/lambda_r2_redirect_blobs.py
Labels: approved, lgtm

#4224 adds a new script to help build and push a ci-tools cmd image to the requested quay account
  Makefile
  hack/build-and-push.sh
Labels: approved, lgtm

#4225 remove Alvaro and Steve from ownership of tools
  images/autotestgridgenerator/Dockerfile
  images/backport-verifier/Dockerfile
  images/blocking-issue-creator/Dockerfile
  images/bugzilla-backporter/Dockerfile
  images/ci-operator-checkconfig/Dockerfile
  images/ci-operator-configresolver/Dockerfile
  images/ci-operator-prowgen/Dockerfile
  images/config-brancher/Dockerfile
  images/config-change-trigger/Dockerfile
  images/config-shard-validator/Dockerfile
  images/determinize-ci-operator/Dockerfile
  images/determinize-peribolos/Dockerfile
  images/determinize-prow-config/Dockerfile
  images/dptp-controller-manager/Dockerfile
  images/pod-scaler/Dockerfile
  images/repo-brancher/Dockerfile
  images/slack-bot/Dockerfile
  images/sprint-automation/Dockerfile
  images/testgrid-config-generator/Dockerfile
Labels: approved, lgtm

#4227 `helpdesk-faq`: sort serialized FAQ items most recent first
  pkg/helpdesk-faq/client.go
  pkg/helpdesk-faq/client_test.go
Labels: approved, lgtm

#4229 PowerVS: Add two new cluster types
  pkg/api/types.go
Labels: approved, lgtm

#4230 Adding new profile: azure-perfscale
  pkg/api/types.go
Labels: approved, lgtm

#4233 OPCT-231: Add profile for OPCT projects on AWS team account
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4240 DPTP-3742: Update the registry_url
  cmd/cluster-init/update_bootstrap_secrets.go
  test/integration/cluster-init/create/expected/core-services/ci-secret-bootstrap/_config.yaml
  test/integration/cluster-init/update/expected/core-services/ci-secret-bootstrap/_config.yaml
Labels: approved, lgtm, jira/valid-reference

#4236 DPTP-4046: Allow more registry domains for OSD clusters
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
  pkg/api/domain.go
Labels: approved, lgtm, jira/valid-reference

#4237 NO-JIRA: Fix JobRuns reference
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
Labels: approved, lgtm, jira/valid-reference

#4241 ci-secret-bootstrap: skip secret sync on error
  cmd/ci-secret-bootstrap/main.go
  cmd/ci-secret-bootstrap/main_test.go
Labels: approved, lgtm
