Repository openshift/ci-tools, pull requests merged in 2024-05, with the labels that each got.

#4097 Do more retires on importing
  pkg/api/constant.go
  pkg/steps/release/import_release.go
  pkg/steps/utils/image.go
  pkg/steps/utils/image_test.go
Labels: approved, lgtm

#4095 releaseSnapshotStep: no dependencies on isTags of the cluster cluster
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
  cmd/ci-operator/main.go
  pkg/api/configresolver/configresolver.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/registry/server/client.go
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
  pkg/steps/release/snapshot.go
Labels: approved, lgtm

#4100 Revert "Merge pull request #4095"
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
  cmd/ci-operator/main.go
  pkg/api/configresolver/configresolver.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/registry/server/client.go
  pkg/steps/release/create_release.go
  pkg/steps/release/release_images.go
  pkg/steps/release/snapshot.go
Labels: approved, lgtm

#4102 configresolver: allow the integrated steams for private jobs
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
Labels: approved, lgtm

#4104 Fix issue DPTP-3994 Update location for hive imagesets
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#4098 configresolver: cache integrated streams
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
  pkg/api/configresolver/configresolver.go
Labels: approved, lgtm

#4105 registry-replacer: consider image aliases when pruning ci-operator replacements
  cmd/registry-replacer/main.go
  cmd/registry-replacer/main_test.go
Labels: approved, lgtm

#4103 Reuse utils.WaitForImportingISTag in import_release
  pkg/steps/release/import_release.go
Labels: approved, lgtm

#4106 ci-operator-configresolver: fix simplifypath
  cmd/ci-operator-configresolver/main.go
Labels: approved, lgtm

#4107 Document QCIAPPCIDomain
  pkg/api/domain.go
  pkg/api/promotion.go
  pkg/steps/input_image_tag.go
Labels: approved, lgtm

#4110 LOG-5375 Register new profile for observability
  pkg/api/types.go
Labels: approved, lgtm

#4108 pj-rehearse: No dependencies of istags on the local cluster
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  pkg/rehearse/rehearse.go
  pkg/rehearse/rehearse_test.go
Labels: approved, lgtm

#4111 ci-images-mirror: support ART images
  cmd/ci-images-mirror/main.go
  pkg/controller/quay_io_ci_images_distributor/supplemental_images.go
  pkg/controller/quay_io_ci_images_distributor/supplemental_images_test.go
Labels: approved, lgtm

#4114 `ci-operator`: limit ip pool leases on the aws profile to "master"/"main" or greater than "4.16"
  pkg/api/leases.go
  pkg/api/leases_test.go
  pkg/defaults/defaults.go
Labels: approved, lgtm

#4115 Increase timeouts for payload testing during k8s rebase 1.30
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm

#4117 Fix the ignored function
  pkg/controller/quay_io_ci_images_distributor/supplemental_images.go
  pkg/controller/quay_io_ci_images_distributor/supplemental_images_test.go
Labels: approved, lgtm

#4119 ci-operator: validate `nvidia.com/gpu` resource
  cmd/gpu-scheduling-webhook/main.go
  cmd/gpu-scheduling-webhook/main_test.go
  pkg/api/constant.go
  pkg/validation/config.go
  pkg/validation/config_test.go
Labels: approved, lgtm

#4120 TRT-1662: jobruntestcaseanalyzer: add test group to verify upgrade success
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/cmd.go
Labels: approved, lgtm, jira/valid-reference

#4121 Add OpenStack TechPreview Periodics to Sippy
  pkg/util/testgrid.go
Labels: approved, lgtm

#4096 TRT-1627: Use variant registry for disruption and remove some outdated half implemented view management
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatorapi/bypass_linter.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_aggregatedtestrun.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_alert.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go
  pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client_mock.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer_test.go
  pkg/jobrunaggregator/jobtableprimer/job_typer.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
  pkg/jobrunaggregator/jobtableprimer/jobs_test.go
  pkg/jobrunaggregator/tablescreator/cmd.go
  pkg/jobrunaggregator/tablescreator/table_creator.go
Labels: approved, lgtm, jira/valid-reference

#4122 exclude variant configuration on multi-arch cluster failover
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_branch_filtered_with_variant__no_cluster_change.yaml
Labels: approved, lgtm

#4125 vSphere - Add elastic lease pool
  pkg/api/types.go
Labels: approved, lgtm

#4126 Revert "TRT-1627: Use variant registry for disruption and remove some outdated half implemented view management"
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatorapi/bypass_linter.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_aggregatedtestrun.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_alert.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go
  pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client_mock.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer_test.go
  pkg/jobrunaggregator/jobtableprimer/job_typer.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
  pkg/jobrunaggregator/jobtableprimer/jobs_test.go
  pkg/jobrunaggregator/tablescreator/cmd.go
  pkg/jobrunaggregator/tablescreator/table_creator.go
Labels: approved, lgtm, jira/valid-reference

#4129 TRT-1627: Unrevert: Use variant registry for disruption and remove some outdated half implemented view management
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/pass_fail.go
  pkg/jobrunaggregator/jobrunaggregatorapi/bypass_linter.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_aggregatedtestrun.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_alert.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_backenddisruption.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_job.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_jobrun.go
  pkg/jobrunaggregator/jobrunaggregatorapi/types_row_testrun.go
  pkg/jobrunaggregator/jobrunaggregatorlib/big_query.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client_mock.go
  pkg/jobrunaggregator/jobrunaggregatorlib/retrying_ci_data_client.go
  pkg/jobrunaggregator/jobrunbigqueryloader/alert.go
  pkg/jobrunaggregator/jobrunbigqueryloader/uploader.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer.go
  pkg/jobrunaggregator/jobruntestcaseanalyzer/analyzer_test.go
  pkg/jobrunaggregator/jobtableprimer/job_typer.go
  pkg/jobrunaggregator/jobtableprimer/jobs.go
  pkg/jobrunaggregator/jobtableprimer/jobs_test.go
  pkg/jobrunaggregator/tablescreator/cmd.go
  pkg/jobrunaggregator/tablescreator/table_creator.go
Labels: approved, lgtm, jira/valid-reference

#4130 `ci-operator`: Allow for the release of unused BYOIP leases
  pkg/defaults/defaults.go
  pkg/steps/ip_pool.go
  pkg/steps/ip_pool_test.go
Labels: approved, tide/merge-method-squash, lgtm

#4118 TRT-1613: Bubble up error for getting alert disruption data
  pkg/jobrunaggregator/jobrunhistoricaldataanalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#4132 Allow more early versions of streams in ocp
  cmd/ci-operator-configresolver/main.go
  cmd/ci-operator-configresolver/main_test.go
Labels: approved, lgtm

#4136 `BYOIP`: simplify configurations for other cluster-profiles to utilize
  pkg/api/leases.go
  pkg/api/types.go
  pkg/steps/ip_pool.go
  pkg/steps/ip_pool_test.go
Labels: approved, lgtm

#4137 create aws-konflux-qe profile
  pkg/api/types.go
Labels: approved, lgtm

#4133 add aws-stackrox cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#4135 ci-operator-config-mirror: disable non ocp promotions
  cmd/ci-operator-config-mirror/main.go
  cmd/ci-operator-config-mirror/main_test.go
Labels: approved, lgtm

#4116 pj-rehearse: remove flags for image mirroring
  cmd/pj-rehearse/main.go
Labels: approved, lgtm

#4138 trt-1627: fix up table references
  pkg/jobrunaggregator/jobrunaggregatorlib/ci_data_client.go
Labels: approved, lgtm, jira/valid-reference

#4140 ci-images-mirror: disable quay_io_ci_images_distributor by default
  cmd/ci-images-mirror/main.go
Labels: approved, lgtm

#4134 pr-reminder: allow updating a channel with brand-new PRs
  cmd/pr-reminder/main.go
  cmd/pr-reminder/main_test.go
Labels: approved, lgtm

#4142 pr-reminder: fix a comment/doc
  cmd/pr-reminder/main.go
Labels: approved, lgtm

#4141 dptp-cm: disable test_images_distributor by default
  cmd/dptp-controller-manager/main.go
Labels: approved, lgtm

#4144 Use the qci-appci's domain
  pkg/api/domain.go
  pkg/steps/input_image_tag_test.go
Labels: approved, lgtm

#4147 ci-operator: support specifing the node architecture on specific tests
  pkg/api/types.go
  pkg/steps/pod.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#4148 create the fakectrlruntimeclient within the Run block to avoid flaky datarace
  pkg/steps/rpm_server_test.go
Labels: approved, lgtm

#4143 pr-reminder: improve signal to noise ratio
  cmd/pr-reminder/main.go
  cmd/pr-reminder/main_test.go
Labels: approved, lgtm

#4146 use vsphere cluster profile for vsphere-elastic
  pkg/api/types.go
Labels: approved, lgtm
