Repository openshift/ci-tools, pull requests merged in 2024-11, with the labels that each got.

#4390 Remove TODO from `ci-operator`
  cmd/ci-operator/main.go
Labels: approved, lgtm

#4392 force the build10 clusters on jobs for additional architecture configuration on images and node architectures for tests
  pkg/config/load.go
  pkg/image-graph-generator/operator.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
Labels: approved, lgtm

#4387 `multi-pr-prow-plugin`: add the ability to abort active multi-pr jobs for the origin PR
  cmd/multi-pr-prow-plugin/server.go
  cmd/multi-pr-prow-plugin/server_test.go
  cmd/multi-pr-prow-plugin/testdata/zz_fixture_TestHandle_abort_multi_pr_jobs.yaml
Labels: approved, lgtm

#4394 `multi-pr`: add plugin help for abort functionality
  cmd/multi-pr-prow-plugin/server.go
Labels: approved, lgtm

#4395 remove Hongkai from OWNERS
  OWNERS
Labels: approved, tide/merge-method-squash, lgtm

#4399 `Payload Testing`: add scheduling state to statuses that are still active
  pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go
Labels: approved, lgtm

#4214 tiny post-GA tool to reduce exec frequency of periodics
  cmd/branchingconfigmanagers/frequency-reducer/main.go
  pkg/api/ocplifecycle/ocplifecycle.go
Labels: approved, lgtm

#4400 remove deprecated code for the manifest-tool cli binary usage
  pkg/controller/multiarchbuildconfig/multiarchbuildconfig_test.go
  pkg/manifestpusher/manifestpusher.go
  pkg/manifestpusher/manifestpusher_test.go
  pkg/steps/source.go
Labels: approved, lgtm

#4401 TRT-1861: fail aggregation when all job runs died early
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer.go
Labels: approved, lgtm, jira/valid-reference

#4391 Remove code related to `cluster/test-deploy`
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  pkg/config/release.go
  pkg/config/release_test.go
  pkg/rehearse/configmaps_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/rehearse.go
  test/integration/pj-rehearse.sh
  test/integration/pj-rehearse/candidate/cluster/test-deploy/test-profile/vars-origin.yaml
  test/integration/pj-rehearse/candidate/cluster/test-deploy/test-profile/vars.yaml
  test/integration/pj-rehearse/expected.yaml
  test/integration/pj-rehearse/master/cluster/test-deploy/test-profile/vars-origin.yaml
  test/integration/pj-rehearse/master/cluster/test-deploy/test-profile/vars.yaml
Labels: approved, lgtm

#4402 `ci-operator`: allow for the possibility of fetching the config from the `CONFIG_SPEC_GCS_URL`
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
Labels: approved, lgtm

#4405 update the ci-operator rolebindings to allow pushing images
  pkg/controller/test-images-distributor/test_images_distributor.go
  pkg/controller/test-images-distributor/test_images_distributor_test.go
Labels: approved, lgtm

#4409 [PERFSCALE-3337] New jetlag-ci cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#4403 Remove ConfigMap() func
  pkg/api/types.go
  pkg/cmd/release/profile.go
Labels: approved, lgtm

#4408 Sippy should pull in ovn-kubernetes periodics
  pkg/util/testgrid.go
Labels: approved, lgtm

#4410 `pj-rehearse` upload the ci-operator config-spec to GCS
  cmd/ci-operator/main.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/rehearse.go
Labels: approved, tide/merge-method-squash, lgtm

#4412 `multi-pr`: fix mergedConfig validation
  cmd/ci-operator/main.go
  pkg/validation/config.go
  pkg/validation/config_test.go
Labels: approved, lgtm

#4415 `payload-testing`: allow for a configurable wait time for the triggered job's URL to appear
  cmd/job-trigger-controller-manager/main.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
Labels: approved, lgtm

#4407 SUSTAINING-345: Add new profile for azure-sustaining-autorelease-412
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4416 `payload testing`: use the `prowjob-dispatcher` client to determine the cluster for jobs
  cmd/job-trigger-controller-manager/main.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_aggregated_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_where_test_name_is_not_found.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_metal_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_variant.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_with_vsphere_override.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_basic_case_without_PR__testing_specified_base.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_PRs_from_different_repositories.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_PRs_from_the_same_repository.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_multiple_case__one_of_the_prowjobs_already_exists.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_initial_and_base_payload_pullspecs.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_url_not_found_in_created_job.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_where_test_name_is_not_found.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_cluster_override.yaml
Labels: approved, lgtm

#4378 owners: add pruan-rht and liangxia
  OWNERS
Labels: approved, lgtm

#4417 `Payload Testing`: consolidate logic to determine if any jobs are still running
  pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer.go
  pkg/controller/prpqr_reconciler/pjstatussyncer/pjstatussyncer_test.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_aggregated_case_with_scheduling.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_basic_case_with_scheduling.yaml
Labels: approved, lgtm

#4418 OSASINFRA-3649: Add cluster profile for RHOSO
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4419 add nutanix flow profile
  pkg/api/types.go
Labels: approved, lgtm

#4411 Capabilities in the dispatcher algorithm
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  cmd/prow-job-dispatcher/prometheus_volumes.go
  cmd/prow-job-dispatcher/prometheus_volumes_test.go
  cmd/sanitize-prow-jobs/main.go
  pkg/dispatcher/config.go
  pkg/dispatcher/config_test.go
  pkg/dispatcher/helpers.go
  pkg/dispatcher/helpers_test.go
  pkg/sanitizer/determinize.go
  pkg/sanitizer/determinize_test.go
Labels: approved, lgtm

#4421 [DPTP-3546] Verify if the repo is public for branch protection
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
Labels: approved, lgtm

#4422 cluster-display: fetch disabled clusters on demand
  cmd/cluster-display/main.go
  cmd/cluster-display/main_test.go
  go.mod
Labels: approved, lgtm

#4414 Adding AWS RHOAI QE Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#4424 `prowgen`: ability to add slack reporting to "images" postsubmits
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_images_job_is_configured_for_slack_reporting.yaml
Labels: approved, lgtm

#4423 Create dedicated GCP cluster profile 'gcp-qe-c3-metal' for GCP C3 bare metal testing (OCPSTRAT-1278)
  pkg/api/types.go
Labels: approved, lgtm

#4425 Adding AWS managed ROSA RHOAI QE Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#4427 Revert "[DPTP-3546] Verify if the repo is public for branch protection"
  cmd/check-gh-automation/main.go
  cmd/check-gh-automation/main_test.go
Labels: approved, lgtm

#4429 Revert "[prowgen] stop forcing cluster on for multi-arch job configuration, add capability labels"
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_postsubmit_images__default_arch_and_others.yaml
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_multiarch_test_job.yaml
Labels: approved, lgtm

#4428 Remove ensure-correct-promotion-dockerfile
  cmd/autoconfigbrancher/main.go
Labels: approved, lgtm

#4426 Adding AWS managed OSD RHOAI QE Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm
