Repository openshift/ci-tools, pull requests merged in 2024-09, with the labels that each got.

#4305 Jobrunaggregator analyzer: add unit tests
  pkg/jobrunaggregator/jobrunaggregatoranalyzer/analyzer_test.go
  pkg/jobrunaggregator/jobrunaggregatorlib/disruption.go
Labels: approved, lgtm

#4247 Fix issue DPTP-4032 Add stanza in test configs to allow accessing RedHat intranet
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/jobbase.go
  pkg/prowgen/podspec.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#4307 ci-operator: treat bundle images as non multi-arch without manifest list
  pkg/steps/bundle_source.go
Labels: approved, lgtm

#4308 Clean-up dispatcher to run only as daemon & fix sanitizer inconsistency with dispatcher
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  cmd/sanitize-prow-jobs/main.go
  pkg/sanitizer/determinize.go
  pkg/sanitizer/determinize_test.go
  pkg/sanitizer/helpers.go
  pkg/sanitizer/helpers_test.go
  test/integration/cluster-init/create/expected/core-services/sanitize-prow-jobs/_clusters.yaml
  test/integration/cluster-init/create/input/core-services/sanitize-prow-jobs/_clusters.yaml
  test/integration/cluster-init/update/expected/core-services/sanitize-prow-jobs/_clusters.yaml
  test/integration/cluster-init/update/input/core-services/sanitize-prow-jobs/_clusters.yaml
  test/integration/repo-init.sh
  test/integration/repo-init/expected/core-services/sanitize-prow-jobs/_clusters.yaml
  test/integration/repo-init/input/core-services/sanitize-prow-jobs/_clusters.yaml
Labels: approved, lgtm, do-not-merge/hold

#4310 Fix bug in sanitizer
  pkg/sanitizer/determinize.go
Labels: approved, lgtm

#4245 ci-images-mirror: add --validate-config-only option
  cmd/ci-images-mirror/main.go
  pkg/controller/quay_io_ci_images_distributor/quay_io_ci_images_distributor.go
  pkg/controller/quay_io_ci_images_distributor/supplemental_images.go
Labels: approved, lgtm

#4311 `ci-operator-configresolver`: base output off of config that requested test is injected from
  pkg/registry/server/server.go
  test/integration/ci-operator-configresolver.sh
  test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-installer-as-base.json
Labels: approved, lgtm

#4238 Create cluster profiles presubmit
  cmd/check-cluster-profiles-config/main.go
  cmd/check-cluster-profiles-config/main_test.go
  images/check-cluster-profiles-config/Dockerfile
Labels: approved, lgtm

#4306 ci-operator: label all resources it creates
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/labeledclient/client.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/pod.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestBuildFromSource_build_args.yaml
  pkg/steps/testdata/zz_fixture_TestBuildFromSource_ref_specified.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_title_in_pull_gets_squashed.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
Labels: approved, lgtm

#4317 Handle rehersals by stripping prefix
  cmd/prow-job-dispatcher/server.go
  cmd/prow-job-dispatcher/server_test.go
Labels: approved, lgtm

#4316 `ci-operator`: treat building the primary ref differently from the extra_refs
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, tide/merge-method-squash, lgtm

#4319 Revert "`ci-operator`: treat building the primary ref differently from the extra_refs"
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved

#4313 Remove default amd64 arch for Generate Pods in Multistage
  pkg/registry/resolver_test.go
  pkg/registry/stack.go
  pkg/steps/multi_stage/gen.go
  test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-injected.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-console-merged-release-4.2-installer-as-base.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-golang111.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-injected.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2-regChange.json
  test/integration/ci-operator-configresolver/expected/openshift-installer-release-4.2.json
  test/integration/ci-operator-configresolver/expected/resolved-config.json
  test/integration/pj-rehearse/expected.yaml
Labels: approved, lgtm

#4320 Revert "ci-operator: label all resources it creates"
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/labeledclient/client.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/pod.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestBuildFromSource_build_args.yaml
  pkg/steps/testdata/zz_fixture_TestBuildFromSource_ref_specified.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_title_in_pull_gets_squashed.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
Labels: approved, lgtm

#4321 Fix `check-breaking-changes` integration test
  test/validate-generation-breaking-changes.sh
Labels: approved, lgtm

#4325 `payload-testing-prow-plugin`: handle errors from config reload
  cmd/payload-testing-prow-plugin/main.go
Labels: approved, lgtm

#4327 Add new profile: aws-kubevirt
  pkg/api/types.go
Labels: approved, lgtm

#4318 Add new cluster profile aro-redhat-tenant
  pkg/api/types.go
Labels: approved, lgtm

#4323 `ci-operator`: treat building the primary ref differently from the extra_refs
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#4330 `payload-testing-prow-plugin`: introduce symlink watcher
  cmd/payload-testing-prow-plugin/main.go
Labels: approved, lgtm

#4332 Revert "`ci-operator`: treat building the primary ref differently from the extra_refs"
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#4331 Fix issue DPTP-4032 Delete firewall when RH intranet access is desired
  cmd/ci-operator/main.go
  pkg/prowgen/jobbase.go
Labels: approved, lgtm

#4337 `payload-testing-prow-plugin`: add "release-repo-git-sync-path"
  cmd/payload-testing-prow-plugin/main.go
Labels: approved, lgtm

#4329 `pj-rehearse`: ignore 'restrict_network_access' option when running rehearsals
  pkg/rehearse/jobs.go
  test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
Labels: approved, lgtm

#4336 `ci-operator`: treat building the primary ref differently from the extra_refs
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
Labels: approved, lgtm

#4334 resolve the step graph dependencies for specific architectures
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/steps/bundle_source.go
  pkg/steps/cluster_claim.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/index_generator.go
  pkg/steps/input_env.go
  pkg/steps/input_image_tag.go
  pkg/steps/ip_pool.go
  pkg/steps/ip_pool_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/release/snapshot.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/template.go
  pkg/steps/write_params.go
Labels: approved, lgtm

#4340 Revert "resolve the step graph dependencies for specific architectures"
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/steps/bundle_source.go
  pkg/steps/cluster_claim.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/index_generator.go
  pkg/steps/input_env.go
  pkg/steps/input_image_tag.go
  pkg/steps/ip_pool.go
  pkg/steps/ip_pool_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/release/snapshot.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/template.go
  pkg/steps/write_params.go
Labels: approved, lgtm

#4339 bump `prow` dependency
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/prow/pkg/github/client.go
  vendor/sigs.k8s.io/prow/pkg/plugins/config.go
Labels: approved, lgtm

#4342 Fix issue DPTP-4032 Warn in all cases
  cmd/ci-operator/main.go
Labels: approved, lgtm

#4341 resolve the step graph dependencies for specific architectures
  pkg/api/graph.go
  pkg/api/graph_test.go
  pkg/steps/bundle_source.go
  pkg/steps/cluster_claim.go
  pkg/steps/clusterinstall/clusterinstall.go
  pkg/steps/git_source.go
  pkg/steps/images_ready.go
  pkg/steps/index_generator.go
  pkg/steps/input_env.go
  pkg/steps/input_image_tag.go
  pkg/steps/ip_pool.go
  pkg/steps/ip_pool_test.go
  pkg/steps/lease.go
  pkg/steps/lease_test.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/output_image_tag.go
  pkg/steps/pipeline_image_cache.go
  pkg/steps/pod.go
  pkg/steps/project_image.go
  pkg/steps/release/create_release.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
  pkg/steps/release/release_images.go
  pkg/steps/release/snapshot.go
  pkg/steps/rpm_injection.go
  pkg/steps/rpm_server.go
  pkg/steps/run_test.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/template.go
  pkg/steps/write_params.go
Labels: approved, lgtm

#4344 ci-operator: warn when CRD `egressfirewalls.k8s.ovn.org` is not available
  cmd/ci-operator/main.go
Labels: approved, lgtm

#4335 ci-operator: label all resources it creates (2nd attempt)
  cmd/ci-operator/main.go
  pkg/defaults/defaults.go
  pkg/labeledclient/client.go
  pkg/labeledclient/client_test.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
  pkg/steps/pod.go
  pkg/steps/rpm_server.go
  pkg/steps/source.go
  pkg/steps/testdata/zz_fixture_TestBuildFromSource_build_args.yaml
  pkg/steps/testdata/zz_fixture_TestBuildFromSource_ref_specified.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_title_in_pull_gets_squashed.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_fails_so_PodStep_terminates_and_returns_an_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Pod_run_by_PodStep_succeeds_so_PodStep_terminates_and_returns_no_error.yaml
  pkg/steps/testdata/zz_fixture_TestPodStepExecution_Successful_pod_with_cloning.yaml
Labels: approved, tide/merge-method-squash, lgtm

#4343 `prowjob-dispatcher`: refactor dispatcher and create a client for use by other tools
  cmd/prow-job-dispatcher/main.go
  pkg/dispatcher/client.go
  pkg/dispatcher/gob.go
  pkg/dispatcher/prowjobs.go
  pkg/dispatcher/server.go
  pkg/dispatcher/server_test.go
Labels: approved, tide/merge-method-squash, lgtm

#4347 Allow for either of the configAgentFn or registryAgentFn to be nil
  pkg/load/agents/utils.go
Labels: approved, lgtm

#4348 `pj-rehearse`: Disable rehearsals on tests where the 'restrict_network_access' config is toggled to 'false'
  cmd/config-change-trigger/main.go
  cmd/pj-rehearse/main.go
  cmd/pj-rehearse/server.go
  pkg/diffs/diffs.go
  pkg/diffs/diffs_test.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/rehearse.go
  test/integration/pj-rehearse/candidate/ci-operator/config/super/trooper/super-trooper-master.yaml
Labels: approved, tide/merge-method-squash, lgtm

#4349 cluster-init: generate Certificates
  cmd/cluster-init/cmd/onboard/buildclusterdir/update.go
  cmd/cluster-init/cmd/onboard/generateconfig.go
  cmd/cluster-init/main.go
  pkg/clustermgmt/onboard/certificate.go
  pkg/clustermgmt/onboard/certificate_test.go
  pkg/clustermgmt/onboard/types.go
  pkg/clustermgmt/types.go
  pkg/util/yaml/yaml.go
  pkg/util/yaml/yaml_test.go
  test/integration/cluster-init.sh
  test/integration/cluster-init/create-ocp/expected/clusters/build-clusters/newCluster/cert-manager/certificate.yaml
  test/integration/cluster-init/create/expected/clusters/build-clusters/newCluster/cert-manager/certificate.yaml
  test/integration/cluster-init/update-ocp/expected/clusters/build-clusters/existingCluster/cert-manager/certificate.yaml
  test/integration/cluster-init/update/expected/clusters/build-clusters/existingCluster/cert-manager/certificate.yaml
  test/validate-generation-breaking-changes.sh
Labels: approved, lgtm

#4350 `pj-rehearse`: add empty line for formatting
  cmd/pj-rehearse/server.go
Labels: approved, lgtm
