Repository openshift/ci-tools, pull requests merged in 2025-04, with the labels that each got.

#4539 Allow to have pipeline triggered only by LGTM
  cmd/pipeline-controller/helpers.go
  cmd/pipeline-controller/main.go
  cmd/pipeline-controller/main_test.go
  cmd/pipeline-controller/reconciler.go
Labels: approved, lgtm

#4540 More logs to Pipelines ctrl
  cmd/pipeline-controller/main.go
Labels: approved, lgtm

#4531 Optional promotion periodic
  pkg/api/types.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_promotion_postsubmit_and_periodic_.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#4541 Fix issue with lgtm pipelines
  cmd/pipeline-controller/main.go
Labels: approved

#4544 Refactor GCS Config Spec Uploader
  pkg/config/gcs.go
  pkg/rehearse/jobs.go
  pkg/rehearse/jobs_test.go
  pkg/rehearse/rehearse.go
Labels: approved, lgtm

#4547 propagate the node architecture config to the multi arch step on resolution
  pkg/registry/resolver.go
Labels: approved, lgtm

#4542 SOSQE-2418: Add cluster profile for RHOS CI
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4546 Konflux: EphemeralCluster reconciler first implementation
  pkg/api/ephemeralcluster/v1/ci.openshift.io_ephemeralclusters.yaml
  pkg/api/ephemeralcluster/v1/doc.go
  pkg/api/ephemeralcluster/v1/register.go
  pkg/api/ephemeralcluster/v1/types.go
  pkg/api/ephemeralcluster/v1/zz_generated.deepcopy.go
  pkg/controller/ephemeralcluster/reconciler.go
  pkg/controller/ephemeralcluster/reconciler_test.go
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Fail_to_create_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Handle_config_upload_error.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_Fail_to_create_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_Handle_config_upload_error.yaml
  pkg/controller/ephemeralcluster/wait-test-complete.sh
Labels: approved, lgtm

#4534 DPTP-4367: Reduce NAT gateway cost using NAT instance
  hack/reduce_nat_gateway_cost/replace_nat_with_nat_instance.py
Labels: approved, lgtm, jira/valid-reference

#4548 ensure correct implementation of multi-stage test step as a multi-arch step node
  pkg/steps/multi_stage/multi_stage.go
Labels: approved, lgtm

#4549 Konflux: Fetch EphemeralCluster kubeconfig
  pkg/api/ephemeralcluster/v1/types.go
  pkg/controller/ephemeralcluster/reconciler.go
  pkg/controller/ephemeralcluster/reconciler_test.go
Labels: approved, tide/merge-method-squash, lgtm

#4555 fix: change separator in release version format
  pkg/steps/release/create_release.go
Labels: approved, lgtm

#4557 Register new Observability GCP ClusterProfile
  pkg/api/types.go
Labels: approved, lgtm

#4552 OCPEDGE-1741: feat: add edge enablement equinix profile
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4560 Konflux: Inline ci-operator Config
  pkg/controller/ephemeralcluster/reconciler.go
  pkg/controller/ephemeralcluster/reconciler_test.go
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Handle_invalid_prow_config.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_Handle_invalid_prow_config.yaml
  pkg/util/slices/slices.go
  pkg/util/slices/slices_test.go
Labels: approved, lgtm

#4561 DPTP-4388: Introduce a mechanism to override the node architecture per step in a multi-stage workflow
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/registry/resolver.go
  pkg/registry/resolver_test.go
  pkg/registry/stack.go
  pkg/validation/test.go
  pkg/validation/test_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm, jira/valid-reference

#4563 `prowgen`: add `shard_count` field to the test step configuration
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/prowgen/podspec.go
  pkg/prowgen/prowgen.go
  pkg/prowgen/prowgen_test.go
  pkg/prowgen/testdata/zz_fixture_TestGenerateJobs_sharded_presubmit.yaml
  pkg/validation/graph.go
  pkg/webreg/zz_generated.ci_operator_reference.go
  test/integration/ci-operator-prowgen/input/config/sharded/repo/sharded-repo-main.yaml
  test/integration/ci-operator-prowgen/output/jobs/sharded/repo/sharded-repo-main-presubmits.yaml
Labels: approved, lgtm

#4564 TRT-2090: When determining the testname for a given jobname, we must trim the shard suffix
  pkg/api/metadata.go
  pkg/api/metadata_test.go
Labels: approved, lgtm, jira/valid-reference

#4566 TRT-2090: quotation mark handling for multi-stage-param override values
  cmd/ci-operator/main.go
  cmd/ci-operator/main_test.go
  pkg/prowgen/podspec.go
  test/integration/ci-operator-prowgen/output/jobs/sharded/repo/sharded-repo-main-presubmits.yaml
Labels: approved, lgtm, jira/valid-reference
