Repository openshift/ci-tools, pull requests merged in 2025-08, with the labels that each got.

#4640 Disable link unfurling in helpdesk messages
  pkg/slack/events/helpdesk/helpdesk-message.go
Labels: approved, lgtm

#4644 [ci-operator] include the --keep-manifest-list option on release payload generation
  pkg/steps/release/create_release.go
  pkg/steps/release/create_release_test.go
  test/e2e/lease/config.yaml
  test/e2e/lease/e2e_test.go
  test/e2e/lease/template.yaml
  test/e2e/simple/artifacts/junit_operator.xml
  test/e2e/simple/e2e_test.go
  test/e2e/simple/template-config.yaml
  test/e2e/simple/template.yaml
Labels: approved, lgtm

#4652 Use sigs.k8s.io/yaml for all yaml operations
  pkg/group/config.go
Labels: approved, lgtm

#4650 api: register azure-oadp-qe cluster profile
  pkg/api/types.go
Labels: approved, lgtm

#4653 Add new AWS Cluster Profile.
  pkg/api/types.go
Labels: approved, lgtm

#4654 DPTP-4341: Fix nil pointer issue and update secret for referencePolicy
  pkg/defaults/defaults.go
  pkg/steps/release/create_release.go
Labels: approved, lgtm, jira/valid-reference

#4648 Send via multiple messages when with large PR numbers
  cmd/pr-reminder/main.go
  cmd/pr-reminder/main_test.go
Labels: approved, lgtm

#4649 Allow special pods to get NET_ caps for diagnostic purposes
  cmd/ci-scheduling-webhook/mutation.go
Labels: approved, lgtm

#4656 Introduce the pod metrics agent plugin, improve the metrics agent debug logs
  pkg/metrics/builds.go
  pkg/metrics/builds_test.go
  pkg/metrics/insights.go
  pkg/metrics/insights_test.go
  pkg/metrics/leases.go
  pkg/metrics/metrics.go
  pkg/metrics/nodes.go
  pkg/metrics/plugins.go
  pkg/metrics/pods.go
  pkg/metrics/pods_test.go
  pkg/util/pods.go
Labels: approved, lgtm

#4660 [ci-operator] record a pod lifecycle event on build pods
  pkg/steps/source.go
Labels: approved, lgtm

#4661 ci-operator: Support Nested Containers
  .golangci.yml
  pkg/api/constant.go
  pkg/api/types.go
  pkg/steps/multi_stage/gen.go
  pkg/steps/multi_stage/gen_test.go
  pkg/steps/multi_stage/init.go
  pkg/steps/multi_stage/init_test.go
  pkg/steps/multi_stage/multi_stage.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods_enable_nested_podman.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods_generate_pods.yaml
  pkg/steps/pod.go
  pkg/util/namespace.go
  pkg/util/namespace_test.go
  pkg/util/pods.go
  pkg/util/rbacs.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, tide/merge-method-squash, lgtm

#4659 Added a logic to chose the name of the mirrored image
  pkg/controller/multiarchbuildconfig/mirror.go
  pkg/controller/multiarchbuildconfig/mirror_test.go
Labels: approved, lgtm

#4665 Add determinize to tide-config-manager
  images/tide-config-manager/Dockerfile
Labels: approved, lgtm
