Repository openshift/ci-tools, pull requests merged in 2025-09, with the labels that each got.

#4676 [ci-operator] improve the pod metric events
  pkg/metrics/metrics.go
  pkg/metrics/pods.go
  pkg/metrics/pods_test.go
  pkg/steps/source.go
  pkg/util/pods.go
Labels: approved, lgtm

#4678 DPTP-4505: Extend maxJobTimeout from 8h to 72h
  pkg/validation/test.go
Labels: approved, lgtm, jira/valid-reference

#4679 tide-config-manager: Install diffutils
  images/tide-config-manager/Dockerfile
Labels: approved, lgtm

#4680 `gsm-secrets`: Rename updater SA suffix
  pkg/gsm-secrets/diff_test.go
  pkg/gsm-secrets/resources.go
  pkg/gsm-secrets/secrets.go
  pkg/gsm-secrets/secrets_test.go
  pkg/gsm-secrets/testdata/zz_fixture_bindings_TestGetDesiredState_basic_config.yaml
  pkg/gsm-secrets/testdata/zz_fixture_bindings_TestGetDesiredState_complex_config.yaml
  pkg/gsm-secrets/testdata/zz_fixture_bindings_TestGetDesiredState_one_secret_collection.yaml
  pkg/gsm-secrets/testdata/zz_fixture_sa_TestGetDesiredState_basic_config.yaml
  pkg/gsm-secrets/testdata/zz_fixture_sa_TestGetDesiredState_complex_config.yaml
  pkg/gsm-secrets/testdata/zz_fixture_sa_TestGetDesiredState_one_secret_collection.yaml
  pkg/gsm-secrets/types.go
  pkg/gsm-secrets/types_test.go
Labels: approved, lgtm

#4686 [ci-operator] improve the insights events in the metrics agent, expand the metrics data
  cmd/ci-operator/main.go
  pkg/metrics/insights.go
  pkg/metrics/metrics.go
Labels: approved, lgtm

#4690 Rename dummy index secret creation on selfservice
  cmd/vault-secret-collection-manager/main.go
  cmd/vault-secret-collection-manager/main_test.go
Labels: approved, lgtm

#4695 Add cluster profile "aws-confidential-qe"
  pkg/api/types.go
Labels: approved, lgtm

#4689 Dispatch EphemeralCluster requests coming from Konflux
  cmd/prow-job-dispatcher/main.go
  pkg/controller/ephemeralcluster/reconciler.go
  pkg/controller/ephemeralcluster/reconciler_test.go
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Handle_invalid_prow_config.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/dispatcher/ephemeralcluster.go
  pkg/dispatcher/ephemeralcluster_test.go
  pkg/dispatcher/server.go
Labels: approved, tide/merge-method-squash, lgtm

#4706 [retester]: ensure the preloading of the aws configuration on the controller initialization
  cmd/retester/main.go
Labels: approved, lgtm

#4705 ci-operator: referencePolicy = Source fix
  pkg/defaults/defaults.go
  pkg/validation/release.go
  pkg/validation/release_test.go
Labels: approved, lgtm

#4711 fix errors in daily job-aggregation table updater
  pkg/jobrunaggregator/jobtableprimer/create_jobs.go
Labels: approved, lgtm

#4716 Add basic 100GiB prometheus pvc
  pkg/clusterinit/onboard/openshiftmonitoring.go
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/openshift-monitoring/cluster-monitoring-config.yaml
Labels: approved, lgtm

#4710 ci-operator: use QCI managed-clonerefs image
  pkg/api/helper/imageextraction.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/steps/source.go
  pkg/steps/source_test.go
  pkg/steps/testdata/zz_fixture_TestCreateBuild_basic_options_for_a_presubmit.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_title_in_pull_gets_squashed.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_OAuth_token.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_a_pull_secret.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_extra_refs_setting_workdir_and_path_alias.yaml
  pkg/steps/testdata/zz_fixture_TestCreateBuild_with_ssh_key.yaml
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#4717 Fix cannonical_go_repository error when merging 2 repos
  pkg/registry/server/server.go
Labels: approved, lgtm
