Repository openshift/ci-tools, pull requests merged in 2025-05, with the labels that each got.

#4568 OSASINFRA-3795: Add a cluster pofile for Vexxhost BM RHOS Clouds
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4574 Konflux: Add phases to the EphemeralCluster
  hack/update-codegen.sh
  pkg/api/ephemeralcluster/v1/ci.openshift.io_ephemeralclusters.yaml
  pkg/api/ephemeralcluster/v1/types.go
  pkg/api/ephemeralcluster/v1/zz_generated.deepcopy.go
  pkg/controller/ephemeralcluster/reconciler.go
  pkg/controller/ephemeralcluster/reconciler_test.go
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Fail_to_create_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Handle_invalid_prow_config.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Invalid_ci_operator_configuration.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_ec_TestCreateProwJob_Invalid_ci_operator_configuration_and_fail_to_update_EC.yaml
Labels: approved, lgtm

#4569 Bumping e2e ocp versions
  test/e2e/multi-stage/cluster-claim.yaml
  test/e2e/multi-stage/e2e_test.go
  test/e2e/multi-stage/integration-releases.yaml
  test/e2e/simple/dynamic-releases.yaml
  test/e2e/simple/e2e_test.go
Labels: approved, lgtm

#4575 Konflux: Force the reconciler to watch a single namespace
  cmd/dptp-controller-manager/main.go
  pkg/controller/ephemeralcluster/reconciler.go
Labels: approved, lgtm

#4577 Revert "feat(ecc): reconcile objs from one namespace only"
  cmd/dptp-controller-manager/main.go
  pkg/controller/ephemeralcluster/reconciler.go
Labels: approved, lgtm

#4578 Konflux: Controller Improvements
  cmd/dptp-controller-manager/main.go
  pkg/api/types.go
  pkg/controller/ephemeralcluster/reconciler.go
  pkg/controller/ephemeralcluster/reconciler_test.go
  pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Kubeconfig_not_ready.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Kubeconfig_ready.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Test_completed__create_secret.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_build01_TestReconcile_Test_completed__secret_exists_do_nothing.yaml
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/wait-test-complete.sh
  pkg/steps/multi_stage/init.go
Labels: approved, lgtm

#4579 Konflux: Fix RBAC to read test-done-signal secret
  pkg/api/types.go
  pkg/controller/ephemeralcluster/reconciler.go
  pkg/controller/ephemeralcluster/reconciler_test.go
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/wait-test-complete.sh
  pkg/steps/multi_stage/init.go
Labels: approved, lgtm

#4581 repo-brancher: Improve error handling
  cmd/repo-brancher/main.go
Labels: approved, tide/merge-method-squash, lgtm

#4582 Created a cloud formation template and script for all regions
  hack/reduce_nat_gateway_cost/deploy.sh
  hack/reduce_nat_gateway_cost/replace_nat_with_nat_instance.py
  hack/reduce_nat_gateway_cost/use-nat-instance-forwarders.yaml
  hack/reduce_nat_gateway_cost/use-nat-instance.yaml
Labels: approved, lgtm

#4559 chore: use quay-proxy for entrypoint-wrapper
  pkg/steps/multi_stage/gen.go
  pkg/steps/multi_stage/testdata/zz_fixture_TestGenerateObservers.yaml
  pkg/steps/multi_stage/testdata/zz_fixture_TestGeneratePods.yaml
Labels: approved, lgtm

#4583 NO-JIRA: fix: resolve cluster profile typo
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4585 Konflux: `wait-test-signal.sh` doesn't give up too early
  pkg/controller/ephemeralcluster/testdata/zz_fixture_pj_TestCreateProwJob_An_EphemeralCluster_request_creates_a_ProwJob.yaml
  pkg/controller/ephemeralcluster/wait-test-complete.sh
Labels: approved, lgtm

#4586 Register new Observability Azure Cluster Profile
  pkg/api/types.go
Labels: approved, lgtm

#4587 cluster-init: use quay.io repo on ProwJobs
  pkg/clusterinit/onboard/prowjob.go
  test/integration/cluster-init/update-build99/expected/ci-operator/jobs/openshift/release/openshift-release-master-postsubmits.yaml
  test/integration/cluster-init/update-build99/expected/ci-operator/jobs/openshift/release/openshift-release-master-presubmits.yaml
Labels: approved, lgtm

#4588 ci-operator: Use * to exclude images from promotion
  pkg/api/promotion.go
  pkg/promotion/promotion.go
  pkg/steps/release/promote.go
  pkg/steps/release/promote_test.go
Labels: approved, lgtm
