Repository openshift/ci-tools, pull requests merged in 2025-03, with the labels that each got.

#4510 Using qci cluster init
  pkg/clusterinit/onboard/manifests/supplemental-ci-images/001_managed-clonerefs_mabc.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/supplemental-ci-images/001_managed-clonerefs_mabc.yaml
Labels: approved, lgtm

#4513 fix node_architecture configuration while loading the step registry
  pkg/registry/resolver.go
  pkg/validation/test.go
Labels: approved, lgtm

#4514 `prowgen`: Add enable_secrets_store_csi_driver field
  pkg/config/load.go
  pkg/prowgen/jobbase.go
  pkg/prowgen/jobbase_test.go
  pkg/prowgen/podspec.go
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_multi_stage_test_with_CSI_enabled.yaml
  pkg/prowgen/testdata/zz_fixture_TestNewProwJobBaseBuilderForTest_simple_test_with_CSI_enabled.yaml
Labels: approved, lgtm

#4518 `pod-scaler`: temporarily use 120% of what we have determined necessary during admission
  cmd/pod-scaler/admission.go
  cmd/pod-scaler/admission_test.go
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add.diff
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePodResources_resources_to_add__limits_disabled.diff
  cmd/pod-scaler/testdata/zz_fixture_TestMutatePods_pod_associated_with_a_build_with_labels.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data.yaml
  test/e2e/pod-scaler/testdata/zz_fixture_TestAdmission_pod_for_which_we_have_data_patch.yaml
Labels: approved, lgtm

#4521 `pj-rehearse`: add list command
  cmd/pj-rehearse/server.go
Labels: approved, lgtm

#4520 `repo-init`: update origin 'master' -> 'main'
  cmd/repo-init/main.go
  test/integration/repo-init/expected/ci-operator/config/openshift/origin/openshift-origin-main.yaml
  test/integration/repo-init/expected/ci-operator/config/org/repo/org-repo-main.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-main-postsubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/openshift/origin/openshift-origin-main-presubmits.yaml
  test/integration/repo-init/expected/ci-operator/jobs/org/repo/org-repo-main-presubmits.yaml
  test/integration/repo-init/expected/core-services/sanitize-prow-jobs/_config.yaml
  test/integration/repo-init/input/ci-operator/config/openshift/origin/openshift-origin-main.yaml
  test/integration/repo-init/input/core-services/sanitize-prow-jobs/_config.yaml
Labels: approved, tide/merge-method-squash, lgtm

#4506 ci-operator: external_images stanza
  cmd/ci-operator/main.go
  pkg/api/helper/imageextraction_test.go
  pkg/api/types.go
  pkg/api/zz_generated.deepcopy.go
  pkg/defaults/defaults.go
  pkg/steps/input_image_tag.go
  pkg/steps/input_image_tag_test.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#4522 Add konflux-nightly to list of supported release controller streams
  cmd/payload-testing-prow-plugin/rcjobresolver.go
  cmd/payload-testing-prow-plugin/rcjobresolver_test.go
  pkg/api/types.go
  pkg/release/candidate/client_test.go
  pkg/validation/release.go
  pkg/validation/release_test.go
Labels: approved, lgtm

#4516 dispatcher: support changing capabilities in the existing job
  cmd/prow-job-dispatcher/main.go
  cmd/prow-job-dispatcher/main_test.go
  cmd/prow-job-dispatcher/testdata/TestDispatchDeltaJobs/capabilities/cluster-api-provider-gcp-presubmits.yaml
  pkg/dispatcher/prowjobs.go
  pkg/dispatcher/server.go
  pkg/prowgen/prowgen.go
  pkg/sanitizer/determinize.go
Labels: approved, lgtm

#4525 cluster-init: add warning header
  pkg/clusterinit/onboard/manifestgenerator.go
  pkg/clusterinit/onboard/types.go
  test/integration/cluster-init/update-build99/expected/clusters/app.ci/dex/manifests.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/assets/admin_cluster_oauth_template.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/assets/quayio-pull-through-cache-icsp.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/cert-manager/certificate.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-operator/admin_ci-operator_rbac.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-longtests-worker-aarch64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-longtests-worker-amd64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-prowjobs-worker-aarch64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-prowjobs-worker-amd64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-tests-worker-aarch64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-tests-worker-amd64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/cloud-credential/cluster-init-credentials-request-aws.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/cloudability-agent.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/machineset/clusterautoscaler.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/machineset/infra-aarch64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/machineset/infra-amd64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/machineset/worker-aarch64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/machineset/worker-amd64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/multi-arch-builder-controller/000_mabc-updater_rbac.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/multi-arch-builder-controller/100_deploy.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/openshift-image-registry/config-cluster.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/openshift-image-registry/imagepruner-cluster.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/openshift-ingress-operator/ingress-controller-default.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/openshift-monitoring/cluster-monitoring-config.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/supplemental-ci-images/001_managed-clonerefs_mabc.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/supplemental-ci-images/002_ci-tools-build-root-mabc.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/upgrader-sa.yaml
Labels: approved, lgtm

#4517 rework payload testing image tag overrides to allow for an aritrary pullspec override
  cmd/ci-operator/main.go
  pkg/api/pullrequestpayloadqualification/v1/ci.openshift.io_pullrequestpayloadqualificationruns.yaml
  pkg/api/pullrequestpayloadqualification/v1/types.go
  pkg/api/types.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler.go
  pkg/controller/prpqr_reconciler/prpqr_reconciler_test.go
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prowjobs_TestReconcile_override_tag.yaml
  pkg/controller/prpqr_reconciler/testdata/zz_fixture_prpqr_TestReconcile_override_tag.yaml
  pkg/defaults/defaults.go
  pkg/defaults/defaults_test.go
  pkg/prowgen/podspec.go
  pkg/steps/input_image_tag.go
  pkg/validation/config.go
  pkg/validation/config_test.go
  pkg/webreg/zz_generated.ci_operator_reference.go
Labels: approved, lgtm

#4526 hypershift-cleaner: delete broken/expired resources
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#4524 MULTIARCH-5360 Adding new cluster profile for ppc64le S2S zone
  pkg/api/types.go
Labels: approved, lgtm

#4527 DPTP-4369 Enable debug logs on promotion pods, upload promotion artifacts to the gcs bucket
  pkg/steps/release/promote.go
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__arm64_only.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_basic_case__multi_architecture.yaml
  pkg/steps/release/testdata/zz_fixture_TestGetPromotionPod_promotion_quay.yaml
Labels: approved, lgtm

#4528 hypershift-cleaner: update deleting
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#4530 hypershift-cleaner: update resources to be deleted
  images/dptp-3312-hypershift-leaks-cleaner/cleanup-hypershift-leaks.sh
Labels: approved, lgtm

#4532 allow gathering the logs from the promotion pods
  pkg/steps/pod.go
  pkg/steps/release/import_release.go
  pkg/steps/release/promote.go
Labels: approved, lgtm

#4511 SUSTAINING-607: Add GCP sustaining cluster profile
  pkg/api/types.go
Labels: approved, lgtm, jira/valid-reference

#4535 Update builds machineset volume
  pkg/clusterinit/onboard/cischedulingwebhook/aws.go
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-builds-worker-aarch64.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/ci-scheduling-webhook/ci-builds-worker-amd64.yaml
Labels: approved, lgtm

#4536 ci-operator: fix failure detection in release build
  pkg/steps/release/create_release.go
Labels: approved, lgtm

#4538 cluster-init: sort aws security groups
  pkg/clusterinit/onboard/cischedulingwebhook/aws.go
  pkg/clusterinit/onboard/machineset/aws.go
  pkg/clusterinit/onboard/manifests/supplemental-ci-images/001_managed-clonerefs_mabc.yaml
  test/integration/cluster-init/update-build99/expected/clusters/build-clusters/build99/supplemental-ci-images/001_managed-clonerefs_mabc.yaml
Labels: approved, lgtm
